### ISSUE TITLE
Als developer van een client applicatie wil ik de datum in een voor een eindgebruiker leesbare vorm

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1000]
zodat ik dat niet zelf hoef samen te stellen per datum type

Dit verzoek komt van een deelnemer van de API lab van 7 april.

Voorbeelden:
- Datum: "7 april 2022"
- JaarMaandDatum: "april 2022"
- JaarDatum: "2022"
- OnbekendDatum: "onbekend"

**Comment by JohanBoer** [comment]
Voor de JaarDatum lijkt het mij geen zin hebben om daar een "leesbaar formaat" aan toe te voegen.

**Comment by fsamwel** [comment]
> Voor de JaarDatum lijkt het mij geen zin hebben om daar een "leesbaar formaat" aan toe te voegen.

In de PR #1021 heb ik aangegeven dat ik het hier niet mee eens ben. Dan kan iemand dus niet altijd leesbaarformaat gebruiken en moet er dus altijd gecheckt worden welke van beide bestaat
