### ISSUE TITLE
Als developer wil ik bij een ontbonden huwelijk/partnerschap deze ook ontvangen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1005]
zodat ik deze direct kan gebruiken in mijn processen

In sommige processen is het ook interessant om de laatste partner te krijgen, ook wanneer deze relatie ontbonden/beëindigd is. Bijvoorbeeld voor sociale zaken

Dus als er een nog geldig partnerschap of huwelijk is (niet ontbonden), wordt alleen deze geleverd. En wanneer het laatste huwelijk of partnerschap is ontbonden wordt alleen deze geleverd.

Zie ook definitie van actuele partner in LO GBA.

Nu zou iemand daarvoor partnerhistorie moeten vragen en dan mogelijk ook (m)eerdere partnerschappen/huwelijken krijgen. Dat laatste past slecht bij dataminimalisatie.
Aan de andere kant wanneer voor een proces alleen de niet-ontbonden partner relevant is, wordt onnodig de ontbonden partner geleverd (terwijl er geen partner meer is).

**Comment by fsamwel** [comment]
M.i. is een nadeel van ook de laatst ontbonden partner leveren dat we dan in de personen resource verschillende definities hanteren van actueel. We hebben in de definitie van de Haal Centraal API juist heel zorgvuldig de verschillende definities van actueel tussen de verschillende LO GBA categorieën gelijkgetrokken.

**Comment by gertjanvanderkooij** [comment]
> @gertjanvanderkooij heb jij een beeld welke processen juist ook de laatst ontbonden partner nodig hebben en welke processen alleen de niet-ontbonden partner nodig hebben?

Kijkend naar de GABA-autorisaties is DatumOntbinding in overgrote deel van de autorsiaties opgenomen. Dat lijkt me niet voor niets. Ook in Autorisatiebesluit 412601 Gemeentelijke Sociale Dienst (zie lijst gemeenten in besluit). Stuur ik wel even via de mail!

**Comment by fsamwel** [comment]
we hebben besloten dat in de Personen bevragen API de partners de meest recente partner gaat bevatten. Dat kan de actuele partner zijn. Wanneer er geen actuele partner is, wordt de laatst ontbonden partner geleverd.
Alleen wanneer er meer dan 1 actuele partners zijn kunnen we meer dan 1 partners worden geleverd.
Dit doen we omdat we op dit moment niet het meest actuele (de laatste) partner leveren en dit wel gevraagd wordt.

- [ ] toevoegen ontbinding aan Partner en aanpassen description (definitie van wat partner is)
- [ ] aanpassen partner feature
