### ISSUE TITLE
Als developer van een client applicatie wil ik de mogelijke waarden van een waardentabel kunnen downloaden

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1006]
zodat ik weet welke mogelijke waarden er zijn en daar mijn code op kan schrijven

Dit betreft ook of met name de velden die in Lo GBA een vaste set mogelijke waarden heeft en in v1.3 van de API nog een enumeratie waren.

Oplossing: 
- elke gebruikte tabel die staat beschreven in de [tabelwaarden feature](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/develop/features/tabelwaarden.feature) beschikbaar stellen via de [tabellen API](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-tabellen-bevragen)
- bij elk veld dat gedefinieerd is als Waardetabel aangeven welke tabel gebruikt is

**Comment by melsk-r** [comment]
> * bij elk veld dat gedefinieerd is als Waardetabel aangeven welke tabel gebruikt is

Waar wil je dit doen? In de API specificatie?

**Comment by fsamwel** [comment]
> Waar wil je dit doen? In de API specificatie?

Ja. Dat kan helaas niet in de description van het veld zelf, dus moet in de groep waar het veld in zit. 

Dus bijvoorbeeld voor veld naam.aanduidingNaamgebruik wordt de description van naam (NaamPersoon) een toelichting toegevoegd dat "aanduidingNaamgebruik" waarden uit de tabel met tabelidentificatie "Aanduiding_Naamgebruik" (of wat we ook kiezen als identificatie van die tabel) kan bevatten.
