### ISSUE TITLE
indicatie onbekend property heeft verschillende naam voor de xxxOnbekend schema componenten

### ISSUE THREAD

**Issue by MelvLee** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1023]
datum: onbekend
kind: indicatieOnbekend
nationaliteit: geen
ouder: indicatieOnbekend
partner: indicatieOnbekend
verblijfplaats: verblijfplaatsOnbekend

Is het niet handig om deze gelijk te trekken?

**Comment by CathyDingemanse** [comment]
Ja absoluut. 

Ik kan mij voorstellen dat we minimaal  de naamgeving van de polymorfische types gelijk trekken (datum, nationaliteit verblijfplaats), en de naamgeving van de indicaties gelijktrekken. 

@JohanBoer, doe jij een voorstel?

**Comment by fsamwel** [comment]
onbekend voor ouder, partner en kind vervalt a.g.v. #940
verblijfplaats onbekend zit in #974. is daar niet nodig en kan dus vervallen

daarmee blijft alleen onbekend in datum over.
