### ISSUE TITLE
wordt met de nationateit property van Nationaliteit schema component niet soort nationaliteit bedoeld?

### ISSUE THREAD

**Issue by MelvLee** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1024]
Is daarom soort of soortNationaliteit geen betere naam voor de nationaliteit property?

**Comment by CathyDingemanse** [comment]
we hebben de types: nationaliteit onbekend, vastgesteldNietNederlander, Staatloos en nationaliteit. De laatste heeft een waardentabel met de volgende omschrijvingen: Belgische (nationaliteit), Duitse (nationaliteit), Franse (nationaliteit), etc...

Lijkt soort nationaliteit dan niet meer op de types die we hebben?

**Comment by MelvLee** [comment]
Ja, dat is zo. Maar de vraag is of het handig is om elke nationaliteit als een component schema te moduleren. Een reden om een type te introduceren als er velden zijn die bij de ene soort nationaliteit wel voorkomt en bij de andere niet (wat we bij de datums hebben gedaan). Een andere reden zou zijn dat er nationaliteiten zijn die eigenlijk niet een nationaliteit zijn zoals onbekend, vastgesteld niet nederlander, staatloos, etc. En een andere reden kan zijn dat de betreffende nationaliteiten veel worden gebruikt, bijv. de Nederlandse. Als een consumer nu wilt weten of iemand de Nederlandse nationaliteit heeft, moet hij eerst checken of de type gelijk is aan 'Nationaliteit' en dan kijken of nationaliteit.code gelijk is aan 0001

**Comment by fsamwel** [comment]
Component Nationaliteit in nationaliteit.yaml wordt NationaliteitBekend. Dit lost ook #1106 op.

**Comment by JohanBoer** [comment]
Tevens NationaliteitInOnderzoek gewijzgd in NationaliteitBekendInOnderzoek
