### ISSUE TITLE
Als PO wil ik dat nationaliteit geen magic strings meer bevat

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1025]
...zodat voor de gebruiker duidelijk is of persoon een nationaliteit heeft, wordt behandeld als Nederlander, de nationaliteit onbekend is, of staatloos is.  

Als code 00002 of 0500 heb je geen nationaliteit, maar is persoon van het type "behandeldAlsNederlander"
Voorgesteld wordt om:

- een type "Staatloos" te introduceren als waarde = ‘Staatloos’ (code 0499)
- een type "nationaliteit onbekend" te introduceren als waarde = "onbekend" (code 0000)

@gertjanvanderkooij , dank voor de input!

@fsamwel, zou jij hiervoor een feature kunnen opstellen?

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by MelvLee** [comment]
Klopt het dat 'behandeld als Nederlander' en 'vastgesteld als niet-Nederlander' op twee manieren kan worden aangegeven? Namelijk via nationaliteit code, resp 0002 en 0500 en met LO element 65.10 aanduiding bijzonder Nederlanderschap?

**Comment by fsamwel** [comment]
> Klopt het dat 'behandeld als Nederlander' en 'vastgesteld als niet-Nederlander' op twee manieren kan worden aangegeven? Namelijk via nationaliteit code, resp 0002 en 0500 en met LO element 65.10 aanduiding bijzonder Nederlanderschap?

Ja. De ene (code voor nationaliteit) is de oude manier. De onderere (aanduiding bijzonder Nederlanderschap) is de nieuwe manier. De oude manier zou niet meer moeten voorkomen, maar het is niet uitgesloten dat het toch nog voorkomt bij bepaalde personen.
