### ISSUE TITLE
In Datum zijn verschillende velden required die niet gevraagd hoeven te zijn met fields

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1038]
In de verschillende Datum componenten in datum.yaml zijn velden datum, jaar, maand en onbekend required.

Het is echter mogelijk dat met fields niet om een required veld gevraagd is.
Bijvoorbeeld:
- fields=geboorte.datum.datum
- fields=geboorte.datum.langFormaat
- fields=geboorte.datum.type

volgens de huidige fields.feature zouden in die gevallen niet alle required velden geleverd worden. Het antwoord voldoet dan niet aan het gedefinieerde schema.

Wat is hier de beste oplossing?
1. required op deze velden verwijderen uit specificaties
2. uitzondering toevoegen aan fields.feature

Nadeel van de eerste optie is dat de specificaties minder beschrijvend worden voor deze polymorfe types.
Nadeel van de tweede optie is dat fields nóg een uitzondering erbij krijgt en dus weer complexer wordt.

**Comment by JohanBoer** [comment]
Wat is de overweging (geweest) om datum required te maken ? Bij nader inzien denk ik dat langFormaat niet requiered hoeft te zijn. Als die niet nodig is hoeft die ook niet geretourneerd te worden. Ik kan me ook voorstellen dat een consumer alleen langFormaat zou willen vragen. 

Wat mij betreft dus required verwijderen, ook voor de datum.

**Comment by MelvLee** [comment]
Ik zou er niet voor kiezen om het igv datum de properties optioneel te maken. Ik kan mij niet voorstellen dat een consumer alleen langFormaat zou vragen, want zodra hij maar iets van logica op basis van datum heeft (bijv. sorteren), dan heeft hij de andere properties nodig.
Een andere reden is dat datum een simple type is als integer of string of zelfs coördinaat. We hebben er een complex type van gemaakt om onvolledige datums te kunnen ondersteunen.

**Comment by fsamwel** [comment]
we kiezen ervoor om de toevoeging te doen in fields zodat altijd alle velden van de datum worden geleverd, ook wanneer maar één veld van de datum wordt gevraagd
