### ISSUE TITLE
Toevoegen links naar develop (i.o.) op GitHub pages

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1059]
naast v1.0 en v2.0 Beto ook in ontwikkeling versie toevoegen op GitHub pages

**Comment by fsamwel** [comment]
**Specificaties v. 2.0 beta (API lab)**
Getting started proefomgeving
Bevragen API (redoc)

**Specificaties v. 2.0 (IO)**
Getting started proxy
User stories
Bevragen API (redoc)
Features

De lijst met features moet ook worden bijgewerkt, zodat niet meer verwezen wordt naar oude features die niet meer bestaan

**Comment by fsamwel** [comment]
voor de mensen van RvIG (en ook voor mij trouwens) is het ook handig wanneer er voor de develop versie ook een link komt naar de gba-genereerversie met Redoc. Voeg je die ook toe?

**Comment by melsk-r** [comment]
We hebben straks in het side-menu 2 links staan naar een redoc omgeving waarin een 2.0.0 versie van de genereervariant staat. 
* Een voor v. 2.0 beta (API lab)
* Een voor v. 2.0 (IO)

Qua versienummer is er geen verschil te zien tussen beide pagina's. Is het niet verstandig er voor te zorgen dat in de redoc versie van de beta variant ook te zien is dat het om de beta variant gaat. Daarvoor is wel een aanpassing nodig van [genereervariant](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/v2.0.0beta1/specificatie/genereervariant/openapi.yaml) en [gba-genereervariant](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/v2.0.0beta1/specificatie/gba-genereervariant/openapi.yaml) in de tag v2.0.0beta1.

**Comment by MelvLee** [comment]
> We hebben straks in het side-menu 2 links staan naar een redoc omgeving waarin een 2.0.0 versie van de genereervariant staat.
> 
>     * Een voor v. 2.0 beta (API lab)
> 
>     * Een voor v. 2.0 (IO)
> 
> 
> Qua versienummer is er geen verschil te zien tussen beide pagina's. Is het niet verstandig er voor te zorgen dat in de redoc versie van de beta variant ook te zien is dat het om de beta variant gaat. Daarvoor is wel een aanpassing nodig van [genereervariant](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/v2.0.0beta1/specificatie/genereervariant/openapi.yaml) en [gba-genereervariant](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/v2.0.0beta1/specificatie/gba-genereervariant/openapi.yaml) in de tag v2.0.0beta1.

Ik weet het niet 100% zeker (moet je uitproberen in je fork), maar volgens mij kan je in de redoc-io.md tussen regel 6 en 7 ook gewoon tekst toevoegen. Dan hoeft je de openapi.yaml niet aan te passen

**Comment by melsk-r** [comment]
> Ik weet het niet 100% zeker (moet je uitproberen in je fork), maar volgens mij kan je in de redoc-io.md tussen regel 6 en 7 ook gewoon tekst toevoegen. Dan hoeft je de openapi.yaml niet aan te passen

Is inderdaad gelukt.
