### ISSUE TITLE
toevoegen europeesKiesrecht aan waardetabel feature

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1062]
https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/pull/1052#issuecomment-1125089029

**Comment by melsk-r** [comment]
Wat zijn de te gebruiken codes in deze tabel en wat zijn de bijbehorende omschrijvingen?

**Comment by fsamwel** [comment]
1 persoon is uitgesloten
2 persoon ontvangt oproep

**Comment by melsk-r** [comment]
Is in voorzien m.b.v. PR #1069.
