### ISSUE TITLE
tabelwaarden komen niet altijd overeen met omschrijving in LO GBA

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1063]
Voor enumeraties (mogelijke waarden) die in de API als Waardetabel zijn opgenomen, zijn de mogelijke waarden opgesomd in tabelwaarden.feature.

Deze waarden zijn soms net iets anders dan in het LO staat. Dat mag denk ik niet, zou gezien worden als bewerking. En is denk ik niet nodig, gewijzigde omschrijvingen zijn niet noodzakelijk veel duidelijker dan hoe het in LO staat.

Bijvoorbeeld aanduidingNaamgebruik
```
    | code                                             | omschrijving                               |
    | ------------------------------------------------ | ------------------------------------------ |
    | E                                                | gebruik alleen de eigen naam               |
    | N                                                | gebruik de eigennaam voor de partnernaam   |
    | P                                                | gebruik alleen de partnernaam              |
    | V                                                | gebruik de partnernaam voor de eigen naam  |
```

In het LO is dit:
E (= eigen geslachtsnaam)
P (= geslachtsnaam echtgenoot/geregistreerd partner)
V (= geslachtsnaam echtgenoot/geregistreerd partner voor eigen geslachtsnaam)
N (= geslachtsnaam echtgenoot/geregistreerd partner na eigen geslachtsnaam)

Ik stel voor dat we de tabelwaarden gelijktrekken met de LO omschrijvingen. Graag ook op andere tabellen checken.

**Comment by melsk-r** [comment]
Is in voorzien m.b.v. PR #1069.
