### ISSUE TITLE
Gezag_Minderjarige ten onrechte opgenomen in tabelwaarden feature

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1065]
In de tabelwaarden.feature staat de tabel "Gezag_Minderjarige" opgesomd. Dat is niet terecht. In tabelwaarden zijn verder alleen waarden opgenomen waar geen landelijke tabel voor is. Dit zijn allen tabellen die zijn afgeleid van mogelijke waarden voor een element in het LO. 

"Gezag_Minderjarige" is tabel 61.

Dus moet m.i. deze tabel worden verwijderd uit de tabelwaarden.feature

**Comment by melsk-r** [comment]
Is in voorzien m.b.v. PR #1069.
