### ISSUE TITLE
velden in gezagsverhouding

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1075]
velden indicatieCurateleRegister en indicatieGezagMinderjarige uit deze groep halen en in de persoon zetten

reden: gegevens horen eigenlijk niet bij elkaar, que autorisatie.

bijvoorbeeld als je vraagt om indicatieGezagMinderjarige bij een persoon met indicatieCurateleRegister, zou je een leeg object leveren, waaruit je zou kunnen concluderen dat er indicatieCurateleRegister is, terwijl daar geen autorisatie voor is en daar niet om gevraagd is

**Comment by MelvLee** [comment]
Volgens mij missen we in de aanpassingen in p.r #1078 een GBA inOnderzoek veld voor Gezagsverhouding. Omdat Gezagsverhouding een categorie is, kan het inOnderzoek veld van GBAPersoon niet ook voor Gezagsverhouding in onderzoek worden gebruikt. Er kunnen tegelijk categorie 1 en categorie 11 gegevens in onderzoek staan, denk ik. Is mijn analyse correct?

**Comment by MelvLee** [comment]
en de mapping bestanden moet hiervoor ook opnieuw worden gegenereerd

**Comment by fsamwel** [comment]
> Volgens mij missen we in de aanpassingen in p.r #1078 een GBA inOnderzoek veld voor Gezagsverhouding. Omdat Gezagsverhouding een categorie is, kan het inOnderzoek veld van GBAPersoon niet ook voor Gezagsverhouding in onderzoek worden gebruikt. Er kunnen tegelijk categorie 1 en categorie 11 gegevens in onderzoek staan, denk ik. Is mijn analyse correct?

je hebt helemaal gelijk. in GbaPersoon zou dus een gezagsverhouding inOnderzoek moeten worden toegevoegd

**Comment by fsamwel** [comment]
besproken dat de volgende structuur wordt gekozen:
```
inOnderzoek	
	datumIngangOnderzoekPersoon	object (AbstractDatum)
	datumIngangOnderzoekGemeente	object (AbstractDatum)
	datumIngangOnderzoekGezag		object (AbstractDatum)
	burgerservicenummer				boolean
	geslacht							boolean
	leeftijd							boolean
	gemeenteVanInschrijving			boolean
	datumInschrijvingInGemeente		boolean
	indicatieCurateleRegister			boolean
	indicatieGezagMinderjarige			boolean
```

in description bij de datums moet worden gezet op welke velden deze datums betrekking hebben.

In de GbaPersoon moeten dus ook 3 velden GbaInOnderzoek komen i.p.v. één:
- persoonInOnderzoek
- gezagInOnderzoek
- gemeenteInOnderzoek
