### ISSUE TITLE
Welke tooling kan worden gebruikt voor het genereren van java-code uit OAS3?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#11]
We willen vaststellen dat uit de Open API Specificaties (we gebruiken versie 3) code kan worden gegenereerd.

Is er tooling om dit te doen voor java op basis van Open API Specificaties versie 3?

**Comment by joeribekker** [comment]
Jazeker, voor bijna alle programmeertalen:

* https://swagger.io/tools/swagger-codegen/
* http://openapi.tools/

**Comment by fsamwel** [comment]
Joeri,
Beide tools ondersteunen OAS3 nog niet. Ze kondigen wel aan dit binnenkort te willen toevoegen, maar nu nog niet. Vandaag mijn vraag of er ergens anders al wel tooling is die dit kan.

**Comment by ehotting** [comment]
OAS3 codegeneratie is nog sterk in ontwikkeling, bijv hier: https://github.com/RSuter/NSwag

**Comment by joeribekker** [comment]
Oh? Ik heb het niet getest maar op de 2e link staat dat Senya dit voor Java ondersteund?

**Comment by fsamwel** [comment]
Inmiddels kan het genereren van java wel vanuit Swagger voor OAS3
<img width="409" alt="schermafbeelding 2018-09-20 om 17 07 28" src="https://user-images.githubusercontent.com/37143495/45827954-c736c700-bcf7-11e8-8c88-40e21390bad4.png">
<img width="413" alt="schermafbeelding 2018-09-20 om 17 07 36" src="https://user-images.githubusercontent.com/37143495/45827965-caca4e00-bcf7-11e8-8468-7cf90dca99f8.png">
