### ISSUE TITLE
inOnderzoek voor adressering uit 3 categorieën

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1113]
Net als beschreven in https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/issues/1075#issuecomment-1134594109 wordt ook adressering uit 3 categorieën: persoon (naam en geslacht), partner en verblijfplaats (adresregels). Er kunnen dus ook 3 verschillende datumIngangOnderzoek zijn.

Dus moet AdresseringInOnderzoek (in adressering.yaml) 3 versies van datumIngangOnderzoek hebben:

- datumIngangOnderzoekPersoon
- datumIngangOnderzoekPartner
- datumIngangOnderzoekVerblijfplaats

Ook de inOnderzoek feature moet hierop worden aangepast, zie https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/issues/1045#issuecomment-1142236228

**Comment by melsk-r** [comment]
@fsamwel Is inmiddels doorgevoerd, dit issue kan n.m.m. dus gesloten worden.
