### ISSUE TITLE
Abstract scenario 'vragen om <fields> bij <in onderzoek> in onderzoek' in 'in_onderzoek.feature' incorrect

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1118]
Daar worden de volgende regels ten onrechte toegevoegd:

```
En heeft de persoon GEEN 'naam.inOnderzoek' gegevens
En heeft de persoon GEEN 'geboorte.inOnderzoek' gegevens
En heeft de persoon GEEN 'verblijfplaats' gegevens
```
De eerste twee omdat betreffende velden helemaal niet in de response van het gba post bericht voorkomen maar pas in de response die de proxy genereert.
De derde omdat 'verblijfplaats' helemaal niet gevraagd en het dus al logisch is dat die niet geleverd moet worden.

**Comment by fsamwel** [comment]
niet mee eens voor de eerste twee regels die je noemt. wat jij zegt is precies waarom het in het scenario staat: GbaPersoon mag geen inOnderzoek volgens Persoon structuur leveren

de derde regel is inderdaad een beetje vreemd, er zijn volgens de Gegeven stappen geen verblijfplaats gegevens en daar wordt ook niet om gevraagd. mee eens dat die overbodig is en weg moet

**Comment by melsk-r** [comment]
Dit scenario komt inmiddels niet meer in deze vorm voor, issue kan gesloten worden.
