### ISSUE TITLE
Wat is het verschil tussen de scenario's 'persoon heeft <groep> <veld> in onderzoek' en 'persoon heeft <veld> van <groep> in onderzoek'

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1119]
In 'in_onderzoek.feature' komen de scenario's 
* 'persoon heeft &lt;groep> &lt;veld> in onderzoek' 

en 
* 'persoon heeft &lt;veld> van &lt;groep> in onderzoek' 

voor. Wat is het verschil tussen beide scenario's?

**Comment by fsamwel** [comment]
de eerste heeft Gegeven stap: En de persoon heeft de volgende 'inOnderzoek' gegevens
de tweede heeft Gegeven stap: En de persoon heeft de volgende '<groep>.inOnderzoek' gegevens

dus de eerste gaat over onderzoek uit de categorie Persoon, die in groepen naam of geboorte terechtkomen
de tweede gaat over onderzoek van andere categorieën

**Comment by melsk-r** [comment]
Beide formuleringen komen niet meer voor in 'in_onderzoek.feature' dus ik ga dit issue sluiten.

> de tweede heeft Gegeven stap: En de persoon heeft de volgende '.inOnderzoek' gegevens

Ik vermoed overigens dat de '.' in '.inOnderzoek' een type foutje was en dat daar dus geen betekenis aan toegekend mag worden.
