### ISSUE TITLE
Scenario 'hele categorie verblijfplaats van een adres is in onderzoek' is incorrect

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1123]
Het scenario 'hele categorie verblijfplaats van een adres is in onderzoek' in 'in_onderzoek.feature' is n.m.m. niet correct.
* De titel klopt denk ik niet, wellicht moet deze 'hele categorie verblijfplaats van een **persoon** is in onderzoek' luiden.
* De regel 'Dan heeft het kind met burgerservicenummer '555550002' de volgende 'verblijfplaats.inOnderzoek' gegevens' klopt niet:
  * ten eerste omdat er in de rest van het scenario met geen woord wordt gerept over een kind;
  * ten tweede omdat de groep 'kinderen' helemaal geen 'verblijfplaats' property kent.
* De regels daarna zijn volgens mij ook niet correct o.a. omdat daarin properties staan (bijv. 'datumVestigingInNederland')  die helemaal niet in 'verblijfplaats.inOnderzoek' te vinden zijn.

**Comment by melsk-r** [comment]
Nu begrijp ik de titel pas. Wat hier bedoeld wordt is 'hele categorie verblijfplaats **als een 'adres'-type** is in onderzoek'.
Wellicht de titel op die wijze aanpassen.

**Comment by melsk-r** [comment]
Bij de scenario's:
* hele categorie verblijfplaats van een locatiebeschrijving is in onderzoek
* hele categorie verblijfplaats van een verblijfplaats buitenland is in onderzoek

spelen gelijksoortige issues.

**Comment by fsamwel** [comment]
Moet het zoiets worden?
- hele categorie verblijfplaats is in onderzoek bij een Nederlands adres
- hele categorie verblijfplaats is in onderzoek bij een locatie
- hele categorie verblijfplaats is in onderzoek bij een buitenlandse verblijfplaats

**Comment by melsk-r** [comment]
Correcties zijn inmiddels aangebracht en ook de door fsamwel voorgestelde titels zijn nu in gebruik. Issue kan gesloten worden.
