### ISSUE TITLE
Titel scenario 'indicatieOverleden van de persoon in onderzoek omdat <gegeven in onderzoek> is in onderzoek' incorrect

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1124]
De titel van het scenario 'indicatieOverleden van de persoon in onderzoek omdat &lt;gegeven in onderzoek&gt; is in onderzoek' in 'in_onderzoek.feature' suggereert dat er in het scenario ergens een kolom is die 'gegeven in onderzoek' heet. Die kolom is er echter niet.

**Comment by fsamwel** [comment]
In voorbeelden moet kolom "reden" worden gewijzigd in "gegeven in onderzoek"

**Comment by melsk-r** [comment]
Correctie is inmiddels aangebracht. Issue wordt gesloten.
