### ISSUE TITLE
Is het bieden van de mogelijkheid voor het gebruik van fields om het antwoord in te perken gewenst?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#114]
N.a.v. https://github.com/Geonovum/KP-APIs/issues/16#issuecomment-444223642 van Gert Jan.

De API strategie stelt:
> De gebruiker van een API heeft niet altijd de volledige representatie (lees alle velden) van een resource nodig. De mogelijkheid bieden om de gewenste velden te selecteren helpt bij het beperken van het netwerkverkeer (relevant voor lichtgewicht toepassingen), vereenvoudigt het gebruik van de API en maakt deze aanpasbaar (op maat). Om dit mogelijk te maken wordt de query-parameter fields ondersteund. 

- Is het beperken van het netwerkverkeer nog een argument? Kijkend naar de autorisatieregels en de splitsing van resources, dan resteert bij een goed gevulde PL ik denk zo’n 10 Kb data. Daar kan igv PL-en het probleem echt niet zitten.

- Of het gebruik van de API voor de consumer wordt vereenvoudigd is arbitrair. Ik moet nu ergens een lijstje bijhouden van gegevens die ik kan opnemen in de Fields. 

Uit de scenario’s blijkt ook wel dat als je Fields wil gebruiken voor bv. alleen de relatie Partners, dat je dan de scope van de resource zelf (de Persoon) eigenlijk ook moet gaan opnemen in de parameter. Als je hiervan alles zou willen zien, ben je minimaal verplicht om alle ‘groepen’ op te nemen. 

Nodigt niet uit tot gebruik. Alternatief is gehele antwoord conform de ingestelde centrale en lokale autorisaties te retourneren en op het device alleen de benodigde elementen te tonen. Op het device moeten toch al ‘opmaak’-zaken worden uitgevoerd. 

- Aan providerside ook extra inspanning: 
  - Aan providerside moeten controles worden uitgevoerd en moet een opgehaald antwoord extra worden gefilterd; naast autorisatie ook op de gevraagde scope.
  - In de logging moet rekening gehouden worden met de daadwerkelijk opgevraagde informatie. Als gehele responses worden gelogd, dan geen probleem. Als alleen de meta-gegevens worden gelogd, dan extra inspanning voor tijdens de vraag geldende ‘autorisatieregels’ en in vraag opgegeven Fields. Hierbij ga ik er vanuit dat ook bij de bron wordt gelogd. 

- Tegen het argument ‘op maat’ is niets in te brengen, maar zal dit in de praktijk vaak worden gebruikt? Is nogal bewerkelijk en je moet dan ook compleet zijn. Als je beperkte uitvoer wenst zou je dit ook via aparte ‘lokale’ autorisatie-instellingen kunnen regelen (applicatie X bevraagt in de rol van Y). Is er een gebruikersbehoefte voor gebruik Fields?

**Comment by ehotting** [comment]
Door met fields parameter te werken kan de developer zelf reduceren welke data wordt opgevraagd, dat is wenselijk in kader 'privacy by design'. Wanneer je autorisatie hebt voor 10 velden maar je hebt er slechts 3 nodig, dan vraag je alleen die drie op.

**Comment by CathyDingemanse** [comment]
Eens met Eelco, en Gert-Jan, zo is het ook bedoeld/gemodelleerd:

Met fields geef je aan welke attributen en/of gegevensgroepen van de resource INP je wilt raadplegen, en welke relaties met andere (sub)resources ER ZIJN (alleen de href, niet het raadplegen van de subresource).

We hebben in deze API verschillende manieren om een relatie te definieren, ieder met een eigen motivatie daarvoor:
- gegevensgroep (verblijfplaats)
- subresource (ouder, kind, partner)
- gerelateerde resource (reisdocument)

Alleen de bovenste kan met de fields parameter echt worden geraadpleegd (zonder de rest van resource). Ik heb aan Frank gevraagd om:

- het gebruik van de fields parameter, 
- het raadplegen van gerelateerde resources en subresources
- en het gebruik van de expand parameter 

in Guirkin te beschrijven, zodat we morgen a.d.h.v. conrete voorbeelden kunnen zien en bespreken hoe het werkt/ moet werken.

**Comment by gertjanvanderkooij** [comment]
👍
