### ISSUE TITLE
Brpservice plaatst plaatsnaam in code

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1140]
Bijvoorbeeld:
```
 {
    "fields": ["geboorte.plaats" ],
    "type": "RaadpleegMetBurgerservicenummer",
    "burgerservicenummer": [ "000009866" ]
}
```

levert:
```
            "geboorte": {
                "plaats": {
                    "code": "Banda-Neira"
                }
            }
```

De geboorteplaats (in principe elke plaats in de API) kan een gemeentecode bevatten of een buitenlandse plaatsnaam of locatiebeschrijving. Dus wanneer de plaats bestaat uit 4 cijfers (ongelijk aan 0000), moet die in plaats.code worden gezet (en moet de omschrijving daarvan in de tabel worden opgezocht). Wanneer de plaats bestaat uit iets anders dan 4 cijfers moet deze worden geplaatst in plaats.omschrijving en wordt plaats.code niet geleverd.

N.B. dit gaat denk ik niet fout in de proxy, maar in de brpservice. Is wel relevant om de combinatie te kunnen gebruiken als proefomgeving voor een leverancier of afnemer.

**Comment by MelvLee** [comment]
Is het niet zonde om deze logica te implementeren in een mock?

**Comment by fsamwel** [comment]
@CathyDingemanse  dat is eigenlijk een vraag aan jou. Is het de bedoeling dat de combinatie mock plus proxy door aansluiters wordt gebruikt als proef omgeving? Dus moet ook de mock goed genoeg daarvoor zijn?

**Comment by CathyDingemanse** [comment]
> @CathyDingemanse dat is eigenlijk een vraag aan jou. Is het de bedoeling dat de combinatie mock plus proxy door aansluiters wordt gebruikt als proef omgeving? Dus moet ook de mock goed genoeg daarvoor zijn?

Ja graag!

**Comment by MelvLee** [comment]
Bij conversie van gba-v testset wordt dit voor de mock uitgevoerd
