### ISSUE TITLE
verwijder indicatieHuwelijkPartnerschapBeeindigd uit ontbindingHuwelijkPartnerschap inOnderzoek

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1180]
partners.ontbindingHuwelijkPartnerschap.inOnderzoek bevat nog indicatieHuwelijkPartnerschapBeeindigd. Die moet eruit

**Comment by JohanBoer** [comment]
Deze is inderdaad al doorgevoerd.
