### ISSUE TITLE
uitbreiden verblijfstitel feature op niet leveren 00 en 98 verblijfstitels

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1200]
in onbekend_waardes.feature staat in geval van Aanduiding verblijfstitel=00 (onbekend), dat de aanduiding niet geleverd moet worden. In dat geval zou er wel een verblijfstitel geleverd worden met een datumIngang en evt. datumEinde, maar geen aanduiding.
@CathyDingemanse klopt dit? Of wil je de verblijfstitel dan niet geleverd krijgen?

Over Aanduiding verblijfstitel=98 (geen verblijfstitel (meer)) is er niks gespecificeerd. moeten we die dus gewoon leveren?

Dit heeft betrekking op zowel de actuele verblijfstitel als de verblijfstitelhistorie

**Comment by CathyDingemanse** [comment]
voor nu: 
00 onbekend leveren als verblijfstitel met de waarde onbekend. Code 00 en omschrijving onbekend. Je kunt immers geen uitspraak doen over of iemand wel of geen verblijfstitel heeft.
Ik ben wel benieuwd wat de bedoeling is van deze waarde. voor welke gevallen/situaties is deze waarde in het leven geroepen? waarom niet het registreren achterwege laten?

verblijfstitel = 98 gewoon niet leveren. Iemand heeft immers geen verblijfstitel, en we willen voorkomen dat dit wordt geïnterpreteerd als dat iemand wel een verblijfstitel heeft (omdat men het type niet goed heeft gezien).

**Comment by fsamwel** [comment]
Ik heb nagevraagd. Volgens de IND is dit geen code die ze nu actueel gebruiken.
Voor de zekerheid blijft de code wel in de tabel staan voor situaties dat er iets fout is met een aangeleverde code en dit dan als default opgenomen kan worden door het ontvangende systeem. In die situatie moet de interpretatie dan zijn: er is een verblijfstitel, maar we weten niet welke. Dan moet er bij een verblijfstitel wel aanduiding 00 met omschrijving worden geleverd, zodat dit duidelijk is

**Comment by JohanBoer** [comment]
Dit is inmiddels verwerkt en staat netjes zoals beschreven in develop
