### ISSUE TITLE
Voeg een scenario voor een dubbele nationaliteit toe

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1209]
Voeg in nationaliteit.feature een scenario voor een dubbele nationaliteit toe.

**Comment by fsamwel** [comment]
scenario bestaat al of is inmiddels al toegevoegd: "Scenario: persoon heeft meerdere nationaliteiten" in nationaliteit.feature.
