### ISSUE TITLE
Als PO wil ik verplicht leveren dat een RNI gegeven is verstrekt door een bestuursorgaan of is geverifieerd door een ABO, inclusief verificatiedatum

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1213]
...zodat de API compliant is aan wet- en regelgeving.

Vanuit de verantwoordelijkheid van MinBZK voor de verstrekkingen uit de BRP, is ervoor gekozen dat bepaalde metagegevens altijd moeten worden meeverstrekt. Die metagegevens zijn:
-	Gegeven staat in onderzoek [groep 83, heeft ook nog een juridische consequentie, namelijk dat de ontvanger van dit (authentieke) gegeven mag afwijken zonder daarover een terugmelding te doen]
-	Gegevens is gemarkeerd als onjuist (groep 84, komt bij ad hoc bevraging niet voor, want daar worden onjuiste gegevens nooit verstrekt)
-	De aanduiding dat het gegeven is verstrekt door een Aangewezen Bestuursorgaan (komt uitsluitend voor bij niet-ingezetenen, gaat om de aanlevering zelf (groep 88) of de mededeling dat is geverifieerd (groep 71) door de ABO dat de opgenomen gegevens nog correct zijn incl de datum waarop dat is gebeurd)
-	Het feit of de burger om geheimhouding van zijn gegevens heeft verzocht (groep 70, 

Zoeken in de BRP, ook als dat via de API wordt gedaan, is een verstrekking (op basis van een zoekvraag) in de zin van de BRP-regelgeving. Dat betekent dat artikel 3.10 Wet BRP van toepassing is, voor alle bovengenoemde metagegevens. 
Als iets op niveau van de Wet BRP (hoogste niveau qua Nederlandse regelgeving) is bepaald, kan daar niet op het niveau van AMvB (Besluit BRP) of ministeriële regeling (Regeling BRP, Logisch Ontwerp) worden afgeweken. Dat is niet impliciet, maar wettelijk zo geregeld. 

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by fsamwel** [comment]
zie concept voor wijzigingsvoorstel LO BRP specificaties, waarin staat waar deze gegevens in de GBA versie moeten komen
[W162 LO BRP v0.4 - Haal Centraal API's Fase I.docx](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/files/9336929/W162.LO.BRP.v0.4.-.Haal.Centraal.API.s.Fase.I.docx)
.

**Comment by JohanBoer** [comment]
Johan past de OAS aan en de mapping voor de betreffende elementen uit het LO.  
Als dit af is wordt het inbouwen in een sprint opgenomen.

**Comment by JohanBoer** [comment]
De structuur zoals die nu in het wijzigingsvoorstel voor het LO-GBA staat is volgens mij niet correct. Deze is nu als volgt voorgesteld : 
![image](https://user-images.githubusercontent.com/18071357/184862659-3eb9a10b-b3c9-4fc2-a112-90ab6bce931a.png)

De Code en omschrijving die hier genoemd zijn komen uit een waardetabel (Tabel 60).
De Omschrijving gedrag maakt geen deel uit van deze waardetabel. Volgens mij moet er dus nog een property tussengevoegd worden waar de code en omschrijving ( de ref naar de component waardetabel ) in kan worden opgenomen. 
Dan ziet dat er als volgt uit : 

![image](https://user-images.githubusercontent.com/18071357/184863204-d36c8cad-82f5-4a57-b1b3-099b91d24657.png)

Volgens mij moet dit doorgevoerd worden in het wijzigingsvoorstel.

Overigens wordt de property "Verificatie" die in dit voorstel staat ook nergens genoemd in onze OAS. Moet die ook worden toegevoegd aan de specs ?
