### ISSUE TITLE
 scenario 'indicatieVestigingVanuitBuitenland in onderzoek omdat landVanWaarIngeschreven is in onderzoek' incorrect

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1219]
Verwijder het scenario 'indicatieVestigingVanuitBuitenland in onderzoek omdat landVanWaarIngeschreven is in onderzoek' of wijzig het in 'indicatieVestigingVanuitBuitenland in onderzoek omdat datumVestigingInNederland is in onderzoek'.

Zie ook de [opmerking hierover](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/pull/1216#issuecomment-1216819096) in PR #1216.

**Comment by fsamwel** [comment]
waarom verwijderen? Kan toch ook gewijzigd naar 'indicatieVestigingVanuitBuitenland in onderzoek omdat datumVestigingInNederland is in onderzoek'?

**Comment by melsk-r** [comment]
Is inmiddels gewijzigd. Issue kan gesloten worden.
