### ISSUE TITLE
InOnderzoek opnemen in PersoonBeperkt. 

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1230]
Volgens het wijzigingsvoorstel LO-GBA moet in de persoonbeperkt ook InOnderzoek opgenomen worden. Dat is nu nog niet het geval.

**Comment by CathyDingemanse** [comment]
Zou jij dat op je willen nemen?

**Comment by melsk-r** [comment]
Is inmiddels uitgevoerd #1417
