### ISSUE TITLE
Als gebruiker wil ik bij zoeken een afgevoerde PL niet vinden

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1233]
...zodat ik alleen correcte persoonslijsten vind.

Wanneer een PL onterecht is opgevoerd, wordt deze afgevoerd door toevoegen van opschorting bijhouding met reden "F".

Dit moet m.i. gelden voor zoeken, niet voor raadplegen op burgerservicenummer.

Hiervoor toevoegen rule en scenario(s) in zoek-met-... features

**Comment by JohanBoer** [comment]
Scenario's voor deze userstory zijn inmiddels toegevoegd.
