### ISSUE TITLE
Zoeken met wildcard in geslachtsnaam vindt geen personen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1240]
```
{
  "fields": ["burgerservicenummer","naam","geboorte","geslacht","verblijfplaats"],
  "type": "ZoekMetGeslachtsnaamEnGeboortedatum",
  "geboortedatum": "1991-05-05",
  "geslachtsnaam": "Thur*"
}
```

Hier vind ik twee personen in de database: 999994864 en 999995212, maar krijg ik een lege collectie als antwoord.

Wanneer ik aan bovenstaande zoekvraag de geslachtsnaam volledig opneem, zonder wildcard (Thursen), krijg ik wel de verwachte personen.

**Comment by KayodeBakker** [comment]
@fsamwel Is dit nu goed in GBA 2.0.1?

**Comment by JohanBoer** [comment]
Dirt werkt nu conform verwachting. Ik krijg netjes de 2 dames Thursen terug.
