### ISSUE TITLE
Response van GBA API bevat ten onrechte geen onbekende kinderen.

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1247]
In de scenario's:
* kind volledig onbekend, veld met onbekend waarde wordt gevraagd met fields
* kind volledig onbekend, veld met onbekend waarde wordt niet gevraagd met fields

In PR #1229 testen de 'Dan' stappen nog niet correct. Er wordt een lege kinderen array in de response terug gegeven terwijl er volgens mij in die array een leeg kind zou moeten worden terug gegeven. Dit komt omdat de response van de GBA API geen onbekende kinderen bevat (zie ook https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/pull/1229#issuecomment-1243284101).

**Comment by KayodeBakker** [comment]
@fsamwel @MelvLee 
Is er ergens gedefinieerd dat de GBA API een . als naam gewoon moet doorsturen? Nu functioneert het zoals Haal Centraal altijd is omgegaan met placeholders.

**Comment by MelvLee** [comment]
> @fsamwel @MelvLee Is er ergens gedefinieerd dat de GBA API een . als naam gewoon moet doorsturen? Nu functioneert het zoals Haal Centraal altijd is omgegaan met placeholders.

Zie https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/pull/1258/files#diff-8780c679ccb5469feec722a91e8d5d165147c29a14fcfda3d4878d35b88ceee1. De scenario staat op regel 76

**Comment by KayodeBakker** [comment]
Helder. Dit wordt dan opgepakt zodra de features die de GBA API uniek moet ondersteunen dan zijn geïmplementeerd.

**Comment by KayodeBakker** [comment]
Alles bij mij is groen rondom kinderen-gba.feature. Deze kan nu gesloten worden toch?

**Comment by melsk-r** [comment]
kinderen-gba.feature test inderdaad helemaal goed. Ik sluit dit issue.
