### ISSUE TITLE
Response van GBA API bevat ten onrechte geen persoonInOnderzoek (en gezagInOnderzoek)

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1270]
In de scenario's:

* vragen om naam bij hele categorie persoon in onderzoek
* vragen om voorvoegsel zonder waarde bij groep naam persoon in onderzoek
* persoon heeft gezagInOnderzoek en persoonInOnderzoek

in PR #1269 testen de 'Dan' stappen nog niet correct. Er wordt geen 'inOnderzoek' groep gecreëerd in de response. Dit komt omdat de response van de GBA API geen persoonInOnderzoek (en gezagInOnderzoek) groep(en) bevat.

Heeft betrekking op de Haal Centraal GBA API 2.0.1.

**Comment by KayodeBakker** [comment]
@melsk-r Vanuit Frank heb ik vernomen dat InOnderzoek samen met een aantal rubrieken voor iedereen beschikbaar moet worden gesteld en dus zal het daardoor niet worden opgenomen in de autorisatie tabel in de database. Ik ging er dus vanuit dat dit er wel in zou zitten ipv een soort impliciete gedachten goed. Ik zal er een patch voor maken, maar het kan zijn dat het resultaat anders uitpakt aangezien ik dit ook even bij Bert het gesignaleerd.

**Comment by KayodeBakker** [comment]
@melsk-r Ik heb wijzigingen gemaakt voor de autorisaties op inOnderzoek. Kan je bevestigen of deze issue nog relevant is?

**Comment by melsk-r** [comment]
Nee, dit issue is opgelost, ik sluit het issue.
