### ISSUE TITLE
Response van GBA API bevat ten onrechte geen naam groep

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1274]
De scenario's
* vondeling (onbekende ouder met ouderaanduiding "1" en geen ouder met ouderaanduiding "2")
* volledig onbekende ouder

in gba-dev/ouders-gba.feature genereren geen 'naam' groep in de response terwijl deze wel verwacht worden met daarin de property 'geslachtsnaam' met de waarde '.'

Ik krijg dit:
```
[
	{
		"ouders": [
			{
				"ouderAanduiding": "1",
				"geslacht": {
					"code": "V",
					"omschrijving": "vrouw"
				},
				"datumIngangFamilierechtelijkeBetrekking": "20190614"
			}
		]
	}
]
```
maar verwacht dit
```
[
	{
		"ouders": [
			{
				"ouderAanduiding": "1",
				"naam": {
					"geslachtsnaam": "."
				},
				"geslacht": {
					"code": "V",
					"omschrijving": "vrouw"
				},
				"datumIngangFamilierechtelijkeBetrekking": "20190614"
			}
		]
	}
]
```
Heeft betrekking op de Haal Centraal GBA API 2.0.1.

**Comment by KayodeBakker** [comment]
Dezelfde oorzaak speelt hier als genoemd bij issue #1247 .

**Comment by KayodeBakker** [comment]
@melsk-r Volgens mij kan deze worden gesloten niet waar? Bij mij is alles van ouders-gba.feature nu groen.

**Comment by melsk-r** [comment]
Klopt, ouders-gba.feature test nu helemaal goed. Ik sluit het issue.
