### ISSUE TITLE
Response van GBA API bevat ten onrechte geen 'ouders' object

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1275]
Het scenario
* met fields vragen om gegevens zonder waarde

in gba-dev/ouders.feature genereert geen 'ouder' object in de response terwijl deze wel verwacht wordt.

Ik krijg dit:
```
[
	{
	}
]
```
maar verwacht dit
```
[
	{
		"ouders": [
			{
			}
		]
	}
]
```
Heeft betrekking op de Haal Centraal GBA API 2.0.1.

**Comment by KayodeBakker** [comment]
Dit kan ik aanpassen. Even voor mijn beeldvorming, is dit noodzakelijk zodat er kan worden bepaald of de BRP API een ouder met type OnbekendOuder moet definieren?

**Comment by MelvLee** [comment]
> Dit kan ik aanpassen. Even voor mijn beeldvorming, is dit noodzakelijk zodat er kan worden bepaald of de BRP API een ouder met type OnbekendOuder moet definieren?

Als er geen lege ouder wordt terug gegeven, kan een consumer niet bepalen of de betreffende persoon geen ouder heeft of dat de ouder de gevraagde field niet heeft. Ouder, kind en partner zijn niet (meer) polymorfisch

**Comment by melsk-r** [comment]
Klopt, ik sluit het issue.
