### ISSUE TITLE
Onterecht foutmelding unique

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1276]
Wanneer een burgerservicenummer meer dan 1 keer voorkomt in de bron, geeft RaadpleegMetBurgerservicenummer op dat burgerservicenummer een foutmelding:
```
       {
       	"invalidParams": [
       		{
       			"code": "unique",
       			"reason": "De opgegeven persoonidentificatie is niet uniek."
       		}
       	],
       	"type": "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_BadRequest",
       	"title": "Een of meerdere parameters zijn niet correct.",
       	"status": "400",
       	"detail": "De foutieve parameter(s) zijn: ",
       	"instance": "https:///haalcentraal/api/brp/personen",
       	"code": "paramsValidation"
       }
```

Dit is niet meer nodig, omdat de response meer dan 1 persoon kan bevatten. @MelvLee mee eens? Of wil je zeker weten dat raadplegen op bsn nooit meer dan 1 persoon levert? (zo ja, hadden we dat dan niet in de interface specificaties moeten afdwingen?)

N.B. ook de foutmelding detail is voor deze fout niet correct, en bij invalidParams ontbreekt "name": "burgerservicenummer"

N.B. deze situatie hoort niet voor te kunnen komen, een burgerservicenummer hoort wel uniek te zijn.

**Comment by KayodeBakker** [comment]
@fsamwel Ik lees voor nu als enige actiepunt voor mij het gedeelte "ook de foutmelding detail is voor deze fout niet correct, en bij invalidParams ontbreekt "name": "burgerservicenummer"".
De rest merk ik dan wel of er iets voor mij tussen zit als je met Melvin hebt gesproken over een conclusie op jouw vraag aan hem.

**Comment by MelvLee** [comment]
> Wanneer een burgerservicenummer meer dan 1 keer voorkomt in de bron, geeft RaadpleegMetBurgerservicenummer op dat burgerservicenummer een foutmelding:
> 
> ```
>        {
>        	"invalidParams": [
>        		{
>        			"code": "unique",
>        			"reason": "De opgegeven persoonidentificatie is niet uniek."
>        		}
>        	],
>        	"type": "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_BadRequest",
>        	"title": "Een of meerdere parameters zijn niet correct.",
>        	"status": "400",
>        	"detail": "De foutieve parameter(s) zijn: ",
>        	"instance": "https:///haalcentraal/api/brp/personen",
>        	"code": "paramsValidation"
>        }
> ```
> 
> Dit is niet meer nodig, omdat de response meer dan 1 persoon kan bevatten. @MelvLee mee eens? Of wil je zeker weten dat raadplegen op bsn nooit meer dan 1 persoon levert? (zo ja, hadden we dat dan niet in de interface specificaties moeten afdwingen?)
>
Ik begrijp niet wat je bedoelt. Als input kan een lijst van burgerservicenummers worden opgegeven
 
> N.B. ook de foutmelding detail is voor deze fout niet correct, en bij invalidParams ontbreekt "name": "burgerservicenummer"
> 
> N.B. deze situatie hoort niet voor te kunnen komen, een burgerservicenummer hoort wel uniek te zijn.

**Comment by KayodeBakker** [comment]
Hoe pakken we dit nu op? @fsamwel @JohanBoer @CathyDingemanse

**Comment by KayodeBakker** [comment]
@fsamwel @JohanBoer @CathyDingemanse @melsk-r 
Deze heeft nog geen conclusie.

**Comment by fsamwel** [comment]
gevraagd aan RvIG. antwoord is dat dit niet voorkomt in productie. burgerservicenummer wordt nooit dubbel gebruikt
