### ISSUE TITLE
bevragen van veld 'geheimhoudingPersoonsgegevens' geeft niet altijd de verwachte boolean waarde

### ISSUE THREAD

**Issue by MelvLee** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1292]
Dit is het geval voor de waarden 2, 4, 6 en 7

**To Reproduce**
npx cucumber-js features/dev/persoon-velden.feature:58
npx cucumber-js features/dev/persoon-velden.feature:60
npx cucumber-js features/dev/persoon-velden.feature:62
npx cucumber-js features/dev/persoon-velden.feature:63

**Verwacht gedrag**
voor de waarden wordt geheimhoudingPersoonsgegevens = true verwacht

gba-api versie: 2.0.2
brpproxy versie: 2.0.4

**Comment by KayodeBakker** [comment]
@MelvLee Ik voer alle 4 de commandos uit en ik krijg alleen maar groen licht bij alles. Kan je de foutmeldingen aanleveren die je krijgt? Ik voer dit e2e uit met de proxy en gba allebei op 2.0.2. 
Daarnaast als ik de gehele feature uitvoer dan krijg ik errors omdat er al een insert heeft plaatsgevonden van een BSN en die meer dan 1 keer wordt geinsert waardoor de bsn niet meer uniek is. Was dat bekend?

**Comment by MelvLee** [comment]
> @MelvLee Ik voer alle 4 de commandos uit en ik krijg alleen maar groen licht bij alles. Kan je de foutmeldingen aanleveren die je krijgt? Ik voer dit e2e uit met de proxy en gba allebei op 2.0.2. Daarnaast als ik de gehele feature uitvoer dan krijg ik errors omdat er al een insert heeft plaatsgevonden van een BSN en die meer dan 1 keer wordt geinsert waardoor de bsn niet meer uniek is. Was dat bekend?

Als de scenario's wordt uitgevoerd krijg ik niet het volgende terug in de response
```
[
  {
    "geheimhoudingPersoonsgegevens": "true"
  }
]
```
Ik denk dat de proxyUrl in world.js niet de correcte url is. Als de url niet goed staat krijgt je nu geen foutmelding waardoor het lijkt dat het is geslaagd. Ik heb een assertion toegevoegd in de step_defs.js om te checken of de endpoint response terug geeft

**Comment by KayodeBakker** [comment]
Ik betwijfel dat de url niet correct is want dan zouden andere features niet resultaten terug geven. Bijv. bij de kinderen feature zou ik netjes het volgende terug krijgen dat aanduidt wat het hoort te zijn en wat ik retourneer.

```
       AssertionError: actual: [
        {
                "kinderen": []
        }
       ]: expected [ { kinderen: [] } ] to deeply equal [ { kinderen: [ { naam: {} } ] } ]
           + expected - actual

            [
              {
           -    "kinderen": []
           +    "kinderen": [
           +      {
           +        "naam": {}
           +      }
           +    ]
              }
            ]
```

**Comment by MelvLee** [comment]
Ik heb nu geheimhouding scenario's toegevoegd die de gba-api valideren. Als je deze uitvoert, zie je dat het geheimhoudingPersoonsgegevens veld geen consistente gedrag heeft. Zie https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/develop/features/gba-dev/persoon.feature

**Comment by MelvLee** [comment]
fix in v2.0.5
