### ISSUE TITLE
Als gemeente wil ik de juiste en consistente aanschrijfwijze van mijn burgers

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#13]
...zodat ik mijn burgers op de juiste wijze kan aanspreken in correspondentie.

Oplossing: We voegen een veld "aanschrijfwijze" toe aan de resource ingeschrevenNatuurlijkPersoon. In dit veld wordt de naam samengesteld op basis van aanduidingAanschrijving, de naam van de persoon (incl. adelijke titel enz.) en de naam van de partner. 

Het algoritme voor het samenstellen moet worden beschreven in de API specificaties.

Zie ook betreffende beslissing in e [design decisions](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/design_decisions.md)

**Acceptatiecriteria**
- [x] De resource /ingeschrevennatuurlijkpersonen bevat een property "aanschrijfwijze"
- [x] Bij deze property is beschreven hoe het wordt samengesteld uit de verschillende properties van de persoon en de partner.
- [x] Properties van de persoon die niet meer relevant zijn, omdat die alleen gebruikt worden voor de aanschrijfwijze, worden uit het antwoord voor zoeken gehaald.

**Definition of done**
- [x] functionele specificatie
- [x] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by fsamwel** [comment]
Het algoritme voor het samenstellen van de aanschrijfwijze staat in RSGB bevragingen 1.0, §3.4.1. Dit moet worden overgenomen in de API-specificaties, dan wel in een specifiek document in de GitHub, met link daarnaar in de API-specificaties.

**Comment by CathyDingemanse** [comment]
| Mannelijke vorm | Vrouwelijke vorm
-- | -- | --
Titels | Prins | Prinses
  | Hertog | Hertogin
  | Graaf | Gravin
  | Baron | Barones
  | Markies | Markiezin
  | Ridder | geen[2]
Predicaten | Jonkheer | Jonkvrouw

**Comment by JohanBoer** [comment]
Frank, wat bedoel je met het acceptatiecriterium "De partner (geslacht, naam) wordt niet embed in het antwoord" ?    
Dit issue is toch niet gerelateerd met het al dan niet embedden van de partners. ouders of kinderen ? Of wordt naar aanleiding van het opnemen van de aanschrijfwijze de partner niet meer embedded opgenomen. En worden de ouders en kinderen dan ook niet embedded opgenomen ?

**Comment by fsamwel** [comment]
@Johan De laatste twee acceptatiecriteria moeten vervallen. 
>   De partner (geslacht, naam) wordt niet embed in het antwoord.

Was relevant toen we nog erg selectief waren in wat wel of wat niet embed kan worden. Inmiddels is besluit genomen dat elke gerelateerde in het antwoord kan worden embed. 

>  Properties van de persoon die niet meer relevant zijn, omdat die alleen gebruikt worden voor de aanschrijfwijze, worden uit het antwoord voor zoeken gehaald.

Dit moet m.i. niet in de API specificatie worden gehaald, maar moet bij het gebruik van de API worden gedaan, en in de autorisatieprofielen bij gemeenten. De API geeft de volledige resource weer (in ons geval beperkt tot gegevens in de bron BRP)
