### ISSUE TITLE
Is er een reden om Waardetabel te kunnen filteren met fields?

### ISSUE THREAD

**Issue by MelvLee** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1301]
bijv. AdellijkeTitelPredicaat. Je zou met fields alleen code,soort en/of omschrijving opvragen. Maar wat heb je eraan als je alleen code ophaalt? Je hebt soort nodig om te weten of het een adellijke titel betreft of een predicaat en je hebt de omschrijving ook nodig als je de aanschrijfwijze wilt bepalen. Anders moet je dit allemaal in code bijhouden. Is het niet beter om voor Waardetabel hetzelfde toe te passen als bij datum? Dus ongeacht of je [WaardeTabel], [WaardeTabel].code, [WaardeTabel].omschrijving en igv AdellijkeTitelPredicaat de soort vraagt, je krijgt altijd de hele WaardeTabel.

**Comment by CathyDingemanse** [comment]
Ik snap je punt. Daar is een waardetabel tenslotte ook voor. In GraphQL noemen ze dat unions begrijp ik :-). Laten we het advies van de costumer zero opvolgen. 

@KayodeBakker graag het geheel teruggeven. Melvin heeft al dev scenario's gemaakt. Morgen in de dagstart even bespreken.

**Comment by KayodeBakker** [comment]
Dit is uitgevoerd bij de GBA API.

**Comment by MelvLee** [comment]
getest en werkt als gewenst
