### ISSUE TITLE
Bij overlijden in onderzoek wordt de inOnderzoek property niet gevuld als een overlijden veld wordt opgevraagd met fields

### ISSUE THREAD

**Issue by MelvLee** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1302]
**To Reproduce**
npx cucumber-js features/gba-dev/persoon.feature:147

Als fields = overlijden.inOnderzoek dan krijgt je wel de inOnderzoek property terug. Zie: npx cucumber-js features/gba-dev/persoon.feature:127

**Comment by KayodeBakker** [comment]
Op dit moment (gba-api: 2.0.7) is dit geen issue meer. Zie jij dat ook zo?

**Comment by MelvLee** [comment]
> Op dit moment (gba-api: 2.0.7) is dit geen issue meer. Zie jij dat ook zo?

net gevalideerd en het klopt. Ik sluit deze issue
