### ISSUE TITLE
Bij immigratie velden in onderzoek wordt de verblijfplaats.inOnderzoek property niet gevuld als een immigratie veld wordt opgevraagd

### ISSUE THREAD

**Issue by MelvLee** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1303]
**To Reproduce**
npx cucumber-js features/gba-dev/immigratie.feature:38

Het opvragen van immigratie.inOnderzoek gaat wel goed. Zie: npx cucumber-js features/gba-dev/immigratie.feature:19

**Comment by KayodeBakker** [comment]
Op dit moment (gba-api: 2.0.7) is dit geen issue meer. Zie jij dat ook zo?

**Comment by MelvLee** [comment]
> Op dit moment (gba-api: 2.0.7) is dit geen issue meer. Zie jij dat ook zo?

getest. Het is geen issue meer
