### ISSUE TITLE
Reden opname nationaliteit = onbekend wordt ten onrechte niet geleverd. 

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1305]
In features/gba-dev/nationaliteit-gbe.feature wordt in scenario "persoon heeft een nationaliteit met reden opname = onbekend"

de redenOpname en bijbehorende omschrijving niet geleverd. 

Deze zou geleverd moeten worden met code = 000 en omschrijving = Onbekend.

**Comment by KayodeBakker** [comment]
Op dit moment (gba-api: 2.0.7) is dit geen issue meer. Zie jij dat ook zo?

**Comment by JohanBoer** [comment]
Zeker. scenario slaagt nu.
