### ISSUE TITLE
Response van de GBA API mist 'inOnderzoek' property

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1311]
Zie hiervoor scenario's in de volgende regels van in_onderzoek.feature:
* 348
* 366 
* 965 t/m 967
* 998 t/m 1003

Deze ontbreekt daar in resp. 'verblijfplaats', 'verblijfstitel', 'overlijden' en 'ouders'.

**Comment by KayodeBakker** [comment]
Als ik in_onderzoek.feature uitvoer dan krijg ik een hoop undefined. Is dit een feature dat nog in een PR staat en niet in de develop branch? Ik kan niet nabootsen wat jij meldt.

**Comment by melsk-r** [comment]
> * 348
> * 366
> * 965 t/m 967
> * 998 t/m 1003

Niet handig om hier de regelnummers op te sommen. De betreffende scenario's kunnen immers al weer op een heel andere positie terecht zijn gekomen.

* Bij 348 kan ik helaas niet meer achterhalen om welk scenario het ging. Zo nodig voer ik wel een nieuw issue op.
* Bij 366 gaat het om het scenario 'persoon heeft aanduiding van verblijfstitel in onderzoek' dat inmiddels goed test.
* Bij 965 t/m 967 gaat het om het abstracte scenario 'indicatieOverleden van de persoon in onderzoek omdat <gegeven in onderzoek> is in onderzoek' waarvan alle voorbeelden inmiddels goed testen.
* Bij 998 t/m 1003 gaat het om het abstracte scenario 'voorletters van een ouder in onderzoek omdat <gegeven in onderzoek> is in onderzoek' waarvan alle voorbeelden inmiddels goed testen.

Ik sluit dit issue.
