### ISSUE TITLE
Response van GBA API bevat ten onrechte een lege persoon array.

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1312]
Zie hiervoor scenario's in de volgende regels van in_onderzoek.feature:
* 341 t/m 346
* 412 t/m 414
* 436 t/m 438
* 625
* 669
* 730, 731
* 801
* 848

Bij de laatste 3 werd in versie 2.0.2 van de GBA API nog wel content geleverd.

**Comment by KayodeBakker** [comment]
Als ik in_onderzoek.feature uitvoer dan krijg ik een hoop undefined. Is dit een feature dat nog in een PR staat en niet in de develop branch? Ik kan niet nabootsen wat jij meldt.

**Comment by melsk-r** [comment]
Voor de volgende regels van 'informatievragen-fields-gba.feature' geldt hetzelfde:

* 449
* 450
* 451
* 453
* 604
* 605
* 607
* 609

**Comment by melsk-r** [comment]
> * 341 t/m 346
> * 412 t/m 414
> * 436 t/m 438
> * 625
> * 669
> * 730, 731
> * 801
> * 848

* Bij 341 t/m 346 gaat het om het abstracte scenario 'persoon heeft <veld> van verblijfadres in onderzoek' dat inmiddels helemaal goed test.
* Bij 412 t/m 414 gaat het om het abstracte scenario 'persoon heeft <veld> van ouder in onderzoek' dat inmiddels helemaal goed test.
* Bij 436 t/m 438 gaat het om het abstracte scenario 'persoon heeft <groep> <veld> van partner in onderzoek' waarvan het 1e en 3e voorbeeld goed testen. Het 2e voorbeeld genereert geen lege persoon array meer maar wel een leeg 'partners.geboorte' gegeven.
* Bij 625, 669, 730, 731, 801 en 848 is niet goed te achterhalen om welk scenario het gaat. Zo nodig zal ik daarvoor een nieuw issue opvoeren.

Zodra het 2e voorbeeld van het abstracte scenario 'persoon heeft <groep> <veld> van partner in onderzoek' ook goed test zal ik dit issue sluiten.
