### ISSUE TITLE
Response van GBA API bevat ten onrechte een leeg persoon object.

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1313]
Zie hiervoor scenario's in de regels 478, 1040 t/m 1046 en 1048 van in_onderzoek.feature.

In 1040 t/m 1046 werd in versie 2.0.2 van de GBA API nog wel content geleverd.

**Comment by KayodeBakker** [comment]
Als ik in_onderzoek.feature uitvoer dan krijg ik een hoop undefined. Is dit een feature dat nog in een PR staat en niet in de develop branch? Ik kan niet nabootsen wat jij meldt.

**Comment by melsk-r** [comment]
> Zie hiervoor scenario's in de regels 478, 1040 t/m 1046 en 1048 van in_onderzoek.feature.
> 
> In 1040 t/m 1046 werd in versie 2.0.2 van de GBA API nog wel content geleverd.

* Bij 478 gaat het om het scenario 'persoon heeft hele groep naam in onderzoek' dat test nog niet goed maar er wordt geen leeg persoon object meer gegenereerd.
* Bij 1040 t/m 1046 gaat het om het abstracte scenario 'verblijfplaats datumVan in onderzoek omdat <gegeven in onderzoek> is in onderzoek' die testen nog niet goed maar er worden geen lege persoon objecten meer gegenereerd.
* Bij 1048 gaat het om het scenario 'indicatieVestigingVanuitBuitenland in onderzoek omdat datumVestigingInNederland is in onderzoek' dit test nog niet goed maar er wordt geen leeg persoon object meer gegenereerd.

Aangezien geen van de scenario's de gedefinieerde fout meer genereren sluit ik dit issue.
