### ISSUE TITLE
Response van GBA API  bevat ten onrechte een leeg  '<object>' object

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1314]
Zie hiervoor scenario's in de regels 589, 1092 t/m 1103 en 1130 t/m 1138 in in_onderzoek.feature.

Het betreft resp. de objecten 'kind', 'verblijfplaats' en 'nationaliteit'.

**Comment by KayodeBakker** [comment]
Als ik in_onderzoek.feature uitvoer dan krijg ik een hoop undefined. Is dit een feature dat nog in een PR staat en niet in de develop branch? Ik kan niet nabootsen wat jij meldt.

**Comment by melsk-r** [comment]
> Zie hiervoor scenario's in de regels 589, 1092 t/m 1103 en 1130 t/m 1138 in in_onderzoek.feature.

* Bij 589 gaat het om het scenario 'hele categorie kind is in onderzoek' dat inmiddels helemaal goed test.
* Bij1092 t/m 1103 gaat het om het abstracte scenario 'verblijfplaats adresregel1, adresregel2 en woonplaats in onderzoek bij <gegeven in onderzoek> is in onderzoek' dat nog wel fout test maar geen lege verblijfplaats meer teruggeeft.
* Bij 1130 t/m 1138 gaat het om het abstracte scenario '<gegeven in onderzoek> is in onderzoek' dat inmiddels helemaal goed test.

Aangezien geen van deze scenario's nog een leeg object teruggeeft sluit ik het issue.
