### ISSUE TITLE
 Fields waarde 'geboorte.datum.datum' lijkt niet toegestaan.

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1315]
Het voorbeeld van regel 312 in in_onderzoek.feature geeft een 400 melding. Blijkbaar is het niet toegestaan om 'geboorte.datum.datum' uit te vragen. Is dat correct?

**Comment by fsamwel** [comment]
is denk ik een bug. als je een veld van een datum vraagt, moet je alle velden van die datum krijgen. we maken alle velden van datum required, zie #1379

**Comment by fsamwel** [comment]
is inmiddels opgelost
