### ISSUE TITLE
ouder, kind en partner in In onderzoek

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#132]
Op dit moment is voor een persoon onder inOnderzoek een attribuut "kind", "ouder" en "partner" opgenomen.
Er kan dus worden aangegeven dat iets in onderzoek is op een partner of op een kind of op een ouder. is dat de manier hoe dat moet worden teruggegeven? Of moet er worden aangegeven voor welke ouder iets in onderzoek is?

**Comment by gertjanvanderkooij** [comment]
In lijn met eerdere ontwerpbeslissingen #74 verwacht ik ook hier het specifiek aan geven van welke ouder/welk kind in onderzoek is. Idem voor welke partner bij de historie-bevraging Partners.

**Comment by CathyDingemanse** [comment]
Eens met Gert Jan.

**Comment by fsamwel** [comment]
@JohanBoer doe jij een voorstel/aanzet hoe dat gemodelleerd kan worden?

**Comment by mvdbro** [comment]
Wat denken jullie van het volgen van de GBA modellering door inOnderzoek ook op te nemen binnen de partners, kinderen en ouders en weg te halen binnen inOnderzoek bij ingeschreven persoon. Je kunt dan de semantiek in de respectievelijke categorieën eenvoudig kwijt.

**Comment by mvdbro** [comment]
> Wat je dan mogelijk in het proces mist is het volgende:
Als ik de resource opvraag zonder 'Expand', krijg ik de links van de gerelateerden (ouder/kind/partner) mee. Als één van die gerelateerden een element inOnderzoek heeft, zie ik dat als eindgebruiker niet direct, maar pas op het moment dat ik 'doorvraag' op een gerelateerde of de oorspronkelijke vraag stel met 'Expand'.

> Klopt bovenstaande?

Ja, zo werkt het dan inderdaad.

> Zoja, is het relevant voor de 'eindgebruiker' om dit wel te weten? Kan het feit dat de Partnergegevens InOnderzoek staan een reden zijn om deze gegevens toch even op te halen, waar je dat zonder dat er gegevens van de gerelateerde InOnderzoek staan wellicht niet zou doen?

Ik vraag me af of het relevant is te weten dat gegevens in onderzoek zijn, terwijl je zonder die wetenschap niet in de partner geinteresseerd bent. Ik ga hierin graag af op de toekomstige gebruikers van de API. Is het geen idee om een aantal van dit soort issues te bundelen en gebundeld voor te leggen aan de toekomstige gebruikers?

**Comment by gertjanvanderkooij** [comment]
Ja, het lijkt me goed om dit te doen; twee richtingen op: 
1. Wrapup van onderwerpen voor de toekomstige gebruikers 
2. Wrapup van onderwerpen voor de toekomstige provider (RvIG)

**Comment by CathyDingemanse** [comment]
> Wat je dan mogelijk in het proces mist is het volgende:
> Als ik de resource opvraag zonder 'Expand', krijg ik de links van de gerelateerden (ouder/kind/partner) mee. Als één van die gerelateerden een element inOnderzoek heeft, zie ik dat als eindgebruiker niet direct, maar pas op het moment dat ik 'doorvraag' op een gerelateerde of de oorspronkelijke vraag stel met 'Expand'.
> 
> Klopt bovenstaande?
> Zoja, is het relevant voor de 'eindgebruiker' om dit wel te weten? Kan het feit dat de Partnergegevens InOnderzoek staan een reden zijn om deze gegevens toch even op te halen, waar je dat zonder dat er gegevens van de gerelateerde InOnderzoek staan wellicht niet zou doen?

Als dit hele specifieke gegeven relevant is voor jouw businessproces (bijvoorbeeld een bepaalde controle) staat het op je checklist of is er BLogic om deze controle uit te voeren. De gebruiker/de consumer gaat hier expliciet naar op zoek, en het is op deze manier ook goed vindbaar. M.a.w., je wordt niet tijdens het raadplegen op ideeen gebracht over mogelijke controles voor jouw businessproces (tenminste, dat mag ik hopen). Dat is ook niet mogelijk als er goed is nagedacht over de doelbinding van gebruikers. Dat laatste is een wettelijke eis.

**Comment by gertjanvanderkooij** [comment]
> M.a.w., je wordt niet tijdens het raadplegen op ideeen gebracht over mogelijke controles voor jouw businessproces (tenminste, dat mag ik hopen).

Normaliter niet; ben ik met je eens. In geval van InOnderzoek zijn van gegevens is dit echter mogelijk wel het geval. Hier gaat een signalerende werking van uit; met als gevolg dat je toch even verder kijkt. 

Stel ik ben vanuit het proces geïnteresseerd of er een partner is (ongeacht wie dat is), dan heb je aan de 'link' voldoende. Als je dan ziet dat gegevens van deze partner in onderzoek zijn (bv. als gevolg van een terugmelding), dan kan ik me voorstellen dat je vanuit het businessproces meer wilt weten; bv. of er überhaupt wel sprake is van een partner, de hierover geregistreerde gegevens wellicht onjuist/strijdig zijn.

**Comment by CathyDingemanse** [comment]
> > M.a.w., je wordt niet tijdens het raadplegen op ideeen gebracht over mogelijke controles voor jouw businessproces (tenminste, dat mag ik hopen).
> 
> Normaliter niet; ben ik met je eens. In geval van InOnderzoek zijn van gegevens is dit echter mogelijk wel het geval. Hier gaat een signalerende werking van uit; met als gevolg dat je toch even verder kijkt.
> 
> Stel ik ben vanuit het proces geïnteresseerd of er een partner is (ongeacht wie dat is), dan heb je aan de 'link' voldoende. Als je dan ziet dat gegevens van deze partner in onderzoek zijn (bv. als gevolg van een terugmelding), dan kan ik me voorstellen dat je vanuit het businessproces meer wilt weten; bv. of er überhaupt wel sprake is van een partner, de hierover geregistreerde gegevens wellicht onjuist/strijdig zijn.

Dat kan, maar dit kan ook als we even bij jouw voorbeeld blijven: je bent geinteresseerd of er een partner is, en niet zozeer in wie dat is. Dan zou je deze ook met de fields parameter op kunnen vragen. Gebruikers proberen immers alleen op te vragen wat nodig is voor het uitvoeren van de taak. In dat geval mis je ook dat de partner "in onderzoek" is. 

Ook kan het voorkomen dat je niet geinteresseerd bent persoon zelf, maar alleen in of hij/zij een partner heeft wie die partner is. Bijvoorbeeld, omdat je de partner wilt volgen in verband met de kostendelersnorm. Deze specifieke vraag kan worden beantwoord door gebruik te maken van de fields en de expand parameter. In dit geval wordt het "in onderzoek" gegeven gemist als deze onderdeel is van de resource zelf en wel getoond als deze onderdeel is van de subresource.
Met het gebruik van de expand parameter voor de (hele) partner vind je voor beide oplossingen (in de resource en in de subresource) de indicatie "in onderzoek" op de partner wel. 

Mijn punt is eigenlijk: omdat er zo veel manieren zijn om de API te gebruiken is het lastig te voorspellen op welke manier een belangrijk gegeven het best onder de aandacht kan worden gebracht. We nog niet  welke gebruikerspatronen het meest zullen voorkomen. En dan nog, meest gebruikt wil niet zeggen dat de processen voor wie dit relevant is dat ook zullen doen. 
Wat we wel weten is dat het gegeven dat iets in onderzoek is voor veel gemeentelijke processen belangrijk is. Omdat het belangrijk is, zal het in bijna alle gevallen onderdeel zijn van de requirements van een consumer. Dan is het belangrijk dat het eenvoudig vindbaar is, en dat we het zo simpel mogelijk houden. Ik denk dat het idee van Maarten daar aan bijdraagt. 

Vervolgens hoor ik graag de feedback van echte gebruikers op dit punt!

**Comment by gertjanvanderkooij** [comment]
OK. Is inderdaad de beste route; simpel houden en zo nodig op basis van ervaringen fijn slijpen!

**Comment by gertjanvanderkooij** [comment]
Ja, wat mij betreft wel. Hierbij dan de lijn volgen zoals opgenomen in #74 .

**NB.** Daarnaast een issue aanmaken om onderwerpen te inventariseren, die (op een geschikt moment) worden voorgelegd aan consumers en uiteindelijke provider RvIG? Of wordt er al een lijstje bijgehouden?

**Comment by gertjanvanderkooij** [comment]
> Gaan we deze oplossing dan ook toepassen op de gegevensgroepen ? Dat sluit wel aan bij hoe het in het LO-GBA is gedefinieerd. Gegevens worden op **categorie-niveau in onderzoek gezet en niet op attribuut-niveau**. 

Met die nuance dat in GBA-element 83.10 wordt aangegeven welke rubrieken van betreffende categorie in onderzoek staan. Dit kan variëren van:

- Een specifieke rubriek binnen de categorie dat in onderzoek staat; bv. element 'Datum aanvang adreshouding' in onderzoek, dan 08.83.10 gevuld met: 081030
- Een specifieke groep binnen de categorie dat in onderzoek staat; bv. de groep 'Adreshouding' in onderzoek, dan 08.83.10 gevuld met: 081000
- De gehele categorie staat in onderzoek; bv. de Categorie Verblijfplaats, dan 08.83.10 gevuld met '080000'. 

> 
> Dan lijkt het mij verstandiger om deze wijziging éénduidig door te voeren ... 
Ik ben voorstander van eenduidig oplossen, zodat ook de afhandeling van 'Gegevens in onderzoek' voor 'consumers' eenduidig kan verlopen. 

Om de casus gezicht te geven volgende verzoek:
Zou je een voorbeeld antwoordberichtfragment (...) kunnen opmaken van een IngeschrevenPersoon met volgende lopende onderzoeken:

1. - De 'Datum aanvang adreshouding' van betreffende persoon is in onderzoek
2. - Persoon heeft meerdere vreemde nationaliteiten; de 'Datum aanvang geldigheid' van één hiervan is in onderzoek
3. - Persoon heeft meerdere kinderen; geboortedatum van één van de kinderen is in onderzoek.
4. - Persoon heeft meerdere partners (één actueel huwelijk, overig ontbonden huwelijken); de ontbindingsdatum van één van de ontbonden huwelijk is in onderzoek.

**Comment by JohanBoer** [comment]
[Voorbeeldberichten bij 132.pdf](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/files/2783518/Voorbeeldberichten.bij.132.pdf)

Ik heb wat voorbeeldberichten gemaakt. Het is geen makkelijke beslissing volgens mij. Als we InOnderzoek in de gegevensgroepen op gaan nemen wordt de structuur best omvangrijk. Dat is niet zo als we de methodiek gebruiken die GertJan beschrijft (en zoals die in het LO GBA stat beschreven. 

Die laatste methodiek maakt het echte voor consumers complex om te achterhalen wat er nu precies in Onderzoek staat. Daarvoor moeten ze dan erg veel zelf gaan administreren en uitzoeken. 

Ik neig naar het opnemen van Booleans voor in Onderzoek op attribuut-niveau  opnemen in de gegevensgroepen en de resources en vervolgens de afspraken uit #74 hanteren dat bij het in onderzoek staan van een hele categorie dan alle booleans op "true" zetten.

**Comment by gertjanvanderkooij** [comment]
Dank voor snelle productie voorbeelden!

Als ik hier naar kijk mis ik de rubrieken 83.20 Datum ingang onderzoek en 83.30 Datum einde onderzoek.
Worden deze niet relevant geacht? Zie ook opmerkingen over vergelijking gegevens wel in GBA niet in BevragingAPI-model. 

Verder nav de voorbeelden het volgende:

- Gebruik van GBA-rubrieknummers zeker niet doen. Als gekozen wordt voor deze variant, dan 'centraal' (door de serviceprovider) de vertaling maken van GBA-rubriek naar 'BevragingAPI-element'.

- Mmm, van overige opties ook niet echt enthousiast.


Eenduidigheid kunnen we ook bereiken door de 'Nationaliteit-constructie' door te trekken voor alle gegevensgroepen (maar dan net even iets anders ...). Dit naar het voorbeeld van implementatie in OperatieBRP; Onderzoek als Orthogonaal op alle Objecten/Gegevensgroepen. 

1. Ieder object/gegevensgroep voorzien van een eigen UUID

1. Als laatste in het bericht onder de Ingeschreven Persoon een lijst Onderzoeken opnemen (zelfde niveau als 'Nationaliteit en ook als repeterende groep)

1. Per onderzoek op te nemen: 'UUID', 'Datum aanvang onderzoek', 'Datum einde onderzoek' en 'Opsomming gegevens in onderzoek'

Als we gegevens over het onderzoek (Datum ingang en Datum einde) op willen nemen, kan het bijna niet anders, denk ik. Voor de consumer kan dit dan steeds op dezelfde manier worden afgehandeld; als laatste stap in de verwerking een 'loopje' over de 'Onderzoeken'.

_**NB.** Wordt wel een probleempje als een GBA-categorie in het model van de BevragingApi in meerdere Gegevensgroepen is gesplitst. Dan logica in deel serviceprovider om dit onderzoek meervoudig op te nemen met goede verwijzing UUID en bijbehorende opsomming gegevens in onderzoek (mapping-kwestie)._

**Comment by gertjanvanderkooij** [comment]
Hey Frank @fsamwel leuk (en goed) dat je nog aangehaakt bent!

'Plat slaan' klinkt inderdaad beter. 'Consumeert' het makkelijkst, want boeltje bij elkaar. Transformeert vanuit GBA-PL als provider ook wel het makkelijkst denk ik. 

> 
> _**NB.** Wordt wel een probleempje als een GBA-categorie in het model van de BevragingApi in meerdere Gegevensgroepen is gesplitst._

Geen probleempje; wel iets om rekening mee te houden. Als er behoefte is aan de onderzoeksrubrieken 'Datum ingang/Einde onderzoek', dan kan het voorkomen dat deze meervoudig worden opgenomen. Maarrr ... boeltje altijd bij elkaar.

**Comment by JohanBoer** [comment]
Veel dank voor jullie bijdragen. Wij neigen nu alledrie naar dezelfde oplossing.  (Opnemen van InOnderzoek in alle groepen en resources met een boolean voor elk element dat in Onderzoek kan zijn.) Als Cathy en Melvin (ga ik per mail vragen mee te denken) deze koers ook onderschrijven ga ik dit doorvoeren.

**Comment by fsamwel** [comment]
[voorbeeld_inOnderzoek.json.txt](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/files/2786903/voorbeeld_inOnderzoek.json.txt)

Zie dit voorbeeld. Hierin moet dan wel bedacht worden in hoeverre naam en geboorte in de ouder/kind/partner ook een element inOnderzoek moet hebben.

**Comment by JohanBoer** [comment]
Dank voor het voorbeeld Frank.
Mijn voorstel zou zijn om in gegevensgroepen die Inonderzoek alleen in de groep onder te brengen als de groep meer dan 1 keer kan voorkomen. Dus de in onderzoek booleans van naam en geboorte worden dat in de InOnderzoek-groep van de Ingeschreven Persoon opgenomen.

Verder zie ik in jouw voorbeeld een Boolean op  "ouderniveau" (laatste inOnderzoek in jouw voorbeeld) bedoel je daarmee dat de hele ouder In onderzoek is ? in #74 hebben we afgesproken dat we dan alle elementaire booleans op true zouden zetten.  

Uiteindelijk is dit een kwestie van wat is handiger  (Melvin, wat vind jij) Functioneel bieden beide oplossingen volgens mij hetzelfde
[voorbeelInOnderzoek2.json.txt](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/files/2787061/voorbeelInOnderzoek2.json.txt)

**Comment by gertjanvanderkooij** [comment]
Ik zou het voorstel van Frank willen volgen; binnen een groep de gegevens en het feit of een gegeven in onderzoek kan zijn elkaar houden. Dit ongeacht of een groep één of meervoudig voor kan komen. 

Is zelfs nodig als er ook behoefte is (komt) om Datum begin/Eind onderzoek op te nemen; vanuit GBA-V worden alle 'procedure'-gegevens geleverd.

**Comment by MelvLee** [comment]
Mijn voorkeur gaat ook naar het voorstel van Frank. Dus voor naamPersoon een eigen inOnderzoek groep opnemen. Dit versimpelt o.a. de UI code, omdat je nu niet apart hoeft te gaan zoeken in een 'grote' inOnderzoek groep of naamPersoon in onderzoek staat. 

Verder zou ik de namen van de properties gelijk houden, dus naamPersoon.voorvoegsel en inOnderzoek.voorvoegsel en niet inOnderzoek.voorvoegselGeslachtsnaam.

**Comment by JohanBoer** [comment]
Duidelijk verhaal. Ik ga op deze manier InOnderzoek opnemen.

**Comment by mvdbro** [comment]
Ik vraag me af in hoeverre de begin- en einddatum van het inderzoek relevant zijn. Op andere plaatsen is de begingeldigheid van gegevens ook niet meegenomen. Daarnaast is de vraag of er een businessbehoefte is om te weten dat gegevens in onderzoek zijn geweest. Is het niet voldoende te weten dat gegevens nu al dan niet in onderzoek zijn. Als deze behoefte er is, dan is het de vraag of het niet natuurlijker is om dit in te vullen als historie.

De StUF-standaard heeft inOnderzoek gemodelleerd met behulp van inOnderzoek elementen die als array de elementnamen of groepsnamen bevatten van de elementen of groepen die in onderzoek zijn. Deze modellering sluit goed aan de vastlegging in de GBA en maakt de API veel simpeler: er zijn nog maar een paar inOnderzoek elementen nodig in plaats van inOnderzoek elementen met een groot aantal subelementen. Lijkt me ook de in de user interface gemakkelijker, want je kunt dan gewoon een lijst tonen met de elementnamen die in onderzoek zijn.

**Comment by mvdbro** [comment]
Ik zie de verschillen in verwerking nog niet direct. In het ene geval krijg je in de respons een elementnaam in een tamelijk ingewikkelde structuur aangereikt met daarbinnen een boolean. In het andere geval krijg je in de respons de elementnaam (zo nodig inclusief pad, maar ik betwijfel of dat nodig is) als waarde in een array aangereikt. Wat maakt dit voor verschil voor een consumer?

Voor de provider en voor de simpelheid van de respons verdient de werkwijze uit StUF de voorkeur. Het scheelt bijvoorbeeld een paar honderd regels in de open api specificatie.

**Comment by mvdbro** [comment]
@CathyDingemanse , Ik snap dit niet, want elke nationaliteit is een separate groep in de respons met een eigen inOnderzoek element. Er is dus helemaal geen probleem met het in onderzoek zijn van meer dan één nationaliteit.

**Comment by mvdbro** [comment]
@CathyDingemanse , Ik denk dat ik inmiddels de verwarring beter begrijp. Ik ben ervan uitgegaan dat het voorstel van Frank
> Ik ben wel voorstander van het opnemen van inOnderzoek in de groepen en sub-resources. De elementwaarden en de aanduiding of deze in onderzoek zijn wil je zo dicht mogelijk bij elkaar houden. Lost direct het meerdere nationaliteiten vraagstuk op.
geaccepteerd was. Ik krijg nu de indruk dat hier nog discussie over is. Als het geaccepteerd wordt, dan zie ik geen problemen met mijn voorstel.

**Comment by fsamwel** [comment]
Ik zie geen reactie terug op de opmerking https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/issues/132#issuecomment-457104535 van Maarten. Is die behoefte er wel?

Vooral over de datumEindeOnderzoek is het (mij) niet direct duidelijk hoe dit werkt. We geven immers alleen actuele gegevens terug. Is dit bedoeld om aan te geven dat gegevens in de groep ooit in onderzoek zijn geweest?

Wat moet gevuld worden wanneer het onderzoek is beëindigd? Moeten dan de gegevens die in onderzoek waren worden opgenomen met waarde true en datumEindeOnderzoek gevuld? Of moet wel datumEindeOnderzoek zijn gevuld, maar de attributen niet (of met waarde false)? 

Ook verbaast het me dat datumIngangOnderzoek en datumEindeOnderzoek alleen op de gegevensgroepen zit, maar niet op de persoon (PersoonInOnderzoek).

Ik denk dat het probleem met de ouder, kind of partner die in onderzoek is nu niet meer goed is opgelost. Bij een persoon worden links naar deze relaties gegeven. Maar wanneer de relatie zelf in twijfel wordt getrokken, is dat bij de persoon niet zichtbaar. Dus wanneer een consumer uit de aanwezigheid van een partners link concludeert dat er een actuele partner is, hoeft dat niet terecht te zijn wanneer die relatie in onderzoek is.

Nog een puntje: ik zie bij de ouder, partner en kind in onderzoek het a_nummer terugkomen. Dat is m.i. niet correct. Het A-nummer kan nooit in onderzoek zijn (zie §3.22.2 van LO GBA en #74).

Bij de ouder, kind en partner zijn inOnderzoek attributen opgenomen voor eigenschappen van de gerelateerde persoon. Bijvoorbeeld naam en geboorte. Wordt de inOnderzoek hiervoor bepaald uit categorie 83 Procedure van Ouder1, Ouder2, enz., of van de persoonslijst van de gerelateerde persoon? (of beide?)

Ander onderwerp: attribuut datumVan bij de Ouder (en OuderInOnderzoek), is dat 62.10 Datum ingang familierechtelijke betrekking? Zo ja,waarom heet het dan niet zo?

**Comment by JohanBoer** [comment]
> Ik zie geen reactie terug op de opmerking [#132 (comment)](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/issues/132#issuecomment-457104535) van Maarten. Is die behoefte er wel?
> 
> Vooral over de datumEindeOnderzoek is het (mij) niet direct duidelijk hoe dit werkt. We geven immers alleen actuele gegevens terug. Is dit bedoeld om aan te geven dat gegevens in de groep ooit in onderzoek zijn geweest?
> 
> Wat moet gevuld worden wanneer het onderzoek is beëindigd? Moeten dan de gegevens die in onderzoek waren worden opgenomen met waarde true en datumEindeOnderzoek gevuld? Of moet wel datumEindeOnderzoek zijn gevuld, maar de attributen niet (of met waarde false)?

DatumEindeOnderzoek wordt uit alle InOnderzoek groepen verwijderd. 


> Ook verbaast het me dat datumIngangOnderzoek en datumEindeOnderzoek alleen op de gegevensgroepen zit, maar niet op de persoon (PersoonInOnderzoek).

DatumIngangOnderzoek wordt toegevoegd aan PersoonInOnderzoek

> Ik denk dat het probleem met de ouder, kind of partner die in onderzoek is nu niet meer goed is opgelost. Bij een persoon worden links naar deze relaties gegeven. Maar wanneer de relatie zelf in twijfel wordt getrokken, is dat bij de persoon niet zichtbaar. Dus wanneer een consumer uit de aanwezigheid van een partners link concludeert dat er een actuele partner is, hoeft dat niet terecht te zijn wanneer die relatie in onderzoek is.

Er wordt toch gekozen om de huidige structuur te behouden. Dat betekent dat om te checken of de relatie in onderzoek is moet de subresource (ouder, kind, partner) opgehaald worden. 

> Nog een puntje: ik zie bij de ouder, partner en kind in onderzoek het a_nummer terugkomen. Dat is m.i. niet correct. Het A-nummer kan nooit in onderzoek zijn (zie §3.22.2 van LO GBA en #74).

anummer inonderzoek is verwijderd.
