### ISSUE TITLE
Burgerlijke staat is wel opgenomen in de Structuur, maar niet in het LO Gba

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#136]
Vraag van Kayo de Bakker n.a.v. proefimplementatie :

De Burgerlijke staat is nu wel opgenomen in de berichtstrucuur omdat die in het RSGB aanwezig was. In het LO GBA is er geen element waarin de burgelijke staat wordt vastgelegd. 

Vraag is nu of we dit als "comfort-gegeven" gaan vullen (zoals bv. met aanschrijfwijze) of dat dit element wordt verwijderd uit de berichtstructuur. 

Bij de eerste optie moet er een feature-beschrijving komen hoe de waarde van het element "Burgerlijke staat" wordt bepaald. In het tweede geval moeten alle consumers die de burgerlijke staat willen weergeven zelf de logica daarvoor implementeren. 

De gegevens die nodig zijn om die logica door te voeren zijn beschikbaar via het huwelijk/geregistreerd partnerschap.

**Comment by CathyDingemanse** [comment]
De definitie van burgerlijke staat is vrees ik ruimer dan hierboven wordt vermeld. Burgerlijke staat is de formele positie van een mens in de zin en betekenis van het burgerlijk wetboek. Te onderscheiden vallen huwelijkse staat, partnerregistratie (geregistreerd partnerschap); de zogenaamde wettige dan wel onwettige afstamming; meerder- of minderjarigheid, eventuele ondercuratelestelling, specifieke situaties van voogdij of ouderlijk gezag, en nationaliteit. 

Ik heb de deskundigen gevraagd een onderzoekje te doen naar het huidige gebruik van dit gegeven, en indien mogelijk naar de vraag bij afnemers. Ik kom hier op terug.
