### ISSUE TITLE
IndicatieGezagCurateleregister ontbreekt. Staat wel in LO Gba en wordt gelevrd door GBA-V

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#137]
Vraag van Kayo de Bakker n.a.v. proefimplementatie :

_Er is geen IndicatieGezagCurateleregister dat ik kan vinden terwijl dit in de GbaV te vinden is als onderdeel. Is hier een keuze voor gemaakt om niet op te nemen?_

In het RSGB staan wel de attribuutsoorten **Handelingsbekwaam** (Aanduiding of de INGESCHREVEN NATUURLIJK PERSOON tussen 16 en 18 jaar oud, handelingsbekwaam is door handlichting of huwelijk.
) en **Onder bewind** (Een aanduiding dat de ingezetene onder (provisioneel) bewind staat.) 

Deze termen komen niet in het LO Gba voor. De term "Curatele" kom ik nergens in het RSGB tegen. 

Er is bij de eerste versie van RSGBbevragingen expliciet gekozen om "onder bewind" en "Hnadelingsbekwaam" niet op te nemen. 

Concrete vraag: Is deze beslissing gezien de huidige context nog valide ? Zo ja, dan veranderd er niets aan de hudige berichtstructuur, Zo nee, dan moet elemnt "IndicatieGezagCurateleregister" opgenomen worden.

**Comment by CathyDingemanse** [comment]
In categorie 11 gezagsverhouding van LO GBA staan:
Indicatie gezag minderjarige 
Indicatie  curateleregister.
Beiden moeten worden opgenomen!

**Comment by JohanBoer** [comment]
Inmiddels de betreffende gegevens toegevoegd en daar een groep van gemaakt. 
![image](https://user-images.githubusercontent.com/18071357/51109317-33808d80-17f5-11e9-804c-5c4fbbac5ebf.png).

Vraag is of er nog andere elementen uit categorie 11/61 gewenst zijn binnen deze gegevensgroep. Het LO GBA kent de volgende elementen in deze categorie : 
![image](https://user-images.githubusercontent.com/18071357/51109377-6296ff00-17f5-11e9-9be3-f10c9ec1d90b.png)

**Comment by CathyDingemanse** [comment]
Laten we hier maar mee beginnen.
