### ISSUE TITLE
waardetabel-gba dient een landcode te hebben bij buitenlandse plaats/locatie scenarios

### ISSUE THREAD

**Issue by KayodeBakker** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1376]
**Beschrijf de verbetering**
Bij de volgende twee scenarios van de features\gba-dev\waardetabel-gba.feature:
Scenario: Plaats is buitenlandse plaats of locatie bij code voor 'partner' plaats huwelijkssluiting/aangaan geregistreerd partnerschap (06.20) features\gba-dev\waardetabel-gba.feature:67
Scenario: Plaats is buitenlandse plaats of locatie bij code voor Overlijden # features\gba-dev\waardetabel-gba.feature:214

wordt verwacht dat alleen code is gevuld want het is een buitenlandse plaats en daarmee zal geen code hebben zoals 0599. Bij het e2e testen komt er echter uit dat er ook een omschrijving gevuld is met dezelfde waarde als de code. Dit komt omdat de logica voor het bepalen van een buitenlands adres gaat als volgt:

Is landcode gevuld EN is deze niet 6030 dan dienen we alleen code te vullen en anders (default want dan Nederlands) code en omschrijving. Omdat bij de scenarios geen landcode geleverd wordt, voldoet deze niet aan het eerste deel van de check.

Mijn vraag is dus: 
Is het mogelijk dat landcode niet is gevuld en zo ja, wat doen we dan qua logica?
In het geval van nee dit is niet mogelijk, dan stel ik voor dat de scenarios landcodes krijgen. In het geval van wel dan is mijn suggestie dat we kijken of de geleverde plaatscode numeriek is en 4 getallen is zodat we niet meer afhankelijk zijn van landcode, maar ik zie niet alle gevolgen hiervan.

**Comment by JohanBoer** [comment]
> Is landcode gevuld EN is deze niet 6030 dan dienen we alleen code te vullen en anders (default want dan Nederlands) code en omschrijving. Omdat bij de scenarios geen landcode geleverd wordt, voldoet deze niet aan het eerste deel van de check.
> 
> Mijn vraag is dus: Is het mogelijk dat landcode niet is gevuld en zo ja, wat doen we dan qua logica? In het geval van nee dit is niet mogelijk, dan stel ik voor dat de scenarios landcodes krijgen. In het geval van wel dan is mijn suggestie dat we kijken of de geleverde plaatscode numeriek is en 4 getallen is zodat we niet meer afhankelijk zijn van landcode, maar ik zie niet alle gevolgen hiervan.

Je maakt nu de controle of een plaats buitenlands is afhankelijk van de landcode.  Is dat een erfenis van 1.3 ? 

In de waardetabel-gba.feature staat op regel 216 staat de volgende rule : 
```
          Rule: wanneer de waarde voor een geboorteplaats(03.20) of een overlijdenplaats (08.20) of plaats huwelijkssluiting/aangaan geregistreerd partnerschap (06.20) geen valide gemeentecode bevat wordt de de code geleverd in zowel de code als de omschrijving
            - een valide gemeentecode bestaat uit vier cijfers en komt voor in de landelijke tabel Gemeenten
            - als er in de geboorteplaats (03.20) of de overlijdenplaats (08.20) of plaats huwelijkssluiting/aangaan geregistreerd partnerschap (06.20) een waarde staat die niet voorkomt in de landelijke tabel Gemeenten
              dan wordt de waarde die in de plaats staat in zowel de code als de omschrijving opgenomen. (Buitenlandse plaatsnaam of coördinaten)
```

Daar staat dus niet in dat het al dan niet buitenlands zijn van een plaats afhangt van de landcode.   
De check is of de waarde die opgenomen is in plaats (geboorteplaats, overlijdenplaats, plaats huwelijk ) voorkomt in lo3_pl_gemeente. Zo niet --> dan buitenlands.

**Comment by KayodeBakker** [comment]
@JohanBoer Is het accuraat om te zeggen dat als de waarde van plaats (code niet omschrijving) geen 1 tot 4 cijfers bevat (wegens voorlopen lager dan 4) dat het dan om een buitenlands plaats gaat? Dat is de logica die ik nu hanteer.
