### ISSUE TITLE
Relaties naar nummeraanduiding en ook standplaats, ligplaats, verblijfsobject?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#14]
Voor de verblijfsplaats van een ingeschreven persoon zijn er relaties naar nummeraanduiding, standplaats, ligplaats, verblijfsobject, enz. Standplaats, ligplaats, verblijfsobject zijn zelf ook weer gerelateerd aan een nummeraanduiding. In het projectoverleg is opgemerkt dat er in feite alleen/vooral behoefte is aan de nummeraanduiding en het vermoeden dat dit ook alleen zo in GBA zit. Wijkt RSGB hier af van GBA? Dus hoe zit dit in LO GBA?

**Comment by fsamwel** [comment]
In overleg afgesproken dit aan Ellen voor te leggen. Ik heb vraag in e-mail aan Ellen en Remko gesteld.

**Comment by fsamwel** [comment]
Dit wordt opgelost door verblijfsadres een relatie te maken naar een resource met daarin het adres. Dit kan een relatie zijn naar een BAG-adres, maar ook naar een adres dat niet in het BAG staat.

**Comment by JohanBoer** [comment]
De terugrelatie van de nummeraanduiding naar de Standplaats Ligplaats of verblijfsobject is buiten scope.

**Comment by fsamwel** [comment]
is inmiddels opgenomen in de API
