### ISSUE TITLE
vragen van naam gegevens bij geen voorvoegsel

### ISSUE THREAD

**Issue by MelvLee** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1402]
Als van een persoon met voornamen en geslachtsnaam maar zonder voorvoegsel de naam wordt gevraagd met fields=naam.voornamen,naam.voorvoegsel,naam.geslachtsnaam, dan krijgt je alleen de geslachtsnaam terug. Met fields=naam of fields=naam.voornamen,naam.geslachtsnaam, krijgt je de voornamen en geslachtsnamen terug

Dit gebeurt ook bij kind. Niet gevalideerd bij ouder en partner

Reproductie pad:
- npx cucumber-js features/gba-dev/persoon-naam-gba.feature:5
- npx cucumber-js features/gba-dev/kind-naam-gba.feature:5

versie gba-api: 2.0.7

**Comment by KayodeBakker** [comment]
Deze is volgens mij nu afgerond. @MelvLee

**Comment by MelvLee** [comment]
getest en goed bevonden
