### ISSUE TITLE
vragen van 'onbekend' geboorte gegevens

### ISSUE THREAD

**Issue by MelvLee** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1404]
De geboorte gegevens van een persoon zijn allemaal onbekend. Bij het vragen van de plaats krijgt je alleen de omschrijving terug. Dit is niet het geval bij vragen van land. Dan krijgt je wel de land.code terug

Dit treedt ook op bij kind. Niet gevalideerd bij ouder en partner

Reproductie pad:
- npx cucumber-js features/gba-dev/persoon-geboorte-gba.feature:5
- npx cucumber-js features/gba-dev/kind-geboorte-gba.feature:5

versie gba-api: 2.0.7

**Comment by KayodeBakker** [comment]
Dit is gekoppeld aan de volgende issue:
#1376 

Ik kan dit pas oplossen als ik weet wat ik moet doen.
