### ISSUE TITLE
Scenario: wel leveren RNI-deelnemer categorie 7 wanneer er opschorting bijhouding is # features\gba-dev\rni-gba.feature:160

### ISSUE THREAD

**Issue by KayodeBakker** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1406]
**Beschrijf de verbetering**
Deels al benoemd bij #1405, maar bij de rni-gba feature worden er impliciet gezegd dat de RNI moet worden getoond als er opschorting bijhouding gaande is. Ook was dit schijnbaar bij geheimhoudingPersoonsgegevens, maar de vraag nu is, of er andere casussen zijn aangezien dit weer een uitzondering zal zijn.

Graag dit expliciet maken deze uitzonderingen.

**Comment by JohanBoer** [comment]
Inmiddels is duidelijk dat bij het vragen van gegevens uit categorie 7 (inschrijving) er geen rni voor categorie 7 meegeleverd wordt. De rni-gba.feature klopt op dit vlak (Zie eerste rule). In de rni.feature kloppen mijns inziens de scenario's ook, maar staat dit nog niet goed in de Rule. Dat herstel ik.

**Comment by JohanBoer** [comment]
Zowel geheimhouding als opschorting zijn onderdeel van categorie 7
