### ISSUE TITLE
RNI gegevens niet verstrekken voor categorie 7 Inschrijving

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1422]
In tegenstelling tot wat nu in de rni feature(s) staat hoeft rni (deelnemer en verdrag) niet geleverd te worden voor categorie 7 Inschrijving.

Dat geldt dus voor de volgende velden, waarbij geen rni hoeft te worden geleverd:

- opschortingBijhouding
- datumEersteInschrijvingGBA
- geheimhoudingPersoonsgegevens
- verificatie

**Comment by JohanBoer** [comment]
Dit is inmiddels opgenomen in de rni-scenario's
