### ISSUE TITLE
gemeente van inschrijving is in onderzoek en wordt gevraagd met fields=gemeenteVanInschrijving.code

### ISSUE THREAD

**Issue by MelvLee** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1425]
In dit geval wordt de inOnderzoek velden niet geretourneerd. Dit is ook het geval bij fields=gemeenteVanInschrijving.omschrijving

Reproductie pad:
- npx cucumber-js features/gba-dev/persoon.feature:191
- npx cucumber-js features/gba-dev/persoon.feature:192

**Comment by KayodeBakker** [comment]
Deze was inderdaad over het hoofd gezien. Zal in 2.0.10 worden gefixt.
