### ISSUE TITLE
onbekend datum huwelijk/geregistreerd partnerschap wordt niet geretourneerd

### ISSUE THREAD

**Issue by MelvLee** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1426]
reproductie pad: npx cucumber-js features/gba-dev/partner.feature:79

**Comment by KayodeBakker** [comment]
De scenario is fout. Zie issue #1430

**Comment by MelvLee** [comment]
De scenario is gecorrigeerd na melding in #1430

**Comment by KayodeBakker** [comment]
Deze heb ik net getest in versie 2.0.14 en lijkt te werken. Kan je dit valideren?
