### ISSUE TITLE
Foutieve verwachting gba-dev\ouders-gba.feature

### ISSUE THREAD

**Issue by KayodeBakker** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1429]
**Beschrijf de bug**
De volgende scenario faalt:
features\gba-dev\ouders-gba.feature:239

De reden hiervoor is als volgt:
**Verwachting**
```json
[
   {
     "ouders": [
       {}
     ]
   }
 ]
```

**Realiteit**
```json
[
  {
          "ouders": [
                  {
                          "naam": {}
                  }
          ]
  }
 ]
```

Naar mijn verwachting is de realiteit kloppend en de verwachting foutief. De reden hiervoor is als volgt:
Gevraagd is 'ouders.naam.voornamen,ouders.geboorte.datum' en de ouder in kwestie heeft naast een datum veld en geslacht ook een geslachtsnaam. Dat betekent dat het naam object niet NULL is, maar leeg. Uit eerder besloten logica dient de GBA API dan juist een lege naam object te retourneren en dus is de realiteit correct.

Graag hier uitsluitsel over.

**Comment by MelvLee** [comment]
De actual response klopt. Scenario is aangepast

**Comment by CathyDingemanse** [comment]
@KayodeBakker , kan deze worden gesloten?
