### ISSUE TITLE
Behoefte aan voorbeeldberichten voor elke service/operatie  

### ISSUE THREAD

**Issue by gertjanvanderkooij** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#143]
Zijn er al voorbeeldberichten voor elke service/operatie. Bij voorkeur fullblown en voorzien van constructen als Relaties/Gereateerden, InOnderzoek (ook voor Nationaliteit), deels onbekende datum etc. 

Gebruik voor:
1) Toetsen features adhv concrete voorbeelden
2) Illustreren features voor eigen service-implementatie (vooruitlopend op die van RvIG) 

We hebben het hier tijdens ons laatste overleg even over gehad. Ik las dat er inmiddels testen wordne uitgevoerd met een proefimplementatie, waardoor eea nu makkelijke te produceren is.

**Comment by CathyDingemanse** [comment]
Graag Swagger hub automock werkend maken:
 https://petstore.swagger.io/?url=https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/Bevraging-Ingeschreven-Persoon/openapi.yaml

**Comment by gertjanvanderkooij** [comment]
Wat is de status van de antwoorden in de SwaggerHubAutomock?

Bijvoorbeeld tav 'onbekende datums'; ik zie bij 'datumVestigingNederland' en 'datumOpschoritingBijhouding' hiervoor geen construct. Zou door johan wel aangepast zijn; zie:
[20181122InventarisatieDeelsOnbekendeDatums_Rea_JohanBoer.xlsx](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/files/2769124/20181122InventarisatieDeelsOnbekendeDatums_Rea_JohanBoer.xlsx)

**Comment by gertjanvanderkooij** [comment]
Hallo Maarten @mvdbro,

Zou heel mooi zijn als je die kunt leveren. Ik heb een paar BSN/Anummers vanuit de nieuwe testset GBA-V geïnventariseerd rondom thema's DatumOnbekend en InOnderzoek:

- BSN: 999 990 457 / ANR: 829 4830 352
- BSN: 999 990 482 / ANR: 396 7096 438
- BSN: 999 992 806 / ANR: 719 6269 672
- BSN: 999 991 449 / ANR: 351 0247 967 
- BSN: 999 994 888 / ANR: 178 6591 927

Als je het geen probleem vindt, dan zoek ik op andere thema's (o.a. volledigheid, relaties, historie) ook enkele BSN's voor de vervaardiging van voorbeeldberichten.

**Comment by mvdbro** [comment]
In onderzoek heb ik nog niet geïmplementeerd, omdat dit nog niet is uitgekristalliseerd in de specificatie. Onvolledige datum is wel al geïmplementeerd. Geef maar aan welke interessant vanuit het oogpunt van onvolledige datums.

Historie in de responsen is ook niet geïmplementeerd, omdat ik in de spec nog niet heb kunnen terugvinden hoe hiermee wordt omgegaan. Ook de historische bevragingen zijn nog niet geïmplementeerd, maar dat is op afzienbare termijn wel mogelijk.

**Comment by gertjanvanderkooij** [comment]
OK, begrijp ik. Heb je dan voor mij:
- BSN: 999 992 806 / ANR: 719 6269 672
- BSN: 999 994 220 / ANR: 752 3826 821
- BSN: 999 990 858 / ANR: 651 5438 525

Graag fullblown (alle expands, alle fields als het mogelijk is).

**Comment by mvdbro** [comment]
Het lijkt me beter, als je mij de url aanlevert met een fictieve hostnaam, dan kan ik die url uitvoeren en je de respons mailen. Zo krijgen we geen verschil van inzicht over wat je wilt hebben.

**Comment by JohanBoer** [comment]
Met het realiseren van de referentie-implementatie die in gang wordt gezet wordt ieder testgeval ook een voorbeeldbericht. Tot die tijd is de Automockup van swaggerhub het voorbeeldbericht op basis van de example-warden van elementen. 
Te vinden op 
https://petstore.swagger.io/?url=https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/Bevraging-Ingeschreven-Persoon/openapi.yaml#/ingeschrevenpersonen/ingeschrevenpersonen
