### ISSUE TITLE
Foutieve verwachting features\gba-dev\rni-gba.feature:192

### ISSUE THREAD

**Issue by KayodeBakker** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1448]
**Beschrijf de bug**
Bij deze scenario wordt er verwacht dat er alleen een bsn terug komt met de RNI van persoon en verblijfplaats, echter de insert bij deze scenario doet ook een insert van de inschrijving (lo3_pl) met ook een RNI 0101. De GBA API levert netjes alle drie de rni's aan (persoon, inschrijving en verblijfplaats) samen met de bsn. De scenario verwacht echter dat alleen bsn + rni persoon + rni verblijfplaats wordt aangeleverd.

Graag hoor ik of dit een scenario fout is of dat er weer impliciete logica is waar de GBA API vanaf hoort te weten.

**Comment by JohanBoer** [comment]
Zoals eerder besproken, dit staat beschreven in de Rule van de rni-gba.feature. Dus het is functioneel beschreven als dat er een scenario is dat de verwachte output in de betreffende situatie beschrijft en test. 
Ik snap niet zo goed waarom dit voor jou dan een impliciete regel is.
