### ISSUE TITLE
veld datumAanvangAdreshouding wordt gevuld met waarde van element 13.20

### ISSUE THREAD

**Issue by MelvLee** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1454]
De waarde van element 13.20 hoort in de datumAanvangAdresBuitenland veld

Reproductie pad: npx cucumber-js features/bevragen/persoon/verblijfplaats/dev/gba.feature:18 in #1453

versie gba-api: 2.0.12

**Comment by KayodeBakker** [comment]
Opgelost in versie 2.0.14
