### ISSUE TITLE
Als Berichtontwikkelaar en als Scrum Master wil ik duidelijkheid hebben over de vaststellingsprocedure van standaarden

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#146]
...zodat de standaard ook formeel in gebruik kan worden genomen door gemeenten en gemeentelijke leveranciers en er duidelijkheid is over de status van de standaard.

**Acceptatiecriteria**
- [ ] API lab voor leveranciers zodat de standaard en referentie implementatie getest wordt 
- [ ] Demo ('s) zodat gemeenten in de gelegenheid zijn om te checken of hun eisen/ wensen voldoende zijn meegenomen.

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JanWillemKooi** [comment]
Aanvullingen bij Acceptatie criteria, na discussie met @wishalg 
- De API standaard en referentie implementaties moeten getest worden door leveranciers in een API -lab
- Gemeenten moeten de gelegenheid krijgen om te controleren of hun eisen/ wensen voldoende zijn meegenomen in het project, door een of meerdere demo's te organiseren.

**Comment by CathyDingemanse** [comment]
Demo en API lab staan op de backlog. Echter, daarvoor moet @wishalg capaciteit regelen voor een referentie implementatie.
