### ISSUE TITLE
De response van de Proxy API geeft  een lege 'geboorte' groep terwijl deze gevuld moet zijn.

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1463]
Het gaat om het 2e voorbeeld van het abstracte scenario 'persoon heeft &lt;groep> &lt;veld> van partner in onderzoek' in de branch 'e2e-automation-inOnderzoek.

**Comment by MelvLee** [comment]
Er zit een fout in de scenario. 050310 geeft aan dat geboorte datum in onderzoek is. geboorte plaats in onderzoek is 050320

**Comment by melsk-r** [comment]
Dat was hem, issue is opgelost.
