### ISSUE TITLE
Fout verwachting rondom (europees) kiesrecht in onbekend_waardes_gba feature

### ISSUE THREAD

**Issue by KayodeBakker** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1498]
**Beschrijf de bug**
Bij het uitvoeren van de volgende scenario:
features\gba-dev\onbekend_waardes_gba.feature:315

wordt een verwachting geschept dat het persoon object de volgende waardes bevat:
```json
{
   "burgerservicenummer": "000000322",
   "opschortingBijhouding": {
     "datum": "00000000"
   },
   "europeesKiesrecht": {
     "einddatumUitsluiting": "00000000"
   },
   "uitsluitingKiesrecht": {
     "einddatum": "00000000"
   }
 }
```

Het response daarentegen bevat het volgende:

```json
{
        "burgerservicenummer": "000000322",
        "opschortingBijhouding": {
                "datum": "00000000"
        }
}
```

Het lijkt er op dat er geen aanduiding wordt geleverd voor europees kiesrecht en het uitsluiting van kiesrecht waardoor de GBA API beide niet opneemt in het response. In november hebben we geconcludeerd (en gevalideerd bij de RvIG) dat het niet voorkomt dat een datum gevuld is voor europees en uitsluiting kiesrecht maar dat er geen aanduiding is voor beiden. Zelfs dan zouden er controles zijn op deze eisen in het LO. Daarmee is deze scenario invalide en zal er geen aanpassing moeten worden verwacht vanuit de GBA API. 

Graag deze scenario bijstellen.

**Comment by JohanBoer** [comment]
Aangepast. Zowel gba als e2e feature. Beide slagen nu.
