### ISSUE TITLE
Briefadres == correspondentieadres?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#15]
In RSGB schijnt het briefadres te zijn gemodelleerd als correspondentieadres. Dit wordt verwarrend gevonden, omdat correspondentieadres ook een plusgegeven/kerngegeven kan zijn. Er is in de berichtuitwisseling wel behoefte aan het briefadres, niet aan een niet-authentiek correspondentieadres dat bijvoorbeeld in een procesapplicatie kan zijn opgeslagen. Hoe kunnen we hiermee omgaan?

**Comment by fsamwel** [comment]
In e-mail heb ik deze vraag voorgelegd aan Ellen en Remko

**Comment by CathyDingemanse** [comment]
De meest voor de hand liggende oplossing is het opnemen van het briefadres (conform BRP definitie) in RSGB.

**Comment by Remkodehaas** [comment]
er is in RSGB gekozen om een een Briefadres te modelleren bij Correspondentieadres van objecttype SUBJECT o.a. omdat het (in de betekenis) gaat om het versturen van correspondentie naar de betreffende persoon. 

Een INGESCHREVEN NATUURLIJK PERSOON (INP) heeft in het GBA **of** een Woonadres **of** een Briefadres. Wanneer het om een Briefadres gaat:

- INP.Verblijfadres ingeschreven natuurlijk persoon. Adresherkomst = 'Briefadres' 
-SUBJECT._heeft als correspondentieadres_ ADRESSEERBAAR OBJECT AANDUIDING met de attributen en relatiesoorten: Huisnummer, Huisletter, Huisnummertoevoeging, Postcode, (relatiesoort) _ligt in_ WOONPLAATS

**Comment by JohanBoer** [comment]
Dit is inmiddels geïmplementeerd door de verblijfsplaats als resource op te nemen en daarin adresgegevens op te nemen. In de verblijfsplaats kan je middels het element "Adresherkomst"  kan je in de verblijfsplaats aangeven of het een woonadres of een briefadres betreft. 
Dat is conform hetgeen op 21 september besproken is.

**Comment by mvdbro** [comment]
Ik vraag me af of de naam verblijfplaats dan wel zo gelukkig is voor de adresgegevens uit de GBA. Inschrijvingsadres lijkt me meer in overeenstemming met het feit dat de verblijfplaats ook een briefadres kan zijn en daarmee een adres waar niet wordt verbleven.

Het een briefadres kunnen zijn van de verblijfplaats lijkt me ook comsequenties te hebben voor de vraag naar bewoning. Het lijkt me niet correct om ook personen terug te geven die het adres als briefadres hebben. Als het laatste wel gewenst is, dan is ook hier de elementnaam inschrijving passender dan bewoning.

**Comment by fsamwel** [comment]
In LO GBA heet dit 08/58 Verblijfplaats. Daarbinnen zit gegeven 10.10 Functie adres.

M.i. moet niet "Verblijfplaats" hernoemd worden, maar "Adresherkomst" (naar "Functie adres")

@CathyDingemanse ben jij het met @mvdbro eens dat bewoning alleen personen als bewoners moet teruggeven met Functie adres = "W"?

**Comment by fsamwel** [comment]
@JohanBoer pas jij de naam van attribuut Adresherkomst aan? Ook even check voor de zekerheid dat RSGB attribuut Adresherkomst inderdaad hetzelfde is als Functie adres. Dank je.

**Comment by gertjanvanderkooij** [comment]
> @CathyDingemanse ben jij het met @mvdbro eens dat bewoning alleen personen als bewoners moet teruggeven met Functie adres = "W"?

Dat is geheel afhankelijk van het gebruik binnen de gemeente. Ikzelf zou de ingeschrevenen met Functie adres = "B" wel terug geven. In de praktijk weliswaar geen daadwerkelijke 'bewoners', maar deze personen zijn in de BRP wel op het betreffende adres ingeschreven. 

Bovendien mogelijk signalerende werking als je binnen de gemeente bewoningssituaties op adressen tegen komt met alleen (of een veelvoud) aan briefadreshouders.

**Comment by fsamwel** [comment]
We kunnen ook functie adres als query parameter opnemen bij bewoning. Dan kan de client zelf kiezen.

**Comment by CathyDingemanse** [comment]
> > @CathyDingemanse ben jij het met @mvdbro eens dat bewoning alleen personen als bewoners moet teruggeven met Functie adres = "W"?
> 
> Dat is geheel afhankelijk van het gebruik binnen de gemeente. Ikzelf zou de ingeschrevenen met Functie adres = "B" wel terug geven. In de praktijk weliswaar geen daadwerkelijke 'bewoners', maar deze personen zijn in de BRP wel op het betreffende adres ingeschreven.
> 
> Bovendien mogelijk signalerende werking als je binnen de gemeente bewoningssituaties op adressen tegen komt met alleen (of een veelvoud) aan briefadreshouders.

Ik vind de benaming bewoning of misschien beter: TijdreisBewoning of BewoningTijdreis (want het is een zuiver historische resource geworden) beter dat iets als historischeInschrijvingOpAdres oid, want dat snap je gewoon niet als je geen domeindeskundige bent. 
Ik zou zeker de ingeschrevenen met functie= briefadres teruggeven, en deze functie opnemen in de resource. Overigens niet met de afkortingen Functie adres = "W" of Functie adres = "B", maar uitgeschreven Functie adres = Woonadres, Functie adres = Briefadres.
Dan kan men zelf zien wat er aan de hand is.

> We kunnen ook functie adres als query parameter opnemen bij bewoning. Dan kan de client zelf kiezen.
>
Eens, dat moeten we zeker doen. Dat geeft ook weer extra awareness.

**Comment by fsamwel** [comment]
De discussie over opnemen code of omschrijving bij enumeraties hebben we eerder gehad. Toen liepen we tegen problemen op in bepaalde enumeraties (enorm lange omschrijvingen en niet-ascii in de omschrijving). Dat hebben we toen teruggedraaid. O.a. omdat de client in de api specificaties duidelijk ziet wat de code ("B" en "W") betekenen, en omdat de client toch niet (zelden) direct de ontvangen waarde ("Briefadres" of "Woonadres") op het scherm zal tonen.

@CathyDingemanse  Wil je hier een voor Functie adres een uitzondering maken op de regel door toch de omschrijving op te nemen?
