### ISSUE TITLE
Opmerkingen n.a.v. testimplementatie door Frank. 

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#150]
Bij het maken van de testimplementatie liep ik wel tegen een aantal punten aan die naar mijn mening anders moeten/kunnen in de yam:
* verwijderen inonderzoek relaties (moeten in betreffende sub-resource worden opgenomen):
  `inonderzoek__partner` bool,
  `inonderzoek__kind` bool,
  `inonderzoek__ouder` bool,
* `voorvoegselGeslachtsnaam` kan worden ingeperkt tot `voorvoegsel` in NaamInOnderzoek (hoewel het in GBA wel "Voorvoegsel geslachtsnaam” heet)
* `redenOpnameNationaliteit`, `redenBeindigenNationaliteit` moet zijn `redenOpname`, `redenBeindigen` in NationaliteitInOnderzoek (niet herhalen van groepsnaam in groepsattributen)
* `geboortedatum`, `geboorteplaats`, `landGeboorte` moet zijn `datum`, `plaats`, `land` in GeboorteInOnderzoek
* `datumOverlijden`, `plaatsOverlijden`, `landOverlijden` moet zijn `datum`, `plaats`, `land` in OverlijdenInOnderzoek
* toevoegen `geldigVan` (element 85.10 ingangsdatum geldigheid) aan Kind
* verwijderen `geldigTotEnMet` bij Ouder (ik heb in GBA geen einde geldigheid gevonden bij Ouder1 of Ouder2
* verwijderen `ouder_aanduiding` bij een kind (dit veronderstelt dat kinderen gehaald worden uit de Ouder1 en Ouder2 van de ouders, i.p.v. uit categorie 9/59 Kind)
* `code` niet integer maar string (maxLength 4) in Nationaliteit_tabel
* `redenopnemen_beeindigennationaliteit` niet integer maar string(maxLength 3) in `Redenverkrijgingopnemen_beeindigennationaliteit_tabel
* `Gemeenten` moet zijn `Gemeenten_tabel` (alle componenten voor een GBA tabel laten we eindigen op _tabel)
* voorvoegsel definiëren als string i.p.v. verwijzing naar voorvoegseltabel (in deze tabel zit immers maar één kolom)
* `verblijfsplaatsenhistorie` wordt `verblijfplaatsenhistorie`
* ingeschrevenPersonen wordt ingeschrevenpersonen in Partner_links
* `ingeschrevennatuurlijkpersonen` moet zijn `ingeschrevenpersonen` in Reisdocument_links
* zoekparameter `verblijfplaats__gemeentevaninschrijving` toevoegen  bij /ingeschrevenpersonen
* zoekparameter `naam__voorvoegsel` toevoegen bij /ingeschrevenpersonen
* zoekparameter `geboorte__plaats` toevoegen bij /ingeschrevenpersonen
* toevoegen inonderzoek aan partner, ouder en kind
* zijn de datums voor reisdocumenten echt terecht allemaal mogelijk onvoledig? Ik kan me daar niet zoveel bij voorstellen.
* gebruiken we consequent geldigVan en geldigTotEnMet of consequent orginele (LO GBA) attribuutnaam? Nu is het soms het ene, soms het andere.

**Comment by JohanBoer** [comment]
> * verwijderen inonderzoek relaties (moeten in betreffende sub-resource worden opgenomen):
>   `inonderzoek__partner` bool,
>   `inonderzoek__kind` bool,
>   `inonderzoek__ouder` bool,

Volgens mij achterhaald door huidige oplossing ïnOnderzoek"

> * `voorvoegselGeslachtsnaam` kan worden ingeperkt tot `voorvoegsel` in NaamInOnderzoek (hoewel het in GBA wel "Voorvoegsel geslachtsnaam” heet)

Done

> * `redenOpnameNationaliteit`, `redenBeindigenNationaliteit` moet zijn `redenOpname`, `redenBeindigen` in NationaliteitInOnderzoek (niet herhalen van groepsnaam in groepsattributen)

Done

> * `geboortedatum`, `geboorteplaats`, `landGeboorte` moet zijn `datum`, `plaats`, `land` in GeboorteInOnderzoek

Done

> * `datumOverlijden`, `plaatsOverlijden`, `landOverlijden` moet zijn `datum`, `plaats`, `land` in OverlijdenInOnderzoek

Done

> * toevoegen `geldigVan` (element 85.10 ingangsdatum geldigheid) aan Kind

Is niet door de productowner aangemerkt als op te nemen n.a.v. de analyse in #147 

> * verwijderen `geldigTotEnMet` bij Ouder (ik heb in GBA geen einde geldigheid gevonden bij Ouder1 of Ouder2

Done

> * verwijderen `ouder_aanduiding` bij een kind (dit veronderstelt dat kinderen gehaald worden uit de Ouder1 en Ouder2 van de ouders, i.p.v. uit categorie 9/59 Kind)

Done

> * `code` niet integer maar string (maxLength 4) in Nationaliteit_tabel

Done

> * `redenopnemen_beeindigennationaliteit` niet integer maar string(maxLength 3) in `Redenverkrijgingopnemen_beeindigennationaliteit_tabel

Done

> * `Gemeenten` moet zijn `Gemeenten_tabel` (alle componenten voor een GBA tabel laten we eindigen op _tabel)

Done

> * voorvoegsel definiëren als string i.p.v. verwijzing naar voorvoegseltabel (in deze tabel zit immers maar één kolom)

Done ( tabel met 1 kolom wordt inmiddels gegenereerd als string)

> * `verblijfsplaatsenhistorie` wordt `verblijfplaatsenhistorie`

Is uiteindelijk 'verblijfplaatshistorie' geworden

> * ingeschrevenPersonen wordt ingeschrevenpersonen in Partner_links

Done

> * `ingeschrevennatuurlijkpersonen` moet zijn `ingeschrevenpersonen` in Reisdocument_links

Endpoint Reisdocumenten is naar de volgende sprint verplaatst

> * zoekparameter `verblijfplaats__gemeentevaninschrijving` toevoegen  bij /ingeschrevenpersonen

Done

> * zoekparameter `naam__voorvoegsel` toevoegen bij /ingeschrevenpersonen

Done

> * zoekparameter `geboorte__plaats` toevoegen bij /ingeschrevenpersonen

Done

> * toevoegen inonderzoek aan partner, ouder en kind

Done

> * zijn de datums voor reisdocumenten echt terecht allemaal mogelijk onvoledig? Ik kan me daar niet zoveel bij voorstellen.


> * gebruiken we consequent geldigVan en geldigTotEnMet of consequent orginele (LO GBA) attribuutnaam? Nu is het soms het ene, soms het andere.

**Comment by fsamwel** [comment]
> verblijfsplaatsenhistorie wordt verblijfplaatsenhistorie
>Is uiteindelijk 'verblijfplaatshistorie' geworden

Dit is blijkbaar weer ongedaan gemaakt?
In IngeschrevenPersoon_links staat nog/weer verblijfsplaatsenhistorie

**Comment by fsamwel** [comment]
> Is uiteindelijk 'verblijfplaatshistorie' geworden
Wijzigt dan ook verblijfstitelshistorie in verblijfstitelhistorie (consequent enkelvoud gebruiken)?

**Comment by fsamwel** [comment]
> Is uiteindelijk 'verblijfplaatshistorie' geworden
> Wijzigt dan ook verblijfstitelshistorie in verblijfstitelhistorie (consequent enkelvoud gebruiken)?

Deze is nog niet meegenomen.

**Comment by JohanBoer** [comment]
Voorzover ik nu kan zien is dit verblijfplaatshitorie en komt de term verblijfstitelshistorie niet voor in de Yaml's . Ik heb wel in diverse decriptions verblijfsplaats vervangen door verblijfplaats. Dit is verwerkt in de eerstvolgende puul-request met de Yaml's.
