### ISSUE TITLE
Nieuwe rules laten bestaande scenarios van features\gba-dev\bag-identificatie.feature falen

### ISSUE THREAD

**Issue by KayodeBakker** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1503]
**Beschrijf de bug**
Dankzij nieuwe rules rondom verblijfplaats falen nu scenarios van features\gba-dev\bag-identificatie.feature omdat er o.a. een straat wordt toegevoegd aan de fields bij het bevragen van een bag identificatie. Nu falen de scenarios omdat deze niet kenmerken als straat verwachten.

Graag de scenarios updaten zodat deze verwachtingen weer correct zijn.

**Comment by JohanBoer** [comment]
@KayodeBakker Welke nieuwe rules bedoel je hier ? De drie scenarios die falen falen omdat er door de GBA-API foutieve nummerAanduidingIdentificaties en adresseerbaarObjectIdentificaties worden geleverd. 

De Functionaliteit is : "BAG-identificatie met waarde die niet voldoet aan de specificatie moet niet geleverd worden ".

De GBA-API zet voorloopnullen voor de te korte identificaties en levert ook identificaties met letters door. Volgens de rule is dat niet de bedoeling en moeten deze foutieve waarden niet geleverd worden.

**Comment by KayodeBakker** [comment]
@JohanBoer Het klinkt alsof je achterloopt op de GBA-API versie. Ik zou een hogere versie hanteren en nogmaals proberen. Nu staan we op 2.0.16.

**Comment by JohanBoer** [comment]
Inmiddels opgelost
