### ISSUE TITLE
Finale review van de features

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#151]
Alle features doorlopen en checken of ze kloppen met de business wens. Ook de bijbehorende testgevallen checken. Bevindingen ook vertalen naar aanpassingen in de API-spec

**Comment by fsamwel** [comment]
- historie_sorteren is achterhaald: klopt niet meer en juiste functionaliteit staat al in de betreffende historie features
- feature voor nationaliteithistorie ontbreekt nog. Zie #526.
