### ISSUE TITLE
fields=verblijfplaats.verblijfadres.huisletter levert geen huisletter van een adres

### ISSUE THREAD

**Issue by MelvLee** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1514]
reproductie pad: npx cucumber-js npx cucumber-js features/bevragen/persoon/verblijfplaats/dev/fields-gba.feature:58

versie: 2.0.16

**Comment by KayodeBakker** [comment]
Ik ben bezig met een 2.0.17 waar dit toevallig al in is gefixt.

**Comment by JohanBoer** [comment]
Getest, Gefixt
