### ISSUE TITLE
Elk scenario geeft waarschuwing "no access token. authenticate"

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#1535]
In de uitvoering van elk scenario van autorisatie-gba.feature geeft Cucumber de volgende melding:

```
.........no access token. authenticate
(node:19590) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
```

Wat betekent dit? Gaat hier iets fout?

**Comment by KayodeBakker** [comment]
@fsamwel Welke autorisatie-gba.feature specifiek is dat? Ik krijg deze meldingen niet.

**Comment by MelvLee** [comment]
de melding 'no access token. authenticate' is een debug melding die ik heb toegevoegd om te valideren dat de automation code maar 1 keer de identity provider aanroept voor een test sessie waarbij meerdere scenario's wordt uitgevoerd. Je wilt namelijk niet dat als er al een access token is verkregen dat de client (idg de automation code) toch weer een nieuwe access token gaat opvragen door opnieuw in te loggen.
De melding '(node:19590) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)' wordt teruggegeven door node-js. De dev identity provider gebruikt een self signed certificate en self signed certificaten worden standaard door node-js niet geaccepteerd. Om dit te omzeilen, heb ik in de automation code een configuratie setting van node-js aangepast. Node-js geeft daarom deze melding om aan te geven dat de setting NODE_TLS_REJECT_UNAUTHORIZED is gewijzigd naar de waarde '0'
