### ISSUE TITLE
partnerhistorie link is gedefinieerd als array maar kan maar één keer voorkomen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#155]
In IngeschrevenPersoon_links is element partnerhistorie gedefinieerd als array. 

Dat is niet terecht, want de partnerhistorie kent url /historie/ingeschrevenpersonen/{burgerservicenummer}/partners

Er kan dus maar één partnerhistorie url zijn per persoon (per burgerservicenummer)

**Comment by JohanBoer** [comment]
Kardinaliteit aangepast.
