### ISSUE TITLE
Geen verplichte attributen in het antwoord

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#157]
Er zijn nu een aantal attributen verplicht (required) gemaakt. Ik zie geen issue die duidelijk maakt waarom dit functioneel gewenst zou zijn. 

O.a. een aantal attributen voor inOnderzoek zijn verplicht, terwijl volgens mij de functionaliteit is dat je een inOnderzoek-attribuut weg mag laten wanneer het betreffende attribuut niet in onderzoek is.

Betreft /Bevraging-Ingeschreven-Persoon/openapi.yaml, is toegevoegd in commit van Jan 31, 2019.

* PersoonInOnderzoek:
      - "datumOpschortingBijhouding"
      - "landVanWaarIngeschreven"
* Kiesrecht: 
      - "einddatumUitsluitingKiesrecht"
* Verblijfplaats:
      - "datumInschrijvingInGemeente"
* VerblijfplaatsInOnderzoek:
      - "datumAanvangAdreshouding"
      - "geldigTotEnMet"
      - "datumInschrijvingInGemeente"
* Gezagsverhouding:
      - "indicatieCurateleRegister"
* GezagsverhoudingInOnderzoek:
      - "indicatieGezagMinderjarige"
* ReisdocumentInOnderzoek:
      - "signaleringVerstrekkenReisdocument"

**Comment by fsamwel** [comment]
zie ook beslissing 
https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/design_decisions.md#de-response-heeft-geen-verplichte-properties en #3

**Comment by JohanBoer** [comment]
Dit is geen functionele wens, maar zijn fouten bij het doorvoeren van wijzigingen. Een deel hiervan was in de commit van 18 februari al verwerkt, maar met jouw lijstje heb ik nog een paar fouten kunnen elimineren. Die worden in de eerstvolgende pull-request meegenomen. Ik wacht even Cathy's reactie op #158  af zodat ik dat ditect mee kan nemen.

**Comment by JohanBoer** [comment]
Deze check moet nog plaatsvinden op de **Historie**-endpoints. Vandaar dat deze is heropend.

**Comment by fsamwel** [comment]
gecheckt: er zit geen required property in de antwoorden (meer)
