### ISSUE TITLE
A-nummer van persoon in het antwoord?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#158]
Is er behoefte aan het A-nummer van een persoon (incl. ouder, partner, kind)?

Komt niet voor in de autorisatietabellen van gemeente Den Haag, dus daar wordt het A-nummer niet gebruikt.

**Comment by CathyDingemanse** [comment]
In principe is het BSN het identificerende gegeven. @ Johan, graag verwijderen!

**Comment by JohanBoer** [comment]
Geldt voor alle gemeenten dat het A-nummer geen rol meer heeft ? In de testset van het RvIG is rubriek 01.01.10 (A-nummer) nog steeds opgenomen. In onze API-specificatie heeft het A-nummer geen identificerende rol, maar wordt het alleen weergegeven. 
Als ik op internet rondsnuffel kan ik nergens vinden dat het A-nummer obsoleet of depricated is en het staat nog steeds in het LO-GBA. 
@CathyDingemanse , als je ondanks bovenstaande toch wil dat ik het A-nummer verwijder doe ik dat natuurlijk graag.

**Comment by CathyDingemanse** [comment]
De gemeente Den Haag is zeker niet het uitgangspunt. De redenatie is dat we het A-nummer altijd kunnen toevoegen als daar behoefte aan blijkt te zijn. Weghalen is lastiger. 
Ook hebben meerdere leveranciers verwonderd gereageerd op de aaneezigheid van het Anummer.  M.a.w. graag verwijderen.
