### ISSUE TITLE
Als ontwikkelaar wil ik slechts 1 endpoint voor het raadplegen van een resource

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#16]
...zodat resources eenduidig worden ontsloten.

Concreet is dit issue gemaakt door [deze ontwerp keuze](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/design_decisions.md):

> Er wordt per combinatie van query parameters voor het zoeken van ingeschreven natuurlijk personen een endpoint gedefineerd. Bijvoorbeeld "/ingeschrevennatuurlijkpersonenpostcode" en "/ingeschrevennatuurlijkpersonengeslachtsnaam". 

Als ik het goed begrijp krijg je dus:
```
/ingeschrevennatuurlijkpersonenpostcode/?postcode=1234AA
/ingeschrevennatuurlijkpersonengeslachtsnaam/?geslachtsachternaam=Janssen
```

Dit lijkt mij een onwenselijke situatie. Er ontstaan zo 2 endpoints, die dezelfde resource ontsluiten, waardoor een specifiek object ook middels verschillende endpoints opvraagbaar zijn en identificeerbaar zijn. Tevens krijg je dus een oneindige lijst aan endpoints die bepaalde query parameters toe staan, die allemaal dezelfde resource terug geven? Waarom hebben we dan nog query parameters?

Volgens mij moet je ten alle tijde 1 endpoint hebben per resource:
```
/ingeschrevennatuurlijkpersonen/?<query params>
```

En mocht het voor business logica nodig zijn om slechts bepaalde query parameters, of combinatie van query parameters, toe te staan, dan moet hier (op de query parameters) gewoon validatie op komen. Er komt dan een foutmelding als je een verkeerde combinatie maakt, en de mogelijke query parameters zijn netjes gedocumenteerd.

Het klopt overigens dat het niet mogelijk is in de OAS programmatisch vast te leggen welke combinaties mogelijk zijn en welke niet. Dit komt neer op een stukje documentatie. Voer voor een andere discussie is wellicht waarom je slechts bepaalde combinaties wil toe staan.

**Comment by CathyDingemanse** [comment]
Beste Joeri, ik denk dat je gelijk hebt, dit experiment is inderdaad enigszins doorgeslagen :-). Hier is voor ieder zoekpad een aparte resource gedefinieerd, hetgeen leidt tot een wildgroei aan resources. En dat terwijl de query parameter speciaal voor dit doel in het leven is geroepen. 

Nu wordt deze API de komende jaren in theorie nog op 380 plekken aangeboden (geen Landelijke Registratie), en we willen bereiken dat consumers van binnengemeentelijke afnemers in meer, zo niet alle gemeenten (met minimale aanpassingen) kunnen worden hergebruikt. Dan is het belangrijk om duidelijk te maken welke zoekpaden (minimaal) moeten worden ondersteund. Op deze manier kom je al een heel eind:
 /ingeschrevennatuurlijkpersonen? geslachtsnaam={geslachtsnaam} 
/ingeschrevennatuurlijkpersonen? geslachtsnaam={geslachtsnaam} & geboortedatum={geboortedatum}
..... etc.
Je hebt gelijk dat dit moet worden aangevuld met documentatie in natuurlijke taal.
Omdat dit bovendien niet allemaal door het API contract kan worden gevalideerd, zou VNG Realisatie misschien een testconsumer kunnen maken die valideert of de API de gespecificeerde paden (op de juiste manier) implementeert (toets op interoperabiliteit) en of de minder wenselijke combinaties van queryparameters adequaat worden geweerd (toets kwaliteit oplossing). 

Dit gezegd hebbende: bovenstaand experiment komt niet helemaal uit de lucht vallen. 
Het is mijn inziens niet zo dat een resource hetzelfde is als een entiteit en deze slechts via 1 endpoint moet kunnen worden gevonden.
De discussie binnen de werkgroep is ontstaan naar aanleiding van het zoeken van een ingeschreven natuurlijk persoon op postcode en huisnummer. De postcode en huisnummer zijn in principe adresgegevens en horen bij een ander domein (BAG), waarbij de relatie wordt beheerd in de BRP. Bij een fijnmazige opzet van resources zoek je dan met de postcode/hn een BAGID en via het BAGID de ingeschreven natuurlijke personen. Om te voorkomen dat deze logica bij de consumer wordt gelegd (die dan domeinkennis moet hebben), zou je kunnen aanbieden:
/ingeschrevennatuurlijkpersonen? postcode={postcode}& huisnummer={huisnummer}
en bijv. zelf in je implementatie de relatie leggen via de BAG.

Je kunt ook zeggen: we maken van deze relatie een resource. Ook deze geeft ingeschreven natuurlijke personen terug:
/bewoners? postcode={postcode}& huisnummer={huisnummer}
/bewoners? nummeraanduiding = {nummeraanduiding}
/bewoners? verblijfsobject = {verblijfsobject}
   
Dit heeft de volgende voordelen:
-  de informatiebehoefte van afnemers heeft vaak betrekking op relaties. Helemaal als het historie betreft. Zo ook in de requirements van RSGB bevragingen/BRP. Heel belangrijk is de businessvraag: wie woonde er op (binnen welke periode) dit adres? Moet je deze "bewoners" dan meegeven als relaties van een adresentiteit/resource? Nee, dat gaat niet. Als je alleen maar denkt: resource=een entiteit, laat je een hele wereld aan mogelijkheden liggen die VOOR EEN GEBRUIKER belangrijk, relevant en betekenisvol zijn. 
- Semantisch duidelijker en intuitiever voor een gebruiker (bewoning associeer ik met adres, persoon met geboortedatum en andere persoonskenmerken).
- het onderliggende model wordt naar je gebruikers toe inzichelijker (ik zoek op een relatie, misschien wel met een ander domein, misschien ook wel met en andere eigenaar/beheerder...). 

Tenslotte: dit is geen pleidooi om van alle relaties tussen objecten een resource te gaan definieren! In tegendeel. Ik stel wel voor om dit te doen ALS DIT INVULLING GEEFT AAN/AANSLUIT BIJ EEN CONCRETE BUSINESSVRAAG VAN AFNEMERS. RSGB bevragingen moet consistent zijn voor gebruikers over de domeinen heen. Denk ook heel even na hoe dit uitpakt voor relaties in de andere domeinen (eigenaren van kadasterale objecten?).

**Comment by joeribekker** [comment]
> Beste Joeri, ik denk dat je gelijk hebt, dit experiment is inderdaad enigszins doorgeslagen

Ha Cathy. Bedankt voor je antwoord. Experimenteren hoort er bij!

Je gaat wel op een aantal andere punten in die wellicht een eigen issue mogen hebben maar dat laat ik aan jullie. IK ga er kort even op in.

> Dit gezegd hebbende: het is mijn inziens niet zo dat een resource hetzelfde is als een entiteit en deze slechts via 1 endpoint moet kunnen worden gevonden [...] Ook deze GET geeft ingeschreven natuurlijke personen terug: `/bewoners? postcode={postcode}& huisnummer={huisnummer}`

Helemaal mee eens, in dit voorbeeld.

> De discussie binnen de werkgroep is ontstaan naar aanleiding van het zoeken van een ingeschreven natuurlijk persoon op postcode en huisnummer. De postcode en huisnummer zijn in principe adresgegevens en horen bij een ander domein (BAG), waarbij de relatie wordt beheerd in de BRP. Bij een fijnmazige opzet van resources zoek je dan met de postcode/hn een BAGID en via het BAGID de ingeschreven natuurlijke personen. Om te voorkomen dat deze logica bij de consumer wordt gelegd (die dan domeinkennis moet hebben), zou je kunnen aanbieden:
> `/ingeschrevennatuurlijkpersonen? postcode={postcode}& huisnummer={huisnummer}`
> en bijv. zelf in je implementatie van de provider de relatie leggen via de BAG.

Ik begrijp de functionele wens maar volgens mij is dat in de onderste service laag niet handig.

Precies wat je aangeeft, moet de consumer in deze situatie 2 calls maken, wat mij helemaal niet erg lijkt. Er moeten **altijd** 2 calls gemaakt worden, alleen in je voorbeeld wordt de 2e call gedaan door de API naar aanleiding van de 1e call. Dit impliceert een aantal zaken, maar grofweg: API 1 moet kennis van, en toegang hebben tot API 2.

Als deze functionele wens een vaak gebruikt scenario is, dan kan het wel, maar ik zou dat in een hoger gelegen API oplossen (composite API layer) die de API die jullie hier aan het bouwen zijn aanspreekt. In die laag kan je dan ook meer kennis regelen van verschillende API's, credential forwardering (oid) en meer applicatie gerichte API's maken.

Echter, het ontbreken van een composite API maakt de functionele vraag niet onmogelijk (2 calls door consumer).

> * Semantisch duidelijker en intuitiever zoeken voor een gebruiker (bewoning associeer ik met adres/ verblijfsobject, persoon met geboortedatum en andere persoonskenmerken).
> * het onderliggende model wordt naar je gebruikers toe inzichelijker (ik zoek op een relatie, misschien wel met een ander domein, misschien ook wel met en andere eigenaar/beheerder...).

Het klinkt alsof je wilt dat deze API's door (eind)gebruikers gebruikt moeten gaan worden? Dat lijkt mij nooit het geval. Als je doelt op ontwikkelaars, die komen er wel uit. En leveranciers moeten een mooie gebruikersvriendelijke interface er op bouwen in de applicatie laag.

> Tenslotte: dit is geen pleidooi om van alle relaties tussen objecten een resource te gaan definieren! In tegendeel. Ik stel wel voor om dit te doen als dit invulling geeft aan een concrete businessvraag van afnemers.

Ah, nog een heet hangijzer :) Ik denk dat je er toch niet om heen kunt dat elke relatie een resource wordt. Zodra je informatie bij een relatie (bijvoorbeeld: wanneer is de relatie gelegd, door wie, wat is de context) wilt opslaan is deze noodzakelijk. Ik denk dat hier genoeg business vragen voor zijn. ALs dat niet zo is, dan moeten we het inderdaad niet doen!

**Comment by CathyDingemanse** [comment]
Ha Joeri, even ter verduidelijking/geruststelling: 

> Het klinkt alsof je wilt dat deze API's door (eind)gebruikers gebruikt moeten gaan worden? Dat lijkt mij nooit het geval. Als je doelt op ontwikkelaars, die komen er wel uit. En leveranciers moeten een mooie gebruikersvriendelijke interface er op bouwen in de applicatie laag die niets weg heeft van hoe een API er uit ziet.

Nee hoor, dat bedoel ik niet :-). Ik bedoel een ontwikkelaar.

**Comment by CathyDingemanse** [comment]
Prima, spreek je op de fieldlab!

**Comment by fsamwel** [comment]
Naar mijn idee is dit issue nu opgelost, door niet meer specifieke endpoints per combinatie van query parameters te definiëren.

**Comment by fsamwel** [comment]
Zie [beslissing](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/docs/design_decisions.md#e%C3%A9n-uniform-endpoint-voor-zoeken-ingeschreven-natuurlijk-persoonsgegevens)

**Comment by joeribekker** [comment]
Top. Had zelfs generieker gemogen maar prima voor nu.

Merk wel in ZDS traject dat dit ook in de OAS moet staan als description can de parameters en niet alleen in een docje.

**Comment by joeribekker** [comment]
@fsamwel Idee lijkt me prima. Paar suggesties: Het hoeft niet perse als querystring, mag ook met bullets of komma gescheiden; ik zou ook aangeven welke optioneel zijn (zoals huisletter); en algemene query params weglaten (page, expand)

> Er kan gezocht worden met verschillende zoekpaden van zoekparameters:
>
> Adres
> * postcode
> * huisnummer
> * huisletter (optioneel)
> * huisnummertoevoeging (optioneel)
> ...

**Comment by fsamwel** [comment]
@JohanBoer: kan je dit ook op endpoint/method niveau in de description zetten? Voorstel van Joeri (bullitted lijsten) lijkt mij ook duidelijk.

**Comment by JohanBoer** [comment]
Voorstel is duidelijk, maar als ik in EA een description opneem dan worden de line-feeds er door Imvertor uitgesloopt. Ik kan dus wel een aantal MARKDOWN edit-faciliteiten gebruiken, maar de bullited list vereist linefeeds. De gewenste beschrijvingen neem ik op en ik maak voor nu met de hand de bullited listen aan. Ik zal een issue indienen om dit ook uit Imvertor te kunnen laten rollen.
