### ISSUE TITLE
Als PO wil ik dat er een oplossing komt voor het "onbekende datum" probleem. 

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#160]
...zodat binnen een comsumer er eenduidige interpretatie gegarandeerd is.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [x] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
In ieder geval aandacht voor overlijden (land altijd meeleveren binnengemeentelijke autorisatie. Object overlijden komt altijd voor bij een overleden persoon. Buitengemeentelijk indien de gemeente als afnemer niet geautoriseerd is voor Land. )

Hetzelfde patroon geldt voor: 

- Sluiting en ontbinding Huwelijk/partnerschap (ook land binnegemeentelijk en leeg object indien buitengemeenteltijk niet geautoriseerd voor Land.).

datumEindeGeldigheid Verblijfstitel (vraag is of de waarde van de datum onbekend in de praktijk volledig onbekend kan zijn. )

datumVestigingInNederland (vraag is of de waarde van de datum onbekend in de praktijk volledig onbekend kan zijn. Moet dan element landVanWaarIngeschreven meegetoond worden ? )

Datumopschortingbijhouding bij inschrijving (categorie 07) (vraag is of er autorisatie is om redenopschortingBijhouding  altijd mee te leveren. )

Categorieën Verblijfstitel en Reisdocument in de praktijk geen gebruik van (deels) onbekende datums.

**Comment by JohanBoer** [comment]
Bij nader inzien kan voor deze categorieën middels een indicatie aangegeven worden of de betreffende situatie van toepassing is. Bv. bij overlijden met een onbekende datum, plaats en land hoeft er geen onbekende datum gecommuniceerd te worden, maar wordt er een indicatie overleden opgenomen met de waarde "true".

Deze oplossing gaan we doorvoeren voor de volgende categorieën.
- Overlijden (indicatie_overleden)
- Sluiting en ontbinding Huwelijk/Partnerschap (Wordt 1 indicator bij Partner Indicatie_HuwelijkPartnerschapBeeindigd)
- Verblijfstitel (verblijfstitel beëindigd)
- DatumVestiging in Nederland (Indicatie_VestigingVanuitBuitenland
- DatumOpschortingBijhouding (Indicatie_OpschortingBijhouding)
- DatumeindegeldigheidReisdocument (Indicatie_ReisdocumentGeldig)

**Comment by fsamwel** [comment]
zie #182 en #198

**Comment by CathyDingemanse** [comment]
Bij nader inzien: zoals hierboven benoemd wordt in de praktijk in de categorie reisdoc geen onbekende datums gebruikt. Verblijfstitel (verblijfstitel beëindigd) en DatumeindegeldigheidReisdocument, krijgen daarom geen indicatie beeindigd. Deze indicatie is immers niet te maken als de einddatum er wel is, maar niet bekend is :-).
Zie ook #198 (DatumeindegeldigheidReisdocument) en  #182 (verblijfstitel beeindigd).

@JohanBoer, naast verwijderen van indicatie verblijfstitel, graag ook indicatie reisdocument beeindigd verwijderen.
