### ISSUE TITLE
De enum van Adelijke titel/predikaat is onjuist.

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#161]
Waarden van partnersschap staan er nu in

**Comment by JohanBoer** [comment]
Bleek een issue in het UML model te zijn. Nu verholpen

**Comment by JohnRooijakkers** [comment]
Bestaat er al een procedure op welke wijze een (toekomstige) wijziging van een enumeratie wordt geïmplementeerd in een productieve omgeving? Leidt dit dan automatisch tot een nieuwe versie van de API? Meer algemeen luidt de vraag hoe wordt omgegaan met wijzigingen in het API "contract".

**Comment by CathyDingemanse** [comment]
Dank voor de opmerking John. De versionering is afhankelijk van of de wijziging een breaking change is. Het beheer van API en de daarbij behorende versioneringsstrategie moet nog worden uitgewerkt en ingericht. Ik zal hiervoor een item op de backlog zetten.
