### ISSUE TITLE
Als PO wil ik dat een versioneringsstrategie wordt opgesteld voor deze API (ea)

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#163]
...zodat de API in beheer kan worden genomen.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by melsk-r** [comment]
Kijk [hier ](https://github.com/VNG-Realisatie/api-beheer/blob/master/versiebeheer.md) eens naar. Wij hebben er al over nagedacht. Input is natuurlijk altijd welkom.

**Comment by CathyDingemanse** [comment]
Super, dank Robert!

**Comment by CathyDingemanse** [comment]
zie https://github.com/Geonovum/KP-APIs/issues/157
