### ISSUE TITLE
Als medewerker van sociale wil ik alle historische verblijfplaatsen kunnen raadplegen 

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#168]
...zodat ik kan onderzoeken of een uitkering rechtmatig is verstrekt .

**Acceptatiecriteria**
- [ ] met periode van tot in de response
- [ ] raadplegen op peildatum
- [ ] raadplegen op periode van tot en met

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
Pas de resource aan door de groep verblijfsplaats te kopieren. Voeg datum einde geldigheid en indicatieeindegeldigheid (voor onbekende datum) toe
