### ISSUE TITLE
Als medewerker sociale zaken wil ik de partnerhistorie van een persoon kunnen raadplegen

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#169]
...zodat ik kan onderzoeken of een uitkering rechtmatig is verstrekt.

**Acceptatiecriteria**
- [x] periode van tot en met in de response
- [x] raadplegen op periode van tot en met
- [x] raadplegen op peildatum

**Definition of done**
- [ ] functionele specificatie
- [x] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JanWillemKooi** [comment]
Nav projectoverleg 23 aug:

Verwijderen:
Adelijke titel predikaat

Toevoegen:

**Comment by JohanBoer** [comment]
Opvragen van historie wordt gedefinieerd met aparte endpoints. Als een provider ervoor kiest om deze niet te implementeren wordt er een 501 geretourneerd. De historische bevraging krijgen dus resourcenaam waaruit blijkt dart het om een historische resource gaat. 
Met deze API kan de historie op het betreffende aspect opgevraagd worden.

Hiermee wordt het zoeken/raadplegen van de volgende historie ondersteund:
- bewoningen (welke personen hebben een adres als verblijfplaats gehad)
- verblijfplaatshistorie (welke verblijfplaatsen heeft een persoon gehad)
- partnerhistorie (welke partnerrelaties heeft een persoon gehad)
- verblijftitelhistorie (welke verblijftitels heeft een persoon gehad)
