### ISSUE TITLE
Als gemeente wil ik de bewoning van een verblijfsadres raadplegen

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#17]
...zodat ik kan zien welke personen gedurende welke periode op een verblijfsadres zijn/waren ingeschreven.

**Acceptatiecriteria**
- [x] consumer moet kunnen kiezen om wel of geen overleden personen in het antwoord terug te krijgen
- [x] consumer moet periode van tot en met op kunnen geven

**Definition of done**
- [ ] functionele specificatie
- [x] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by fsamwel** [comment]
voor het opvragen van bewoningshistorie wordt er endpoint toegevoegd:
/bewoningshistorie?van={periode.van}&totenmet={periode.totEnMet}&geldigOp={peildatum}

**Comment by JohanBoer** [comment]
> Kan niet vanuit adres, want die zit niet in BAG, alleen in BRP.

Als we een verblijfsplaats als adres onderkennen dan neem ik haast aan dat dat adres (met een verwijzing naar de nummeraanduiding (wel in de BRP wordt opgeslagen. Als je dat namelijk niet doet heeft deze zoekfunctie geen enkele zijn. Als je alleen bewoningen op basis van datums gaat selecteren krijg je rijp en groen door elkaar. Ik neem dus haast aan dat hier ook de postcode,  huisnummer  etc als parameters worden onderkend. In ieder geval heb ik deze endpoint nu wel zo gemaakt.  

Deze endpoint heb ik ook /bewoningen genoemd. Met het introduceren van de "GeldigOp" -parameter krijg je dus de actuele bewoners als de geldigOp-parameter op de actuele datum wordt gezet.
