### ISSUE TITLE
Als medewerker sociale zaken wil de verblijfstitelhistorie van een persoon raadplegen  

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#170]
...zodat ik kan onderzoeken of een uitkering rechtmatig is verstrekt.

**Acceptatiecriteria**
- [x] periode van tot in de response
- [x] raadplegen op periode van tot
- [x] raadplegen op peildatum

**Definition of done**
- [ ] functionele specificatie
- [x] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JanWillemKooi** [comment]
Update nav projectoverleg 23 aug:
Review is gedaan.
OAS moet aangepast worden.
Check naamgeving datum einde, datum ingang.
