### ISSUE TITLE
Waarom wordt het burgerservicenummer gebruikt in urls?

### ISSUE THREAD

**Issue by ThijsBroersen** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#172]
In de openapi-spec van Bevraging-Ingeschreven-Persoon kwam ik {burgerservicenummer} tegen in de paths. Dit is toch een uniek en beschermd persoonsgegevens? Dit kan terecht komen in logging en blijft hangen in de browsergeschiedenis. Tokens nemen we ook niet op in url's (API-16 van de api-strategie).

**Comment by CathyDingemanse** [comment]
Dit punt is ook in ons SCRUm team besproken. Hieronder onze overwegingen:

1. Het BSN vervangen voor een GUID of Unique Identifier lost dit probleem niet op. De URI is per definitie een unique identifier, ook de URI van een resource met persoongegevens. Ook deze zal op allerlei plekken (moeten) worden opgeslagen/bijgehouden, waarmee we er in no time met z’n allen een nieuwe BSN bij hebben. En dan eentje waarvan men misschien wel denkt dat hij "minder gevoelig is" dan het BSN en dat het daarom niet zo erg is als die wel mag "blijven hangen" in logging en caches. Oftewel: security by obscurity. Doe mij dan maar de BSN, dan gaan iig alle alarmbellen af die af moeten gaan.

2. Een ander alternatief is om alle uitwisseling met POST op te lossen, waarmee de URL niet langer een unique identifier meer is. De BSN maakt immers geen onderdeel meer uit van de URL, en kan niet meer worden gecached. Dan zijn we weer terug bij SOAP :-) en niet erg RESTful. POST is bedoeld om een nieuwe resource aan te maken, niet om resources op deze manier te raadplegen. 

Onze conclusie was en is: De URI is per definitie een unique identifier, ook voor persoonsgegevens. Daar moeten we dus goed mee leren omgaan. De provider geeft met “no-cache” in de header aan dat e.e.a. niet mag worden gecached. Buiten dat de API niet is bedoeld voor gebruik door browsers, is het “blijven hangen” in browsergeschiedenis en proxy’s en andere intermediairies een verantwoordelijkheid van de consumer. Iedere afnemer van persoonsgegevens heeft een eigenstandige verantwoordelijkheid om te zorgen dat dit in zijn domein niet gebeurt. Net zoals de consumer verantwoordelijk is voor het tonen van persoonsgegevens conform de doelbinding van eindgebruikers. Neem die verantwoordelijkheid en investeer in informatieveiligheid.

**Comment by RoelWKramer** [comment]
OWASP zegt het volgende over gevoelige data in een REST api's. 
https://cheatsheetseries.owasp.org/cheatsheets/REST_Security_Cheat_Sheet.html#sensitive-information-in-http-requests

> Sensitive information in HTTP requests¶
> RESTful web services should be careful to prevent leaking credentials. Passwords, security tokens, and API keys should > not appear in the URL, as this can be captured in web server logs, which makes them intrinsically valuable.
> 
> In POST/PUT requests sensitive data should be transferred in the request body or request headers.
> **In GET requests sensitive data should be transferred in an HTTP Header.**

Proxies, zowel aan client kant, als aan (jullie) server kant, kunnen de BSN in het url-path loggen. Als nu uitgesloten is dat die paden niet gelogd mogen worden, dan kan dat op een later moment bij configuratie changes mis gaan. Een path hebben in de logging is een handig debug middel bijvoorbeeld... 

Privacy en security gevoelige gegevens moeten m.i. per default niet op deze wijze gestuurd worden. Dan kan het ook niet later mis gaan.

Evt een token uitwisselen waarmee de bsn in het get request versleuteld wordt kan ook helpen, maar dat maakt werken met de api niet makkelijker.
