### ISSUE TITLE
Pattern in huisnummertoevoeging niet correct

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#174]
Attribuut huisnummertoevoeging in Verblijfplaats is niet correct gedefinieerd:
          pattern: "^[a-zA-Z0-9]$"
          maxLength: 4
          example: "2"

* volgens het pattern moet deze exact 1 teken lang zijn, maar de maxLength is 4
* het voorbeeld "2" is een vreemd (maar technisch wel correct) voorbeeld hiervoor, is er geen realistischer voorbeeld, zoals "rood"?

**Comment by fsamwel** [comment]
juiste pattern zou volgens mij zijn: "^[a-zA-Z0-9]{1,4}$"

**Comment by JohanBoer** [comment]
Dankjewel voor de input. Aangepast pattern zit in de eerstvolgende pull-request die ik doe met een nieuwe versie van de Yaml.
