### ISSUE TITLE
VerblijfplaatsInOnderzoek heeft geen adres-attributen (groep 11)

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#175]
In VerblijfplaatsInOnderzoek zitten nu (vrijwel) alleen attributen uit groepen 10 en 12. De belangrijkste gegevens zitten in groepen 11 (adres) of 13 (adres buitenland). Waarom zitten die er niet in?

(van groep 11 hebben we alleen identificatiecodeNummeraanduiding, niet bijvoorbeeld naamOpenbareRuimte)

In de GBA-V testset zit bijvoorbeeld een aantal gevallen met 08.83.10 = 081100
Hoe moet dat vertaald worden naar onze inOnderzoek groep? Alleen verblijfplaats.inOnderzoek.identificatiecodeNummeraanduiding=true?

**Comment by gertjanvanderkooij** [comment]
Hebben we afgelopen dinsdag tijdens Fieldlab besproken (you were there) en wordt als één van de openstaande punten aangepast.

**Comment by JohanBoer** [comment]
Dit is inmiddels doorgevoerd in EA en zit in de eerstvolgende pull request met de yaml.
