### ISSUE TITLE
naamPersoon of naam?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#176]
In IngeschrevenPersoon zit groepsattribuut naamPersoon. Waarom heet dit niet gewoon "naam" zoals in GBA groep 02 Naam?
Bij een ouder, kind of partner zitten dezelfde gegevens wel in een attribuut "naam".
Is dit een bewuste keuze?

**Comment by JohanBoer** [comment]
Dit is geen bewuste keuze. 
Inmiddels aangepast naar "naam" in het volgende pull-request met de yaml  is deze opgenomen.
