### ISSUE TITLE
Enumeratie aanduidingBijHuisnummer sluit niet aan bij GBA definitie

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#177]
In LO GBA is aanduidingBijHuisnummer gedefinieerd als enumeratie met mogelijke waarden:
* by - bij
* to - tegenover

In de API wordt dit echter gedefinieerd met mogelijke waarden:
* M - Man
* O - Onbekend

Hoe mappen de waarden "M" en "O" op "by" en "to"?

Waarom is ervoor gekozen af te wijken van de LO GBA enumeratiewaarden?

De beschrijving bij deze enumeratiewaarden, man en onbekend helpen hier ook niet bij.

**Comment by JohanBoer** [comment]
Dit heeft te maken met een fout in het aanleggen van de traces in de UML. Dit is nu hersteld en is in de volgende pull request aangepast.
