### ISSUE TITLE
indicatieOpschortingBijhouding wel in PersoonInOnderzoek niet in Persoon

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#178]
In component PersoonInOnderzoek zit attribuut indicatieOpschortingBijhouding. Deze zit niet in Persoon

**Comment by fsamwel** [comment]
Ik herken dit ook niet als GBA attribuut (zit niet in groep 67 Opschorting)

Is dit bedoeld als indicator in het geval van volledig onbekende datumOpschortingBijhouding?

**Comment by JohanBoer** [comment]
Dat is de juiste conclusie Frank, Ik heb deze indicatie verplaats naar de ingeschrevenPersson, waar hij thuis hoort.
