### ISSUE TITLE
voorbeeld parameter geboorte__datum niet correct

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#179]
bij /ingeschrevenpersonen staat de parameter:
        - in: query
          name: geboorte__datum
          description: "Datum waarop de INGESCHREVEN NATUURLIJK PERSOON geboren is. Er kan alleen gezocht worden met een volledige geboortedatum. Zie [functionele specificaties](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/features/parametervalidatie.feature)"
          required: false
          schema:
            type: string
            format: date
            example: 24-09-1964

Dit voorbeeld (24-09-1964) is niet correct volgens date format. Dit moet zijn "1964-09-24"

**Comment by JohanBoer** [comment]
Aangepsat zoals beschreven
