### ISSUE TITLE
Kiesrecht kan niet in onderzoek zijn

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#181]
Binnen de groep kiesrecht is nu een attribuut inOnderzoek opgenomen.

Dit is denk ik niet terecht, want volgens LO GBA heeft categorie 13 Kiesrecht geen groep 83 procedure

**Comment by fsamwel** [comment]
hetzelfde geldt voor attrinuten datumOpschortingBijhouding,indicatieGeheim, datumEersteInschrijvingGBA en redenOpschortingBijhouding.

Deze attributen komen uit categorie 07 Inschrijving. Deze categorie kan ook niet in onderzoek zijn.

**Comment by fsamwel** [comment]
in verblijfplaatsInOnderzoek zit wel attribuut datumInschrijvingInGemeente (09.20), maar niet gemeenteVanInschrijving (09.10).

Hoe kan er wel onderzoek zijn naar de datum inschrijving, maar niet naar de inschrijving zelf?

**Comment by JohanBoer** [comment]
Wijzigingen die Frank voorstelt doorvoeren door "Inonderzoek" bij kiesrecht te verwijderen en bij datumOpschortingBijhouding,indicatieGeheim, datumEersteInschrijvingGBA en redenOpschortingBijhouding de Inonderzoek indicaties te verwijderen. 

Over datumInschrijving waarop je van gemeente A naar gemeente B gaat kan in Onderzoek zijn. Of je in de betreffende Gemeente bent ingeschreven is een feit. Dat kan niet in onderzoek zijn. Als iemand zich ten onrechte in een andere gemeente heeft ingeschreven (om bv een hogere uitkering te krijgen) Dan is is de verblijfplaats in onderzoek en eventueel ook wel de datuminschrijving maar niet de gemeente van inschrijving want iemand heeft zich daadwerkelijk in die gemeente ingeschreven.  

@gertjanvanderkooij Kan jij dit bevestigen (of aangeven hoe het anders zit)?

**Comment by fsamwel** [comment]
> @gertjanvanderkooij Kan jij dit bevestigen (of aangeven hoe het anders zit)?

Is dit de [uitleg van Johan](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/issues/181#issuecomment-482481184) nu bevestigd? Dus dat de datum inschrijving in de gemeente in onderzoek kan zijn

**Comment by JohanBoer** [comment]
N.a.v. discussie van scrumteam op 07-06-2019 de conclusie getrokken dat we toch de indicatie gemeenteVanInschrijving in de groep "InOnderzoek" opnemen. We zijn het er over eens dat de betekenis van deze indicatie niet helemaal duidelijk is, maar we volgen het LO GBA
