### ISSUE TITLE
verblijfstitel bevat nog onterecht indicatie_verblijfstitelBeeindigd

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#182]
In de verblijfstitel zitten nog attributen datumEinde en indicatie_verblijfstitelBeeindigd.

Dit suggereert dat ook een beëindigde verblijfstitel moet worden opgenomen.

Op andere plekken nemen we alleen actuele gegevens op. Bijvoorbeeld een beëindigd huwelijk wordt niet opgenomen bij partners.

Ik kan me voorstellen dat een datumEinde wordt opgegeven met een datum in de toekomst, in het geval van een verblijfstitel met bepaalde tijd. Maar in dat geval is indicatie_verblijfstitelBeeindigd niet relevant (de einddatum van de verblijfstitel kan dan niet onbekend 00000000 zijn).
Ook moet er dan een feature komen (of beschrijving in de Swagger) waarin staat dat alleen de actuele verblijfstitel wordt opgenomen == met datumEinde leeg of in de toekomst.

**Comment by JohanBoer** [comment]
Datum_Einde in de toekomst is inderdaad mogelijk en blijft dus opgenomen. De indicatie_verblijfstitelBeeindigd wordt wel verwijderd uit de API. Het is correct dat alleen  actuele verblijfstitels worden meegeleverd.
