### ISSUE TITLE
Wel opnemen van de datum indicatoren wanneer de datum geen waarde heeft?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#183]
Wat kan ik verwachten voor een datum-indicator wanneer de bijbehorende datum geen waarde heeft?
Wordt deze dan opgenomen met waarde false? Of wordt deze niet opgenomen?

Bijvoorbeeld wanneer er geen opschorting is (datumOpschortingBijhouding en redenOpschortingBijhouding zitten niet in het bericht). Wordt dan indicatieOpschortingBijhouding=false? Of zit indicatieOpschortingBijhouding ook niet in het bericht?

Of bijvoorbeeld wanneer een persoon geboren is in Nederland (datumVestigingInNederland en landVanwaarIngeschreven hebben geen waarde en worden niet in het bericht opgenomen). Krijgt indicatieVestigingVanuitBuitenland dan alsnog de waarde false of wordt deze ook niet opgenomen?

Hoe zit dat dan wanneer de hele groep of categorie niet bestaat? Bijvoorbeeld wanneer een persoon nog leeft, wordt dan alsnog groep overlijden opgenomen met indicatieOverleden=false? Of wordt in dat geval de hele groep overlijden niet opgenomen?

**Comment by JohanBoer** [comment]
De indicatoren hebben vooral een rol als er wel bekend is dat iets beëindigd is, maar de datum is onbekend. Om te voorkomen dat we in de datum bv. 00000000 moeten communiceren gebruiken we daar de indicator voor. Dit wordt in de OAS3 beter gespecificeerd , want dit moet glashelder zijn voor de developer. 

Nadere toelichting,  als je weet dat iets beëindigd is , maar de datum is onbekend geeft deze indicatie uitsluitsel dat  het beëindigd is. Als de datum_einde wel bekend is wordt deze altijd meegeleverd, maar wordt ook altijd de indicator meegeleverd met waarde "true". Als er geen sprake is van een beëindiging dan wordt de indicator niet meegeleverd.

**Comment by fsamwel** [comment]
Bijv. bij indicatieOverleden staat ook de argumentatie in de beschrijving. Zou ik weglaten want kan verwarrend zijn voor gebruiker. Wellicht ook explicieter zijn "Als de waarde false is hoeft de indicator niet meegeleverd te worden." Hoeft te worden --> wordt
	Idem voor verblijfplaats.indicatieVestigingVanuitBuitenland
	Idem voor partner.indicatieHuwelijkPartnerschapBeeindigd
	
	indicatieOpschortingBijhouding: werking niet gespecificeerd
	
IndicatieReisdocumentGeldig: werking niet gespecificeerd, maar element m.i. onterecht zie #198

**Comment by fsamwel** [comment]
einddatumUitsluitingEuropeesKiesrechtOnbekend: werking niet gespecificeerd
einddatumUitsluitingKiesrechtOnbekend: werking niet gespecificeerd

**Comment by fsamwel** [comment]
werking einddatumUitsluitingEuropeesKiesrechtOnbekend en einddatumUitsluitingKiesrechtOnbekend: is nog niet gespecificeerd (zie mijn opmerking 29 april).

**Comment by CathyDingemanse** [comment]
Er is al een indicatie uitsluiting kiesrecht, dus we weten al dat iemand is uitgesloten (ookal is de datum onbekend). Deze is geintroduceerd om "bekend onbekende datum problematiek" niet naar de consumer te hoeven doorkoppen. Die weet echt niet wat hij/zij hier mee moet.
Daarmee moet de einddatumUitsluitingEuropeesKiesrechtOnbekend en einddatumUitsluitingEuropeesKiesrechtOnbekend worden verwijderd.

**Comment by JohanBoer** [comment]
Bovenstaande indicatie verwijderd uit de actuele versie van de YAML op Github.

**Comment by fsamwel** [comment]
We hebben nu nog wel het attribuut datumEuropeesKiesrechtOnbekend. Moet deze volgens redenatie van Cathy (er is al een aanduidingEuropeesKiesrecht) niet ook verwijderd worden?

**Comment by CathyDingemanse** [comment]
Er wordt alleen een indicator opgenomen bij een onbekende datum als de datum naast gewoon een datum ook een indicator is voor iets anders (overleden oid). Dan ontstaat onduidelijkheid over de betekenis van de waarde 000000, oftwel "bekend onbekend". Als we hiermee willen communiceren dat iemand wel is overleden, maar we weten niet wanneer, dan kan dat duidelijker. 
Wanneer wij afhankelijk zijn van een datum die onbekend kan zijn om iets anders dan de datum alleen te communiceren, dan:
- is een indicator in het leven geroepen om dit duidelijk te maken (bijvoobeeld of iemand is overleden) , 
- en geven we een volledig onbekende datum niet mee. Wat moet een consumer immers met al die nullen en "bekend onbekend".

In dit specifieke geval biedt LO GBA al een indicator (31.10 aanduiding Europees Kiesrecht, waarde 1 of 2), en hoeven er geen indicatoren te worden toegevoegd. Wanneer Datum(VerzoekOfMededeling)EuropeesKiesrecht,  EinddatumUitsluitingEuropeesKiesrecht, de waarde 00000000 heeft wordt het element niet geretourneerd 

Hetzelfde geldt voor kiesrecht. Ook hier biedt LO GBA al een indicator AanduidingUitgeslotenKiesrecht (38.10). Wanneer EinddatumUitsluitingKiesrecht volledig onbekend is, dan niet retourneren.
