### ISSUE TITLE
attributen in redenOpname onnodig lang

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#184]
in nationaliteit.redenOpname zitten nu de volgende attributen:

- redenOpnemen_beeindigenNationaliteit
- omschrijvingOpnemen_beeindigenNationaliteit
- soortOpnemen_beeindigenNationaliteit

in de tabellen nemen we de naam van de betreffende tabel niet elke keer over in elk attribuut.

Dus had ik verwacht:
- reden
- omschrijving
- soort

**Comment by fsamwel** [comment]
zo te zien gebeurt dit nog op meer plaatsen. Ik dacht me te herinneren dat we ooit besloten hebben al deze namen in te korten, Dus niet in een sub-element in een groep de groepsnaam meenemen. Dit is wel gedaan voor groepen als geboorte en overlijden, maar nog niet voor de tabellen.

Bijvoorbeeld:
         "land":          {
            "landcode": "6030",
            "landnaam": "Nederland"
         }
moet zijn:
         "land":          {
            "code": "6030",
            "naam": "Nederland"
         }

**Comment by JohanBoer** [comment]
Ik neem het model door en zal hier aangeven waar ik namen ingekort heb. Ik sta open voor suggesties in de komende dagen !

**Comment by fsamwel** [comment]
idem verblijfstitel.aanduiding.verblijfstitelNumeriek

**Comment by JohanBoer** [comment]
Alle tabellen doorgenomen en de namen kort en bondig gemaakt waar mogelijk zonde betekenis te verliezen in de naamgeving : Nationalitei, adelijketitel_predikaat, land, verblijfstitel, gemeentenredenVerkrijgingOpnemen en beeindigen nationaliteit, redenontbindingHuwelijk_geregistreerdPartnerschap.

**Comment by fsamwel** [comment]
Nog te doen:
	AdellijkeTitel_predikaat_tabel: 
		adellijkeTitel_predikaat=code
	NederlandsReisdocument_tabel: 
		nederlandsReisdocument=code, reisdocumentomschrijving=omschrijving
	AutoriteitAfgifteNederlandsReisdocument_tabel:
		autoriteitVanAfgifte=code, omschrijvingAutoriteit=omschrijving
