### ISSUE TITLE
geboorteplaats als code of plaatsnaam?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#186]
voor geboorte.plaats is de volgende omschrijving opgenomen:

> De naam van de Nederlandse gemeente of een buitenlandse plaats of een plaatsbepaling, die aangeeft waar de persoon is overleden De naam van de Nederlandse gemeente of een buitenlandse plaats of een plaatsbepaling, die aangeeft waar de persoon is geboren. In afwijking van GBA attribuut 03.20 wordt voor een Nederlandse plaats niet de code, maar de plaatsnaam opgenomen In afwijking van het corresponderende GBA-attribuutsoort wordt voor gemeenten niet de code vastgelegd maar de gemeentenaam. Het betreft een gemeente in het Europese deel van het Koninkrijk. Zie verder de toelichting in de GBA. Wanneer het niet een Nederandse gemeente betreft, wordt een buitenlandse plaatsnaam of een omschrijving zo nodig aangevuld met een aanduiding in lengte- en breedtegraden, indien de geboorte niet in een gemeente of buitenlandse plaats heeft plaatsgevonden (bijvoorbeeld bij een geboorte op of boven internationaal gebied). Standaardwaarde '0000' indien onbekend.

Dit is overgenomen van het RSGB en wijkt af van GBA. is dit een bewuste functionele keuze? 
Op zich begrijp ik wel dat we in de API iets moeten doen met zowel Nederlandse gemeenten als buitenlandse plaatsen, en in ieder geval delen van de plaatsnaam (zowel voor de Nederlandse gemeente als buitenlandse plaats). Is er dus geen behoefte aan het ontvangen van de gemeentecode?

Ik begrijp hierin vooral niet de keuze om altijd de omschrijving (plaatsnaam) te gebruiken, behalve wanneer het onbekend is. Dan wordt wel de code 0000 gebruikt. Waarom dan niet ook een omschrijving "Onbekend"?

**Comment by fsamwel** [comment]
De combinatie code en naam kan hier ook worden gebruikt.

Voor persoon geboren in Nederland, is dat gewoon de gemeentecode + gemeentenaam van geboorte
Voor een persoon geboren buiten Nederland is gemeentecode=1999 (RNI) en gemeentenaam de buitenlandse plaatsnaam of aanduiding
En bij onbekende geboorteplaats is gemeentecode=0000 en gemeentenaam=Onbekend

**Comment by JohanBoer** [comment]
Dit is waarschijnlijk vanuit het RSGB strat-scenario blijven hangen. We conformeren ons aan het LO GBA en nemen de combinatie code naam op.

**Comment by fsamwel** [comment]
Oke, hetzelfde geldt dan ook voor overlijden.plaats

**Comment by fsamwel** [comment]
> nemen de combinatie code naam op
wat nemen we op bij een geboorteplaats buiten Nederland? De registratie kent dan geen code, maar alleen de plaatsnaam. Wordt code dan weggelaten of krijgt het een standaardwaarde?

**Comment by JohanBoer** [comment]
Jouw voorstel lijkt mij uitstekend Frank 👍 

> Voor persoon geboren in Nederland, is dat gewoon de gemeentecode + gemeentenaam van geboorte
> Voor een persoon geboren buiten Nederland is gemeentecode=1999 (RNI) en gemeentenaam de buitenlandse plaatsnaam of aanduiding
> En bij onbekende geboorteplaats is gemeentecode=0000 en gemeentenaam=Onbekend

**Comment by fsamwel** [comment]
in de GBA-V testdata heb ik een situatie gevonden waarbij de code in 5.03.20 (geboortedatum van de partner) niet voorkomt in tabel 33 Gemeententabel. idem voor 5.06.20 (plaats aangaan partnerschap) en 5.81.10 (partner registergemeenteAkte).

Hoe moet de API hiermee omgaan?
* plaats(naam) weg laten: de API kent de code niet, dus kan geen naam meegeven
* plaats(naam) vullen met "Onbekend"
* foutmelding (500): de API kan de gegevens niet goed weergeven

**Comment by gertjanvanderkooij** [comment]
> Voor persoon geboren in Nederland, is dat gewoon de gemeentecode + gemeentenaam van geboorte
> Voor een persoon geboren buiten Nederland is gemeentecode=1999 (RNI) en gemeentenaam de buitenlandse plaatsnaam of aanduiding

Als we werken met twee elementen (code en plaatsnaam), zou ik hiervoor de vulling in de geest van LO GBA aanhouden en voor 'code' geen vulling bedenken '1999' of '0000'. Bij de vulling rekening houden met bijbehorende Land.

Indien het Land = Nederland (6030), dan kan de plaatsnaam-rubriek (xx.03.20) gevuld zijn met een gemeentecode of een locatie-aanduiding (bv. lengte-/breedtegraden). Indien gevuld met een gemeentecode, dan zowel de 'code' als de 'plaatsnaam' (bijgelezen vanuit tabel) vullen. Indien gevuld met een locatie-aanduiding, dan alleen de 'plaatsnaam' vullen. Element 'code' hier dan weglaten en niet vervangen door '0000' of iets anders.  

Indien het Land # Nederland (ongelijk 6030), dan kan de plaatsnaamrubriek (xx.03.20) gevuld zijn met een buitenlandse plaatsnaam of een locatie-aanduiding (bv. lengte-/breedtegraden). In die gevallen alleen de 'plaatsnaam' vullen. Element 'code' hier dan weglaten en niet vervangen door '0000', '1999' of iets anders.

In de casus van Frank hierboven, zou ik gaan voor optie 1.

**Comment by CathyDingemanse** [comment]
Dus: 
- als er in de registratie een code staat vullen we die en tonen de bijbehorende omschrijving
- als er alleen een omschrijving wordt geleverd, dan wordt de plaatsnaam gevuld en de code niet meegegeven (geen magic strings!).
