### ISSUE TITLE
ontbindingPartnerschap bij een actuele partner?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#187]
In de resource partners zit groep ontbindingPartnerschap. Bij een actueel partnerschap (volgens onze definitie) kan deze nooit voorkomen. We geven een (volgens GBA actuele) beëindigde partnerschap immers niet mee bij partners.

**Comment by gertjanvanderkooij** [comment]
Deze even aanhouden irt laatste review features. Naar mijn mening zouden we bij de actuele gegevens van een persoon de laatst bekende situatie van het meest recente huwelijk/partnerschap moeten meegeven. Dus als het meest recente huwelijk/partnerschap van een persoon is ontbonden/beeindigd deze info wel meegeven.
 
Eventueel eerdere huwelijken/partnerschappen die ontbonden/beeindigd zijn niet; deze via de historie-bevraging.

**Comment by JohanBoer** [comment]
We stellen voor om voor voorlopig de eerste versie ook de eerdere design decision aan te houden (dus nog geen definitieve keuze) en dus geen beëindigde partnerschappen/huwelijken mee te leveren. Ook de groep ontbinding is dan niet meer nodig. In het traject dat we met de RVIG ingaan wordt deze discussie weer gevoerd en wordt de definitieve keuze gemaakt.

**Comment by gertjanvanderkooij** [comment]
Prima om eerste versie zo te houden. Naast afstemming met RvIG kan ook het eerste gebruik (joepieeee) wellicht leiden tot een andere invulling. Eerst afhechten en implementeren maarrr ...

**Comment by fsamwel** [comment]
@JohanBoer ontbindingPartnerschap is correct verwijderd, maar indicatieHuwelijkPartnerschapBeeindigd staat er nog wel in. Haal je die er ook nog uit?

**Comment by JohanBoer** [comment]
indicatieHuwelijkPartnerschapBeeindigd  is verwijderd uit de resource Partner. Bij de eerstvolgende pull request is dat te checken.
