### ISSUE TITLE
datumAanvangFamilierechtelijkeBetrekking ontbreekt in OuderInOnderzoek

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#188]
datumAanvangFamilierechtelijkeBetrekking (GBA element 62.10) kan ook in onderzoek zijn. Dus zou die ook in OuderInOnderzoek moeten zijn opgenomen

In OuderInOnderzoek zit een element datumVan. Die vind ik echter niet in de ouder.

Moet datumVan in OuderInOnderzoek  worden omgenoemd naar datumAanvangFamilierechtelijkeBetrekking?

**Comment by JohanBoer** [comment]
> Moet datumVan in OuderInOnderzoek worden omgenoemd naar datumAanvangFamilierechtelijkeBetrekking?

Klopt. Zo ook doorgevoerd.
