### ISSUE TITLE
aanschrijfwijze en aanduidingNaamgebruik toevoegen aan inOnderzoek

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#189]
aanduidingNaamgebruik van een ingeschreven persoon kan in onderzoek zijn (016110). Dus zou deze moeten worden toegevoegd aan NaamInOnderzoek voor een ingeschreven persoon (NIET voor partner, ouder of kind).

Wanneer de naam of de aanduidingNaamgebruik in onderzoek zijn, dan moet in de API ook worden aangegeven dat aanschrijfwijze in onderzoek is. 

Wellicht ook algoritme wanneer aanduidingNaamgebruik <> E (dus de naam partner wordt gebruikt in aanschrijfwijze) én partner is in onderzoek (050000 of 050200), dan ook naam.inOnderzoek.aanschrijfwijze = true?

**Comment by JohanBoer** [comment]
AanduidingNaamGebruik kan in onderzoek zijn, dus die wordt toegevoegd. Aanschrijwijze is een "comfort" gegeven. Dat wordt samengesteld, maar kan niet inOnderzoek zijn.

**Comment by gertjanvanderkooij** [comment]
Vind ik lastig; als backlog-item even vasthouden voor versie 2.0  ... 
Wat als (één van) de samenstellende delen in onderzoek staan en afnemer hiervoor niet is geautoriseerd of deze elementen niet opvraagt via fields? In dat geval weet afnemer niet dat de Aanschrijfwijze is samengesteld uit elementen die in onderzoek staan. De serviceprovider zou dit wel kunnen doorgeven.

**Comment by JohanBoer** [comment]
AanduidingNaamgebruik bij NaamInOnderzoek toegevoegd. Dit item op de Backlog gezet voor nader uitzoekwerk.

**Comment by fsamwel** [comment]
@JohanBoer je hebt aanduidingNaamgebruik nu toegevoegd aan NaamInOnderzoek.

Hiermee is aanduidingNaamgebruik ook toegevoegd aan de naam.inOnderzoek van ouders, partners en kinderen. Dat is niet terecht, omdat daar het attribuut aanduidingNaamgebruik niet in de naam is opgenomen.

**Comment by JohanBoer** [comment]
Nu zo gerealiseerd dat alleen bij de ingeschrevenPersoon de aanduidingNaamgebruik in onderzoek kan zijn. Ben wel benieuwd of dit problemen op gaat leveren bij code-generatie. Is wel een wat complexe schema-situatie.

**Comment by CathyDingemanse** [comment]
Even terug..... naamgebruik in onderzoek? Dit kan door de persoon zelf worden aangegeven, dus kan ik mij niks voorstellen bij een onderzoek. Mocht het niet naar wens zijn, dan kan de ingeschreven persoon dit zelf, meestal digitaal, wijzigen. Ook even de experts in Den Haag geraadpleegd, zij hebben nog nooit een dergelijk onderzoeksgeval meegemaakt, of er van gehoord.
Conclusie: ook al is het technisch mogelijk om de aanduiding naamgebruik in de BRP in onderzoek te zetten, de BRP bevragen API ondersteunt het niet/ geeft het niet door.

**Comment by JohanBoer** [comment]
Conform laatste opmerking van Cathy alle hiervoor gedane wijzigingen weer teruggedraaid. Er is dus geen boolean waarmee je kunt aangeven dat aanduidingNaamGebruik in onderzoek is.
