### ISSUE TITLE
is uitsluiting kiesrecht met einddatumUitsluitingKiesrecht/einddatumUitsluitingEuropeesKiesrecht actueel?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#192]
Moet groep kiesrecht worden opgenomen wanneer:
* aanduidingEuropeesKiesrecht=1 en einddatumUitsluitingEuropeesKiesrecht ligt in het verleden
* aanduidingUitsluitingKiesrecht=A en einddatumUitsluitingKiesrecht ligt in het verleden

de einddatum-attributen zijn opgenomen, inclusief einddatum...Onbekend, wat suggereert dat dit wel moet.
maar voor het overige in de API nemen we alleen actuele gegevens op, en kan je deze situaties beschouwen als niet actueel (de persoon heeft inmiddels weer kiesrecht)

**Comment by fsamwel** [comment]
Zelfde vraag voor verblijfstitel. Hierin is datumEinde en indicatie_verblijfstitelBeeindigd opgenomen.
Naar mijn idee is een beëindigde verblijfstitel niet actueel in de zin die we in deze API hebben gebruikt.

**Comment by JohanBoer** [comment]
> Zelfde vraag voor verblijfstitel. Hierin is datumEinde en indicatie_verblijfstitelBeeindigd opgenomen.
> Naar mijn idee is een beëindigde verblijfstitel niet actueel in de zin die we in deze API hebben gebruikt.

Zie #182 

Het al dan niet vullen van de groep Kiesrecht als er bepaalde waardes in elementen zitten zal vanuit de business beantwoord moeten worden. GertJan en/of Cathy, kunnen jullie hier uitsluitsel op geven. Tot die tijd verander ik niets op basis van deze melding.

**Comment by CathyDingemanse** [comment]
Bij deze:

aanduidingEuropeesKiesrecht=1 en einddatumUitsluitingEuropeesKiesrecht ligt in het verleden
aanduidingUitsluitingKiesrecht=A en einddatumUitsluitingKiesrecht ligt in het verleden

is niet actueel, en wordt niet in de API opgenomen.

**Comment by JohanBoer** [comment]
Ik weet niet hoe ik dit moet verwerken in de API. Ik kan attributen verwijderen uit kiesrecht (is dat de bedoeling hier) of ik kan in de beschrijving van een element opnemen dat in geval van bepaalde waarden een element (of misschien wel een hele groep) niet meegeleverd wordt, Volgens mij moet dat laatste een .feature worden omdat je hier business-rules beschrijft voor het al dan niet leveren van gegevens. Dat kan niet in de OAS3-specificatie worden afgedwongen.

**Comment by fsamwel** [comment]
De elementen met (indicatoren voor) einddatums van kiesrecht hoeven denk ik niet verwijderd te worden, hoewel ik het nut van datumEuropeesKiesrechtOnbekend, einddatumUitsluitingKiesrechtOnbekend en einddatumUitsluitingEuropeesKiesrechtOnbekend hier niet begrijp. Wat betekent dat in de processen? Is een onbekende einddatum iets anders dan "voor onbepaalde tijd"? En wat is dan het verschil met het niet opnemen van een einddatum? 

Ik denk dat er een feature moet komen over actuele gegevens. Daarin moet o.a. kiesrecht komen, maar ook bijv. verblijfstitel.
