### ISSUE TITLE
aanduidingUitsluitingKiesrecht mag alleen waarde "A" hebben

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#193]
aanduidingUitsluitingKiesrecht is gedefinieerd als string, maxLength: 1, example: A

volgens LO GBA mag dit alleen de waarde "A" hebben.

Dit kan strakker gedefinieerd, bijvoorbeeld (bij voorkeur) via een enumeratie

**Comment by CathyDingemanse** [comment]
Graag een enumeratie van maken en daarbij aangeven A= uitgesloten van kiesrecht.

**Comment by JohanBoer** [comment]
Is verwerkt met een toegevoegde e-numeratie met 1 waarde. Na de eerstvolgende pul request wordt dit issue in "review" gezet
