### ISSUE TITLE
datumAanvangFamilierechtelijkeBetrekking == Datum ingang familirechtelijke betrekking

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#195]
attribuut datumAanvangFamilierechtelijkeBetrekking van een ouder zou eigenlijk moeten heten datumIngangFamilierechtelijkeBetrekking

Dan komt de naam overeen met de naam van het corresponderende attribuut 62.10 in LO GBA

**Comment by JohanBoer** [comment]
Done.
