### ISSUE TITLE
attribuut reisdocumentInOnderzoek

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#197]
in de response voor een reisdocument zit element "reisdocumentInOnderzoek". Dit moet denk ik zijn "inOnderzoek" (is op alle andere plekken zo genoemd)

**Comment by CathyDingemanse** [comment]
@JohanBoer, graag aanpassen.

**Comment by JohanBoer** [comment]
Done, in de eerstvolgen pull request is dit opgenomen. Als die op github komt wordt dit issue in "review" gezet.

**Comment by fsamwel** [comment]
@JohanBoer De component waarnaar verwezen wordt heet "InOnderzoek". Dat is denk ik verwarrend. kan deze weer ReisdocumentInOnderzoek heten?
