### ISSUE TITLE
Betekenis indicatieReisdocumentGeldig?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#198]
De betekenis van indicatieReisdocumentGeldig is niet helemaal duidelijk uit de beschrijving: "Indicator waarmee aangegeven wordt of het reisdocument geldig is."

Hoe leidt de API dit attribuut af? Alleen op basis van datumEindeGeldigheid? Of ook op basis van aanduidingInhouding_vermissing?
Kan dus een ingehouden of vermist reisdocument nog "geldig" zijn?

**Comment by CathyDingemanse** [comment]
@JohanBoer, graag verwijderen zie # 160

**Comment by JohanBoer** [comment]
Is verwijderd. Als ik de nieuwe versie van de OAS3 merge dan zet ik deze in "review"
