### ISSUE TITLE
zoeken op naamOpenbareRuimte of straatnaam?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#199]
ingeschrevenpersonen kunnen worden gezocht met de parameter verblijfplaats__naamopenbareruimte.
Deze keuze is gemaakt toen we nog geen element straatnaam in de verblijfplaats hadden opgenomen.

In de testdata van GBA-V zie ik situaties dat er bij een persoon op de verblijfplaats wel een straatnaam is, maar geen naam openbare ruimte. Andersom heb ik niet gevonden.
Is het dan niet beter om te zoeken op straatnaam? Dus een zoekparameter verblijfplaats__straatnaam.

**Comment by fsamwel** [comment]
> Gaat het om een zgn. GBA adres (ipv een BAG adres)?
Maken we hier onderscheid tussen bij het zoeken van personen? We zoeken op de verblijfplaats van de persoon. Dat kan een BAG adres zijn, maar ook een niet-BAG adres. Voor beide soorten adressen zou je de persoon moeten kunnen zoeken op het adres (straat, plaats, huisnummer).

**Comment by CathyDingemanse** [comment]
Hoewel niet verplicht, zou ieder adres waarop een persoon wordt ingeschreven een BAG adres moeten zijn.
Niet BAG adressen (GBA adressen) kunnen worden gevonden met de zoekparameters postcode en huisnummer. Het gebruik van deze adressen nog verder faciliteren door er speciale zoekparameters (Verblijfplaats_straatnaam etc.) voor te definieren gaat mij wat ver. Dit doen we uiteraard wel voor BAG adressen (verblijfplaats_openbareruimtenaam etc.).

Voorbehoud: mochten we in de BAG-bevragen API een resource "adres" definieren oid, dan kunnen we deze beslissing wellicht heroverwegen.
