### ISSUE TITLE
gemeentecode met voorloopnullen?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#202]
In de beschrijving van code in Gemeente_tabel staat:

> De code, behorende bij de gemeentenaam opgenomen in de Gemeentetabel van de GBA. 0000 en verder alleen natuurlijke getallen **zonder voorloopnullen**

Dit is vreemd want in de gemeentetabel staan de codes juist met voorloopnul. 
Ook is code gedefinieerd als string, niet als integer 
(maar in Lo GBA is bijvoorbeeld element 9.10 Gemeente van inschrijving wel is gedefinieerd als Numeriek).
GBA-V levert de gemeentecode inclusief voorloopnul:
                <ns2:categorievoorkomens>
                  <ns2:item>
                    <ns2:categorienummer>8</ns2:categorienummer>
                    <ns2:elementen>
                      <ns2:item>
                        <ns2:nummer>910</ns2:nummer>
                        <ns2:waarde>0363</ns2:waarde>
                      </ns2:item>

Ik denk dat het voor een gebruiker duidelijk moet zijn wat deze kan verwachten, een integer (dus getal zonder voorloopnullen) of een string (inclusief of exclusief voorloopnullen?).

N.B. @CathyDingemanse en @JohanBoer de definitie hier is denk ik nog een RSGB omschrijving. Moet er nog een "opschoning" komen waarbij alle definities uit GBA worden gehaald i.p.v. uit RSGB?

**Comment by JohanBoer** [comment]
Ik heb de zin "0000 en verder alleen natuurlijke getallen zonder voorloopnullen" verwijderd. Mijns inziens conformeren we ons aan de implementatie van de GBA-V  (@CathyDingemanse is dat ok ?)

> N.B. @CathyDingemanse en @JohanBoer de definitie hier is denk ik nog een RSGB omschrijving. 
> Moet er nog een "opschoning" komen waarbij alle definities uit GBA worden gehaald i.p.v. uit RSGB?

Ja, zoals bij #204 aangegeven is er geen capaciteit beschikbaar om het gewenste informatiemodel te maken dat 100% gebaseerd is op het LO GBA. Dat betekent dat we qua omschrijvingen nog met een RSGB-erfenis zitten.
