### ISSUE TITLE
verblijfplaats.landVanwaarIngeschreven <> verblijfplaats.inOnderzoek.landVanWaarIngeschreven

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#203]
er zit een hoofdletterverschil tussen element landVanwaarIngeschreven en het corresponderende inOnderzoek attribuut landVanWaarIngeschreven.

Om implementatiefouten te voorkomen moeten de attribuutnamen in inOnderzoek zo mogelijk volledig identiek worden gehouden.

In dit geval is landVanwaarIngeschreven  de correcte schrijfwijze, aangezien het is afgeleid uit element 14.10 Land vanwaar ingeschreven (vanwaar is één woord)

**Comment by JohanBoer** [comment]
Ik heb in het BSM de hoofletter W vervangen door een w . In de eerstvolgende versie is de attribuutnaam aangepast.
