### ISSUE TITLE
omschrijving voorvoegsel dubbel

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#204]
De omschrijving bij element voorvoegsel (in Naam) is:

> Dat deel van de geslachtsnaam dat voorkomt in de Voorvoegseltabel en, gescheiden door een spatie, vooraf gaat aan de rest van de geslachtsnaam. Element 02.30 Dat deel van de geslachtsnaam dat voorkomt in Tabel 36, Voorvoegseltabel en, gescheiden door een spatie, vooraf gaat aan de rest van de geslachtsnaam.

Vrijwel dezelfde omschrijving zit er dus twee keer in. Eén keer is denk ik genoeg, waarbij de tweede zin m.i. de betere is (is letterlijk overgenomen uit LO GBA)

**Comment by JohanBoer** [comment]
Om deze dubbeling te elimineren zijn er  3 opties. 

- Het informatiemodel en uitwisselingsmodel voor LO-GBA correct opstellen
- Het laatste deel van de tekst verwijderen (en dus geen exacte kopie van de tekst uit het LO GBA) 
- Het elimineren van de huidige traceerbaarheid naar het RSGB- informatiemodel. 

Ik opteer voor de 2e optie.

De 1e optie is de meest ideale, maar daarvoor zijn geen resources beschikbaar bij VNG-realisatie. De derde optie doet afbreuk aan de opzet van het modeldriven design. Asl optie 1 wel gerealiseerd is kan dit backward compatibel aangepast worden.

**Comment by JohanBoer** [comment]
Ik heb in het BSM de de 2e optie doorgevoerd.In de eerstvolgende versie is de description aangepast.

**Comment by JohanBoer** [comment]
Overleg met Robert over het niveau waarop de documentatie overerfd wordd. M.b.v. de betreffende TV kan geforceerd worden dat de SIM documnetatie niet wordt mee-gegenereerd.
