### ISSUE TITLE
Tegenstrijdige beschrijving van query parameter verblijfplaats__gemeentevaninschrijving

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#205]
> - in: query
          name: verblijfplaats__gemeentevaninschrijving
          description: "Een code die aangeeft in welke gemeente de PL zich bevindt of de gemeente waarnaar de PL is uitgeschreven of de gemeente waar de PL voor de eerste keer is opgenomen. De standaardwaarde (0000) is geen geldige inhoud voor de query-parameter. standaardwaarde is 0000 indien onbekend"

Hierin staat dat 0000 betekent onbekend én dat gebruik van de waarde 0000 geen geldige waarde is.
Eén van de twee (ik denk "standaardwaarde is 0000 indien onbekend") moet worden weggehaald.

**Comment by JohanBoer** [comment]
Ik heb in het BSM de zin "standaardwaarde is 0000 indien onbekend" nu verwijderd. In de eerstvolgende versie is de description aangepast.
