### ISSUE TITLE
Functionele specificatie (feature) voor actuele gegevens

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#206]
De API levert alleen actuele gegevens. Per soort gegeven kan de definitie daarvan verschillen. Bijvoorbeeld volgens #147 (bijlage daarin) moet indicatie onjuist voor een verblijfplaats worden opgenomen (en dus wordt een onjuiste verblijfplaats opgenomen). Ook wijken we af van de definitie van onjuist van LO GBA (waarin een beëindigd huwelijk nog actueel is).
Afhandeling bijvoorbeeld bij einddatum volledig onbekend is niet duidelijk.

Voor partners, ouders en kinderen is er een feature waarin dit beschreven is, nog niet voor reisdocumenten, verblijfstitels, kiesrecht, nationaliteit, enz.

**Comment by fsamwel** [comment]
zie ook #192

**Comment by JohanBoer** [comment]
Dit kan worden opgelost door een heel korte feature "actuele_gegevens" op te nemen waarin wordt beschreven dat voor alle entiteiten geldt dat alleen die voorkomens meegeleverd worden waar geen einddatum in het verleden is ingevuld.

**Comment by fsamwel** [comment]
Naar mijn idee zou je iets verder moeten gaan dan verwijzen naar een einddatum.

Algemeen kan je zeggen:
- dat geen gegevens uit historische categorieën worden opgenomen
- geen gegevens uit categorieën waarbij groep 84 onjuist is gevuld

Ik heb de volgende groepen/elementen voor beëindigen van categorieën gevonden:

- 04 Nationaliteit: 64.10 Reden beëindiging nationaliteit
- 05 Huwelijk/partnerschap: 07 ontbinding
- 10 Verblijfstitel: 39.20 datum einde verblijfstitel
- 12 Reisdocument: 35.50 datum einde geldigheid Nederlands reisdocument, 35.60 datum inhouding of vermissing Nederlands reisdocument / 35.70 aanduiding inhouding of vermissing Nederlands reisdocument
- 13 Kiesrecht: 31.30 Einddatum uitsluiting Europees kiesrecht, 38.20 Einddatum uitsluiting kiesrecht

Ook zou m.i. in de feature de situatie uit issue #214 moeten worden beschreven. Kan betrekking hebben op ouders, kinderen, partners, nationaliteit, overlijden, verblijfstitel, gezagsverhouding

Ik zou ook willen voorstellen de feature voor actueel en feature partners_ouders_kinderen.feature te integreren tot één feature.

**Comment by gertjanvanderkooij** [comment]
>     * 05 Huwelijk/partnerschap: 07 ontbinding

Bij partners hadden we nog een openstaand punt:
Als van het laatste huwelijk de ontbindingsgegevens zijn gevuld, dan is de actuele situatie van het huwelijk dat deze is ontbonden. Dit lijkt me relevant voor afnemers om te weten of een persoon nooit of ooit gehuwd is geweest. 

Hier hebben we naar mijn weten nog geen belsuit over genomen. @CathyDingemanse Lijkt me vooral voor Welzijn en welicht andere domeinen relevante informatie. Kunnen we dit nog achterhalen om algoritme zo scherp mogelijk te hebben?

**Comment by JohnRooijakkers** [comment]
@gertjanvanderkooij : Als de actuele burgerlijke staat als (afgeleid) gegeven wordt opgenomen (met daarin het onderscheid of iemand nooit gehuwd, gescheiden, weduwnaar etc is) dan is die informatie beschikbaar. Vraag is dan nog of deze actuele burgerlijke staat ook een ingangsdatum heeft. Bijvoorbeeld dat iemand is gescheiden per datum x (= datum huwelijksontbinding).

**Comment by CathyDingemanse** [comment]
@gertjanvanderkooij 
Als informatie over een ontbonden huwelijk gewenst is, dan kan kan de historie endpoint worden gebruikt. Zie https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/tree/master/api-specificatie/Bevraging-Historie  
Voor de aanschrijfwijze hoeft dit uiteraard niet meer, omdat deze standaard wordt meegegeven.
@JohnRooijakkers heb je voor mij een concrete businessvraag van gemeenten waarvoor het gegeven burgerlijke staat nodig is?

**Comment by JanWillemKooi** [comment]
nav overleg 23 aug
Johan gaat een feature hiervoor maken. (eventueel met hulp van Gert Jan)

**Comment by JohanBoer** [comment]
> @JohnRooijakkers heb je voor mij een concrete businessvraag van gemeenten waarvoor het gegeven burgerlijke staat nodig is?

Hans van Dijk geeft in #528 ook aan behoefte te hebben aan een element burgelijke staat.

**Comment by JohanBoer** [comment]
Feature voor actuele gegevens is in #531 aangeboden. 

Al dan niet opnemen van  de burgerlijke staat is in #528 geborgd qua afhandeling.
