### ISSUE TITLE
Hoe werkt inOnderzoek in relatie tot de fields parameter?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#207]
In de specificaties wordt nu niks gezegd over inOnderzoek in relatie tot de fields parameter. Wel is er een voorbeeld waarin inOnderzoek in de fields parameter is opgenomen.
Wordt inOnderzoek (en alle voorkomens daarvan binnen groepen) beschouwd als een "normaal" element?

Bijvoorbeeld: ik vraag een persoon op met fields=geboorte.datum, en de geboortedatum is in onderzoek (83.10=010310). Moet dan alleen de geboortedatum worden teruggegeven of ook (ongevraagd) geboorte.inOnderzoek.datum?

Andersom: wanneer ik een vraag doe met fields=geboorte.datum,geboorte.inOnderzoek en de hele persoon is in onderzoek (83.10=010000). Moet ik dan ook geboorte.inOnderzoek.plaats terugkrijgen?

In GBA-V is groep 83.10 (in onderzoek) niet expliciet te bevragen met de filter. Deze krijg je daar automatisch mee wanneer deze bestaat én de waarde betrekking heeft op een gevraagd gegeven.

**Comment by gertjanvanderkooij** [comment]
Hier regels zoals in GBA-V volgen, zoals je hebt aangegeven. Dit geheel door de serviceprovider af te handelen. 

Alhoewel niet in LO GBA voorgeschreven zou iets dergelijks m.i. ook moeten gelden voor '**indicatie geheim**'. Indien 'indicatie geheim' gevuld dan altijd meegeven, ook al wordt hier in de 'fields' (scope) niet om gevraagd.

**Comment by CathyDingemanse** [comment]
Mee eens voor zowel "in onderzoek" als "indicatie geheim". "In onderzoek" moet altijd worden teruggegeven voor de gegevens die worden opgevraagd.

**Comment by fsamwel** [comment]
indicatieGeheim (70.10) is denk ik altijd gevuld, meestal met waarde 0. Er moet dus een regel komen dat indicatiegeheim altijd wordt teruggegeven -ongeacht wat er in fields parameter staat- wanneer de waarde ongelijk is aan 0?

**Comment by fsamwel** [comment]
GBA-V gaat op dezelfde manier om met opschorting bijhouding.

Dus wanneer niet gevraagd is om 07.67.10 (datumOpschortingBijhouding) of 07.67.20 (redenOpschortingBijhouding) worden deze gegevens toch meegeleverd wanneer ze een waarde hebben. 

Geldt dan ook hetzelfde voor deze elementen? Dus meeleveren wanneer ze een waarde hebben, ook wanneer er in fields niet om gevraagd is.

GBA-V levert ook groepen 71 (verificatie) en 88 (RNI deelnemer) mee. Beide zijn nu niet opgenomen in de resource. Klopt het dat deze gegevens voor de gebruikers van de API niet belangrijk zijn? (terwijl ze volgens LO GBA wel zo belangrijk zijn dat ze altijd meegeleverd worden)

**Comment by gertjanvanderkooij** [comment]
Vwb groep Opschorting: 
Ja; ook hier gaat een signalerende werking vanuit bij bevragen. Dit om fouten in proces te voorkomen.

Vwb groep 71:
Lijkt mij niet; navraag bij domeindeskundige.

Vwb groep 88:
Alleen indien vanuit het afnemer-proces behoefte is aan verificatie bij de partij (RNI-deelnemer) die de gegevens heeft aangeleverd. Lijkt mij van niet; ook hier navraag bij domeindeskundige.

**Comment by CathyDingemanse** [comment]
Eens met Gert Jan, reden opschorting bijhouding is belangrijk om de opschorting goed te kunnen interpreteren, dus verplicht meeleveren. 
Kun jij de overige twee vragen neerleggen bij, bespreken met Vrien? Als daar geen belangrijk argument  uit komt laten we het zo, en komt het op de lijst "te bespreken met RvIG".
