### ISSUE TITLE
Reisdocument zoeken in GBA-V op reisdocumentnummer kan niet

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#209]
Voorlopig, zolang we nog GBA-V nodig hebben voor buitengemeentelijke personen, kan endpoint /reisdocumenten/{reisdocumentnummer} niet worden gerealiseerd. GBA-V vereist immers minimaal burgerservicenummer, geboortedatum, geslachtsnaam of postcode.

Het endpoint omzetten naar /ingeschrevenpersonen/{burgerservicenummer/reisdocumenten/{reisdocumentnummer} zou implementatie wel mogelijk maken. De reisdocumenten worden dan gezien als sub-resource van de ingeschrevenpersonen.

Voldoet dit dan nog aan de functionele wens? M.a.w. moet een reisdocument kunnen worden geraadpleegd op reisdocumentnummer zonder burgerservicenummer? (waarmee het reisdocumentnummer ook een indirecte methode is om de persoonsgegevens op te halen)

**Comment by JohanBoer** [comment]
In overleg met PO besloten om de het endpoint /ingeschrevenpersonen/{burgerservicenummer/reisdocumenten toe te voegen en daarbij ook de query-parameter voor het type reisdocument toe te voegen. 
Dat betekent dat je op basis van het burgerservicenummer een reisdocumenten akn ophalen en ook direct op basis van het reisdocument het reisdocument kan ophalen.

**Comment by JohanBoer** [comment]
Deze wijziging is doorgevoerd. Na de eerstvolgende pull-request kan dit issue naar  "review"worden verplaats.

**Comment by JohanBoer** [comment]
Frank heeft aangegeven dat deze wijziging het probleem van het issue niet oplost, Het GBA-V vereist een burgerservicenummer (of geboortedatum, geslachtsnaam of postcode) bij opvraging van een reisdocument. Met de toegevoegde endpoint kan niet meer een uniek reisdocument opgehaald worden. 

> Het endpoint omzetten naar /ingeschrevenpersonen/{burgerservicenummer/reisdocumenten/{reisdocumentnummer} zou implementatie wel mogelijk maken. De reisdocumenten worden dan gezien als sub-resource van de ingeschrevenpersonen.

Dit lost het probleem wel op. 

Vraag is of er dan nog behoefte is aan /reisdocumenten/{reisdocumentnummer}.

Cathy, Gert Jan,  Kunnen jullie hier op reageren ?

**Comment by JohanBoer** [comment]
Of we bovenstaande oplossing doorvoeren heeft te maken met autorisering. Als gemeenten geen reisdocumenten van buiitengemeentelijke personen op mogen vragen bij de GBA-V dan heeft de bovenstaande oplossing geen zin.

**Comment by fsamwel** [comment]
De gemeente (i.c. gemeente Den Haag) heeft in haar autorisatieprofiel helemaal geen autorisatie voor reisdocumenten. Deze aanpassing heeft dus geen zin. 

Het is ook de vraag of de toevoeging van endpoint /ingeschrevenpersonen/{burgerservicenummer}/reisdocumenten die n.a.v. die issue is gedaan wel zin heeft. De gebruiker kan namelijk al via /ingeschrevenpersonen in _links.reisdocumenten de links naar de reisdocumenten krijgen. Aangezien er zelden meer dan één of twee actuele reisdocumenten zijn is het ook niet zo erg de links te volgen om details over de reisdocumenten te krijgen.

@CathyDingemanse moet Johan dit endpoint weer verwijderen?

**Comment by CathyDingemanse** [comment]
> De gemeente (i.c. gemeente Den Haag) heeft in haar autorisatieprofiel helemaal geen autorisatie voor reisdocumenten. Deze aanpassing heeft dus geen zin.

Daar was ik al bang voor, zal voor alle andere gemeenten ook gelden. Laat onverlet binnengemeentelijke afnemers wel info over reisdocumenten nodig hebben van binnengemeentelijke inwoners. 
Mijn voorstel is om terug te gaan naar de oorspronkelijke situatie:  
/reisdocumenten/{reisdocumentnummer} 
en dit voorlopig alleen voor binnengemeentelijke personen te ondersteunen.

/ingeschrevenpersonen/{burgerservicenummer}/reisdocumenten
kan komen te vervallen. De reisdocumenten kunnen ook worden ontdekt via de links in /ingeschrevenpersonen.

**Comment by fsamwel** [comment]
@CathyDingemanse hoe moet de API nu werken voor personen uit GBA-V? Moet hierbij de link naar reisdocumenten worden opgenomen (volgen van die links

**Comment by JohanBoer** [comment]
Doorgevoerd conform het laatst commentaar van Cathy. In de eerstvolgende pull request (met Yaml van historie) is dit opgenomen.
