### ISSUE TITLE
Als gemeente wil kunnen aangeven of ik buitengemeentelijk of binnengemeentelijk ingeschreven natuurlijke personen wil zoeken  

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#21]
...zodat ik gerichter kan zoeken, en de kans minder groot is dat mijn zoekvraag niet wordt ondersteund.

**Acceptatiecriteria**
- Deze mogelijkheid wordt geboden bij zoeken op persoonskenmerken.

**Definition of done**
- [ ] functionele specificatie
- [x] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
Is het niet zo dat dit een kwestie van applicatie-inrichting is ? Ik neem aan dat er een API komt die binnengemeentelijk zoekt en een andere API die buitengemeentelijk zoekt. Deze API's kunnen qua werking wel 100% hetzelfde zijn, maar hebben verschillende endpoints (want verschillende bronnen).  Afhankelijk van de keuze zal dan dus een andere API aangeroepen worden. 

Volgens mij lossen we dit niet in de API-specificatie op.

**Comment by CathyDingemanse** [comment]
Nu nog wel (lokale BRP met gemeentelijke ingezetenen), maar straks hopelijk niet meer.... Willen we de specificatie afhankelijk maken van de huidige implementatie? Of willen we de API specificatie opstellen voor de gewenste situatie? Als de API straks binnengemeentelijk wordt gebruikt heb ik liever geen breaking changes wanneer van bron wordt gewisseld.

**Comment by JohanBoer** [comment]
Ik denk dat we elkaar niet goed begrijpen, want als ik jouw toelichting lees, dan begrijp ik daaruit dat op applicatie-niveau de keuze gemaakt wordt om binnengemeentelijk of buitengemeentelijk te zoeken. Voor nu zouden dat nog 2 verschillende endpoints zijn, maar technisch wel exact dezelfde API's. Dat betekent dat als er (op termijn) 1 landelijke bron komt dat dat geen breaking change op de API oplevert, maar alleen dat zowel binnengemeentelijke als buitengemeentelijke personen op dezelfde endpoint te vinden zijn.  Ik denk dat ik dan vooral de gewenste situatie voor oog heb, maar volgens mij is die in de huidige implementatie ook toe te passen. Vrijdag graag bespreken om te checken of we elkaar goed begrijpen...

**Comment by CathyDingemanse** [comment]
Probleemschets ter bespreking op 12 oktober:

Bij veel zoekopdrachten van gemeenten wordt op dit moment impliciet wordt gezocht met de parameter "gemeente van inschrijving". Gemeenten zoeken immers in twee registraties: de lokale kopie van eigen ingezetenen, en de GBA-V als men op zoek is naar personen met een verblijfplaats buiten de gemeente.
Bij het opstellen van de specs voor de RSGB bevragingen 1 standaard is niet het uitgangspunt geweest dat alle vragen gesteld worden aan 1 landelijke registratie. Dit is echter wel van invloed op:
- relevantie van het zoekresultaat voor de consumer
- belasting van de provider

De zoekvragen zoals gespecificeerd in RSGB bevragingen waarvoor het niet veel uitmaakt of in 1 of 2 registraties wordt gezocht zijn bijvoorbeeld:
- raadpleeg op bsn
- zoeken op postcode en huisnummer
- zoeken op nummeraanduidingidentificatie

Zoekvragen waarvoor het waarschijnlijk wel uitmaakt zijn:
- zoeken op geslachtsnaam in combinatie met geboortedatum of voornamen of geboorteplaats, (evt. aangevuld met voorvoegsel geslachtsnaam en geslacht).

De zoekvraag waarvoor het absoluut uitmaakt:
- zoek op geslachtsnaam (minimaal 2 karakters en wildcards toegestaan)

Oplossing 1: Zoeken op geslachtsnaam alleen ondersteunen icm gemeente van inschrijving. In documentatie adviseren de gemeente van inschrijving (standaard) mee te geven bij binnengemeentelijk zoeken.   

Oplossing 2:
een boolean waarmee de afnemer expliciet aangeeft binnen- of buitengemeentelijk te willen zoeken, en zoeken op geslachtsnaam alleen ondersteunen wanneer men binnengemeentelijke zoekt.  
In feite is deze boolean hetzelfde als het opnemen van de extra zoekparameter "gemeente van inschrijving" voor alle zoekvragen.

Overwegingen:

1. het opgeven van de boolean heeft geen toegevoegde waarde bij de zoekpaden en kan zelfs contraproductief zijn. 
      - raadpleeg op bsn
      - zoeken op postcode en huisnummer
      - zoeken op nummeraanduidingidentificatie

2.  De boolean binnengemeentelijk kan alleen verplicht worden gesteld icm zoeken op geslachtsnaam, waarmee hetzelfde resultaat wordt bereikt als met optie 1.

3.  Wat is het meest eenduidig en eenvoudig voor de gebruiker, verplichte zoekparametercombies of combies met boolean?

Andere overwegingen?

**Comment by fsamwel** [comment]
ik zou zo dicht mogelijk bij de resource blijven, dus heeft het mijn voorkeur zoveel mogelijk query parameters te gebruiken die ook attributen zijn in de resource. Dan is de werking van de API direct en intuïtief duidelijk.

**Comment by JohanBoer** [comment]
Ik heb nu oplossing 1 (de gemeentevaninschrijving opgenomen als parameter) in de Openapi specificatie opgenomen. De beschrijving welke combinaties van parameters toegestaan zijn moet nog opgenomen worden. De provider zal hier op moeten controleren.

**Comment by fsamwel** [comment]
> Zoeken op geslachtsnaam alleen ondersteunen icm gemeente van inschrijving.

@CathyDingemanse bedoel je dit letterlijk zo? Dus dat bij zoeken op geslachtsnaam  de parameter gemeentevaninschrijving verplicht is? (is nu nog niet in de beschrijvingen van de api opgenomen)

Is zoeken met gemeentevaninschrijving=0000 toegestaan? 
Hoe interpreteren we de waarde 0000 bij gemeentevaninschrijving? Zoeken we dan een persoon waarvan de gemeentevaninschrijving onbekend is in de registratie (kan dat?) of zoeken we dan een persoon waarvan gemeentevaninschrijving onbekend is voor de client? Dus in willekeurige gemeente (dus zoeken met 0000 is equivalent aan zoeken zonder deze parameter)? 

@JohanBoer beschrijving "standaardwaarde is 0000 indien onbekend" bij gemeentevaninschrijving is m.i. niet duidelijk genoeg voor een client.

**Comment by CathyDingemanse** [comment]
> > Zoeken op geslachtsnaam alleen ondersteunen icm gemeente van inschrijving.
> 
> @CathyDingemanse bedoel je dit letterlijk zo? Dus dat bij zoeken op geslachtsnaam de parameter gemeentevaninschrijving verplicht is? (is nu nog niet in de beschrijvingen van de api opgenomen)
> Ja dat bedoel ik letterlijk zo

> Is zoeken met gemeentevaninschrijving=0000 toegestaan?
Nee, dat is niet toegestaan, indien 0000 geen geldige gemeente van inschrijving is.

> Hoe interpreteren we de waarde 0000 bij gemeentevaninschrijving? Zoeken we dan een persoon waarvan de gemeentevaninschrijving onbekend is in de registratie (kan dat?) 
of zoeken we dan een persoon waarvan gemeentevaninschrijving onbekend is voor de client? Dus in willekeurige gemeente (dus zoeken met 0000 is equivalent aan zoeken zonder deze parameter)?
> Dat zou niet moeten kunnen.

> @JohanBoer beschrijving "standaardwaarde is 0000 indien onbekend" bij gemeentevaninschrijving is m.i. niet duidelijk genoeg voor een client.

**Comment by fsamwel** [comment]
> @CathyDingemanse bedoel je dit letterlijk zo? Dus dat bij zoeken op geslachtsnaam de parameter gemeentevaninschrijving verplicht is? (is nu nog niet in de beschrijvingen van de api opgenomen)
Ja dat bedoel ik letterlijk zo

Dus:
```
  Scenario: Bij zoeken op geslachtsnaam zijn geslachtsnaam en gemeentevaninschrijving verplicht en zijn de overige parameters optioneel
    ALS ingeschreven personen gezocht worden met ?geslachtsnaam=groen&gemeentevaninschrijving=0014
    DAN levert dit zoekresultaten
    # verplicht attribuut gemeentevaninschrijving ontbreekt
    ALS ingeschreven personen gezocht worden met ?geslachtsnaam=groen
    DAN levert dit een foutmelding
    # verplicht attribuut geslachtsnaam ontbreekt
    ALS ingeschreven personen gezocht worden met ?gemeentevaninschrijving=0014&geboortedatum=1975-01-01&voornamen=Frank&voorvoegselGeslachtsnaam=van&geslachtsaanduiding=M&geboorteplaats=Sas%20van%20Gent
    DAN levert dit een foutmelding
    # verplicht attribuut geslachtsnaam is leeg/heeft geen waarde
    ALS ingeschreven personen gezocht worden met ?geslachtsnaam=&gemeentevaninschrijving=0014&geboortedatum=1975-01-01&voornamen=Frank&voorvoegselGeslachtsnaam=van&geslachtsaanduiding=M&geboorteplaats=Sas%20van%20Gent
    DAN levert dit een foutmelding
    # verplicht attribuut gemeentevaninschrijving ontbreekt
    ALS ingeschreven personen gezocht worden met ?geslachtsnaam=groen&geboortedatum=1975-01-01&voornamen=Frank&voorvoegselGeslachtsnaam=van&geslachtsaanduiding=M&geboorteplaats=Sas%20van%20Gent
    DAN levert dit een foutmelding
    # verplicht attribuut gemeentevaninschrijving is leeg/heeft geen waarde
    ALS ingeschreven personen gezocht worden met ?geslachtsnaam=groen&gemeentevaninschrijving=&geboortedatum=1975-01-01&voornamen=Frank&voorvoegselGeslachtsnaam=van&geslachtsaanduiding=M&geboorteplaats=Sas%20van%20Gent
    DAN levert dit een foutmelding
```

**Comment by fsamwel** [comment]
ah, dus je bedoeld dat wanneer je zoekt met alleen geslachtsnaam, zonder geboortedatum, dan is gemeentevaninschrijving verplicht. en wanneer gezocht wordt op geslachtsnaam in combinatie mét geboortedatum, is gemeentevaninschrijving niet verplicht.

mag ik dit ook zo interpreteren dat bij combinatie geslachtsnaam met voornamen en tussenvoegsel ook gemeentevaninschrijving verplicht is?

Dus dit:
  Scenario: Bij zoeken op geslachtsnaam zijn geslachtsnaam en gemeentevaninschrijving of geboortedatum verplicht en zijn de overige parameters optioneel
    ALS ingeschreven personen gezocht worden met ?geslachtsnaam=groen&gemeentevaninschrijving=0014
    DAN levert dit zoekresultaten
    ALS ingeschreven personen gezocht worden met ?geslachtsnaam=groen&geboortedatum=1975-01-01
    DAN levert dit zoekresultaten
    # verplichte attributen gemeentevaninschrijving én geboortedatum ontbreken
    ALS ingeschreven personen gezocht worden met ?geslachtsnaam=groen
    DAN levert dit een foutmelding
    # verplicht attribuut geslachtsnaam ontbreekt
    ALS ingeschreven personen gezocht worden met ?gemeentevaninschrijving=0014&geboortedatum=1975-01-01&voornamen=Frank&voorvoegselGeslachtsnaam=van&geslachtsaanduiding=M&geboorteplaats=Sas%20van%20Gent
    DAN levert dit een foutmelding
    # verplicht attribuut geslachtsnaam is leeg/heeft geen waarde
    ALS ingeschreven personen gezocht worden met ?geslachtsnaam=&gemeentevaninschrijving=0014&geboortedatum=1975-01-01&voornamen=Frank&voorvoegselGeslachtsnaam=van&geslachtsaanduiding=M&geboorteplaats=Sas%20van%20Gent
    DAN levert dit een foutmelding
    # verplicht attribuut gemeentevaninschrijving ontbreekt
    ALS ingeschreven personen gezocht worden met ?geslachtsnaam=groen&geboortedatum=1975-01-01&voornamen=Frank&voorvoegselGeslachtsnaam=van&geslachtsaanduiding=M&geboorteplaats=Sas%20van%20Gent
    DAN levert dit een foutmelding
    # verplicht attribuut gemeentevaninschrijving is leeg/heeft geen waarde en geboortedatum ontbreekt
    ALS ingeschreven personen gezocht worden met ?geslachtsnaam=groen&gemeentevaninschrijving=&voornamen=Frank&voorvoegselGeslachtsnaam=van&geslachtsaanduiding=M&geboorteplaats=Sas%20van%20Gent
    DAN levert dit een foutmelding
    # verplicht attribuut geboortedatum is leeg/heeft geen waarde en gemeentevaninschrijving ontbreekt
    ALS ingeschreven personen gezocht worden met ?geslachtsnaam=groen&geboortedatum=&voornamen=Frank&voorvoegselGeslachtsnaam=van&geslachtsaanduiding=M&geboorteplaats=Sas%20van%20Gent
    DAN levert dit een foutmelding

**Comment by CathyDingemanse** [comment]
Super!

**Comment by JohanBoer** [comment]
Bij GemeenteVan Inschrijving is inmiddels in de beschrijving van de query-parameter opgenomen dat deze geen 0000 mag bevatten en in de uitleg over de combinaties van query-parameters is benadrukt dat binnen een combinatie van parameters alle genoemde parameters van die combinatie verplicht zijn.

**Comment by fsamwel** [comment]
Combinatie zoeken op geslachtsnaam + gemeentevaninschrijving zit nog niet in feature parametercombinaties

**Comment by fsamwel** [comment]
feature toegevoegd, dus issue kan gesloten worden
