### ISSUE TITLE
Wat is het nut van indicatieOpschortingBijhouding?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#210]
Er is een indicator indicatieOpschortingBijhouding toegevoegd, om af te vangen wanneer datumOpschortingBijhouding geheel onbekend is.

Alleen in dit geval is er ook een redenOpschortingBijhouding die alleen opgenomen wordt wanneer de bijhouding is opgeschort. Dit is dus in feite ook een indicatie opschorting bijhouding, alleen dan verrijkt met de reden daarvoor.

Ik begrijp daarom de toegevoegde waarde van indicatieOpschortingBijhouding niet.

**Comment by gertjanvanderkooij** [comment]
Deze indicatie is in dit geval inderdaad overbodig ... 
Goed bezig Frank! Stap voor stap, steen voor steen ... de final specs daar gaan we heen!

**Comment by JohanBoer** [comment]
Wordt verwerkt conform voorstel.

**Comment by JohanBoer** [comment]
Dit is verwerkt. Na de eerstvolgende pulle request kan dit issue naar "review". 
Ik heb ook bij de documentatie van redenOpschortingBijhouding het volgende toegevoegd: 
*Indien er wel een redenOpschortingBijhouding is maar er wordt geen datumOpschortingBijhouding geleverd, dan is dat datumOpschortingBijhouding onbekend. *
