### ISSUE TITLE
indicatieCurateleRegister onjuist gedefinieerd

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#211]
De definitie van indicatieCurateleRegister is niet juist:
      indicatieCurateleRegister:
          type: "integer"
          title: "indicatieCurateleRegister"
          description: "Element 33.10 Een aanduiding dat de ingeschrevene onder curatele\
            \ is gesteld."
          maximum: 9
          example: "1"

De enige toegestane waarde is 1.

Dus maximum 9 is niet correct, moet maximum 1 zijn. Daarnaast is er ook een minimum 1. 

Naar mijn idee is een enumeratie beter, omdat daarin alleen de toegestane waarde is opgenomen, plus voor de developer direct zichtbaar is wat die waarde 1 betekent (er is een curator aangesteld)

**Comment by JohanBoer** [comment]
Aangezien het hier een indicatie betreft hebben we in overleg met de PO besloten hier een boolean van te maken, conform de andere indicaties. Wordt binnenkort doorgevoerd.

**Comment by JohanBoer** [comment]
Is verwerkt. Bij de eerstvolgende pull request wordt dit issue in "review" gezet.
