### ISSUE TITLE
Waarde onbekend niet opnemen - is nu niet consequent doorgevoerd

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#213]
Voor de API is het uitgangspunt steeds geweest dat wanneer de waarde onbekend is, het attribuut niet wordt opgenomen. Bijvoorbeeld wanneer een datum volledig onbekend is (00000000) wordt de datum niet in het antwoord opgenomen.

Er zijn echter elementen die een gedefinieerde waarde voor "onbekend" hebben. Moeten die dan worden verwijderd (niet opgenomen in het antwoord)?

Dit betreft de volgende enumeraties:
* AanduidingInhoudingVermissingReisdocument (`.` - Onbekend)
* Geslacht (`O` - Onbekend)
* RedenOpschortingBijhouding (`.` - standaardwaarde indien onbekend)

En dit betreft de volgende tabellen:
* Gemeenten (0000 Onbekend)
* Landen (0000 Onbekend)
* Nationaliteiten (0000 Onbekend)
* Reden opnemen/beëindigen nationaliteit (000 Onbekend)
* Verblijfstitels (00 Onbekend)
* Nederlands reisdocument (.. Onbekend)
* Autoriteit van afgifte Nederlands reisdocument (.. Onbekend)

**Comment by gertjanvanderkooij** [comment]
En zo hebben we ook '.'-adressen en '.'-namen in de GBA. 

Mijn advies ... indien deze waarden voorkomen in de BRP deze gewoon doorgeven; zijn gedefinieerde waarden in de BRP en ook de stamgegevens (LO GBA). Eventuele aanscherping specificaties wel/niet opnemen 'waarde onbekend' in het overleg met RvIG als toekomstig serviceprovider opnemen.

**Comment by JohnRooijakkers** [comment]
Voor zover mij bekend betekent de waarde 00000000 bij datumOverlijden, DAT iemand is overleden maar dat onbekend is op welke datum (nabij een jaarwisseling). Het niet doorgeven van deze datum of aannemen dat "onbekend" is OF iemand is overleden, is dan feitelijk onjuist. Hoe wordt een dergelijke situatie verstrekt aan een vragende applicatie?

**Comment by CathyDingemanse** [comment]
@JohnRooijakkers, wij hebben er voor gekozen om een indicator geintroduceerd om aan te geven of iemand is overleden. 
Wij willen liever niet communiceren in magic strings, zoals een 000000000 bij datumOverlijden.

**Comment by CathyDingemanse** [comment]
@fsamwel @gertjanvanderkooij 
De genoemde waarden zijn allemaal valide enumeratiewaarden of tabelwaarden. Dus deze laten we zo. 
Wel gaan we even een testje doen op codegeneratie bij gebruik van de punt "." en de twee puntjes "..". Alleen als deze geen goede code opleveren, veranderen we de puntjes in de letter "o".
