### ISSUE TITLE
Wordt een volledig onbekende ouder opgenomen?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#214]
Bij een inschrijving wordt altijd ouder 1 en ouder 2 (tenzij is vastgesteld dat er maan één ouder is) gevuld, ook wanneer (bij immigratie) er geen gegevens van de ouders bekend is.
In de registratie staan dan wel de categorieën, maar is niks gevuld (met soms alleen geslacht V voor ouder 1 en en M voor ouder 2). Geboortedatum, voornamen, geslachtsnaam, enz. van de ouder zijn dan leeg.

Moet een ouder waarbij alle identificerende gegevens (burgerservicenummer, geboortedatum, voornamen, geslachtsnaam) ontbreken/volledig onbekend zijn worden opgenomen in de API?

**Comment by gertjanvanderkooij** [comment]
> Geboortedatum, voornamen, geslachtsnaam, enz. van de ouder zijn dan leeg.

De combi wel geslacht gevuld, maar geen naam/gebrootegegevens is mi niet juist. In dat geval zouden voor deze rubrieken de standaardwaarden (resp. "." en "00000000" zijn gevuld. Zie HUP GBA v3.2 (blz 55 e.v.). Te verifiëren bij domeindeskundige.

Afhandeling hangt verder samen met eerdere issue; gebruik van '.' als waarde vanuit Development-optiek. Kan geen probleem zijn lijkt me!

**Comment by fsamwel** [comment]
> De combi wel geslacht gevuld, maar geen naam/gebrootegegevens is mi niet juist.

Dit is wat ik zie in de registratie. Dus met voornamen en geslachtsnaam leeg i.p.v. gevuld met een punt. Heb dat ook nagevraagd bij een domeindeskundige, die dit bevestigde.

Situatie die ik in de database zie is dat er geen punten staan bij de onbekende voornamen en geslachtsnaam, ik vermoed omdat de hele persoon onbekend is (niet alleen de voornamen of alleen de geslachtsnaam). Mogelijk voldoet dit niet aan LO GBA, maar het blijkt wel voor te komen.

> Afhandeling hangt verder samen met eerdere issue; gebruik van '.' als waarde vanuit Development-optiek. Kan geen probleem zijn lijkt me!

Wanneer de op beschreven manier opgevoerde onbekende ouder wordt teruggegeven, bevat het antwoord geen enkel attribuut (volledig lege response, alleen een self-link), dan wel alleen het attribuut geslacht.
Of moet de API lege attribuutwaarden vervangen door een punt?

**Comment by gertjanvanderkooij** [comment]
Dat laatst zou ik niet doen; geen 'verrijking' als iets in de bron niet aanwezig cq. niet goed gevuld is. In dat geval dus alleen doorgeven wat er wel is.

Heeft de domeindeskundige ook bevestigd of de oudercategorie op PL in dat geval eigenlijk niet juist is gevuld? Dit eigenlijk gecorrigeerd zou moeten worden of is het volgens hem/haar niet fout?

**Comment by CathyDingemanse** [comment]
Eens, doorgeven wat er wel is. Als er niks is leveren we een link naar een lege ouder met alleen een self link.

**Comment by JohanBoer** [comment]
Blijkbaar geeft de documentatie geen uitsluitsel. Hoe kunnen we deze beslissing vastleggen ? Is dit een design decision of moet deze situatie opgenomen in een BDD feature ?

**Comment by fsamwel** [comment]
> Blijkbaar geeft de documentatie geen uitsluitsel. Hoe kunnen we deze beslissing vastleggen ? Is dit een design decision of moet deze situatie opgenomen in een BDD feature ?

Lijkt mij de beste plek om dit toe te voegen aan [ouders.feature](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/master/features/ouders.feature)

**Comment by fsamwel** [comment]
Ik heb toch moeite met deze oplossing, wanneer je deze werkwijze consequent doortrekt naar de andere gerelateerde sub-resources.
Bijvoorbeeld persoon met burgerservicenummer 999993008 in de GBA-V proefomgeving. Deze had een partner geregistreerd, maar die is onjuist (05.84.10="O") en dus historisch geworden. Het actuele voorkomen van categorie 05 bevat alleen waarden in 81.10 (registergemeenteAkte) en 81.20 (aktenummer). Dus levert de API dan de volgende partner:
GET /ingeschrevenpersonen/999993008/partners
{
   "_links": {"self": {"href": "https://www.voorbeeldgemeente.nl/api/bevragenpersonen/v1/ingeschrevenpersonen/999993008/partners"}},
   "_embedded": {"partners": [   {
      "registergemeenteAkte": {"code": "0518"},
      "aktenummer": "5XC1111",
      "_links": { "self": { "href": "https://www.voorbeeldgemeente.nl/api/bevragenpersonen/v1/ingeschrevenpersonen/999993008/partners/ac7e830e-c949-4ec6-8cef-493ed566329b"} }
   }]}
}

En bij het bevragen van deze persoon komt in _links.partners ook een link te staan

**Comment by fsamwel** [comment]
in feature partners_ouders_kinderen.feature staat nu dat alleen actuele ouders, partners en kinderen worden opgehaald. Dat is geoperationaliseerd naar het niet-onjuist zijn van de ouder, partner of kind.
In de praktijk wordt dan het historische voorkomen onjuist, en komt er een nieuw voorkomen waarin de ouder, partner of kind leeg is gemaakt. Daarin staat dan alleen (ten hoogste) de akte of het document op basis waarvan de ouder, partner of kind verwijderd is.

Bij het opvoeren van een persoon met één of geen ouder wordt volgens mij hetzelfde gedaan, namelijk het opvoeren van een voorkomen ouder (cat. 2 en/of 3) met alleen het document of de akte waaruit blijkt dat er geen ouder is.

Bij het opvragen van de actuele situatie kan de API niet het verschil zien tussen een "lege" ouder als gevolg van onjuist, of een ouder die bij voorbaat vastgesteld niet bestaat. Het relevante onderscheid zie ik ook niet. In beide gevallen is vastgesteld en vastgelegd dat de ouder niet bestaat.
M.i. is er alleen een ouder wanneer ten minste de geslachtsnaam (desnoods als ".") en datum familierechtelijke betrekking (desnoods als "00000000") voorkomen.

**Comment by CathyDingemanse** [comment]
Ok, dus als ik het goed begrijp wordt een gebruiker door de aanwezigheid van de link (naar een niet bestaande of onjuiste partner/ouder/kind) op het verkeerde been gezet. Voor de akte of het document dat aangeeft dat de relatie onjuist is of niet bekend is oid is het overgrote deel van de afnemers niet geautoriseerd. Veruit de meeste gebruiker kunnen niet uit het document opmaken wat er aan de hand is.
e.e.a. veronderstelt kennis van de BRP.

Bij nader inzien lijkt het toch beter om deze gegevens niet te leveren.

**Comment by MelvLee** [comment]
Voor consistentie binnen de API zou het handig zijn om onbekende/geen ouders op dezelfde manier te behandelen als met onbekend/geen datum. Dus geen ouder retourneren als deze onbekend is

**Comment by CathyDingemanse** [comment]
> Voor consistentie binnen de API zou het handig zijn om onbekende/geen ouders op dezelfde manier te behandelen als met onbekend/geen datum. Dus geen ouder retourneren als deze onbekend is

@Melvin, zou jij hier voor een feature kunnen schrijven?

**Comment by CathyDingemanse** [comment]
Ik zie in de feature nog geen scenario waarbij geen identificerende gegevens zijn gevuld, maar wel andere gegevens, zoals bijvoorbeeld M of V zoals in het begin van deze is gemeld. 
Ik stel voor dat alleen iets wordt teruggegeven als minimaal geslachtsnaam OF voornamen (ivm naamketen) of geboortedatum is gevuld?

**Comment by Robkromwijk** [comment]
> Ik zie in de feature nog geen scenario waarbij geen identificerende gegevens zijn gevuld, maar wel andere gegevens, zoals bijvoorbeeld M of V zoals in het begin van deze is gemeld.
> Ik stel voor dat alleen iets wordt teruggegeven als minimaal geslachtsnaam OF voornamen (ivm naamketen) of geboortedatum is gevuld?

Geld de regel "minimaal geslachtsnaam OF voornamen (ivm naamketen) of geboortedatum is gevuld:, zoals deze nu is gespecificeerd in https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/master/features/ouders.feature#L8 ook niet voor partners en kinderen?
Dit staat nu niet expliciet gespecificeerd.

**Comment by fsamwel** [comment]
> Geld de regel "minimaal geslachtsnaam OF voornamen (ivm naamketen) of geboortedatum is gevuld:, zoals deze nu is gespecificeerd in https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/master/features/ouders.feature#L8 ook niet voor partners en kinderen?
Dit staat nu niet expliciet gespecificeerd.

Ik denk dat het voor verschillende processen relevant is of de persoon een partner heeft. Het moet dan niet zo zijn dat een persoon wordt behandeld als alleenstaand, omdat we niet weten hoe de partner heet. Wanneer we deze regel ook op de partner(s) toe gaan passen, moeten we dit op een andere manier oplossen, bijvoorbeeld door een burgerlijkestaat property toe te voegen aan de persoon.
We hebben het nu expliciet voor ouders gedefinieerd, omdat deze situatie (volledig onbekende ouder) regelmatig voorkomt. 

Volledig onbekende partner of volledig onbekend kind hoort het niet voor te komen dat deze volledig onbekend zijn. Alleen b bij ouders is daar namelijk gespecificeerd dat deze kunnen worden opgenomen, terwijl ze in juridische zin er niet zijn. In dat geval is Naam niet opgenomen. Bij partners en kinderen wordt Naam altijd opgenomen. Zie LO GBA:

**3.3.2 Opnemen oudergegevens bij eerste inschrijving**
Bij de eerste inschrijving (zie hoofdstuk 2) worden de volgende groepen opgenomen:
Akte of 02.82 Document Geldigheid
Opneming

Indien vaststaat dat de ouder er in juridische zin niet is, worden er verder geen gegevens opgenomen. Anders worden aanvullend de volgende groepen opgenomen:
02.02 Naam
02.62 Familierechtelijke betrekking

Indien bekend, worden vanaf de bron of de PL van de ouder aanvullend de volgende groepen opgenomen:
02.01 Identificatienummers
02.03 Geboorte
02.04 Geslacht

**3.6.2 Opnemen van één of meer huwelijken/geregistreerd partnerschappen**
Bij eerste inschrijving in de GBA (zie hoofdstuk 2) dienen alle ooit gesloten huwelijken/ geregistreerd partnerschappen met betrekking tot de ingeschrevene opgenomen te worden. Ook elk daarna gesloten huwelijk/geregistreerd partnerschap dient opgenomen te worden.
De volgende groepen worden opgenomen:
Naam
Geboorte
Huwelijkssluiting/aangaan geregistreerd partnerschap Soort verbintenis
Akte of 05.82 Document
Geldigheid
Opneming

Indien bekend, worden vanaf de PL van de echtgenoot/geregistreerd partner aanvullend de volgende groepen opgenomen:
05.01 Identificatienummers 
05.04 Geslacht

**3.10.2 Opnemen kindgegevens bij eerste inschrijving**
Bij de eerste inschrijving van een persoon die ouder is van een of meer kinderen, worden voor elk kind de volgende groepen opgenomen:
Naam
Akte of 09.82 Document Geldigheid
Opneming

Indien bekend, worden vanaf de bron of de PL van het betreffende kind aanvullend de volgende groepen opgenomen:
Identificatienummers 
Geboorte
