### ISSUE TITLE
Als (tijdelijke lokale) API aanbieder wil ik dat foutmeldingen die specifieker zijn dan de standaard http statuscodes centraal worden beheerd

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#215]
...zodat iedere API aanbieder hier naar kan verwijzen.

**Acceptatiecriteria**
- [ het beheer van deze beschrijvingen kan net als de API worden overgedragen aan de aanbieder van een centrale API (RvIG)]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
Check mail van Cathy dd 21-05-2019
