### ISSUE TITLE
update specificaties op actuele landelijke API strategie

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#216]
De landelijke API strategie is de afgelopen tijd op een aantal punten aangepast. Bijvoorbeeld bij validatiefouten worden foutparameters niet meer opgenomen in invalid-params, maar in invalidParams.

De specificaties van de API zouden m.i. moeten worden geactualiseerd naar de huidige versie van de API strategie. Wellicht niet direct, maar zodra er voor de API strategie een vastgestelde versie (release) is of voor we de BRP API willen vaststellen als versie 1.0.

 Zie https://github.com/Geonovum/KP-APIs

**Comment by gertjanvanderkooij** [comment]
Eens! We hebben de review uitgezet KP API (Sergej?). @JohanBoer Resultaten hiervan al bekend? Zodra deze binnen zijn, impact bepalen en wat mij betreft z.s.m. doorvoeren zodat we in-sync zijn/blijven met API-strategie.

**Comment by CathyDingemanse** [comment]
Deze moet worden uitgevoerd voor de RC.

**Comment by fsamwel** [comment]
@CathyDingemanse in de tabel Reden opnemen/beëindigen nationaliteit zit naast de standaardkolommen ook een kolom soort. Daarin is aangegeven of het een reden opnemen is of een reden beëindigen:
VK - verkrijging
OP - opname
VL - verlies
BE - beëindiging

Moet dit gegeven ook worden opgenomen in de landelijke tabel API? Zo ja is dat dan ook iets waar men op wil filteren (zoekparameter)?

**Comment by fsamwel** [comment]
@JohanBoer property soort in RedenNationaliteit is nu gedefinieerd als string. Mooier/juister is om dit te definiëren als enumeratie, want er zijn maar vier mogelijk waarden (zie bovenstaande opmerking). Alleen zouden we dan niet de twee-lettercode gebruiken maar de volledige naam (zonder hoofdletters en ë=e).

**Comment by fsamwel** [comment]
@JohanBoer waarom zit in de endpoints nu /tabellen toegevoegd? In de actuele bevragingen heb je niet zoiets toegevoegd. Aangezien dit een andere api is, krijgt de tabellen api so-wie-so al een andere basis url dan de actuele bevragingen.
(bij bewoning heb je iets vergelijkbaars gedaan door elk endpoint met /haalcentraal te laten beginnen)

**Comment by JohanBoer** [comment]
> (bij bewoning heb je iets vergelijkbaars gedaan door elk endpoint met /haalcentraal te laten beginnen)

Dit heb ik gedaan omdat die zo zijn aangegeven in de Goals-canvas die door Cathy is opgesteld. Als we het er over eens zijn dat "/haalcentraal" er af moet is dat zo geregeld....

**Comment by JohanBoer** [comment]
> @JohanBoer property soort in RedenNationaliteit is nu gedefinieerd als string. Mooier/juister is om dit te definiëren als enumeratie, want er zijn maar vier mogelijk waarden (zie bovenstaande opmerking). Alleen zouden we dan niet de twee-lettercode gebruiken maar de volledige naam (zonder hoofdletters en ë=e).

Dit zou betekenen dat bij uitbreiding of beperking van deze enumeratie de OAS3 ook aangepast moet worden. Aangezien er alleen maar opgevraagd wordt vraag ik me af of die enumeratie meerwaarde heeft.

**Comment by JohanBoer** [comment]
Er zijn in deze issue wat comments over de landelijke tabellen geplaatst. 
Back on topic. ik heb een korte analyse gedaan in hoeverre we aan de landelijke API-strategie voldoen. 
Stand van zaken nu te vinden in de bijgevoegde excel. 
Niet 100%, maar we komen heel ver en kunnen een aantal keuzes toelichten. 
Nog een paar vraagtekentjes, Als iemande (Kayo, Melvin, Frank? )  die punten zou kunnen beoordelen, dan graag

[Check op api_principes ingeschreven persoon.xlsx](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/files/3927442/Check.op.api_principes.ingeschreven.persoon.xlsx)

**Comment by CathyDingemanse** [comment]
API-11 is een ja, met additioneel een client certificaat (2-zijdig TLS).  
API-14 is in de meeste gevallen ook een ja. Dit wordt in de implementatie bij gemeenten geregeld. 
API-18 is een ja.

**Comment by JohanBoer** [comment]
Johan past de xlsx aan en zet deze issue dan op done.
