### ISSUE TITLE
Mogelijke waarden indicatie geheim beperken tot 0 en 7

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#220]
indicatieGeheim is nu gedefinieerd met mogelijke waarden 0 t/m 7. Dit komt overeen met de definitie in LO GBA voor element 70.10 (pag. 316).

Maar in §3.8.7 van LO GBA staat:
> 3.8.7 Wijziging in geheim
> Op verzoek van de ingeschrevene wordt geregistreerd dat het verstrekken van gegevens over die ingeschrevene aan bepaalde derden wel/niet is toegestaan (rubriek 07.70.10 krijgt de waarde “0”, respectievelijk “7”).
De volgende groep wordt gewijzigd: 07.70 Geheim

Onze BRP specialist geeft aan dat je dus  alleen waarden 0 of 7 wilt terugkrijgen. Dan zou de enumeratie moeten worden beperkt tot de waarden 0 en 7.
Mocht een gemeente nog geen conversie hebben gedaan naar deze 2 waarden, en dus een andere waarde dan 0 of 7 kennen op een persoon, moet die waarde (>0) worden vertaald naar de waarde 7.

**Comment by fsamwel** [comment]
Overigens is hier binnen Den Haag nog wel discussie over. Is de bron altijd leidend, ook wanneer deze gevuld is met gegevens die er volgens LO GBA niet in zouden moeten staan (1, 2, 3, 4, 5 of 6)? Of vertalen we deze waarden naar juiste waarden volgens LO GBA (0 of 7)?

**Comment by CathyDingemanse** [comment]
Dat laatste, aangezien het onderscheid dat gemaakt wordt in 1-6 niet meer relevant is.

**Comment by JohanBoer** [comment]
Enumeratiewaaren 1 t/m 6 verwijderd en de volgende toelichting toegevoegd aan de enumeratie : 

_Conform & 3.8.7 LO GBA is alleen de waarde 0 en de waarde 7 toegestaan. Mocht de bron de waarde 1 t/m 6 bevatten dan dient deze geconverteerd te worden naar waarde 7._

**Comment by fsamwel** [comment]
> Conform & 3.8.7 LO GBA

Wordt hier bedoeld "Conform §3.8.7 LO GBA"?

**Comment by JohanBoer** [comment]
Aanpassen in de description.

**Comment by JohanBoer** [comment]
Wordt omgezet in een boolean en er moet een feature worden geschreven hoe dat 1 tot en met 6 omgezet wordt true.

**Comment by fsamwel** [comment]
In de yaml zit nog wel component IndicatieGeheim_enum. Deze wordt niet meer gebruikt en kan dus verwijderd worden uit de specificaties.

**Comment by fsamwel** [comment]
Er zit nu foutje in yaml voor indicatieGeheim, zie #268

**Comment by JohanBoer** [comment]
Zowel foutje (#268)  als de overbodige enum zijn verwerkt.
