### ISSUE TITLE
Als medewerker bezwaar Sociale Zaken wil ik alle familie- en partnerrelaties kunnen opzoeken en raadplegen    

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#221]
...zodat ik het onderzoek dat heeft geleid tot het bestreden besluit opnieuw kan uitvoeren en de argumentatie (niet mijn vader, niet mijn kind etc.) van bezwaarde kan controleren..

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
Als het om actuele relaties gaat valt deze user story onder de actuele bevragingen (en kan deze vraag reeds beantwoordt worden. 
Als het ook om historische partners gaat kan deze vraag beantwoord worden door 2 endpoints aan te roepen.
