### ISSUE TITLE
Als medewerker bezwaar Sociale Zaken wil ik weten of en wanneer iemand zich heeft uitgeschreven op een adres 

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#225]
...zodat ik kan onderzoeken of de uitschrijving in overeenstemming is met de feitelijke bewoning van een adres. 

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
Dit kan via de enpoint bewoning opgevraagd worden als de ingang een adres is. Als de ingang de persoon is kan dit opgevraag worden via de endpoint verblijfplaatshistorie.
