### ISSUE TITLE
Generatie van lijst objecten resulteert in generic objecten

### ISSUE THREAD

**Issue by KayodeBakker** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#226]
# Impediment

Bij het implementeren van BRP bevragen zagen we dat de generatie van responses voor de zoekpaden ingeschrevenpersonen, kinderen, ouders en partners resulteerde in half generieke objecten genaamd:

- InlineResponse200.cs (ingeschrevenpersonen lijst)
- InlineResponse200Embedded.cs
- InlineResponse2001.cs (kinderen lijst)
- InlineResponse2001Embedded.cs
- InlineResponse2002.cs (ouders lijst)
- InlineResponse2002Embedded.cs
- InlineResponse2003.cs (partners lijst)
- InlineResponse2003Embedded.cs

Hier verwachten we eigenlijk meer iets in de trend als :

- IngeschrevenPersoonCollection.cs
- IngeschrevenPersoonCollectionEmbedded.cs
- KindCollection.cs
- KindCollectionEmbedded.cs
- OuderCollection.cs
- OuderCollectionEmbedded.cs
- PartnerCollection.cs
- PartnerCollectionEmbedded.cs

Bij HR bevragen zien we in een vergelijkbare scenario de gewenste resultaat wel voorkomen. Bij het vergelijken van de yaml's zien we een opvallend verschil wat waarschijnlijk de oorzaak is.

Voorbeeld scenario BRP bevragen:

> content:
            application/hal+json:
              schema:
                type: object
                properties:
                  _links:
                    $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/components.yaml#/HalCollectionLinks"
                  _embedded:
                    type: object
                    properties:
                      ingeschrevenpersonen:
                        type: array
                        items:
                          $ref: '#/components/schemas/IngeschrevenPersoon'

Voorbeeld scenario HR bevragen:

> content:
            application/json:
              schema:
                $ref: '#/components/schemas/VestigingCollection'
........
VestigingCollection:
      type: object
      properties:
        _links:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/components.yaml#/HalPaginationLinks"
        _embedded:
          type: object
          properties:
            vestigingen:
              type: array
              items:
                $ref: '#/components/schemas/VestigingLijst'

Omdat bij HR bevragen de response type een referentie is naar een schema object, zal de generatie ook specifiekere objecten aanmaken. 

Mijn voorstel is dan ook om bij BRP bevragen ditzelfde concept te hanteren.

**Comment by fsamwel** [comment]
Dit is zo gestructureerd (aangepast eind oktober) op advies van SIG, omdat dit de standaard manier zou zijn volgens Swagger.
(@JohanBoer: zie RedMine issue 490352)

Maar in de huidige versie van de [Swagger specificaties](https://swagger.io/docs/specification/describing-responses/) zie ik dat niet meer terug. Ze geven zelf ook een voorbeeld waar de response verwijst naar een ArrayOfUsers (dus een collection). Wellicht zijn ze ook bij Swagger anders hierover gaan denken.

Ook is het denk ik belangrijker dat developers goed en eenvoudig code kunnen genereren belangrijker dan het volgen van een impliciete standaard afgeleid op basis van enkele voorbeelden.

**Comment by MelvLee** [comment]
De InlineResponseXXX en InlineResponseXXXEmbedded blijken te worden gegenereerd voor de objecten die zijn gespecificeerd als response voor status code 200. Een voorbeeld hiervan is de content voor 200 van get ingeschrevenpersonen die er als volgt uit ziet:

            application/hal+json:
              schema:
                type: object
                properties:
                  _links:
                    $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/components.yaml#/HalCollectionLinks"
                  _embedded:
                    type: object
                    properties:
                      ingeschrevenpersonen:
                        type: array
                        items:
                          $ref: '#/components/schemas/IngeschrevenPersoon'

De InlineResponseXXX class mapt naar het eerste object met properties _links en _embedded en de InlineResponseXXXEmbedded class mapt naar het tweede object met properties ingeschrevenpersonen.

Het genereren van InlineResponse classes kan worden voorkomen door bovenstaande specificatie op te nemen onder components/schemas:

    ZoekIngeschrevenPersonenResponseContent:
      type: object
      properties:
        _links:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/components.yaml#/HalCollectionLinks"
        _embedded:
          type: object
          properties:
            ingeschrevenpersonen:
              type: array
              items:
                $ref: '#/components/schemas/IngeschrevenPersoon'

De content voor 200 van get ingeschrevenpersonen kan dan worden vervangen door een $ref en ziet er dan als volgt uit:

        application/hal+json:
          schema:
            $ref: '#/components/schemas/ZoekIngeschrevenPersonenResponseContent'

De classes die nu worden gegenereerd heten dan ZoekIngeschrevenPersonenResponseContent en ZoekIngeschrevenPersonenResponseContent__embedded

**Comment by JohanBoer** [comment]
Dit combineren we met het inzicht dat Hal- specifieke schema-componenten apart worden gemodelleerd.

**Comment by fsamwel** [comment]
De oplossing is in de yaml:

bij /ingeschrevenpersonen wijzigen van de content schema definitie:
      responses:
        '200':
          description: "Zoekactie geslaagd"
          headers:
            ...
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/IngeschrevenPersoonCollectie'

En aan components schemas toevoegen:
    IngeschrevenPersoonCollectie:
      type: object
      properties:
        _links:
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/components.yaml#/HalCollectionLinks"
        _embedded:
          type: object
          properties:
            ingeschrevenpersonen:
              type: array
              items:
                $ref: '#/components/schemas/IngeschrevenPersoon'

Hetzelfde moet gebeuren voor elke collectie, dus de kinderen, ouders, partners en (wanneer dat endpoint niet wordt verwijderd) reisdocumenten.

**Comment by JohanBoer** [comment]
Deze wijziging is nu doorgevoerd en is opgenomen in de YAML die op Github staat.
