### ISSUE TITLE
standaardwaarde . voor soortVerbintenis

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#227]
Voor soortVerbintenis is de enumeratie gedefinieerd:
H - huwelijk
P - geregistreerd partnerschap

In LO GBA staat bij attribuut 15.10 Soort verbintenis:

> Standaardwaarde .
Mogelijke waarden 
H (= huwelijk)
P (= geregistreerd partnerschap)
Standaardwaarde indien onbekend.

Dus zou een punt aan de enumeratie moeten worden toegevoegd voor onbekend

**Comment by JohanBoer** [comment]
Verwerkt conform voorstel

**Comment by fsamwel** [comment]
deze wijziging zal ongedaan gemaakt worden door #228
