### ISSUE TITLE
Onbekend-waardes melden in description van elementen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#228]
GBA kent op een aantal attributen een standaardwaarde, bijvoorbeeld "." voor geslachtsnaam, "0000000000000000" voor de BAG-identificaties.

Ik denk dat een client de API moet kunnen gebruiken en interpreteren zonder het LO GBA in detail te hoeven kennen.
Dus zou ik het goed vinden wanneer in de toelichtingen op velden deze standaardwaarden genoemd worden, voor zover dat niet al in de enumeratie of tabel zit.

Gaat over:
- straatnaam
- woonplaatsnaam
- huisnummer
- identificatiecodeVerblijfplaats
- identificatiecodeNummeraanduiding
- reisdocumentnummer

**Comment by JohanBoer** [comment]
Gaat over:

- [ ] straatnaam
- [ ] woonplaatsnaam
- [ ] huisnummer
- [ ] identificatiecodeVerblijfplaats
- [ ] identificatiecodeNummeraanduiding
- [ ] reisdocumentnummer

**Comment by fsamwel** [comment]
Ik zie nu juist bij straatnaam geen opmerking toegevoegd over de standaardwaarde, terwijl dit de enige plek is (naast het reisdocumentnummer) waar juist wel expliciet in LO GBA staat dat de standaardwaarde moet worden gebruikt.

**Comment by JohanBoer** [comment]
Nu ook bij straatnaam de standaardwaarde vermeld.

**Comment by MelvLee** [comment]
Ik denk dat het handig is om deze onbekende waardes op dezelfde manier te behandelen als onbekend datum. Dus niet teruggeven igv onbekend.
Om toch onbekende waardes terug te communiceren stel ik voor om iets soortgelijks te introduceren als InOnderzoek. Je krijgt dan een Onbekend gegevensgroep waarin wordt aangegeven of een gegeven (bijv straatnaam) onbekend is.
Ik hoef dan als developer niet logica in te bouwen om 0000000 of . te interpreteren. En als ik in mijn applicatie wat van moet zeggen kan ik kijken of er Onbekend property is en of idg de straatnaam property de waarde true heeft.
Ik hoef dan ook niet in de documentatie te zoeken wat de default waarde is van een property

**Comment by CathyDingemanse** [comment]
Ik ben er ook voor om deze "onbekend waardes" niet terug te geven. Svp geen magic strings (of punt :-)) in de API.     
Het voorstel van Melvin om deze te isoleren en er niet alle gebruikers mee te belasten vind ik een  goed voorstel MITS iemand mij kan uitleggen waarom en waarvoor hij/zij zo'n "bekend onbekend" waarde of andere "standaardwaarde" nodig heeft, EN wij hiervoor geen alternatief kunnen vinden zoals bijvoorbeeld de boolean "overleden" bij een onbekende overlijdensdatum.

**Comment by fsamwel** [comment]
@MelvLee @CathyDingemanse wil je deze "onbekend" waardes ook niet meer voor tabellen (gemeentecode 0000 betekent Onbekend) en enumeraties (geslacht O betekent Onbekend)?

**Comment by CathyDingemanse** [comment]
Ja in principe wel. Echter, specifiek voor de geslachtsaanduiding leveren wij d waarde geslacht O = Onbekend. Ik realiseer mij dat dit een uitzondering is binnen de API, maar wil mij hier letterlijk houden aan wat de BRP voorschrijft.

**Comment by JohanBoer** [comment]
Ik snap de redenering bij de onbekende waardes voor gewone elementen (de punten en 0000000) maar als het om tabellen gaat is de waarde "onbekend" gewoon een valide tabel-waarde. Je krijgt dan gewoon een geldige tabelcode en/of omschrijving terug. Of zie ik hier ook iets over het hoofd Melvin ?

**Comment by MelvLee** [comment]
Een belangrijk design principe voor een API is dat hij consistent is, zodat een consumer geen complexe code hoeft te implementeren om de gegevens te interpreteren. Als de provider de tabel waarden as-is terug zou geven (minder werk voor de provider), dan zou elke consumer voor bijvoorbeeld een Nederlands Reisdocument moeten checken op code = "..", voor Reden opnemen/beëindigen nationaliteit op code = "000", voor reden ontbinding op code = "." en voor gemeente op code = "0000". Dit is volgens mij niet consistent.
Om het helemaal consistent te krijgen zou dus ook bij enumeraties de onbekende waarde weggehaald moeten worden. Enum geslacht is zoals Cathy aangeeft de enige uitzondering

**Comment by fsamwel** [comment]
Ik heb een korte inventarisatie gedaan. Het betreft:
- gemeente (code en omschrijving paar): 0000 en Onbekend
- land (code en omschrijving paar): 0000 en Onbekend
- geslachtsnaam: .
- nationaliteit: 0000
- straatnaam:  .
- woonplaatsnaam:  .
- huisnummer:   0
- identificatiecodeVerblijfplaats en identificatiecodeNummeraanduiding:  0000000000000000
- soortVerbintenis:  .
- soortReisdocument:  ..
- reisdocumentnummer:  .........
- autoriteitAfgifte:  ..
- aanduidingInhouding_vermissing: .
- verblijfstitel.aanduiding: 00
- nationaliteit.redenOpname: 000
- redenOpschortingBijhouding: .
- aktenummer: .......

De API moet dus deze waarden uit het antwoord filteren, zodat bijvoorbeeld wanneer in de bron straatnaam=".", property straatnaam niet wordt opgenomen in het antwoord

**Comment by gertjanvanderkooij** [comment]
> Om toch onbekende waardes terug te communiceren stel ik voor om iets soortgelijks te introduceren als InOnderzoek. Je krijgt dan een Onbekend gegevensgroep waarin wordt aangegeven of een gegeven (bijv straatnaam) onbekend is.

Is nette en eenduidige oplossing; iets meer logica aan de provider-kant maar lijkt mij alleszins te overzien. 

@MelvLee Volgende vraag/opmerking:
1) Vervallen hiermee ook de indicatoren die aangeven dat een bepaalde Datum (bv. Overlijdensdatum) geheel onbekend is? Ik zou zeggen "Ja"; alles met 'Onbekend' (of Standaardwaarde zoals de BRP dit noemt) wordt dan op eenzelfde manier behandeld/afgehandeld.

2) Ter verificatie: In de Onderzoeks- en Onbekend-gegevensgroep is een element niet opgenomen als hier niet om is gevraagd (Fields) of als een Consumer hiervoor niet is geautoriseerd.

NB. Ik kan het lijstje van Frank nog even checken als hier behoefte aan is. Just let me know 


> De API moet dus deze waarden uit het antwoord filteren, zodat bijvoorbeeld wanneer in de bron straatnaam=".", property straatnaam niet wordt opgenomen in het antwoord

@fsamwel Just checking:
In dat geval wordt dan "straatnaam" opgenomen in de 'OnbekendGegevensgroep'. Correct?

**Comment by CathyDingemanse** [comment]
> > Om toch onbekende waardes terug te communiceren stel ik voor om iets soortgelijks te introduceren als InOnderzoek. Je krijgt dan een Onbekend gegevensgroep waarin wordt aangegeven of een gegeven (bijv straatnaam) onbekend is.
> 
> Is nette en eenduidige oplossing; iets meer logica aan de provider-kant maar lijkt mij alleszins te overzien.
> 
> @MelvLee Volgende vraag/opmerking:
> 
> 1. Vervallen hiermee ook de indicatoren die aangeven dat een bepaalde Datum (bv. Overlijdensdatum) geheel onbekend is? Ik zou zeggen "Ja"; alles met 'Onbekend' (of Standaardwaarde zoals de BRP dit noemt) wordt dan op eenzelfde manier behandeld/afgehandeld.
> 2. Ter verificatie: In de Onderzoeks- en Onbekend-gegevensgroep is een element niet opgenomen als hier niet om is gevraagd (Fields) of als een Consumer hiervoor niet is geautoriseerd.
> 
> NB. Ik kan het lijstje van Frank nog even checken als hier behoefte aan is. Just let me know
> 
> > De API moet dus deze waarden uit het antwoord filteren, zodat bijvoorbeeld wanneer in de bron straatnaam=".", property straatnaam niet wordt opgenomen in het antwoord
> 
> @fsamwel Just checking:
> In dat geval wordt dan "straatnaam" opgenomen in de 'OnbekendGegevensgroep'. Correct?

Welk probleem lossen wij hier mee op? We lossen alleen een probleem op voor een afnemer die expliciet vraagt om deze onbekende waarden. Deze afnemer heeft zich nog niet gemeld. Ik wil deze constructie alleen overwegen als zich een afnemer meldt met een goede reden waarom de waarden onbekend in de diverse varianten gewenst zijn, EN wij geen andere oplossing voor het probleem van de afnemer kunnen verzinnen.

**Comment by gertjanvanderkooij** [comment]
Keuze die we dan maken is om een gegeven zoals met standaardwaarde/onbekend is opgenomen in de authentiek bron niet door te geven aan de consumer. Uitzonderingen die we hier nu op lijken te maken zijn voor geheel onbekende datums en geslacht. 

Als we niks doen met standaardwaarden/onbekend, dan kan een gegeven om de volgende redenen niet in de response zijn opgenomen:
1) Consumer is niet geautoriseerd --> Kennis bij consumer
2) Consumer heeft er niet om gevraagd (Fields) --> Kennis bij consumer
3) Gegeven is niet in de BRP aanwezig (niet gevuld) --> Kennis bij de authentieke bron
4) Gegeven is als 'onbekend'/'standaardwaarde' in de BRP aanwezig --> Kennis bij de authentieke bron.

Als we gaan filteren op de inhoud en verder niets doen is het onderscheid tussen 3 en 4 voor de consumer niet meer te maken. 

Leidt dit bv. niet tot problemen in het gebruik … 'Hé, waarom is de straatnaam niet gevuld?' of "Ik heb wel een datum ingang verblijfstitel, maar geen verblijfstitelcode? of "Mmm, da's vreemd … deze persoon heeft geen nationaliteit en wordt ook niet behandeld als NL. Hoe zou dat nu zitten?' Daar ga ik toch maar eens even over bellen. (… of straks terugmelden ;-) "

Hadden we eerder niet besproken om standaardwaarden één op één door te geven (behalve de volledig onbekende datum, want te magische string en botst met datatype) en het geheel (omgaan met staandaardwaarden/onbekend) als bespreekpunt voor RvIG te adresseren? 

Daar voel ik eerlijk gezegd meer voor, dan nu te gaan filteren op de inhoud van elementen en tabelwaarden; en als gevolg hiervan BRP-gegevens niet door te geven. Met de constructie die Melvin aan geeft kan het aan consumer-zijde generiek worden afgehandeld.

Donderdag wellicht even een momentje nemen?

**Comment by fsamwel** [comment]
@gertjanvanderkooij zijn het niet (bijna) alleen elementen die verplicht voorkomen in een groep die een standaardwaarde krijgen? In die gevallen kan optie 3 (geen waarde) namelijk niet voorkomen en is het onderscheid met optie 4 (waarde onbekend) niet meer van belang.

Verder een paar overwegingen:
- Ik zou zeggen dat de grote vraag is of het voor de consumer van de API relevant is onderscheid te maken tussen geen waarde en waarde onbekend. Ik vermoed dat voor de meeste (of zelfs alle?) processen dat onderscheid niet relevant is.
- Opnemen van onbekend waardes verplicht consumers die deze niet nodig hebben code te schrijven deze eruit te filteren. Oppassen dus dat we veel consumers belasten (incl. risico op fouten) met functionaliteit die maar weinig consumers nodig hebben.
- Er zijn volgens mij ook veel backward compatible mogelijkheden later, wanneer dat nodig blijkt, constructies toe te voegen om alsnog waarde onbekend op te nemen. Melvin doet al een suggestie voor een oplossing. Later de onbekend waardes verwijderen kan niet meer backward compatible.

**Comment by fsamwel** [comment]
@CathyDingemanse Als ik het goed begrijp is nu de beslissing genomen dat:
1. we voorlopig geen "onbekend" constructie toevoegen, tot daar een businessproces om vraagt
2. we de onbekend waardes verwijderen uit de OAS alle enumeraties waarin die voorkomen, m.u.v. geslacht=O.
3. we de beschrijving van onbekend waarden verwijderen uit de property descripties in de OAS (toegevoegd n.a.v. dit issue)
4. in de API implementatie alle onbekend waardes gefilterd moeten worden. Bijvoorbeeld straatnaam="." wordt null, dus straatnaam wordt niet opgenomen in het antwoord. Bijvoorbeeld geboorte.plaats.code="0000" wordt null, dus geboorte.plaats wordt niet opgenomen in het antwoord. 
Betreft alle property types met een standaardwaarde (string, integer, tabel).

Heb ik dit zo goed begrepen?

**Comment by CathyDingemanse** [comment]
Jazeker, dank Frank!

**Comment by gertjanvanderkooij** [comment]
Ik vind 'm erg (te) kort door de bocht ... gegevens weglaten zoals deze in de BRP cf. LO GBA zijn opgenomen! Ik zou ze in afwachting van een 

**Suggestie:**
Na de succesvolle FieldLab van afgelopen donderdag hebben we er zo maar 20 potentiële consumers bij. Variërend van Prefill in webformulier (Kodesion), Documentproductie (B-Ware), Prikken vanuit de kaart (GisKit), Integratie iBurgerzaken (PinkRoccade), Toepassing Leefomgeving (Centric), de U-pas (Utrecht/VNGR) ... maar bv. ook BRP-Afnemertoepassing (T&T), gebruik irt bv. Verkiezingen (Conxillium/Procura) en dichter bij CommonGround-huis ... het ZGW-team. 

Laten we een deel van deze consumers de casus en mogelijke implementatie eens actief (bv. via belronde?) voorleggen:
1) Inhoud doorgeven zoals nu opgenomen in BRP en beschreven in LO GBA
2) Introductie 'In_BRP_Onbekend'-construct ala 'InOnderzoek'
3) In voorkomende gevallen niets doorgeven (zoals nu is besloten)

Dit in plaats van het nu voorgestelde recept "_Wachten tot een businessproces hier om vraagt_.".

@fsamwel  
> zijn het niet (bijna) alleen elementen die verplicht voorkomen in een groep die een standaardwaarde krijgen? In die gevallen kan optie 3 (geen waarde) namelijk niet voorkomen en is het onderscheid met optie 4 (waarde onbekend) niet meer van belang.

Het venijn zit 'm hier volgens mij in gebruik van Fields-parameter en de Autorisatie-instellingen. Als je bv. alleen de Verblijfstitelcode opvraagt (Fields) of alleen hiervoor bent geautoriseerd en deze is in de BRP met '00 - Onbekend' gevuld, dan krijg ik met de voorgestelde oplossing als consumer niets meer terug in de response (wordt weg gefilterd), terwijl er wel iets rondom de Verblijfstitel speelt. Anders was dit namelijk niet geregistreerd. Het wegfilteren van deze waarde doet m.i. tekort aan het businessproces dat behoefte heeft aan de Verblijfstitel-gegevens. Of Nationaliteitgegevens of LandVanwaarIngeschreven-gegevens of ... 

Betreft evenals 'Geslacht onbekend' toegestane domeinwaarden. Ik zou deze nu conceptueel hetzelfde afhandelen.

**Comment by fsamwel** [comment]
We hebben de verschillende properties met een mogelijke "onbekend" waarde doorgenomen en gekeken in hoeverre hier een voor een consumer (≠ de registratie) relevant verschil is tussen leeg en onbekend. 
De conclusie is dat al deze properties dit onderscheid niet relevant is behalve:
- geslachtsaanduiding: deze is te gevoelig en dus blijft de waarde onbekend gehandhaafd
- immigratie (landVanwaarIngeschreven en datumVestigingInNederland): hier worden twee indicatoren toegevoegd: indicatieVestigingVanuitBuitenland en vanuitVertrokkenOnbekendWaarheen
  - indicatieVestigingVanuitBuitenland (boolean) is true wanneer datumVestigingInNederland een waarde heeft (incl. 00000000). Hieruit kan de consumer concluderen dat de persoon uit het buitenland geïmmigreerd is.
  - vanuitVertrokkenOnbekendWaarheen (boolean) is true wanneer landVanwaarIngeschreven = 0000. Hieruit kan de consumer concluderen dat de persoon is teruggekeerd uit een situatie van vertrokken onbekend waarmee
- verblijfBuitenland.land: wanneer land = 0000 wordt een indicator vertrokkenOnbekendWaarheen (boolean) toegevoegd
- reisdocument.aanduidingInhoudingOfVermissing: hier is het relevant te weten dat het reisdocument niet meer in het bezit is van de persoon. Waarde . (Onbekend) wordt gewijzigd naar N (Niet in het bezit van).

Van alle andere mogelijke onbekend waardes is de conclusie dat de consumer niet kan of wil weten wat het verschil is tussen de onbekend waarde en geen waarde. 
Bijvoorbeeld een persoon met verblijfstitel.code=00 heeft in feite geen geldige verblijfstitel (dan hadden we wel geweten welke dat is). De afhandeling van eventuele twijfel of onduidelijkheid rond de verblijfstitel moet niet worden afgehandeld door de consumer, maar door de registratie.

@JohanBoer kan jij deze wijzigingen doorvoeren in de OAS:
- toevoegen indicatieVestigingVanuitBuitenland (boolean) 
- toevoegen vanuitVertrokkenOnbekendWaarheen (boolean)
- toevoegen verblijfplaats.verblijfBuitenland.vertrokkenOnbekendWaarheen (boolean)
- wijzigen in AanduidingInhoudingVermissingReisdocument_enum de enumeratiewaarde . ~ Onbekend naar N ~ Niet in het bezit van
- verwijderen uit RedenOpschortingBijhouding_enum de enumeratiewaarde . - standaardwaarde indien onbekend
- verwijderen uit SoortVerbintenis_enum de enumeratiewaarde . - standaardwaarde indien onbekend

Ik zal zelf een feature schrijven over het filteren van onbekend waardes uit de verschillende properties

**Comment by CathyDingemanse** [comment]
@gertjanvanderkooij 
Zoals gisteren ook telefonisch toegelicht, is de gedachte achter deze werkwijze dat we niet langer onduidelijkheden uit de registratie ongefilterd doorgeven aan een consumer. Dit zijn situaties waar een domeindeskundige, lees burgerzakenexpert, misschien nog gehakt van kan maken, maar die een normaal mens echt niet snapt, of in ieder geval de nuances voor een juiste interpretatie zal missen. Hoe gek is het dat je een overlijdensdatum 00-00-0000 interpreteert als dat de goede man of vrouw nog leeft? Alleen de domeindeskundige weet dat de persoon is overleden op een onbekende datum. 
Het adagium "letterlijk doorgeven wat de bron registreert" is een dwaling, en leidt nogal eens tot het doorkoppen van problemen naar consumers die nog veel minder goed weten wat ze met de aangeboden dilemma's uit de registratie moeten doen dan de domeindeskundige provider. Ik ben van mening dat DE PROVIDER die verantwoordelijkheid moet nemen door zelf de interpretatie ter hand te nemen en voor de gebruiker RELEVANTE gegevens (service abstraction) moet leveren die NIET voor meerdere uitleg vatbaar is. In mijn visie biedt onze API een specifieke AFNEMERS-VIEW op de bron.
De bron is, zoals ik al eerder heb aangegeven, ontworpen met het oog op een juiste registratie en alle processen en documenten die daaraan ten grondslag liggen. En is dus niet optimaal ingericht voor verstrekking aan gebruikers in andere domeinen en met een ander vak (vergunningen, bezwaar, handhaving, bestrijden ondermijning etc.).

Iedereen in dit dit domein weet dat een verkeerde interpretatie van persoonsgegevens kan leiden tot de grootst mogelijke persoonlijke en maatschappelijke drama's. Laten we ons uiterste best doen deze te voorkomen!

**Comment by fsamwel** [comment]
@JohanBoer heb jij de aanpassingen gedaan zoals ik woensdag heb beschreven?

> * toevoegen indicatieVestigingVanuitBuitenland (boolean)
> * toevoegen vanuitVertrokkenOnbekendWaarheen (boolean)
> * toevoegen verblijfplaats.verblijfBuitenland.vertrokkenOnbekendWaarheen (boolean)
> * wijzigen in AanduidingInhoudingVermissingReisdocument_enum de enumeratiewaarde . ~ Onbekend naar N ~ Niet in het bezit van
> * verwijderen uit RedenOpschortingBijhouding_enum de enumeratiewaarde . - standaardwaarde indien onbekend
> * verwijderen uit SoortVerbintenis_enum de enumeratiewaarde . - standaardwaarde indien onbekend

Zo ja, dan kan deze wat mij betreft in review

**Comment by JohanBoer** [comment]
- [ ] toevoegen indicatieVestigingVanuitBuitenland (boolean)
- [ ] toevoegen vanuitVertrokkenOnbekendWaarheen (boolean)
- [ ] toevoegen verblijfplaats.verblijfBuitenland.vertrokkenOnbekendWaarheen (boolean)
- [ ] wijzigen in AanduidingInhoudingVermissingReisdocument_enum de enumeratiewaarde . ~ Onbekend naar N ~ Niet in het bezit van
- [ ] verwijderen uit RedenOpschortingBijhouding_enum de enumeratiewaarde . - standaardwaarde indien onbekend
- [ ] verwijderen uit SoortVerbintenis_enum de enumeratiewaarde . - standaardwaarde indien onbekend

**Comment by fsamwel** [comment]
@JohanBoer Ik mis nog een paar van de aanpassingen in de huidige versie van de OAS:
- vanuitVertrokkenOnbekendWaarheen
- vertrokkenOnbekendWaarheen
- AanduidingInhoudingVermissingReisdocument_enum de enumeratiewaarde . ~ Onbekend naar N ~ Niet in het bezit van
