### ISSUE TITLE
consequente naamgeving reisdocument inhouding/vermissing

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#229]
Bij reisdocumenten hebben we een attribuut datumInhoudingOfVermissing en een attribuut aanduidingInhouding_vermissing.

In het ene geval is de "/" in de oorspronkelijke naam vertaald naar "Of", in het andere geval naar "_".

Voorstel: aanduidingInhouding_vermissing wijzigen naar aanduidingInhoudingOfVermissing

**Comment by JohanBoer** [comment]
Verwerkt conform voorstel
