### ISSUE TITLE
Willen we inverse relaties naar andere registraties opnemen ?

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#23]
In hoeverre willen we inverse relaties opnemen.  De ingeschreven persoon kan eigenaar zijn van een maatschappelijke activiteit. Ook de relaties "is zakelijk gerechtigde van"  en "heeft als voornaamste zakelijk gerechtigde" bestaan nu. De laatste 2 zijn volgens mij BRK-elaties die onbderhouden worden door het kadaster (en dus niet opgenomen zouden moeten worden. De eerste (is eigenaar van) is een NHR-relatie die onderhouden wordt door de KvK. 
De "is functionaris van" relatie wordt volgens mij ook onderhouden door het NHR.

Vooralsnog neem ik deze relaties niet op en ik denk dat we hier een expliciete design decision aan moeten weiden.

**Comment by fsamwel** [comment]
geen inverse relaties opnemen uit een ander domein. wordt ontwerpbeslissing. Deze relaties komen uit een ander domein en zijn dus niet beschikbaar in deze bron.
Wel inverse relaties binnen domein/registratie, op basis van functionele behoefte, zoals bewoning

**Comment by fsamwel** [comment]
Is verwerkt in design decisions
