### ISSUE TITLE
Hoe afleiden aanschrijfwijze bij meerdere partners

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#231]
In pull request #219 is voorstel gedaan voor feature aanschrijfwijze bij meerdere partners.

Hierover is discussie ontstaan of dit juist is beschreven.

Beschreven is dat in geval van meerdere actuele partners de partner van de oudste relatie gebruikt wordt. In geval van meerdere beëindigde relaties wordt partner van de laatst beëindigde relatie gebruikt.
Er wordt hierbij onderscheid gemaakt tussen een actuele relatie, waarbij de oudste geacht wordt het meest “recht” te hebben op gebruik van de naam, en beëindigde relaties, waarbij altijd de laatst ontbonden relatie wordt gebruikt.

Eigenlijk hoort de afleiding te zijn:
1. De actuele partner waarmee de persoon op hetzelfde adres woont
2. De actuele partner met wie de persoon een kind heeft
3. De actuele partner met oudste begindatum van de relatie
4. De laatst ontbonden niet-actuele partner

Dit is echter behoorlijk complex. En de situatie van een persoon met meerdere actuele partners én aanduidingNaamgebruik <> 'E' zal zeer zelfden (of nooit?) voorkomen. Dus wellicht is een vereenvoudigde afleiding voldoende.

@gertjanvanderkooij stelt voor:
1. Altijd uitgaan van het meest recente huwelijk/geregistreerd partnerschap
2. Geen afleidingen introduceren als ‘op hetzelfde adres’ of ‘met wie persoon een kind heeft’

**Comment by JohanBoer** [comment]
> @gertjanvanderkooij stelt voor:
> 
> 1. Altijd uitgaan van het meest recente huwelijk/geregistreerd partnerschap
> 2. Geen afleidingen introduceren als ‘op hetzelfde adres’ of ‘met wie persoon een kind heeft’

PO heeft besloten dat het voorstel van Gertjan wordt overgenomen
