### ISSUE TITLE
Als developer wil ik weten hoe ik de HAL links moet gebruiken

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#232]
...zodat ik niet in de HAL specs hoef te duiken (wat mij veel tijd gaat kosten).

**Acceptatiecriteria**
- er zijn BDD features voor het specifieke gebruik van HAL links in deze API die de werking van de links duidelijk maken, zonder dat de HAL specs geraadpleegd hoeven te worden.
- gereviewed door 1 of meer developers

**Definition of done**
- [BDD features gebruik HAL links]
- [review door een developer]

**Comment by fsamwel** [comment]
@JohanBoer  waarom staat dit issue in review? ik kan de gevraagde BDD feature niet vinden en zo te zien is er ook geen pull request/commit geweest t.b.v. dit issue

**Comment by JohanBoer** [comment]
Moet een vergissing zijn geweest. Ik zet hem terug in de Sprint Backlog

**Comment by JohanBoer** [comment]
Melvin checked de links.feature die nu onder /docs/features staat
