### ISSUE TITLE
verblijfplaats__gemeentevaninschrijving gedefinieerd als integer?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#233]
zoekparameter verblijfplaats__gemeentevaninschrijving is gedefinieerd als integer. 

De gemeente van inschrijving in de response wordt gedefinieerd door een code en omschrijving, beide een string.

Wat verwacht je hier voor gemeentecode 0518 (Den Haag), moet dat worden opgegeven als integer 518 en door de provider vertaald naar string "0518" bij het zoeken?

**Comment by JohanBoer** [comment]
In de gemeente-tabel is deze code met voorloopnullen gedefinieerd. De  code is in de gemeentetabel ook als alfanumeriek gedefinieerd. 

![image](https://user-images.githubusercontent.com/18071357/58246937-b5ab3080-7d58-11e9-8c02-cccd5593b773.png)
 
Deze code was dus onterecht als numeriek gedefinieerd. Dat pas ik aan.
