### ISSUE TITLE
ook specificeren http statuscode 503 service unavailable

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#236]
Er is nu een beperkt aantal http statuscodes gedefinieerd. Ook in de foutafhandeling.feature is een beperkt aantal fouten benoemd.

De situatie dat de API niet beschikbaar is, wordt nu niet ondervangen.

Bijvoorbeeld wanneer de API gebruik maakt van GBA-V en die geeft een storing, moet de API dit op de juiste manier communiceren naar de gebruiker.
Op dit moment is daarvoor alleen statuscode 500 internal server error gedefinieerd, maar eigenlijk is 503 service unavailable hier beter.

Moet dus code 503 niet worden toegevoegd aan de gespecificeerde responses?

**Comment by CathyDingemanse** [comment]
Eens, 503 graag toevoegen.

**Comment by fsamwel** [comment]
Ik heb het ook toegevoegd aan feature foutafhandeling. Wanneer die is gemerged kan issue gesloten worden

**Comment by fsamwel** [comment]
@JohanBoer deze moet ook nog worden doorgevoerd in de historische bevragingen
