### ISSUE TITLE
Namen van een aantal links zijn niet duidelijk

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#239]
Een aantal links heeft nu als naam de gerefereerde resource (in meervoud). Dat is (mijn mening) niet altijd duidelijk voor de gebruiker. O.a. ook omdat het een naam in meervoud is, ook wanneer het maar één voorkomen kan betreffen.

Dit betreft:
- bij ouders, kinderen en partners de link ingeschrevenpersonen
- bij ingeschrevenpersonen de link nummeraanduidingen

Dit is volgens mij oorspronkelijk zo gemodelleerd omdat de API strategie resourcenamen in meervoud vereist. Mijn interpretatie daarvan is dat dit niet betekent dat ook links naar resources dezelfde naam moeten hebben.

Ik pleit dus voor duidelijker link-namen in deze gevallen. 
In plaats van "nummeraanduidingen" stel ik voor "verblijfplaatsNummeraanduiding".

Heeft iemand een suggestie voor een duidelijker naam van de link naar de ingeschreven persoon die de ouder, het kind of de partner is?

Ook denk ik dat naast de link naar de nummeraanduiding ook een link naar de verblijfplaats (verblijfsobject, ligplaats of standplaats) in BAG toegevoegd zou moeten worden.

**Comment by fsamwel** [comment]
idem voor nummeraanduidingen in Bewoning. Dit is een onduidelijke naam, aangezien het maximaal om 1 nummeraanduiding kan gaan.

**Comment by CathyDingemanse** [comment]
Graag doorvoeren voor RC. @Melvin, lukt dit in een pull request n.a.v. https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/issues/250?

**Comment by CathyDingemanse** [comment]
Graag doorvoeren voor Release Candidate. @MelvLee lukt het om dit gelijk mee te nemen bij de pull request n.a.v. https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/issues/250?

**Comment by JohanBoer** [comment]
> Heeft iemand een suggestie voor een duidelijker naam van de link naar de ingeschreven persoon die de ouder, het kind of de partner is?

Hier is ik nog geen antwoord op. Daar is wel een suggestie voor nodig. Ik voer nu "isIngeschrevenPersoon" door. Indien er een andere naam gewenst is dan hoor ik dat graag.  

> Ook denk ik dat naast de link naar de nummeraanduiding ook een link naar de verblijfplaats (verblijfsobject, ligplaats of standplaats) in BAG toegevoegd zou moeten worden.

Vooralsnog heb ik via de PO geen indicatie dat er een afnemer aan deze informatie behoefte heeft, dus ik neem deze (nog) niet op. Als dit wel nodig blijkt te zijn voegen we alsnog toe. 

Samenvatting: 

- [ ] Bij ouder, kind en partner naam van de link = isIngeschrevenPersoon
- [ ] Bij nummeraanduidng bij ingeschrevenpersonen = verblijfplaatsNummeraanduiding
- [ ] Bij historie wordt nummeraanduidingen bij bewoning = nummeraanduiding.

**Comment by fsamwel** [comment]
@JohanBoer dit issue staat in review, maar ik zie de wijzigingen nog niet in de OAS. Komt dat nog?

**Comment by JohanBoer** [comment]
Die staan in de pull request die ik nog open heb staan.

**Comment by gertjanvanderkooij** [comment]
Is niet altijd een ingeschreven persoon ... isPersoon?

**Comment by CathyDingemanse** [comment]
Jawel toch Gert-Jan? Dit is nu juist wel altijd de ingeschreven persoon. Anders is de link er niet, omdat er dan alleen een subresource is.

**Comment by gertjanvanderkooij** [comment]
Negeer mijn opmerking maar, blackout ... ;-) 

Ik maal nog even op suggestie naam.

**Comment by fsamwel** [comment]
@JohanBoer kan je ook de link in Reisdocument_links willen aanpassen naar ingeschrevenPersoon? Dan is het consistent met de andere links.

**Comment by fsamwel** [comment]
@JohanBoer om consequent te blijven: in Reisdocument_links heet het ingeschrevenpersooon, in de anderen (bijv. Ouder_links) heet het ingeschrevenPersoon.

Het is maar een hoofdletter/kleine letter verschil, maar toch.

**Comment by fsamwel** [comment]
@JohanBoer zie vorige opmerking. De links heten nu ingeschrevenpersooon i.p.v. ingeschrevenPersoon.  Er is dus geen camelCase meer toegepast op de attribuutnaam.

Kunnen we dit nog aanpassen?

**Comment by JohanBoer** [comment]
> Er is dus geen camelCase meer toegepast op de attribuutnaam.

Dit is niet recent gewijzigd, maar ik ben het met je eens dat het vreemd is dat hier geen camelCase is toegepast. Dit kan (en zal) ik voor de releasecandidate nog aanpassen

**Comment by fsamwel** [comment]
@JohanBoer de links in bewoning zijn nog niet aangepast:
Bewoning_links:
        ingeschrevenpersonen ---> ingeschrevenPersoon
HoofdBewoner_links:
        ingeschrevenpersonen ---> ingeschrevenPersonen (camelCase toepassen)
