### ISSUE TITLE
Versienummer in url

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#240]
Conform de API/URI strategie zit er nu in de url van de API het versienummer.

Eerder hebben we hierover een discussie gevoerd, omdat verwijzingen tussen basisregistraties niet makkelijk zullen werken wanneer het versienummer in de url zit.
Dit betekent namelijk:
- dat basisregistraties de actuele versies van api's bij andere basisregistraties moeten bijhouden
- dat clients links krijgen naar resources in een versie van een api die ze mogelijk (nog) niet ondersteunen

Zie ook https://github.com/Geonovum/KP-APIs/issues/7

In de URI strategie (ik kijk in de versie van 12 maart) staat (§2.10):

> Er zijn een verschillende strategieën die gebruikt kunnen worden om te versioneren. Deze strategieën zijn toepasbare op zowel SOAP web services als REST API’s.
> 1. Een versienummer toevoegen aan de URI;
> 2. Een versienummer toevoegen aan de payload; 
> 3. Een eigen request header gebruiken; of
> 4. Toevoegen aan de HTTP Accept Header.

In de opbouw van de Uri's is nu gekozen voor optie 1. Gezien dit issue lijkt me opties 3 of 4 beter aansluiten. 

Vraag voor het project: hoe gaan we hier nu, zolang de API werkgroep nog geen keuze heeft gemaakt, mee om voor onze API?

**Comment by CathyDingemanse** [comment]
Voorstel van Jasper is om zelf het initiatief te nemen voor een werkgroepje dat hier aan werkt en een gedragen voorstel doet. Ik voel daar wel voor vanwege de controle op het tempo en actieve sturing.

**Comment by CathyDingemanse** [comment]
Melvin heeft inmiddels een analyse gedaan, zie https://github.com/Geonovum/KP-APIs/issues/157 .
@JohanBoer, zou jij de versienummer uit de URL willen halen? De header is al aanwezig in de response. Zou jij met Melvin de mogelijkheid willen implementeren voor de consumer om een versie in de request mee te geven?

**Comment by fsamwel** [comment]
de request header voor de gevraagde versie heet (volgens de [api strategie](https://geonovum.github.io/KP-APIs/#versioning)) api-version, identiek aan de gelijknamige response header

**Comment by JohanBoer** [comment]
Dank voor het uitzoekwerk Frank. Die ga ik morgen dan toevoegen.
