### ISSUE TITLE
Als waterschap/gemeente wil ik voorletters ter beschikking hebben voor correspondentie en visualisatie

### ISSUE THREAD

**Issue by KayodeBakker** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#241]
...zodat een overzichtelijk naamgeving kan worden samengesteld dat netjes en correct is.

Wij, bij Processfive, hebben bij een waterschap op dit moment een implementatie van BRP bevragen draaien met als bron de GbaV service van Vertrouwd Verbonden. Hieruit is de wens ontstaan voor het kunnen ontsluiten van voorletters. Beide de GbaV als de BRP bevragen specs hanteren geen voorletters.

De input die is gegeven is als volgt:

* Personen worden voor diverse processen direct aangeschreven. Dit veelal niet met de gehele aanschrijfwijze omdat dit een beetje ouderwets is en de volledige aanschrijfwijze niet altijd volledig in een venster van een envelop past (denk aan: meerdere voornamen). De waterschap stuurt brieven (ook digitaal), altijd voorzien van voorletters, dit is hun standaard template;
* Ditzelfde voor de visualisatie in de Persoonlijke Internetpagina’s (PIP) en e-formulieren. Een lange reeks voornamen / de hele aanschrijfwijze resulteert soms in meerdere regels onder elkaar waardoor de pagina een stuk meer minder netjes over komt.

Wij verwachten dat meerdere overheidsorganisaties hier behoefte aan hebben. Zeker omdat de stufbg prefill standaard haar afnemers wel voorziet in voorletters (als afgeleide van de voornamen) en deze bij veel gemeenten in gebruik is voor Zaak-, DMS systemen, de PIP en e-formulieren.

Nu staat in de feature voor aanschrijfwijze het volgende:
  Attribuut aanschrijfwijze wordt samengesteld op basis van:
  * voornamen (wordt omgezet naar voorletters)
  * voorvoegselGeslachtsnaam
  * geslachtsnaam
  * voorvoegselGeslachtsnaam partner
  * geslachtsnaam partner
  * aanduidingAanschrijving
  * adellijkeTitel_predikaat

Echter is aanschrijfwijze hier niet altijd bruikbaar voor aangezien adellijkeTitel_predikaat hier dan weer ongewenst is en dus is er meer vraag naar een losse veld voor 'voorletters' waar de afnemende partij zelf kan bepalen welke velden er kan worden gebruikt en samengesteld.

**Acceptatiecriteria**
- [x] BRP bevragen specs krijgt een aanpassing waar het attribuut voorletters in opgenomen wordt.

**Definition of done**
- [ ] functionele specificatie
- [x] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by MelvLee** [comment]
Voorletters.feature toegevoegd
