### ISSUE TITLE
Als klant van gemeenten wil ik dat mijn voorletters in plaats van mijn geboortenamen automatisch kunnen worden ingevuld in e-formulieren en gepersonaliseerde "mijn"omgevingen

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#242]
...zodat mijn naam overzichtelijk wordt weergegeven.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [x] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
Ik voeg het element "Voorletters" toe aan de gegevensgroep naam. @Melvin, maak jij een BDD-feature waarin beschreven wordt hoe die voorletters afgeleid moeten worden van de voornamen. Die functionaliteit staat ook beschreven in de Feature "Aanschrijfwijze.

**Comment by fsamwel** [comment]
Het is nu zo geïmplementeerd dat ook in de naam van partners, ouders en kinderen het element voorletters is toegevoegd. Is dat ook de bedoeling?

**Comment by CathyDingemanse** [comment]
Jazeker! Denk aan toepassingen als verhuisformulieren (wie verhuist er mee?) etc.
