### ISSUE TITLE
Als developer wil ik dat de specifieke HAL-elementen losgekoppeld worden van de content in het JSON schema

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#250]
...zodat we andere JSON-serialisaties kunnen toepassen (JSON LD, Plain JSON XML op basis van YAML-components) 

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by fsamwel** [comment]
Volgens mij betekent dit dat de _links en _embedded elementen uit de normale componenten moeten worden gehaald. Deze worden dan toegevoegd in de HAL versie. Voor een niet-HAL versie moet dan wellicht iets anders worden toegevoegd om alsnog de links te krijgen.

```
    IngeschrevenPersoonHal:
      allOf:
        - $ref: '#/components/schemas/IngeschrevenPersoon'
        - type: "object"
          properties:
            _links:
              $ref: "#/components/schemas/IngeschrevenPersoon_links"
            _embedded:
              $ref: "#/components/schemas/IngeschrevenPersoon_embedded"
```

@MelvLee is dit ook hoe jij dit had bedacht?

**Comment by MelvLee** [comment]
@fsamwel, dit is inderdaad zoals ik het voor mij zie

**Comment by JohanBoer** [comment]
Voorstel gemaakt en aangeboden middel Pull request 374. Gaarne eerst grondige review alvorens goed te keuren.

**Comment by JohanBoer** [comment]
N.a.v. reacties van @MelvLee en @fsamwel bij de pull-request beloten om de plain json variant nu niet door te voeren en alleen het splitsen van de HAL-specifieke elementen door te voeren.

**Comment by fsamwel** [comment]
@JohanBoer is dit issue niet afgehandeld? Of moet hier nog iets voor gedaan worden?

**Comment by JohanBoer** [comment]
Ja, kan met de merge die ik giseren gedaan heb in review gezet worden (en is gereviewed in de pull request). Kan naar done.
