### ISSUE TITLE
Als PO wil ik een API lab 

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#252]
...zodat het team input van gebruikers kan ophalen.

**Acceptatiecriteria**
- voor de zomervakantie (6 juli regio zuid)
- werkende provider beschikbaar

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JanWillemKooi** [comment]
Telefonisch contact gehad met Cathy. Het voorstel is om dit als 1 dag event te organiseren op basis van de reeds bestaande provider implementatie van een van de leveranciers. Beste week is week 27 (de week van 1 juli bijvoorbeeld op woensdag 3 of donderdag 4 juli)
Jan Willem zoekt contact met @wishalg over hoe dit het beste uitgevoerd kan worden.
