### ISSUE TITLE
inclusiefverledenpersonen parameter van bewoningen

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#255]
ik zie in de YAML:
_inclusiefverledenpersonen_ indien true worden overleden personen opgenomen in het zoekresultaat.

Overleden personen moeten standaard in het resultaat van bewoningen worden opgenomen tot aan het moment van overlijden. Na deze datum mogen ze niet meer in het resultaat voorkomen (anders dan in de GBA!). 

De inclusiefverledenpersonen parameter graag weghalen.

**Comment by fsamwel** [comment]
Is dan de groep overlijden van bewoners niet ook overbodig? Of moet dit de actuele gegevens van de bewoners weergeven?

Kan dus bijvoorbeeld dit:
```
        "_embedded": {
          "bewoners": [
            {
              "geldigTotEnmet": {
                "dag": "15",
                "datum": "2019-04-15",
                "jaar": "2019",
                "maand": "04"
              },
              "overlijden": {
                "overlijdensdatum": {
                  "dag": "28",
                  "datum": "2019-06-28",
                  "jaar": "2019",
                  "maand": "06"
                }, 
                ...
            }
            ...
          ]
        }
```

**Comment by CathyDingemanse** [comment]
bespreken op 5 juli.

**Comment by gertjanvanderkooij** [comment]
Naar mijn mening niet overbodig. Zodra we zoeken op peildatum mogelijk maken is het wel handig om te weten dat persoon inmiddels (in het nu) is overleden. Ik zou de groep om die reden handhaven.

**Comment by JanWillemKooi** [comment]
Update nav BRP projectoverleg 23 aug: 
Na discussie: Overleden personen moeten alleen worden meegenomen in het resultaat tot aan de datum waarop deze persoon in overleden. 
Bij nadere analyse: alleen de namen en BSN meegeven, 
verwijderen overlijden, burgerlijke staat,   
In de groep naam gaat weg: adelijke titlel predikaat
en geboortedatum en de aanschijfwijze  komt er bij.

**Comment by JohanBoer** [comment]
Volgens mij was de afspraak dat al er de wens was om de aanschrijfwijze of de geboortdatum te gebruiken voor inhoudelijke business-processen, dan wordt de gebruiker geacht de ingschreven personen waarvoor dat gewenst is op te halen. 

Ik heb dus geboortdatum en aanschrijfwijze niet toegevoegd. 

@CathyDingemanse  en @gertjanvanderkooij  : Is dat correct ?

**Comment by CathyDingemanse** [comment]
Akkoord om aanschrijfwijze niet mee te nemen. Geboortedatum wel meenemen, want dat is erg identificerend. Personen met dezelfde naam en voorletters (ouders en kinderen) zijn anders erg lastig uit elkaar te halen.

**Comment by fsamwel** [comment]
@JohanBoer leeftijd zit er ook nog in. Moet die er niet uit? (is niet identificerend)

**Comment by JohanBoer** [comment]
> Moet die er niet uit? (is niet identificerend)

Doe ik.
