### ISSUE TITLE
Als developer of tester wil ik bij een nieuwe versie eenvoudig exact kunnen zien welke delen in de specificaties gewijzigd zijn

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#261]
...zodat ik weet welke delen van mijn code en tests ik moet aanpassen.

Het is nu erg moeilijk te achterhalen wat er gewijzigd is aan specificaties in elke nieuwe commit aan de openapi.yaml. Dit komt omdat bij elke nieuwe versie de volgorde van elementen anders wordt. Hierdoor kan zowel GitHub als een lokale diff tool geen overzicht geven van de wijzigingen (het toont veel wijzigingen die eigenlijk geen wijziging zijn).

Dit wordt nog een beetje erger doordat de commits in GitHub meestal als omschrijving “Update openapi.yaml” hebben, zodat je daar ook weinig uit kunt concluderen.

Bijvoorbeeld de volgorde van parameters van /ingeschrevenpersonen, de volgorde van properties in IngeschrevenPersoon. Volgens GitHub zijn de parameters en properties met elke Commit gewijzigd, terwijl dit niet het geval is.

Voor (toekomstige) releases moet het voor leveranciers (met weinig moeite) duidelijk zijn wat precies de wijzigingen zijn in de specificaties. Alleen dat weet de developer in welke classes iets gewijzigd moet worden en weet de tester welke testgevallen aangepast moeten worden.
Ik bedoel dan niet release notes, maar gewoon direct in de spes kunnen zien welke stukken exact gewijzigd zijn. GitHub ondersteunt dit door het tonen van de diff per commit.

Op dit moment speelt dit issue al bij de implementatie in Den Haag, die tot nu toe gebaseerd is op de versie van 15 april, maar die nu de stap naar de laatste versie (11 juni) moet maken.

Is het niet mogelijk dat bij het genereren van de yaml er altijd een consequente volgorde wordt gebruikt? Maakt mij niet zoveel uit welke volgorde, bijvoorbeeld alfabetisch (maar liefst natuurlijk op een logische volgorde), als het maar met elke versie dezelfde volgorde is.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
Inmiddels is in de yaml-generator een vaste volgorde van elementen ingebouwd. Daarmee is de volgorde altijd gelijk en kunnen de verschillen middels een diff in beeld gebracht worden.

**Comment by fsamwel** [comment]
Zo te zien is de volgorde nu goed (alfabetisch, met required parameters bovenaan)
