### ISSUE TITLE
Landcode met voorloopnullen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#264]
In issue #202 is de description voor gemeentecode aangepast op het voorkomen van voorloopnullen (tekst "alleen natuurlijke getallen zonder voorloopnullen" is verwijderd)

In Land_tabel staat bij code nog dezelfde tekst. Ook voor de landcodes geldt dat dat eventuele voorloopnullen moeten worden opgenomen. Er worden altijd exact de codes gebruikt zoals die in tabel 34 staan.

N.B. dit is een iets minder groot issue dan bij gemeentecode, aangezien geen van de landcodes op dit moment begint met een 0. Maar het is niet correct, en heeft bovendien het risico dat developers onnodig code gaan schrijven om hiermee om te gaan (in de API nullen eraf halen, in de client nullen weer toevoegen)

**Comment by JohanBoer** [comment]
Description aanpassen

**Comment by JohanBoer** [comment]
tekst "alleen natuurlijke getallen zonder voorloopnullen" is verwijderd
