### ISSUE TITLE
zoeken op naam__voorvoegsel ook case-insensitive?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#271]
Zoeken op een aantal parameters is case-insensitive. Maar zoeken op naam__voorvoegsel is dat niet.
Technisch gezien is dat wellicht logisch (het is immers eigenlijk geen string maar een waarde uit een landelijke tabel). Maar functioneel lijkt me dat niet handig.

In de landelijke tabel komen veel voorvoegsel zowel in een hoofdletter variant (bijv. "Van der" en "Van Der") als in een kleine letter variant (bijv. "van der") voor. 
Iemand die zoekt op naam weet denk ik niet altijd zeker in welke case het voorvoegsel geschreven wordt.

Dus denk ik dat "van der" ook "Van der" en "Van Der" moet vinden.

**Comment by CathyDingemanse** [comment]
zoeken op naam__voorvoegsel ook case-insensitive? Ja absoluut!

**Comment by JohanBoer** [comment]
Aanpassen in de parameter-note van de betreffende parameter.
