### ISSUE TITLE
Zodat ik de eigenaren hiervan kan opzoeken

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#273]
...zodat [vul aan].

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
@CathyDingemanse Deze issue ontgaat mij een beetje. Kan jij beter beschrijven wat je hiermee bedoelt >

**Comment by CathyDingemanse** [comment]
Ik denk dat dit een typfoutje is, zou het nl ook niet weten :-). Ik sluit hem af!
