### ISSUE TITLE
Specifieke tabel components terugbrengen naar 1 generieke tabel 

### ISSUE THREAD

**Issue by MelvLee** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#281]
omdat dit scheelt in het aantal gegenereerde classes die dezelfde structuur hebben.

De tabel components (Gemeenten_tabel, Adellijketitel_predikaat_tabel, Land_tabel, Nationaliteit_tabel, Verblijfstitel_tabel, AutoriteitAfgifteNederlandseReisdocument_tabel, NederlandsReisdocument_tabel) hebben bijna allemaal dezelfde properties en dit zou naar 1 Tabel component kunnen worden teruggebracht met properties: code, naam, omschrijving

**Comment by CathyDingemanse** [comment]
Goed idee, doen!

**Comment by fsamwel** [comment]
Helemaal eens met Melvin. 

Een opmerking: Waarom naam én omschrijving? Dat is denk ik hetzelfde. Daar waar we nu proportie naam gebruiken in een tabel (gemeenten en landen), had dat eigenlijk ook omschrijving moeten zijn (althans zo heet het in de landelijke tabel).

We hebben een paar tabellen met uitzonderlijke definitie:
- voorvoegsels heeft één kolom (is daarom niet als tabel maar als string gedefinieerd
- adellijke titel/predikaat heeft drie kolommen, namelijk soort (gevuld met titel of predikaat)

Ik kan me niet zoveel voorstellen bij een businessbehoefte aan property soort hier. Deze is wel nodig voor samenstellen van de aanschrijfwijze, maar wat moet een client hiermee? Dus naar mijn idee (@CathyDingemanse klopt dit?) zou ook hier alleen code en omschrijving voldoende zijn.

**Comment by CathyDingemanse** [comment]
> ik kan me niet zoveel voorstellen bij een businessbehoefte aan property soort hier. Deze is wel nodig voor samenstellen van de aanschrijfwijze, maar wat moet een client hiermee? Dus naar mijn idee (@CathyDingemanse klopt dit?) zou ook hier alleen code en omschrijving voldoende zijn.

Ben het wel met je eens.

**Comment by JohanBoer** [comment]
Samenvattend: 
- [ ] Ik zorg ervoor dat al deze tabelverwijzingen naar 1 generieke waarde-tabel gaan verwijzen. 
- [ ] Ik documenteer bij het betreffende element welke tabel dat is  
- [ ] Ik documenteer ook dat de onbekend waarden uit die tabel niet geretourneerd hoeven te worden. 

Overigens is dat laatste waarschijnlijk een feature. Ik kan de inhoud van de tabellen niet manipuleren, dus er moet door de provider logica ingebouwd worden dat een geldige tabelwaarde die als omschrijving "onbekend" heeft niet wordt geretourneerd tenzij het over het geslacht gaat. 

Zie overigens ook de discussie bij #228 .Ik ben het in principe niet eens met het niet retourneren van onbekend waarden van tabellen. Cathy: wil jij op basis van de arguymenten als PO het eindoordeel vellen ?

**Comment by fsamwel** [comment]
> Ik documenteer bij het betreffende element welke tabel dat is

@JohanBoer hoe ga je dat doen? Je kan niet zowel een $ref naar de generieke tabel-component doen én een eigen description voor het element. Gebruik van een standaard element heeft als nadeel dat de specifieke elementen geen eigen beschrijving krijgen. Dat is nu ook het geval bij alle datums.

**Comment by MelvLee** [comment]
In [de volgende issue in de OpenAPI specification repo](https://github.com/OAI/OpenAPI-Specification/issues/556#issuecomment-192007034) geeft men aan dat je dit kan oplossen door gebruik te maken van allOf keyword.
Ik heb dit geprobeerd en zowel Swagger Editor als Swagger Hub accepteren deze constructie
Echter de Swagger code generatoren niet. Zowel de door Swagger gegenereerde .NET en Java code bevat fouten. Met NSwagStudio kan wel correcte code worden gegenereerd.
Helaas is dit dus (nog) geen oplossing voor het description probleem 

Is het een idee om de documentatie van dit soort properties op te nemen in de documentatie van het object zelf? En indien gewenst een link opnemen naar een  pagina met uitgebreide documentatie.

**Comment by fsamwel** [comment]
> Is het een idee om de documentatie van dit soort properties op te nemen in de documentatie van het object zelf?

@JohanBoer kan jij dit doen? Wellicht eerst handmatig, zodat we kunnen beoordelen of dit inderdaad de gewenste oplossing is?

**Comment by fsamwel** [comment]
Naast adellijke titel/predikaat hebben we nog een tabel met meer dan 2 kolommen: 
Tabel 37 Reden opnemen/beëindigen nationaliteit (RedenVerkrijgingOpnemen_beeindigenNationaliteit_tabel)

Deze heeft de kolom (property) soort:
VK - verkrijging
OP - opname
VL - verlies
BE - beëindiging

@CathyDingemanse kan deze ook vervallen? Is er in processen behoefte aan te weten of de nationaliteit verkregen dan wel opgenomen is?

**Comment by gertjanvanderkooij** [comment]
@MelvLee Mechanisme van één code/omschrijving-tabel passen wij intern ook regelmatig toe. 
1) Hier voegen wij dan ook de DatumIngang/DatumEinde geldigheid toe. Is dit aan consumer-zijde nog van belang? 
2) Zijn er al gedachten hoe we deze tabel in sync houden met de GBA-tabellen cq. hoe komen consumers aan updates op deze tabellen?

**Comment by CathyDingemanse** [comment]
> Naast adellijke titel/predikaat hebben we nog een tabel met meer dan 2 kolommen:
> Tabel 37 Reden opnemen/beëindigen nationaliteit (RedenVerkrijgingOpnemen_beeindigenNationaliteit_tabel)
> 
> Deze heeft de kolom (property) soort:
> VK - verkrijging
> OP - opname
> VL - verlies
> BE - beëindiging
> 
> @CathyDingemanse kan deze ook vervallen? Is er in processen behoefte aan te weten of de nationaliteit verkregen dan wel opgenomen is?

Jazeker, er zijn meerdere afdelingen die dit nodig hebben. Hte document dat hieraan ten grondslag ligt en de gemeente waar dit document zich bevindt, is niet van belang totdat zich hiervoor een afnemer meldt.

**Comment by CathyDingemanse** [comment]
> > Is het een idee om de documentatie van dit soort properties op te nemen in de documentatie van het object zelf?
> 
> @JohanBoer kan jij dit doen? Wellicht eerst handmatig, zodat we kunnen beoordelen of dit inderdaad de gewenste oplossing is?

Dit hoeft dan toch niet meer gezien bovenstaand antwoord?

**Comment by JohanBoer** [comment]
Samenvattend : 
- [ ] Ik ga de tabelverwijzingen aanpassen naar 1 generieke tabeldefinitie (Code (string) en omschrijving (string) )

- [ ] Er wordt een feature geschreven waarin uitgelegd wordt dat onbekende waarden niet geretourneerd kunnen worden. 
 

- Voorvoegsel is als string gedefinieerd, dus er is geen verwijzing naar een tabel.
- Adellijke titel/predikaat-tabel wordt voor gebruik in deze API aangepast zodat de property "soort" vervalt.
- Reden opnemen/Beeindigen nationaliteit-tabel wordt voor gebruik in deze API aangepast zodat de property "soort" vervalt.

- [ ] De documentatie van de betekenis van de elementen kan niet meer uit een (betekenisvolle) tabelbeschrijving gehaald worden, dus die documenteer ik 1 niveau hoger, conform de datum_onvolledig oplossing. (zie #299)

**Comment by joeribekker** [comment]
@MelvLee Ik gebruik niet zo vaak code generatie tools maar het zijn uiteindelijk toch aparte tabellen en dus classes? Of wil je het in een generieke class hebben en dan op basis van het attribuut besluiten in/uit welke tabel het moet komen?

Zou bijv. `GemeenteTabel` niet als superklasse `WaardeTabel` moeten hebben. Zo voorkom je dubbeling van code maar behoud je de specifieke tabel classes.

**Comment by MelvLee** [comment]
Het zijn inderdaad aparte tabellen (bijv. gemeente, reden opname), maar wat van deze tabellen wordt ontsloten is alleen de code en omschrijving kenmerken/column. Het is dan niet nodig om voor elk van deze tabellen een specifieke resource te definieren.
In .NET (en ik denk ook in Java) maken we dan gebruik van ORM's of mappers om data uit tabellen te mappen naar de resource class
