### ISSUE TITLE
Gebruik maken van components/responses voor o.a. fout response specificaties

### ISSUE THREAD

**Issue by MelvLee** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#282]
zodat een fout response eenmalig kan worden gespecificeerd en meermalig kan worden hergebruikt. Dit verbetert volgens mij ook de leesbaarheid van de yaml

Voorbeeld:

components;
&nbsp;&nbsp;responses:
&nbsp;&nbsp;&nbsp;&nbsp;503:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;description: Service Unavailable
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;headers:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;api-version:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/headers.yaml#/api_version"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;content:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;application/problem+json:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;schema:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$ref: "https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/components.yaml#/Foutbericht"

En in een path referencen:

/ingeschrevenpersonen/{burgerservicenummer}/reisdocumenten:
&nbsp;&nbsp;get:
&nbsp;&nbsp;&nbsp;&nbsp;responses:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'503'
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;$ref: "#/components/responses/503"

**Comment by JohanBoer** [comment]
Gechecked en dit werkt. Dit ga ik doorvoeren. Eerst met de hand, maar dit eordt ook ingeschoten als issue op onze genereer-scripts. 
Ook voor parameters is een keyword gereserveerd en dat zou op dezelfde manier kunnen worden gedaan.
