### ISSUE TITLE
Als medewerker gebiedsontwikkeling wil ik eigenaren van woningen in een bepaald gebied gericht kunnen aanschrijven (op naam)

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#285]
...zodat ik hen bij gebiedsontwikkeling kan betrekken.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
Ik neem haast aan dat deze user-story bij de bevraging Kadastraal Onroerende zaak thuis hoort. Anders heb ik wat toelichting nodig.

**Comment by CathyDingemanse** [comment]
> Ik neem haast aan dat deze user-story bij de bevraging Kadastraal Onroerende zaak thuis hoort. Anders heb ik wat toelichting nodig.

Klopt! wordt verplaatst!
