### ISSUE TITLE
verkeerde beschrijving aanduiding Europees Kiesrecht

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#295]
# Impediment

> aanduidingEuropeesKiesrecht | AanduidingEuropeesKiesrecht_enumstringDe mogelijke waarden van de aanduiding van inhouding of vermissing van een Nederlands reisdocument. Zie logisch ontwerp BRP bij de stamtabellen:1 - persoon is uitgesloten2 - persoon ontvangt oproepEnum:Array [ 2 ] -- | --

de beschrijving: 

> De mogelijke waarden van de aanduiding van inhouding of vermissing van een Nederlands reisdocument 

moet worden verwijderd, maar gaat in een moeite door met #296

**Comment by JohanBoer** [comment]
In de versie die nu op GitHub staat zie ik alleen de correcte beschrijving. Waarschijnlijk eerder al aangepast en met een andere wijziging meegekomen.

**Comment by CathyDingemanse** [comment]
Sorry maar is nog steeds onjuist.
