### ISSUE TITLE
Als PO wil ik een gebruikersvriendelijke API die informatie over kiesrecht eenduidig overbrengt  

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#296]
...zodat evt. interpretatieverschillen en registratieverschillen in de bron door de provider kunnen worden opgelost, ipv consumers hier mee op te zadelen.

**Acceptatiecriteria**
- [ communicatie  over kiesrecht en Europees kiesrecht is eenduidig ]
- [ consumer kan geen tegenstrijdige informatie ontvangen]

**Definition of done**
- [ ] Open API specificatie
- [ ] gegenereerde code

Voorstel: de huidige LO GBA rubrieken en elementen vervangen door:

- Kiesrecht: true or false (boolean)
true: persoon ontvangt oproep
false: persoon is uitgesloten

- Einddatum uitsluiting kiesrecht: onvolledige datum 
description: de datum waarop een uitsluiting kiesrecht niet meer van toepassing is als er sprake is van uitsluiting voor bepaalde tijd.  
Let op! geen volledig onbekende datums en 00000000 waarden! Er wordt alleen een einddatum uitsluiting kiesrecht meegegeven als deze bekend is. 

- Europees Kiesrecht: true or false (boolean)
true: persoon ontvangt oproep
false: persoon is uitgesloten

- Einddatum uitsluiting Europees kiesrecht: onvolledige datum 
description: de datum waarop een uitsluiting voor deelname aan verkiezingen voor het Europees parlement niet meer van toepassing is, als er sprake is van uitsluiting voor bepaalde tijd.  
Let op! geen volledig onbekende datums en 00000000 waarden! Er wordt alleen een einddatum uitsluiting kiesrecht meegegeven als deze bekend is. 

De volgende gegevens uit LO GBA kunnen waardevol zijn voor een burger zelf die wil weten hoe de toekenning kiesrecht is verlopen:
31.20 Datum verzoek of mededeling Europees kiesrecht (een verklaring voor van Nederlanders in het buitenland dat zij niet in een ander land al deelnemen aan de Europese verkiezingen of registratieverzoek voor inwoners van Caraibisch Nederland) 
82.10 Gemeente waar de gegevens over kiesrecht aan het document ontleend zijn (waar kan ik verhaal halen?)
82.20 Datum van de ontlening van de gegevens over kiesrecht (wanneer is de toekenning gebeurd?)
82.30 Beschrijving van het document waaraan de gegevens over kiesrecht ontleend zijn (op basis van welk verzoek, verklaring of het ontbreken daarvan is kiesrecht toegekend of ontnomen)

Voor deze gegevens hebben zich echter nog geen afnemers gemeld, ik hoor het graag!! 
Stel voor om deze gegevens nu nog niet op te nemen, en ze evt. later toe te voegen als er behoefte aan is.

**Comment by CathyDingemanse** [comment]
Het lijkt er op dat het LO is gemaakt ten behoeve van een juiste registratie, niet voor communicatie ten behoeve van gebruik. Deze wijziging is gedaan ter voorkoming van "provider perspective" waarbij een heleboel gegevens worden gecommuniceerd die vooral te maken hebben met de juistheid van de registratie (denk aan de datum waarop een persoon een verklaring afgeeft dat hij/zij niet in een ander Europees land stemt), maar die voor een afnemer niet relevant is.

**Comment by gertjanvanderkooij** [comment]
Zie eerdere opmerking over vastleggen van ontwerpbeslissingen ResourceModel API vs. inhoud LO GBA.

Volgende acties zie ik:
1) Controle of dit concept (in communicatie domeinwaarde vertalen naar boolean) ook voor andere gegevens van toepassing is
2) Specificatie opstellen voor provider-implementatie in welke gevallen de boolean aan/uit staat. Samenhang met element Datum einde.
3) Check op GBA-V autorisaties ... voor gemeente als GABA geen autorisatie voor Kiesrecht opgenomen; voor gemeente 'Burgerzaken-taken' geen autorisatie Europees (mmm ...). Verkiezingsproces verloopt via lokale GBA. 
4) Welke afnemer gebruikt Kiesrecht-gegevens?

**Comment by JohanBoer** [comment]
Nu gespecificeerd zoals in de eerste comment door PO is aangegeven. Cathy, zie jij kans om op Gert Jan's comment te reageren ?

**Comment by CathyDingemanse** [comment]
> Zie eerdere opmerking over vastleggen van ontwerpbeslissingen ResourceModel API vs. inhoud LO GBA.
> 
> Volgende acties zie ik:
> 
> 1. Controle of dit concept (in communicatie domeinwaarde vertalen naar boolean) ook voor andere gegevens van toepassing is

OK, hebben we zoveel mogelijk geprobeerd. Zou jij de API ook nog eens met een dergelijke blik willen beoordelen?

> 2. Specificatie opstellen voor provider-implementatie in welke gevallen de boolean aan/uit staat. Samenhang met element Datum einde.
Will do, @MelvLee, wil je hier een feature voor schrijven? 

> 3. Check op GBA-V autorisaties ... voor gemeente als GABA geen autorisatie voor Kiesrecht opgenomen; voor gemeente 'Burgerzaken-taken' geen autorisatie Europees (mmm ...). Verkiezingsproces verloopt via lokale GBA.
Klopt

> 4. Welke afnemer gebruikt Kiesrecht-gegevens?
In de gemeente Den Haag: afdelingen van Burgerzaken, of gerelateerd aan Burgerzaken (helpdesk, onderzoeksafdelingen, beheerders)

**Comment by fsamwel** [comment]
@MelvLee 
> Will do, @MelvLee, wil je hier een feature voor schrijven?

ik kan deze feature niet vinden. Had je deze al gemaakt?

**Comment by MelvLee** [comment]
@fsamwel Ik heb deze feature nog niet gemaakt. Ik zal dat vanmiddag doen

**Comment by fsamwel** [comment]
De oplossing en feature doet nu aannames en uitspraken over kiesrecht die mogelijk niet terecht zijn:
- ook minderjarige personen, overleden personen en personen met niet-Europese nationaliteit krijgen kiesrecht: true; dit suggereert dat deze personen wel kiesrecht hebben: persoon ontvangt oproep
- gedeeltelijk onbekende einddatum uitsluiting wordt nu niet opgenomen. Bijvoorbeeld einddatum uitsluiting=20180000 levert volgens feature kiesrecht: false en geen einddatum uitsluiting. ik zou hier verwachten kiesrecht: true en geen einddatum uitsluiting (ligt immers in het verleden)

Afgesproken met Cathy dat zij featue aanpast. We moeten geen aannames doen over kiesrecht.

**Comment by CathyDingemanse** [comment]
Voortschrijdend inzicht leert dat we het beoogde doel op dit moment met deze bron gewoon niet kunnen waarmaken. 
@fsamwel, maak jij de feature?
@JohanBoer, graag OAS aanpassen:
bij nationaal (dus niet bij Europees kiesrecht) kiesrecht:
- attribuut kiesrecht true/false verwijderen
- uitsluiting van kiesrecht toevoegen, wel graag een boolean van maken.
