### ISSUE TITLE
Als PO wil ik een beschrijving van het Burgerservicenummer zonder implementatiedetails van de provider

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#297]
...zodat de API alleen voor gebruikers relevante informatie levert.

**Acceptatiecriteria**
- [geen implementatiedetails van de provider in de beschrijving van het BSN}

**Definition of done**
- [ ] Open API specificatie

De description is nu

> Het burgerservicenummer, bedoeld in artikel 1.1 van de Wet algemene bepalingen burgerservicenummer. Element 01.20 Het burgerservicenummer, bedoeld in artikel 1.1 van de Wet algemene bepalingen burgerservicenummer. Alle nummers waarvoor geldt dat, indien aangeduid als (s0 s1 s2 s3 s4 s5 s6 s7 s8), het resultaat van (9s0) + (8s1) + (7s2) +...+ (2s7) - (1*s8) deelbaar is door elf. Er moeten dus 9 cijfers aanwezig zijn.

de description moet worden:

> Het burgerservicenummer, zoals bedoeld in artikel 1.1 van de Wet algemene bepalingen burgerservicenummer. Een burgerservicenummer bestaat uit 9 cijfers en is, indien aangeduid als (s0 s1 s2 s3 s4 s5 s6 s7 s8), het resultaat van (9s0) + (8s1) + (7s2) +...+ (2s7) - (1*s8) deelbaar door elf.

**Comment by fsamwel** [comment]
@CathyDingemanse Welke implementatiedetails bedoel je hier? 

In de nieuwe descriptie is verwijzing naar het element in LO GBA weggehaald. Ik denk dat verwijzen naar het LO GBA element handig is, want daarmee is er een verwijzing naar een breed gebruikt en bekend gegevensmodel, waarmee voor veel gebruikers de betekenis direct duidelijk is.

De beschrijving van de 11-proef staat er ook nog is, maar die lijkt me voor clients dan weer niet zo relevant. Zij moeten het ontvangen burgerservicenummer namelijk gewoon overnemen (hoeven denk ik geen 11-proef te doen over response van de API).

**Comment by CathyDingemanse** [comment]
> De beschrijving van de 11-proef staat er ook nog is, maar die lijkt me voor clients dan weer niet zo relevant. Zij moeten het ontvangen burgerservicenummer namelijk gewoon overnemen (hoeven denk ik geen 11-proef te doen over response van de API).

De BSN is ook een zoekargument/ queryparameter die een afnemende applicatie indien gewenst kan valideren.

**Comment by CathyDingemanse** [comment]
> In de nieuwe descriptie is verwijzing naar het element in LO GBA weggehaald. Ik denk dat verwijzen naar het LO GBA element handig is, want daarmee is er een verwijzing naar een breed gebruikt en bekend gegevensmodel, waarmee voor veel gebruikers de betekenis direct duidelijk is.

Dat klopt, maar dat wil niet zeggen dat dat altijd zo blijft. Misschien wil de provider van deze API wel langzaam allerlei wijzigingen doorvoeren in de bron, of migreren naar een ander model. Hoe minder implementatiedetails die niet relevant zijn voor een afnemer, hoe simpeler en des te kleiner de kans op breaking changes. Daarnaast kunnen de waarden, wanneer zij rechtstreeks zijn ontleend aan het LO GBA ook zonder elementnummers, standaardwaarden e.d. worden opgezocht.
