### ISSUE TITLE
Als PO wil ik een juiste en gebruikersvriendelijke beschrijving van "indicatie geheim"

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#298]
...zodat de API juiste en bruikbare informatie verstrekt 

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen
In de yaml staat nu:

> indicatieGeheim
 | booleantitle: indicatieGeheimIndicator die aangeeft of het corresponderende gegeven voor deze persoon in onderzoek is. redenOpschortingBijhouding: $ref:
-- | --

de beschrijving gaat over in onderzoek :-), dat is sowieso niet correct.

Moet worden: geheimhoudingPersoonsgegevens (boolean)
description true: op verzoek van deze persoon is het verstrekken van gegevens over deze persoon aan bepaalde derden niet toegestaan.

**Comment by fsamwel** [comment]
@JohanBoer de description bevat “j(a)” of leeg. Zou je die hieruit willen verwijderen?
