### ISSUE TITLE
Als PO mis ik gegevens over de reden van opschorting en een duidelijke toelichting

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#299]
...zodat ik invulling kan geven aan de stories van o.a. medewerkers ondermijning (Gitlab).

**Acceptatiecriteria**
- [ OAS spec is aangevuld met een bruikbare reden opschorting]
- [ OAS spec is aangevuld met een duidelijke en bruikbare toelichting]

**Definition of done**
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

Er is nu geen description voor datum opschorting.
Deze moet zijn: 
"De datum waarop de bijhouding van de persoonsgegevens is gestaakt."

Vervolgens moet de reden opschorting worden toegevoegd:

Omschrijving reden opschorting bijhouding 
Description: de reden waarom de bijhouding van de persoonsgegevens is gestaakt. 
Enumeratie
Mogelijke waarden:
O (= overlijden) 
E (= emigratie) 
M (= Ministerieel besluit) 
R (= persoonsgegevens opgenomen in de RNI) 
F (= fout) 

Description M = Ministerieel besluit: de melding van de Minister van Buitenlandse Zaken dat personen die als ingezetene in de GBA zijn ingeschreven, niet langer als ingezetene behoren te zijn ingeschreven. Daarbij moet gedacht worden aan personen met een diplomatieke status en aan geprivilegieerden. De ontvangst van een ministerieel besluit wordt behandeld als een emigratie naar een onbekend land. 

De gegevens wordt NIET geretourneerd indien onbekend.

**Comment by JohanBoer** [comment]
- [ ] Oplossing voor dit specifieke geval is een tussen niveau "OpschortingBijhouding" introduceren en in de desription van deze "groep" nemen we de beschrijvingen van de elementen op die gebruik maken van een REF. 
- [ ] Niet vergeten de elementnamen te wijzigen.
- [ ] API doorlopen op vergelijkbare situatie 
- [ ] Alle elementen die niet onder de bovenstaande situatie vallen daar wordt de beschrijving op het hogere groepsniveau of resource niveau opgenomen
