### ISSUE TITLE
Als PO wil ik geen implementatiedetails van de provider verstrekken bij gegevens over de ingeschreven persoon

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#301]
...zodat de gebruiker alleen krijgt wat hij nodig heeft.

**Acceptatiecriteria**
- descriptions zonder elementnummers, standaardwaardes, onbekend waardes etc. 

**Definition of done**

- [ ] aangepaste open API specificatie
- [ ] gegenereerde code

Nu staat bij de description van geslachtsnaam: 

> De (geslachts)naam waarvan de eventueel aanwezige voorvoegsels en adellijke titel/predikaat zijn afgesplitst. Element 02.40 De (geslachts)naam waarvan de eventueel aanwezige voorvoegsels (tabel 36) en adellijke titel/predikaat (tabel 38) zijn afgesplitst. Standaardwaarde . Mogelijke waarden De geslachtsnaam. Standaardwaarde indien onbekend.

"Element 02.40", "Mogelijke waarden De geslachtsnaam" en "Standaardwaarde indien onbekend" zijn implementatiedetails van de bron waar een consumer geen boodschap aan heeft. Deze, en andere implementatiedetails komen op veel plaatsen voor. 

Graag alle toelichtingen van onderstaande gegevens veranderen in:

- Kiesrecht:
Gegevens over het kiesrecht van de ingeschrevene.

- Geslachtsnaam: 
De (geslachts)naam waarvan de eventueel aanwezige voorvoegsels en adellijke titel/predikaat zijn afgesplitst. 

- voorvoegsel
Dat deel van de geslachtsnaam dat voorkomt in de Voorvoegseltabel en, gescheiden door een spatie, vooraf gaat aan de rest van de geslachtsnaam.

- adellijke titel en predikaat:
geen description bij tabelwaarde.
Bij de code:
de code van de Adellijke titel of het predikaat
Bij de omschrijving:
de omschrijving van de adellijke titel of het predikaat.
 
- aanschrijfwijze:
Samengestelde naam zoals die in communicatie met de persoon gebruikt kan worden. De samenstelling is beschreven in de _functionele specificaties_

- nationaliteit
Gegevens over een nationaliteit van de ingeschreven persoon

- aanduiding bijzonder Nederlanderschap
Een aanduiding die of aangeeft dat de ingeschrevene behandeld wordt als Nederlander, of dat door de rechter is vastgesteld dat de ingeschrevene niet de Nederlandse nationaliteit bezit.

- nationaliteit tabelwaarde 
code
Een code die aangeeft welke nationaliteit de ingeschrevene bezit.

**Comment by JohanBoer** [comment]
Waarom verwijderen we deze informatie voor de consumers-ontwikkelaars ? We laten optimaal zien welke gegevens uit het LO GBA we bedoelen en daarmee weten de consumer-ontwikkelaars ook wat ze binnen hun applicatie met die gegevens moeten of kunnen doen. Als we de categorie-benaming weghalen is er ruimte (en misschien wel noodzaak) voor consumers-onbtwikkelaars om te interpreteren. Mijn advies is om de verwijzing naar de categorie uit het LO-GBA te handhaven. 

Het is een tijdrovende klus geweest om deze verwijzingen aan te brengen en het kost ook tijd om deze overal te verwijderen. Dat is op zich geen reden om de verwijzingen te handhaven, maar ik wil wel graag zeker weten dat we de goede beslissing nemen.

**Comment by gertjanvanderkooij** [comment]
Eens met Johan. Interpretatie zal de provider zelf ook willen voorkomen. Voor nu zo laten en meenemen in overleg met RvIG.

**Comment by CathyDingemanse** [comment]
> Waarom verwijderen we deze informatie voor de consumers-ontwikkelaars ? We laten optimaal zien welke gegevens uit het LO GBA we bedoelen en daarmee weten de consumer-ontwikkelaars ook wat ze binnen hun applicatie met die gegevens moeten of kunnen doen. Als we de categorie-benaming weghalen is er ruimte (en misschien wel noodzaak) voor consumers-onbtwikkelaars om te interpreteren. Mijn advies is om de verwijzing naar de categorie uit het LO-GBA te handhaven.
> 
> Het is een tijdrovende klus geweest om deze verwijzingen aan te brengen en het kost ook tijd om deze overal te verwijderen. Dat is op zich geen reden om de verwijzingen te handhaven, maar ik wil wel graag zeker weten dat we de goede beslissing nemen.

Ja, we nemen de goed beslissing.

**Comment by gertjanvanderkooij** [comment]
Eerder besloten om de BRP (LO GBA) als bron hanteren voor het ResourceModel 'Ingeschreven persoon'. 
Gezien de status van de BRP is zo'n 'tight coupling' tussen provider-implementatie en consumer dan niet zo vreemd. 

Als dit in het gebruik op te veel plekken gaat schuren (magische strings, omgaan met in onderzoek, standaardwaarden, geheel onbekende datums, onlogische plekken bepaalde elementen) en tot 'implementation bleed' leidt en 'de onafhankelijke ontwikkeling van de API in de weg staat' dan laten we ons vertrekpunt meer en meer los.

Het lijkt me goed dit met redenen omkleed vast te leggen in een apart document, zodat we dit straks met RvIG ('bron beheerder') kunnen afstemmen. In dit document dan wel de link te leggen met de betreffende rubrieknummers en LO-voorschriften; de werelden zo buiten de API om aan elkaar schrijvend en af te stemmen met de partij die de provider-implementatie uiteindelijk voor z'n rekening neemt en ter beschikking zal stellen aan haar afnemers (waaronder gemeenten). Hiervoor apart story opnemen.  

@CathyDingemanse @JohanBoer 
Hoe verloopt dit proces momenteel met Bevraging BRK? Komen we hier ook voor de consumer 'storende elementen' tegen? Worden deze op natuurlijke wijze opgelost, bv. omdat Kadaster direct betrokken is of is dit soms even flink afstemmen omdat de bronhouder voet bij stuk houdt?
