### ISSUE TITLE
definitie dag, maand, jaar als string of integer?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#304]
In /api-specificatie/Bevraging-Ingeschreven-Persoon/openapi.yaml#Datum_onvolledig zijn jaar, dag en maand gedefinieerd als string.
In /api-specificatie/components.yaml#Datum_onvolledig zijn jaar, maand, dag gedefinieerd als integer.

We gebruiken nu niet de definitie uit Components.yaml (waarom eigenlijk niet?). Beter zou deze definitie dan uit components.yaml verwijderd moeten worden, omdat er nu dus inconsistentie is met wat we in de API gebruiken.

Of is definitie van deze velden als integer beter?

**Comment by MelvLee** [comment]
Als developer heb ik voorkeur voor de integer versie. Als de datum niet is ingevuld, dan zal ik getal vergelijkingen moeten doen met jaar, maand en/of dag

**Comment by fsamwel** [comment]
@JohanBoer, kan je dit oplossen in de operapi.yaml?

**Comment by fsamwel** [comment]
@CathyDingemanse ben je het met me eens dat dit in de release candidate moet zijn opgelost?

**Comment by JohanBoer** [comment]
Frank, Melvin,

Aanpassing doorgevoerd, gaarne review op pull request. Definitie is als volgt geworden :  
 
    Datum_onvolledig:
      type: "object"
      description: "Gegevens over de datums die mogelijk niet volledig zijn, maar\
        \ waarvan de bekende gedeeltes wel moeten kunnen worden uitgewisseld. Als\
        \ de volledige datum bekend is worden alle elementen gevuld."
      properties:
        dag:
          type: "integer"
          title: "dag"
          description: "De dag. Als de dag van de datum bekend is wordt deze hier\
            \ ingevuld. Ook als de volledige datum bekend is."
          minimum: 1
          maximum: 31
          example: "5"
        datum:
          type: "string"
          title: "datum"
          description: "De volledige datum die in de `date` definitie past. Dit element\
            \ wordt alleen gevuld als de volledige datum bekend is."
          format: "date"
          example: "1989-05-03"
        jaar:
          type: "integer"
          title: "jaar"
          description: "Het jaar van de datum. Als het jaar bekend is wordt dit element\
            \ gevuld, ook als de volledige datum bekend is."
          maximum: 9999
          example: "1989"
        maand:
          type: "integer"
          title: "maand"
          description: "De maand. Als de maand van een datum bekend is wordt deze\
            \ hier ingevuld. Ook als de volledige datum is ingevuld."
          minimum: 1
          maximum: 12
          example: "3"

**Comment by CathyDingemanse** [comment]
> @CathyDingemanse ben je het met me eens dat dit in de release candidate moet zijn opgelost?

Ja!
