### ISSUE TITLE
Voorbeeldwaarden bij foutberichten in components.yaml komen niet overeen met feature

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#305]
De waarden in example bij de properties voor foutberichten (o.a. Foutbericht401) komen niet overeen met de verwachting volgens [feature foutafhandeling](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/master/features/foutafhandeling.feature)

Ook ontbreken voorbeelden voor property code, die ook zijn beschreven in de feature.

**Comment by JohanBoer** [comment]
Examples in de components.yaml aangepast.

**Comment by fsamwel** [comment]
@JohanBoer zou je dit ook willen doen voor het invalid-params deel van de 400 response:
```
{
  "type": "https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#/10.4.1 400 Bad Request",
  "title": "Ten minste één parameter moet worden opgegeven.",
  "status": 400,
  "detail": "The request could not be understood by the server due to malformed syntax. The client SHOULD NOT repeat the request without modification.",
  "instance": "https://datapunt.voorbeeldgemeente.nl/api/v1/resourcenaam?parameter=waarde",
  "code": "paramsRequired",
  "invalid-params": [
    {
      "type": "https://datapunt.voorbeeldgemeente.nl/api/v1/resourcenaam?parameter=waarde",
      "name": "parameternaam",
      "code": "string",
      "reason": "Mag alleen numeriek karakter bevatten"
    }
  ]
}
```

**Comment by JohanBoer** [comment]
Ik snap je verzoek niet Frank. Wat wil je dat ik aanpas ?

**Comment by fsamwel** [comment]
@JohanBoer je hebt in de basis van de berichten waarden gebruikt (in type, title, code) zoals die mogen voorkomen volgens de foutafhandeling feature.
In het stuk invalide-params heb je dat niet gedaan.

Het verzoek is dus dat je voor name een echte parameternaam gebruikt, voor code een code uit de foutafhandeling feature en de bijbehorende reason.

Bijvoorbeeld:
"invalid-params": [
    {
      "type": "https://www.vng.nl/realisatie/api/validaties/integer",
      "name": "verblijfplaats__huisnummer",
      "code": "integer",
      "reason": "Waarde is geen geldige integer."
    }
  ]
