### ISSUE TITLE
aanduidingBijHuisnummer ontbreekt in Bewoning

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#309]
In Bewoning zit geen property aanduidingBijHuisnummer.

Is dit een bewuste keuze (alleen opnemen BAG-adressen)?

**Comment by JohanBoer** [comment]
Dit is geen bewuste keuze. Ik heb aanduidingBijHuisnummer toegevoegd. 
Gaarne bevestigen of dit conform businesswens is.
