### ISSUE TITLE
inclusiefoverledenpersonen in /historie/bewoningen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#310]
Bij /historie/bewoningen is parameter inclusiefoverledenpersonen opgenomen. Is dit hier relevant?
Is het ooit relevant te weten welke personen op een adres waren ingeschreven na hun overlijden?

Dus volgens mij zou de standaard werking moeten zijn dat:
- overleden personen op een adres nooit als bewoner worden aangemerkt na hun overlijden
- overleden personen wel als bewoner worden aangemerkt voor de tijd dat ze nog wel leefden

Bijvoorbeeld iemand woonde op het gevraagde adres, maar is overleden op 15 april. Dan is de persoon bewoner tot (en met?) 15 april, en geen bewoner na (vanaf?) 15 april

**Comment by CathyDingemanse** [comment]
Dat had ik al opgemerkt, duplicaat met issue #255
