### ISSUE TITLE
parameter gemeentevaninschrijving en naamopenbareruimte ontbreekt bij /bewoningen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#311]
Voor /historie/bewoningen is geen parameter gemeentevaninschrijving gedefinieerd en geen parameter naamopenbareruimte. 

In de description van de operatie staat echter:
Op basis van de parameters wordt een meerdere bewoningen geretourneerd inclusief de bewoners van het betreffende verblijfplaats. Ten minste één van de volgende combinaties van parameters moet zijn opgenomen.

1. Postcode
verblijfplaats__postcode
verblijfplaats__huisnummer
2. NaamOpenbareRuimte
verblijfplaats__naamOpenbareRuimte
verblijfplaats__gemeentevaninschrijving
verblijfplaats__huisnummer
3. Nummeraanduiding
verblijfsplaats__nummeraanduiding

Er moet dus óf de description worden aangepast (optie 2 vervalt) óf er moeten parameters worden toegevoegd.

De description is bovendien onjuist, omdat hierin de parameternamen beginnen
met "verblijfplaats__".

**Comment by JohanBoer** [comment]
Inmiddels de parameters naamopenbareruimte en gemeentevaninschrijving toegevoegd en de description aangepast.

**Comment by fsamwel** [comment]
naamOpenbareruimte zit erin, gemeenteVanInschrijving niet. Dat is terecht.
