### ISSUE TITLE
Definitie van bewoners in bewoning wijkt af van definitie ingeschrevenpersonen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#313]
De definitie van Bewoners zoals die wordt gebruikt in Bewoning _embedded.bewoners wijkt op een aantal punten af van de definitie van ingeschreven personen. Een beperkte definitie begrijp is, toevoegen van geldigheidsdatums ook, maar een afwijkende definitie lijkt me niet wenselijk. 

Bijvoorbeeld:
- burgerlijkeStaat
- indicatieGeheim
- overlijden (datum, plaats, land)

**Comment by JohanBoer** [comment]
Door voortschrijdend inzicht ( dit is een best wel oude issue) wijkt de definitie van de bewoner volledig af van die van de ingeschreven persoon. Elementen die dezelfde betekenis hebben komen wel overeen.

**Comment by fsamwel** [comment]
@JohanBoer wat ik bedoel is dat zelfde eigenschappen opnieuw (en destijds anders, nu vooral dubbel) zijn opgenomen in de bewoners yaml dan in de ingeschrevenpersonen yaml.

Zie https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/issues/558#issuecomment-577689956:
- AanduidingBijHuisnummer_enum
- SoortAdres_enum
- Burgerservicenummer

In de bewoners kan hiervoor verwezen worden naar de ingeschrevenpersonen yaml.

Ook zou ik IngeschrevenPersoonHal in de bewoners hernoemen naar bijv. BewonerPersoonHal. Dan is er helemaal geen overlap meer in componenten tussen ingeschrevenpersonen en bewoners.

Aangezien dezelfde gegevens ook worden gebruikt via de bewoners[]._embedded.ingeschrevenPersoon levert dit in gegenereerde code dubbele componenten op. Bijv. Burgerservicenummer en Burgerservicenummer2.
