### ISSUE TITLE
Resource bewoners is niet gedefinieerd, maar er is wel link naar en embed van bewoners

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#314]
In het antwoord van /historie/bewoningen (Bewoning) zitten links naar bewoners en _embedded.bewoners met daarin _links.self.

Het is onduidelijk hoe de url in _embedded. bewoners[]._links.self eruit moet zien, of de url in _links.bewoners. Er is geen resource/operatie /bewoners/{uuid} gedefinieerd.

**Comment by JohanBoer** [comment]
Inmiddels ide link naar bewoners vervangen door een link naar de ingeschreven persoon.

**Comment by JohanBoer** [comment]
Ook de selflink bij de hoofdbewoner verwijderd. Wel een link naar de ingeschreven persoon bij de hoofdbewoner.

**Comment by CathyDingemanse** [comment]
> Ook de selflink bij de hoofdbewoner verwijderd. Wel een link naar de ingeschreven persoon bij de hoofdbewoner.

Hoofdbewoner graag verwijderen.
