### ISSUE TITLE
Properties ontbreken of zijn niet verwacht bij historie verblijfplaatsen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#316]
De response op /historie/ingeschrevenpersonen/{burgerservicenummer}/verblijfplaatsen (gedefinieerd in Verblijfplaats) bevat geen verblijfBuitenland. De bevraagde persoon kan in de gevraagde periode ook in het buitenland gewoond hebben.

Daarnaast zitten er enkele properties in het antwoord die ik niet had verwacht (minder logisch vindt hier):
- datumInschrijvingInGemeente
- datumVestigingInNederland
- landVanwaarIngeschreven

**Comment by gertjanvanderkooij** [comment]
> De response op /historie/ingeschrevenpersonen/{burgerservicenummer}/verblijfplaatsen (gedefinieerd in Verblijfplaats) bevat geen verblijfBuitenland. De bevraagde persoon kan in de gevraagde periode ook in het buitenland gewoond hebben.

Eens; verblijfBuitenland hier toevoegen
  

> Daarnaast zitten er enkele properties in het antwoord die ik niet had verwacht (minder logisch vindt hier):
>     * datumInschrijvingInGemeente
>     * datumVestigingInNederland
>     * landVanwaarIngeschreven

Evenals bij BevragingActueel wordt hier Categorie 08 van de GBA gevolgd. Is minder logisch (was in OperatieBRP ook anders gemodelleerd) maar zou ik voor nu zo houden. Gelijk aan ActueelBevraging.
