### ISSUE TITLE
inOnderzoek van bewoners

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#317]
Voor de bewoners bij /historie/bewoningen is er een element inOnderzoek voor de naam van de bewoners. Andere elementen kunnen dus blijkbaar niet in onderzoek worden aangegeven. Bijvoorbeeld wanneer de verblijfplaats zelf in onderzoek is.

**Comment by CathyDingemanse** [comment]
Zou jij met Vrien kunnen bespreken of historische gegevens actief worden onderzocht bij de afdeling onderzoek Burgerzaken?

**Comment by fsamwel** [comment]
@CathyDingemanse besproken met Vrien. Het is mogelijk dat een historisch voorkomen in onderzoek is.

**Comment by fsamwel** [comment]
ik denk dat daarnaast moet kunnen worden aangegeven wanneer de verblijfplaats in onderzoek is. Dan is dus niet een van de gegevens van de bewoner in onderzoek, maar de betreffende bewoning

**Comment by CathyDingemanse** [comment]
> ik denk dat daarnaast moet kunnen worden aangegeven wanneer de verblijfplaats in onderzoek is. Dan is dus niet een van de gegevens van de bewoner in onderzoek, maar de betreffende bewoning

Ik denk dat we bewoners/bewoning de in onderzoek functionaliteit van de verblijfplaatshistorie moeten hergebruiken.  Laten we dat doen, en dan bekijken of dat past.

**Comment by fsamwel** [comment]
@CathyDingemanse Hoe moet dit eruit zien?
> Ik denk dat we bewoners/bewoning de in onderzoek functionaliteit van de verblijfplaatshistorie moeten hergebruiken.

inOnderzoek voor verblijfplaatshistorie is toch niet anders dan inOnderzoek voor een verblijfplaats?

Nu is de structuur:
bewoningen met daarin adressen
-- bewoners met daarin persoonsgegevens en de begin/einddatum van de verblijfplaats

Moeten de verblijfplaats.inOnderzoek elementen dan toegevoegd worden aan de bewoners? Dan bevat bewoners.inOnderzoek elementen die niet in bewoners zitten. 
Ik vrees dat we hier last hebben van de bewoning/bewoners constructie waarin we gegevens van personen en hun verblijfplaatsen door elkaar husselen in de resources bewoningen en bewoners (#415).

**Comment by JohanBoer** [comment]
Ik heb nu (op basis van eerdere discussies) een indicatie verblijfplaats in onderzoek opgenomen bij de bewoner. Dat geeft niet exact aan wat er in onderzoek is maar geeft de gebruiker wel een indicatie dat er iets in de verblijfplaats in onderzoek is. 
Gaarne bevestiging dat deze indicatie de business wens afdekt. (Of een alternatieve oplossing....)
