### ISSUE TITLE
Punt achter voornaam van 1 letter

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#325]
het is mogelijk (en voorgekomen) dat iemand een voornaam heeft van één (1) letter.

Moet er in dat geval een punt achter deze letter komen in de voorletters en het voorletters-deel van de aanschrijfwijze? Een punt suggereert immers een afkorting.

Zie bijvoorbeeld http://www.gerritbloothooft.nl/Publications/B&R%202007%2012%20Opmerkelijke%20namen%20in%20de%20GBA.pdf:

> Het Hof van Amsterdam stelt in de uitspraak over
> een voornaam van een enkele letter (NJ 1994:571)
> dat een hoofdletter gevolgd door een punt als een
> afkorting - en dus als fout - zal worden opgevat,
> en staat alleen een enkele hoofdletter toe. Maar
> inmiddels is K. Roshani Wouterina geregistreerd,
> en ook Jim A. en Samuel H.J. bijvoorbeeld. Hier
> wordt klaarblijkelijk in de officiële naam de Amerikaanse gewoonte gevolgd om een middle name
> tot een initiaal te beperken [maar de presidenten
> John F. (Fitzgerald) Kennedy, Lyndon B. (Baines)
> Johnson, Richard M. (Milhous) Nixon, George W.
> (Walker) Bush hebben officieel wel degelijk uitgeschreven namen; in tegenstelling tot Harry S
> Truman].

**Comment by CathyDingemanse** [comment]
Ik stel voor om over te nemen wat er in de BRP is geregistreerd.

**Comment by fsamwel** [comment]
@CathyDingemanse 
> Ik stel voor om over te nemen wat er in de BRP is geregistreerd.

Hoe bedoel je dit? In BRP (LO GBA 3.11) zijn geen voorletters geregistreerd, alleen voornamen.
Het gaat er hier om hoe we de voornaam (vanuit een algoritme) omzetten naar voorletter.

**Comment by CathyDingemanse** [comment]
Ah ok. Dan is de regel: als er een voornaam is met 1 letter, dan geen punt zetten.
