### ISSUE TITLE
Als PO wil ik geen implementatiedetails van de provider verstrekken bij gegevens over de ingeschreven persoon deel 2

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#326]
...zodat de gebruiker alleen krijgt wat hij nodig heeft en ongewenste "coupling" aan de provider implementatie wordt voorkomen.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

Nationaliteit:
is: 04/54 Gegevens over een nationaliteit van de ingeschrevene.
wordt: Gegevens over een nationaliteit van de ingeschreven persoon.

tabelwaarden description: 
is: Een waarde, opgenomen in Tabel 32, Nationaliteitentabel, die aangeeft welke nationaliteit de ingeschrevene bezit.
wordt: Een waarde die aangeeft welke nationaliteit de ingeschreven persoon bezit.

code: 
is: Een code die aangeeft welke nationaliteit de ingeschrevene bezit. Een code, opgenomen in Tabel 32, Nationaliteitentabel, die aangeeft welke nationaliteit de ingeschrevene bezit.
wordt: Een code die aangeeft welke nationaliteit de ingeschreven persoon bezit. 

redenOpname 
is: redenOpname
wordt: redenOpnameBeeindiging

Tabelwaarde, description:
is: Waarde uit GBA Tabel 37 Reden opnemen beëindigen nationaliteit. 63: Gegevens over de verkrijging van de Nederlandse nationaliteit dan wel het opnemen van een niet-Nederlandse nationaliteit. 64: Gegevens over het verlies van de Nederlandse nationaliteit dan wel het bee¨indigen van een niet-Nederlandse nationaliteit 
wordt: 
Waarde reden opnemen of beëindigen nationaliteit. Gegevens over de verkrijging van de Nederlandse nationaliteit dan wel het opnemen van een niet-Nederlandse nationaliteit en gegevens over het verlies van de Nederlandse nationaliteit dan wel het beeindigen van een niet-Nederlandse nationaliteit.

@JohanBoer graag alles op deze manier even langs gaan? Zou je alle tabelwaarden, nummers, elementnummers, teksten over standaardwaarden etc. er uit willen halen, en van "ingeschrevene" "ingeschreven persoon" willen maken? 

Graag deze ook nog even veranderen:
indicatieOverleden | booleantitle: indicatieOverleden 
is: Deze indicatie heeft als rol om aan te geven dat iemand is overleden (waarde true). Deze indicator wordt altijd meegeleverd als de waarde true is (dus als iemand overleden is). Als de waarde false is wordt de indicator niet meegeleverd.

wordt: Deze indicatie geeft aan dat iemand is overleden (waarde true), en wordt altijd geleverd als de persoon is overleden. Als de waarde false is wordt de indicator niet geleverd.

**Comment by fsamwel** [comment]
> redenOpname
is: redenOpname
wordt: redenOpnameBeeindiging

@JohanBoer dit is nu niet doorgevoerd
@CathyDingemanse klopt dit wel? we tonen alleen actuele nationaliteiten, dus reden opname is gevuld, reden beëindiging is nooit gevuld. Dat zijn bovendien twee verschillende properties, waarvan de om dezelfde reden property reden beëindigen niet hebben opgenomen.

**Comment by fsamwel** [comment]
@JohanBoer in Nationaliteit_tabel heeft code nu de description dubbel

**Comment by fsamwel** [comment]
> Tabelwaarde, description:
is: Waarde uit GBA Tabel 37 Reden opnemen beëindigen nationaliteit. 63: Gegevens over de verkrijging van de Nederlandse nationaliteit dan wel het opnemen van een niet-Nederlandse nationaliteit. 64: Gegevens over het verlies van de Nederlandse nationaliteit dan wel het bee¨indigen van een niet-Nederlandse nationaliteit
wordt:
Waarde reden opnemen of beëindigen nationaliteit. Gegevens over de verkrijging van de Nederlandse nationaliteit dan wel het opnemen van een niet-Nederlandse nationaliteit en gegevens over het verlies van de Nederlandse nationaliteit dan wel het beeindigen van een niet-Nederlandse nationaliteit.

@CathyDingemanse ook hier zou ik het beperken tot reden opname. Dat is waar het hier over gaat. Dus moet m.i.:
- component RedenVerkrijgingOpnemen_beeindigenNationaliteit_tabel gewijzigd worden naar RedenVerkrijgingOpnemen_tabel
- de description alleen spreken over reden opnemen of verkrijgen
- de enumeratiewaarden verlies en beëindiging verwijderen

Hadden we niet besproken dat dit hele property redenOpname moet worden verwijderd? Dat is -was onze conclusie als ik het me goed herinner- alleen interessant voor de registratie.

**Comment by CathyDingemanse** [comment]
> > redenOpname
> > is: redenOpname
> > wordt: redenOpnameBeeindiging
> 
> @JohanBoer dit is nu niet doorgevoerd
> @CathyDingemanse klopt dit wel? we tonen alleen actuele nationaliteiten, dus reden opname is gevuld, reden beëindiging is nooit gevuld. Dat zijn bovendien twee verschillende properties, waarvan de om dezelfde reden property reden beëindigen niet hebben opgenomen.

OK, natuurlijk.

**Comment by JohanBoer** [comment]
> @CathyDingemanse ook hier zou ik het beperken tot reden opname. Dat is waar het hier over gaat. Dus moet m.i.:
> 
> * component RedenVerkrijgingOpnemen_beeindigenNationaliteit_tabel gewijzigd worden naar RedenVerkrijgingOpnemen_tabel

Deze tabel is nu vervangen door een generiek Waardetabel met alleen code en omschrijving. 

> * de description alleen spreken over reden opnemen of verkrijgen

De omschrijving van dit element is nu  "De reden op grond waarvan de ingeschreven persoon de nationaliteit verkregen heeft." Deze omschrijving opgenomen in de description van de nationaliteit.

> * de enumeratiewaarden verlies en beëindiging verwijderen

Door het gebruik van de generieke Waardentabel komt deze enumeratie niet meer voor. 

> Hadden we niet besproken dat dit hele property redenOpname moet worden verwijderd? Dat is -was onze conclusie als ik het me goed herinner- alleen interessant voor de registratie.

Dit ben ik nergens in een issue tegengekomen. Dat zou kunnen zzijn omdat ik het gemist heb maar ik acht de kans groter dat het niet in een issue is verwoord. @CathyDingemanse Blijft dit element of moet het verwijderd worden.

**Comment by CathyDingemanse** [comment]
> > @CathyDingemanse ook hier zou ik het beperken tot reden opname. Dat is waar het hier over gaat. Dus moet m.i.:
> > 
> > * component RedenVerkrijgingOpnemen_beeindigenNationaliteit_tabel gewijzigd worden naar RedenVerkrijgingOpnemen_tabel
> Deze tabel is nu vervangen door een generiek Waardetabel met alleen code en omschrijving.

Akkoord
> 
> > * de description alleen spreken over reden opnemen of verkrijgen


> De omschrijving van dit element is nu "De reden op grond waarvan de ingeschreven persoon de nationaliteit verkregen heeft." Deze omschrijving opgenomen in de description van de nationaliteit.

Akkoord 


> 
> > * de enumeratiewaarden verlies en beëindiging verwijderen
> 
> Door het gebruik van de generieke Waardentabel komt deze enumeratie niet meer voor.

Akkoord
> 
> > Hadden we niet besproken dat dit hele property redenOpname moet worden verwijderd? Dat is -was onze conclusie als ik het me goed herinner- alleen interessant voor de registratie.

Niet akkoord. Deze moet blijven! Er zijn verschillende en veel afnemers voor!
> 
> Dit ben ik nergens in een issue tegengekomen. Dat zou kunnen zzijn omdat ik het gemist heb maar ik acht de kans groter dat het niet in een issue is verwoord. @CathyDingemanse Blijft dit element of moet het verwijderd worden.
