### ISSUE TITLE
Als ontwikkelaar wil ik kunnen zoeken/filteren op BSN 

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#327]
...zodat ik niet probeer/faal (try/except) pogingen hoef te doen met URLs opvragen.

Probleem is dat je nu niet kan zoeken op BSN maar een URL met BSN moet proberen op te vragen. Dit komt zo terecht bij foutafhandeling en wijkt geheel af van de andere zoek/filter mogelijkheden.

**Acceptatiecriteria**
- [ ] BSN is een query parameter in ingeschrevenpersonen resource

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
Dit kan gerealiseerd worden door bij de endpoint /ingeschrevenpersonen het burgerservicenummer toe te voegen als query-prarmeter. Dat gan we doorvoeren.

**Comment by fsamwel** [comment]
@joeribekker is het issue zo naar wens ingevuld, m.a.w. kan deze naar Done?

**Comment by joeribekker** [comment]
Prima! Kan gesloten worden.

**Comment by CathyDingemanse** [comment]
N.a.v. vragen over deze nieuwe zoekparameter:

Nadeel van het exclusief gebruik van het BSN is dat je een 404 krijgt wanneer hij niet bestaat in de registratie. Dit leidt meestal tot een exceptie, waarvoor je extra code moet implementen (bestaat niet, verkeerde BSN opgegeven etc.)

Wanneer de BSN ook als zoekparameter kan worden gebruikt kan ook een 200 met een lege collectie worden geretourneerd, net als bij alle andere zoekparameters. Je hoeft daarmee geen exceptie block te implementeren. Dit is alleen nodig als je wilt aangeven dat er iets is fout gegaan. Het opgeven van een juiste BSN die niet aan een persoon gekoppeld is wil je niet noodzakelijkerwijs als een exceptie of validatiefout afhandelen, want kan gewoon betekenen dat de BSN niet in de registratie voorkomt.
