### ISSUE TITLE
Als ontwikkelaar wil ik het BSN niet in de URL hebben

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#328]
...zodat ik conform AVG niet onnodig het BSN bewaar terwijl ik alleen maar een referentie naar een persoon wil hebben.

*Volgens mij eerder aangekaart maar kon het niet vinden in GitHub*

**Acceptatiecriteria**
- [ ] Geen BSN meer in de URL can ingeschrevenpersonen

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by macedvisioned** [comment]
Als je zelfstandig professional bent gaat hier per 2020 iets in veranderen. Zie de regeling bij de KvK. 
https://www.kvk.nl/advies-en-informatie/zzp/nieuw-btw-nummer-in-2020-voor-alle-eenmanszaken/
Hoe kunnen we hier op inspringen in deze api.  Misschien coderen middels Blockchain technologie. Iemand een suggestie?

**Comment by joeribekker** [comment]
Het probleem is dat ik alleen een referentie naar een persoon wil hebben.

Afhankelijk van de autorisaties mag ik deze referentie resolven en details opvragen, en dan het BSN kan zien. Nu zie ik zonder ENIGE autorisaties tot personen TOCH het BSN van de betrokkenen bij een zaak als hier een referentie naar is.

Ik vind je opmerking en suggestie van blockchain verder niet zo relevant voor dit probleem. Of je nu wel of niet zelfstandige bent (en je BSN wordt gebruikt als publiek nummer in het KvK)

**Comment by CathyDingemanse** [comment]
Dit punt is eerder geadresseerd in issue 172. Zie:

https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/issues/172#issuecomment-473379420

**Comment by CathyDingemanse** [comment]
> Het probleem is dat ik alleen een referentie naar een persoon wil hebben.
> 
> Afhankelijk van de autorisaties mag ik deze referentie resolven en details opvragen, en dan het BSN kan zien. Nu zie ik zonder ENIGE autorisaties tot personen TOCH het BSN van de betrokkenen bij een zaak als hier een referentie naar is.


In aanvulling op het commentaar uit #172  is het natuurlijk uitgesloten dat deze API zonder enige autorisatie gebruikt kan worden.

**Comment by CathyDingemanse** [comment]
Daarnaast is vanuit Conduction de waarschuwing gekomen dat BSN en andere Query parameters in DNS servers zouden blijven hangen. 

Het statement dat paden en/of query parameters (en dus de BSN’s) in DNS zouden blijven hangen klopt niet. DNS is een hostname resolver en werkt alleen op basis van hostnames en IP adressen.

Het GET request is onderdeel van het http protocol en worden voor deze API verplicht met TLS (+ client certificaat of OAuth) versleuteld. In https verkeer zijn de paden gegarandeerd (en in de meeste gevallen de hostnames) ook encrypted. Alleen de client en server kunnen het pad zien.
