### ISSUE TITLE
Als ontwikkelaar wil het versienummer in de URL hebben

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#329]
...zodat ik weet met welke versie van de API ik praat

Tevens volgens DSO (op dit moment). Het versienummer ontbreekt in ieder geval in de API-lab URL. I'm not invested ;-)

**Acceptatiecriteria**
- [ ] `v1` toevoegen aan de API root URL.

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by joeribekker** [comment]
Zie voor versie migraties van URLs overigens ook: https://github.com/VNG-Realisatie/gemma-zaken/blob/master/docs/_content/ontwikkelaars/algemeen/versies-en-migraties.md

**Comment by bartjkdp** [comment]
Het is ook fijn om algemene richtlijnen te hebben hoelang een bepaalde versie van de API ondersteund wordt en een waarmerk om te communiceren hoe stabiel een bepaalde versie is (bijv. alpha / beta of LTS).

Is dit een duplicaat van #240?

**Comment by joeribekker** [comment]
Dit lijkt inderdaad een duplicaat, excuus. Ticket mag wat mij betreft gesloten worden.

@bartjkdp Jouw opmerkingen zijn wel nieuwe toevoegingen :) Wij van ZGW hanteren in ieder geval `alpha`, `beta` en `RC [nummer]` als postfixes.

**Comment by CathyDingemanse** [comment]
Zie https://github.com/Geonovum/KP-APIs/issues/157
