### ISSUE TITLE
Als ontwikkelaar wil ik genereerbare en leesbare enum waarden

### ISSUE THREAD

**Issue by andyverberne** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#330]
Sommige enums in de OAS, zoals IndicatieGeheimEnum, hebben numerieke waarden (0 .. 7). Dit geeft 2 problemen:
- Er zijn programmeertalen waarbij enum waarden niet kunnen beginnen met een cijfer. De workaround is dan bijvoorbeeld om de waarde "_1" te gebruiken in plaats van "1". Er is dus een technische oplossing maar het is niet zo fraai.
- De numerieke waarden hebben geen betekenis. Wat betekend "0" of "1"? Het is duidelijker als er termen met betekenis gebruikt worden zoals bijvoorbeeld GEHEIM, ZEER_GEHEIM, OPENBAAR etc. (aangenomen dat dat de betekenis is van de cijfers 0 t/m 7)

**Comment by joeribekker** [comment]
Ik ben ook voor zelf beschrijvende codes, liefst bestaande uit alleen eenvoudige karakters (`regex: A-Za-z_`) karakters. We merkten het probleem bij ZGW ook al op dat spaties en vreemde tekens niet lekker werkten met code generatie, en soms ook niet in de OAS zelf.

**Comment by JohanBoer** [comment]
We passen de enumeraties aan. Dat betekent dat we niet meer de codes communiceren, maar de omschrijving. In de description wordt bij de omschrijving getoond welke code er bij hoort voor eventuele mapping doeleinden.

**Comment by joeribekker** [comment]
@JohanBoer dat lijkt me onwenselijk. Het is voor ontwikkelaars vele malen handiger om leesbare "codes" te verkrijgen. Dus geen cijfers en geen omschrijvingen maar korte beschrijvende codes.

Voorbeeelden in volgorde van handigheid:

* GEHEIM, OPENBAAR, etc. (begrijpelijk en geen vreemde tekens die lastig zijn in programmeertalen)
* 3, 5, etc. (niet begrijpelijk - je moet opzoeken wat 3 betekent - maar werkt in programmeertalen)
* Classificatie geheim, Openbaar document, etc. (begrijpelijk maar foutgevoelig en lastiger in programmeertalen)

Als de omschrijving essentieel is, hanteren wij bij ZGW een (readonly) attribuut `<naam>Weergave` waarbij `naam` de attribuut aan is die de `enum` bevat.

**Comment by fsamwel** [comment]
Volgens mij is het de bedoeling dat de codes niet identiek worden aan de huidige omschrijving, maar daar zoveel mogelijk van afgeleid zijn. Dus geen niet alfanumerieke tekens, geen spaties, enz.
Het gaat er dus om codes te maken die foutloos code genereren, handig werken in de code (niet te lang) én betekenisvol zijn.

Bijvoorbeeld voor IndicatieGezagMinderjarige_enum:
ouder1 (1 - ouder1 heeft het gezag)
ouder2 (2 - ouder2 heeft het gezag)
eenOfMeerDerden (D - een of meer derden hebben het gezag)
ouder1PlusDerde (1D - ouder1 + een derde hebben het gezag)
ouder2PlusDerde (2D - ouder2 + een derde hebben het gezag)
ouder1En2 (12 - ouder1 + ouder2 hebben het gezag)

**Comment by CathyDingemanse** [comment]
Nog een kleine wijziging:
@JohanBoer, de GBA codes 1,2,D,1D,2D,12 graag weghalen.
Dit is in feite implementatiedetail van de provider die niet voor de consumer relevant zijn. 

Dit is echter wel van belang voor de provider bij de implementatie van de API. 
@Melvin, wil jij voor de mapping naar de GBA codes een feature schrijven?

**Comment by fsamwel** [comment]
@JohanBoer ik zie nu enumeratiewaardes met een spatie erin of een min-teken of een diakriet. Volgens mij is dat niet wenselijk voor genereren of gebruik in code. Ik zou het echt beperken tot alphanumerieke waarden [a-zA-Z0-9] met desnoods een underscore.

AanduidingInhoudingVermissingReisdocument_enum:
- "Ingehouden of ingeleverd"
AanduidingBijzonderNederlanderschap_enum:
- "behandeld als Nederlander"
- "vastgesteld niet-Nederlander"
IndicatieGezagMinderjarige_enum:
- "ouder1 en derde"
- "ouder2 en derde"
- "ouder1 en ouder2"
Naamgebruik_enum:
- "Partner en eigen"
- "Eigen en partner"
RedenOpschortingBijhouding_enum:
- "Ministerieel besluit"
- "PL aangelegd in de RNI"
SoortRedenWijzigingNationaliteit_enum:
- "beëindiging"
SoortVerbintenis_enum:
- "geregistreerd partnerschap"

**Comment by fsamwel** [comment]
@MelvLee klopt mijn bovenstaande comment, dus geeft de huidige OAS problemen in de code?

**Comment by MelvLee** [comment]
NSwagStudio vertaalt spaties naar _. In code wordt bijvoorbeeld "ouder1 en derde" Ouder1_en_derde.
Underscores blijft as-is. Als je er zeker van wilt zijn dat de meeste code generatoren hiermee kom kan gaan is het inderdaad beter om alleen alphanumerieke waarden en underscore te gebruiken.

**Comment by JohanBoer** [comment]
Alle enumeratie waarden bevatten nu alleen alfanumerieke waarden en/of underscores.

**Comment by fsamwel** [comment]
@andyverberne is het issue nu ook naar jouw opgelost (mogen we het sluiten)?

**Comment by fsamwel** [comment]
@JohanBoer wil je uit enumeratiewaarde "Partner_en _eigen" in Naamgebruik_enum de spatie verwijderen? Dank je!
