### ISSUE TITLE
Codegeneratie met NSwagStudio faalt

### ISSUE THREAD

**Issue by svercammen** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#331]
# Impediment

[NSwagStudio](https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/master/api-specificatie/Bevraging-Ingeschreven-Persoon/openapi.yaml) is niet in staat code te genereren voor [Bevraging-Ingeschreven-Persoon/openapi.yaml](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/master/api-specificatie/Bevraging-Ingeschreven-Persoon/openapi.yaml). De volledige fout is als volgt:

> System.InvalidOperationException: Could not resolve the JSON path 'https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/headers.yaml#/api_version' with the full JSON path 'https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/headers.yaml#/api_version'. ---> System.InvalidOperationException: Could not resolve the path '#/api_version'.

**Comment by JohanBoer** [comment]
Dit kan worden opgelost door de ge-resolvde versie van de Yaml te gebruiken. We overwegen om naast de yaml met verwijzingen ook de geresolvde versie aan te bieden. 
Dit kan gegarandeerd worden door het resolven op te nemen in de buildstraat.
