### ISSUE TITLE
naast woonplaatsnaam ook graag woonplaatscode net als in geboorteplaats

### ISSUE THREAD

**Issue by lordie2** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#332]
woonplaatsnaam is niet uniek in nederland dus ook graag woonplaatscode toevoegen, net als is gedaan met geboorte->plaats->code en geboorte->plaats->naam

**Comment by JohanBoer** [comment]
Deze woonplaatscodes worden door de BAG geregistreerd. bij de woonplaats wordt dus ook een link naar de BAG-API (in ontwikkeling) aangebracht.

**Comment by JohanBoer** [comment]
Bij nader inzien is deze link (impliciet ) al aanwezig. De ingeschreven persoon heeft een link naar de nummeraanduiding van het adres waar de persoon op is ingeschreven. Deze link verwijst naar de BAG. De nummeraanduiding zelf heeft weer een verwijzing naar de woonplaats zoals die in de BAG is geregistreerd. 
Als er dus behoefte is aan de betreffende woonplaatscode, dan kan die via deze route opgehaald worden bij de authentieke bron (BAG)
