### ISSUE TITLE
Als ontwikkelaar wil ik de tabel 33 via de API ontsloten hebben.

### ISSUE THREAD

**Issue by warrantyvoids** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#333]
Als ontwikkelaar wil ik de gemeentecode/gemeentenaam-tabel uit een centrale bron halen, zodat ik deze niet zelf hoef te beheren, maar met andere softwarecomponenten dezelfde gegevens kan delen. Op deze manier verminderen we onderhoud per applicatie.

**Acceptatiecriteria**
- [Er bestaat een API om deze tabel in zijn geheel te ontvangen (dus inclusief historische data)]
- [Er bestaat een API om de huidig actieve entries te ontvangen]
Potentieel:
- [Er bestaat een API om te zoeken op basis van Gemeentenaam]
- [Er bestaat een API om een enkele gemeentenaam op basis van een code op te halen]

**Definition of done**
- [ ] functionele specificatie
- [x] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
Inventariseer de hele "actueel" ingeschreven Persoon Api en check welke tabellen daarvoor al van een endpoint moeten worden voorzien. Zie ook #281

**Comment by fsamwel** [comment]
@JohanBoer mooie aanzet. Ik denk dat (naast raadplegen op code) juist behoefte is aan zoeken op omschrijving. En dat inclusief ondersteuning voor wildcards en case-insensitive.

Ik vraag me af of er behoefte is aan de metagegevens in de tabel (datumIngang en datumEinde). Nieuwe code zou ik in links stoppen, zodat doorgeklikt kan worden naar de nieuwe tabelwaarde.

**Comment by JohanBoer** [comment]
Ik heb zoekfuncties voor gemeenten en adellijke titels toegevoegd inclusief wildcards en case-insensitive. 

datumIngang en datumEinde heb ik toegevoegd omdat ik dan alle elementen uit de (PDF) tabellen ontsluit. Ik kan me voorstellen dat er wel afnemers voor deze gegevens zijn en het lijkt mij niet nodig om voor een tabel met 5 elementen meerdere endpoints op functionaliteit te gaan specificeren.

**Comment by fsamwel** [comment]
Heropend. Issue is nog niet goed doordacht. Door mij destijds ten onrecht op done gezet.

Zie suggesties voor verbetering in #441
