### ISSUE TITLE
Aanschrijfnaam is niet toereikend voor het gebruik in lopende tekst.

### ISSUE THREAD

**Issue by warrantyvoids** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#334]
# Impediment
Aanschrijfnaam is niet toereikend voor het gebruik in lopende tekst. De naam van een persoon zoals gebruikt in documenten, kent een paar locaties. Dit kan zijn in een aanhef, in lopende tekst en in een adresblok.

De aanschrijfnaam zoals nu gespecificeerd is uitsluitend te gebruiken in een adresblok. Zie bijvoorbeeld het volgende scenario:

Aan:
Jonkheer T. de Tester
Fictief adres,
Fictief adres

Hoogwelgeboren heer de Tester,

In uw brief van 12 mei jongstleden, geeft u het overlijden van uw vader, heer de Tester, aan. (etc, etc).

In feite zijn er drie aanspreektitels: Deze voor een adresblok (nu geimplementeerd), die voor een aanhef (missend), en die voor een persoon in een lopende tekst (missend). Deze beperking zorgt er voor dat er nu nogsteeds een naam samengesteld moet worden uit andere gegevens, waardoor de aanspreekvorm nog niet bruikbaar is.

**Comment by JohanBoer** [comment]
Zie ook #337

**Comment by fsamwel** [comment]
Er zijn als ik het goed begrijp 3 plekken in communicatie waarin we een persoon willen benoemen:

1. In de adressering
Hiervoor hebben we al naam.aanschrijfwijze bij ingeschreven personen. Dit wordt gevuld met bijvoorbeeld "A.B. de Vries-de Jong", "Jonkvrouw A.B. van Hoogh" of "A.B. baron van Aedel".

2. In de aanhef van een brief
Hiervoor willen we een nieuw property "aanhef" toevoegen aan de groep naam van een ingeschreven persoon. Dit wordt gevuld met bijvoorbeeld "Geachte mevrouw de Vries-de Jong", "Geachte heer de Jong" of "Hoogwelgeboren vrouwe van Hoogh"

3. In lopende tekst
Hiervoor willen we een nieuw property "gebruikInLopendeTekst" toevoegen aan de groep naam van een ingeschreven persoon. Dit wordt gevuld met bijvoorbeeld "mevrouw de Vries-de Jong", "de heer de Jong", "jonkvrouw van Hoogh" of "baron van Aedel".

Zowel de aanhef als gebruikInLopendeTekst worden samengesteld op basis van voorvoegsel en geslachtsnaam, voorvoegsel en geslachtsnaam van de evt. partner, aanduiding naamgebruik, adellijke titel of predikaat, geslachtsaanduiding.

**Comment by warrantyvoids** [comment]
Ja, dit klopt!

In principe zijn er drie cases: Aanhef, en de twee weergaveversies (1 met initialen en 1 zonder initialen), waarbij de laatste twee ook in gebruikersinterfaces getoont kunnen worden bij het weergeven in bijvoorbeeld een overzicht. Misschien is het mogelijk om de naamgeving c.q. documentatie van deze velden zo op te stellen dat consumers van de API aangeraden wordt ze te gebruiken als weergavenaam?

**Comment by gertjanvanderkooij** [comment]
Moet er nog rekening gehouden worden met een smaakje 'aanschrijven zonder titels/predikaten'?

**Comment by warrantyvoids** [comment]
Dat is mogelijkerwijs voor weergaveschermen wel wenselijk en lijkt me een goede/logische uitbreiding!

**Comment by CathyDingemanse** [comment]
De API zal **DE** CORRECTE aanschrijfwijze, aanhef en benoeming in lopende tekst communiceren. Alle overige varianten zijn indien gewenst aan de consumer om te fabriceren.

**Comment by fsamwel** [comment]
@JohanBoer Is er een speciale bedoeling of betekenis om bij aanhef, aanschrijfwijze en gebruikInLopendeTekst de description te laten beginnen met "| "?

**Comment by JohanBoer** [comment]
@fsamwel  Ja, daarmee geef je aan dat de rest van de description geïnterpreteerd moet worden als Markdown inclusief de line-feeds. Helaas haalt imvertor nu de control Linfeeds weg uit de descritiptions en valt alle opmaak weg (wordt aan gewerkt door Robert, bijna opgelost. . Bij de description van de endpoint ïngeschrevenpersonen zie je een mooi voorbeeld. Als je daat de "|" weghaalt krijg je een foutmelding.

**Comment by fsamwel** [comment]
@JohanBoer 
> Bij de description van de endpoint ïngeschrevenpersonen zie je een mooi voorbeeld. Als je daat de "|" weghaalt krijg je een foutmelding.

Bij de description van een property zoals die nu is vormgegeven werkt dat nog niet:
- Wanneer ik een line-feed na de | zet, wordt de | nog steeds getoond in Swagger
- Wanneer ik een line-feed na de | zet wordt een line-feed in de tekst niet getoond in Swagger (tekst blijft achter elkaar staan)

Oorzaak dat deze opmaak niet werkt is omdat de description van een property tussen aanhalingstekens wordt geplaatst.  Wanneer het niet tussen aanhalingstekens staat en er wel een pip staat, werkt het wel zoals je bedoeld hebt.

**Comment by JanWillemKooi** [comment]
Update van 23 aug:
Er moet een nieuwe feature komen op basis van het document: "Naamgebruik API2.docs
Frank gaat dit doen.

**Comment by fsamwel** [comment]
@JohanBoer de beschrijving van gebruikInLopendeTekst kan nog nét iets duidelijker
> De naam zoals die in lopende tekst kan worden.

Hier is denk ik het woord "gebruikt" weggevallen. Zou kunnen worden:
> De naam zoals die in lopende tekst gebruikt kan worden.

Ook is het voorbeeld bij aanhef niet correct. Ik zou eigenlijk voorbeelden met adellijke personen vermijden. Je raakt hier direct al ingewikkelde grensgevallen die zeer weinig tot nooit voor zullen komen.

**Comment by fsamwel** [comment]
@JohanBoer 
de descriptions voor aanhef, aanschrijfwijze en gebruikInLopendeTekst bevatten nu link naar featue. De feature is puur gericht op de provider en is niet interessant voor de consumers. Op andere plekken hebben we alleen verwijzing naar feature opgenomen wanneer dit relevant is voor de gebruiker, zoals bij gebruik van wildcards.
Dus wat mij betreft mogen die referenties eruit.

**Comment by JohanBoer** [comment]
Referenties verwijderd
