### ISSUE TITLE
Als ontwikkelaar wil ik tabel 38 ontsloten hebben.

### ISSUE THREAD

**Issue by warrantyvoids** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#336]
Dit, zodat gegevens over de adelijke titel zoals gebruikt in Naam binnen een Natuurlijk Persoon op een centrale plek kan raadplegen, in plaats van deze tabel zelf te implementeren (naast de implementatie die reeds nodig is voor BRP)

**Acceptatiecriteria**
- [Er bestaat een API/call om een lijst van alle adelijke titels op te vragen]
- [Er bestaat een API/call om een enkele adelijke titel op te vragen]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
Zie #281 en #333
