### ISSUE TITLE
Als ontwikkelaar wil ik zelf niet de logica uitvoeren voor het naamgebruik.

### ISSUE THREAD

**Issue by warrantyvoids** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#337]
Momenteel wordt het naamsgebruik nog meegegeven. Vervolgens moet de gebruiker hier voor een naam zoals gebruikt in bijna alle gevallen zelf samengesteld worden op basis van de waarde van naamsgebruik. Gelet op de recentelijk aangenomen motie die niet herenigbaar is met dit model (https://www.tweedekamer.nl/kamerstukken/moties/detail?id=2019Z01275&did=2019D02867), lijkt het beter te zijn om een onderscheid te maken tussen 'geslachtnaam' en 'aanspreeknaam' of iets van deze trant. Daarnaast, met de recentelijke ontwikkelingen meegenomen, is het niet ondenkbaar dat dit model in de toekomst meer waarde verliest.

Dit voorkomt dat consumers van de data hier logica voor gaan inbouwen, en is voor de providers van de API compleet compatible.

**Acceptatiecriteria**
- [Het veld 'naamgebruik' is deprecated]
- [De logica voor het samenstellen van dergelijke namen leeft in de BRP-implementaties.]
- [Voor consumers is dit een op te vragen veld in het Naam-object]
- [Het wordt mensen in de documentatie afgeraden om geslachtsnaam te gebruiken waar eigenlijk aanspreeknaam wordt verwacht]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by CathyDingemanse** [comment]
Uit het kamerstuk maak ik op dat men graag dubbele achternamen mogelijk wil maken. In dat geval verandert dat toch niets aan de implementatie van de aanspreekvormen zoals genoemd in 334? In plaats van een geslachtsnaam worden dan twee geslachtnamen geimplementeerd. Dit heeft toch geen consequenties voor de logica van aanschrijfwijze, aanhef en gebruik in lopende tekst. Of zie ik dat verkeerd?

**Comment by warrantyvoids** [comment]
Nee, dit heeft (momenteel) geen directe invloed op deze naam; Echter heeft een dergelijke wijziging tot gevolg dat de enum Naamsgebruik dus niet alleen de relatie van de partner mee hoeft te nemen, maar ook die van een combinatie van eventuele ouders. Gezien deze ontwikkelingen en het feit dat er nu een kans bestaat om deze logica expliciet uit te laten voeren door een BRP systeem in plaats van bij de verschillende consumers, kunnen problemen en aanpassingen hieruit voortvloeiend nu al bij voorbaat worden weggenomen.

Als er verschillende velden komen voor de verschillende gebruiken van de naam heeft dit inderdaad geen consequenties meer.

**Comment by CathyDingemanse** [comment]
Ok duidelijk. We gaan e.e.a. conform #334 uitvoeren. Thnx voor jullie bijdrage, denk dat heel veel consumers hier baat bij hebben!

**Comment by CathyDingemanse** [comment]
> Momenteel wordt het naamsgebruik nog meegegeven. Vervolgens moet de gebruiker hier voor een naam zoals gebruikt in bijna alle gevallen zelf samengesteld worden op basis van de waarde van naamsgebruik. 
> **Acceptatiecriteria**
> 
> * [Het veld 'naamgebruik' is deprecated]

**Comment by CathyDingemanse** [comment]
> > Momenteel wordt het naamsgebruik nog meegegeven. Vervolgens moet de gebruiker hier voor een naam zoals gebruikt in bijna alle gevallen zelf samengesteld worden op basis van de waarde van naamsgebruik.
> > **Acceptatiecriteria**
> > 
> > * [Het veld 'naamgebruik' is deprecated]

Wie is het eens met dit  deel van de issue? Kunnen we aanduiding naamgebruik en dan ook adellijke titel en predikaten depricaten? Ik zal dit ook op de september API lab vragen, maar alle reacties zijn alvast welkom! Graag reageren met +1 thumbs up of -1 thump down.

**Comment by CathyDingemanse** [comment]
Let's do it. Het gebruik van deze API is een mooi moment voor gebruikers om eigen legacy code te depricaten. We kunnen aanduiding naamgebruik en adellijke titels altijd nog opnemen als op de API lab in september blijkt dat levering echt noodzakelijk is.

**Comment by JohanBoer** [comment]
@CathyDingemanse Wat betekent dat concreet ? Verwijder ik deze elementen uit de API of geef ik in de description aan dat deze elementen depricated zijn en in een volgende (major) versie verwijderd worden ?

**Comment by CathyDingemanse** [comment]
Verwijderen!!!

**Comment by CathyDingemanse** [comment]
Spec is ter review aangeboden bij de Hoge Raad van Adel. De verwachting is dat er volgende week een goedgekeurd specificatie ligt.

**Comment by JohanBoer** [comment]
Verwijderen :  

- [ ] aanduidingNaamgebruik
- [ ] adellijkeTitel_predikaat (inOnderzoek)
- [ ] adellijkeTitel_predikaat

**Comment by JanWillemKooi** [comment]
Frank moet het commentaar verwerken die tijdens de zomer is opgehaald. Vervolgens moet een review uitgevoerd worden.
- [x] verwerken commentaar Frank
- [x] feature aanpassen Frank
- [x] review Frank

**Comment by JanWillemKooi** [comment]
Frank heeft aanpassingen gedaan.
