### ISSUE TITLE
Als ontwikkelaar wil ik dat een API key definitie is opgenomen in de api beschrijving

### ISSUE THREAD

**Issue by suliban** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#338]
...zodat ik in mijn gegenereerde code met een API key kan werken.

Er wordt gewerkt o.b.v. een API-key en in dat geval help het als dit ook is opgenomen in de openapi.yaml conform https://swagger.io/docs/specification/authentication/api-keys/.

**Comment by JohanBoer** [comment]
De API-Key is alleen beschikbaar gesteld voor de API-LAB. Hoe dit in productie geregeld wordt hangt af van de policy van de provider.
