### ISSUE TITLE
Als ontwikkelaar wil ik een referentie implementatie

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#34]
...zodat ik een werkend voorbeeld kan zien en zelf kan opzetten.

**Acceptatiecriteria**
- [ ] Implementatie gebruikt de OAS uit Imvertor voor zover mogelijk
- [ ] Implementatie is publiekelijk beschikbaar

**Definition of done**
- [ ] Code op Github
- [ ] Code uitgerold op omgeving t.b.v. publieke bereikbaarheid

**Comment by joeribekker** [comment]
Code toegevoegd via PR #52.

API documentatie: http://brp.tst.vng.cloud/api/v1/schema/
API endpoint: http://brp.tst.vng.cloud/api/v1/

NLx API adres (t.b.v. outway): http://{your-outway-address}:{port}/vng-realisatie/Basisregistratie-personen/api/v1/ingeschrevennatuurlijkpersonen/

Voorbeeld van een persoon opvragen op basis van BSN: http://brp.tst.vng.cloud/api/v1/ingeschrevennatuurlijkpersonen?burgerservicenummer=999990639

**Comment by wishalg** [comment]
@CathyDingemanse Provider referentie-implementatie bouwen lukt volgens de planning van MakinMedia niet eerder dan April. Moet dit eerder plaatsvinden, dan dienen we op zoek te gaan naar een andere partij.

**Comment by CathyDingemanse** [comment]
Graag!

**Comment by JanWillemKooi** [comment]
@CathyDingemanse Tijdens een gesprek met @wishalg gisteren, vertelde hij dat er voortgang is met het vinden van een goede ontwikkelpartij om de referentie implementatie te maken. @JohanBoer en ik hebben vorige week besproken om, zodra Johan terug is, een opdrachtomschrijving te maken.

**Comment by fsamwel** [comment]
@JanWillemKooi dit issue staat in review, maar er is nog geen referentie implementatie. Moet die dan terug in de back log? Of kan deze worden gesloten, omdat/wanneer er opdracht is voor het bouwen van de referentie implementatie?

**Comment by JanWillemKooi** [comment]
@fsamwel We zijn nu, as you speak, in de afrondende fase van het gunnen van de referentie implementatie. Ik denk dat deze US kan worden afgesloten zodra de gunning rond is en de contacten zijn getekend. Niet dat dat helemaal correct is, maar dan staat de referentie implementatie formeel op de rit. En dat moeten we een aantal nieuwe US's aanmaken die te maken hebben met de daadwerkelijke implementatie en het in beheer nemen ervan. Misschien dat we dat ook vanuit een andere repository doen zodat deze repository de focus op de standaard kan blijven houden en niet vervuild wordt door implementatie en code gerelateerde issue's. 
Eens?

**Comment by fsamwel** [comment]
> Eens?

Prima

**Comment by joeribekker** [comment]
Kunnen jullie ook de map "code" verwijderen, waar mijn oude code in staat? Dit leidt tot verwarring, zoals is opgemerkt op Slack door een leverancier.

**Comment by JanWillemKooi** [comment]
@joeribekker Dat vind ik wat riskant nu Johan met vakantie is. Misschien dat Melvin kan helpen maar als niemand van de inhoud aanwezig is, ga ik geen map "code" verwijderen. Kan die even wachten tot het team weer terug is?

**Comment by joeribekker** [comment]
@JanWillemKooi uiteraard!

Is overigens niets gevaarlijks aan :) Het is namelijk nooit echt weg in Github. Het is alleen dan niet meer aanwezig in de versie vanaf de verwijdering. In alle versies daarvoor is het er wel nog. Voor het oog is het dan in ieder geval wel weg omdat je standaard laatste versie ziet.

**Comment by JohanBoer** [comment]
@joeribekker Map code is inmiddels verwijderd
