### ISSUE TITLE
Filteren en berekende attributen

### ISSUE THREAD

**Issue by sjefvanleeuwen** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#341]
Als behandelaar wil ik gefilterde en, indien haalbaar, berekende attributen ontvangen die ten grondslag liggen aan een verordening zodat er in het kader van doelbinding geen onnodige informatie over de lijn gaat om een voorziening toe te kennen aan de inwoner.

**Acceptatiecriteria**
- Een generieke filter implementatie welke een deel van de (berekende) BRP attributen teruggeeft. De gegevens voor de filter wordt doorgegeven vanuit de geldende verordening. Bijv. geef alleen leeftijden terug van de inwonende kinderen i.p.v. geboortedatums.

**Definition of done**
- [*] functionele specificatie
- [*] Open API specificatie
- [*] gegenereerde code
- [*] testgevallen

**Comment by JohanBoer** [comment]
In het algemeen is het filteren te realiseren door de fields-parameter toe te passen. 

Het teruggeven van leeftijden in plaats van geboortedatum heeft als gevolg dat leeftijd toegevoegd gaat worden als property bij kinderen en bij de ingeschreven persoon. De leeftijd wordt niet teruggegeven als de geboortedatum (gedeeltelijk) onbekend is.

Tijdens de API-LAB is ook de property "thuiswonend" (boolean) ter sprake gekomen. Deze property wordt ook toegevoegd bij de kinderen.

**Comment by gertjanvanderkooij** [comment]
Volgende opmerkingen:   

1) Tav de leeftijd lijkt me dit een goed idee; gegeven is ook afleidbaar van de resource die wordt opgevraagd.
  
2) Tav 'thuiswonend' lijkt me dit niet zo'n goed idee. Dit vereist bijlezen van de gehele PL van de kinderen en vergelijken van de adresgegevens. In geval van ‘peildatum’-vraag ook het selecteren van de juiste situatie op peildatum en vervolgens vergelijken. Op welke termijn wil je dit introduceren en is hier qua specificatie en ook performance afdoende naar gekeken? 

is dit niet meer iets voor een aparte API; iets van 'Geef Medebewoners', zoals we die ten tijde van Operatie BRP ook als aparte dienst hadden voorzien. Ingang op BSN of Adresgegevens. Een dergelijke API straks ook heel goed bruikbaar voor het verhuisproces (Wie verhuist er mee?). In de response kan de onderlinge relatie (ouder/kind/partner) worden meegegeven, indien gewenst/vereist.

**Comment by CathyDingemanse** [comment]
> Volgende opmerkingen:
> 
> 1. Tav de leeftijd lijkt me dit een goed idee; gegeven is ook afleidbaar van de resource die wordt opgevraagd.
> 2. Tav 'thuiswonend' (of is het 'inwonend'?) lijkt me dit niet zo'n goed idee. Dit vereist bijlezen van de gehele PL van de kinderen en vergelijken van de adresgegevens. In geval van ‘peildatum’-vraag ook het selecteren van de juiste situatie op peildatum en vervolgens vergelijken. Op welke termijn wil je dit introduceren en is hier qua specificatie en ook performance afdoende naar gekeken?
> 

> is dit niet meer iets voor de aparte API - Bewoning, zoals we die ten tijde van Operatie BRP ook als aparte dienst hadden voorzien. Ingang op BSN of Adresgegevens. Een dergelijke API straks ook heel goed bruikbaar voor het verhuisproces (Wie verhuist er mee?). In de response kan de onderlinge relatie (ouder/kind/partner) worden meegegeven, indien gewenst/vereist.
> 
Het betreft een valide rquirement, waar je in principe alleen last van hebt als je met een expand ook direct het kind of de kinderen ophaalt. Dat betekent dat we hier niet iedereen mee lastig vallen. Misschien is het performanceverlies nu enigszins voorbarig. Laten we even afwachten of creatieve ontwikkelaars hier iets op kunnen vinden. 

> Is wel extra vraagstelling voor consumer, maar dit af te wegen tegen het bij iedere Bevraging (met Expand?) uitvoeren van het 'inwoning'-algoritme. Als besluit is/wordt om deze wel te ondersteunen in BevragingPersoon, dan is sturing via een aparte parameter wellicht ook een mogelijkheid om dit te voorkomen ; bv. indicatieInwoning (default 'false').

Dit is een optie, maar laten we dit even afwachten. Ik stel voor om deze vraag tijdens de API lab aan de orde te laten komen. Suggesties zijn welkom!!

**Comment by fsamwel** [comment]
@JohanBoer @CathyDingemanse 
> In het algemeen is het filteren te realiseren door de fields-parameter toe te passen.

Filteren is nu alleen toegepast op de persoon, niet op de overige (sub)resources (ouders, partners, kinderen, reisdocumenten. Is filteren op deze resources niet ook gewenst t.b.v. beperken tot doelbinding?

**Comment by JohanBoer** [comment]
Volgens mij is het filteren op de embedded subresources ook gewenst. De API-strategie geeft hier geen uitsluitsel over :

_In the case of HAL, linked resources are embedded in the default representation. Applying the aforementioned fields parameter, the contents of the body can be customised as required._  

Bij deze stelling zou dus de requirement gedefinieerd moeten worden dat embedded subresources ook gefilterd kunnen worden. Ik zeg doen, maar vooral als daar ook vanuit de Business behoefte aan is.... Cathy ?
