### ISSUE TITLE
Eenduidige authorisatie van VNG API's

### ISSUE THREAD

**Issue by sjefvanleeuwen** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#342]
Als CISO wil ik dat alle VNG API's hetzelfde mechanisme gebruiken voor autorisatie zodat de beveiliging uniform is, wat helpt bij minimaliseren van custom code die omgaat met autorisaties op de verscheidenheid aan API's en ik eenduidiger security tokens kan aanvragen bij de VNG.

**Acceptatiecriteria**
- Graag refereer ik naar scopes als autorisatie mechanisme https://ref.tst.vng.cloud/ontwikkelaars/algemeen/scopes
- v.w.b. self service aanvraag tokens, refereer ik graag naar: https://ref.tst.vng.cloud/tokens/

**Definition of done**
- [x] functionele specificatie
- [x] Open API specificatie
- [x] gegenereerde code
- [x] testgevallen

**Comment by JohanBoer** [comment]
Zolang alle API's van de VNG in verschillende "vertrouwelijkheidsklassen" vallen is het mechanisme  van beveiligen per definitie verschillend. In het kennisplatform API's van het Geonovum wordt gepoogd hier binnen iedere klasse zoveel mogelijk uniformiteit te bereiken. 
Hieraan zullen wij ons conformeren.
