### ISSUE TITLE
Als developer wil ik de generieke Persoon resource kunnen benaderen

### ISSUE THREAD

**Issue by jessevanmuijden** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#343]
zodat er één plek is om gegevens over personen op te vragen. Stel dat er straks de volgende resources zijn:
- GeregistreerdePersonen
- OngeregistreerdePersonen
- NatuurlijkePersonen
- NietNatuurlijkePersonen

Als ik gewoon persoonsgegevens op wil vragen op basis van een BSN nummer, dan wil ik niet na hoeven denken over welke specifieke resource voor Personen ik daarvoor aan moet boren. Als ik alleen specifieke personen met een bepaalde eigenschappen op wil zoeken, dan wil ik wel filters toe kunnen passen op die eigenschappen. Bijvoorbeeld:

- welke soort persoon dan ook:
`/personen?geboorte__datum=18-02-1987`
- alleen natuurlijke personen:
`/personen?geboorte__datum=18-02-1987&natuurlijk=true`

Dit, volgens het principe: resources zijn zo veel mogelijk zelfstandige naamworden en bijvoeglijke naamwoorden worden zo veel mogelijk gebruikt als attributen van die resources.

**Acceptatiecriteria**
- Persoon resource met ingeschreven:boolean als attribute
- Kunnen filteren op Persoon.ingeschreven (ja/nee)

**Definition of done**
- [x] functionele specificatie
- [x] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by CathyDingemanse** [comment]
Jouw voorstel suggereert de aanwezigheid van een nieuw endpoint die "personen" generaliseert en daarvoor de verschillende registraties voor personen als bron gebruikt (BRP voor Ingeschreven natuurlijke personen, HR voor ingeschreven niet natuurlijke personen, BRK voor (niet ingeschreven) natuurlijke en niet natuurlijke kadasterpersonen, en HR voor (niet ingeschreven) natuurlijke en niet natuurlijke handelsregisterpersonen). Vanuit DX kan ik me voorstellen dat deze behoefte er is.

Echter, dit kan niet worden gerealiseerd zonder de afzonderlijke bronnen ieder op zich toegankelijk te maken. Dat is waar we met Haal Centraal aan werken. Als dat klaar is en de behoefte bij gemeenten is groot, dan zie ik een mooie toekomst voor een generieke BevragenPersonen API!
