### ISSUE TITLE
Pandid als zoekparameter voor het zoeken op personen

### ISSUE THREAD

**Issue by EmilBontje** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#345]
...zodat je bijvoorbeeld vanuit de BGT de bewoners van een pand kunt zoeken. De BGT bevat namelijk geen informatie over de nummeraanduidingid's en alleen de minimum en maximum waarde van de gerelateerde verblijfsobjecten, met dat laatste kunnen overigens ook niet de bijbehorende nummeraanduidingid's worden gevonden, omdat de verblijfsobjectid's geen opeenvolgende reeks hoeven te vormen. Ik begreep dat dit punt al ter tafel is geweest maar vind het niet terug in de bestaande issues, daarom heb er een issue van gemaakt...

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by CathyDingemanse** [comment]
Dit is een prachtige feauture, maar kan op dit moment nog niet worden gerealiseerd. 
Voorlopige werkwijze is het ophalen van de verblijfsobjecten in het Pand in de BAG en vervolgens met de verblijfsobjecten de BRP bevragen, zie #410
