### ISSUE TITLE
geometrie opnemen bij de ingeschreven

### ISSUE THREAD

**Issue by EmilBontje** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#346]
...zodat je op grond van een polygoon de bewoners kan opvragen, bijvoorbeeld in het geval van een ramp of het bepalen van de impact van een evenement. In de API van de Zaaksystemen is er de mogelijkheid om aan zaken geometrien te koppelen, dat zou hier ook handig zijn. Daarnaast zou je het kunnen gebruiken om individuele bewoners op grond van hun eigenschappen op een kaart te af te beelden.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
Deze functionaliteit wordt in de API "Bewoning" ingevuld. Die is nu volop in ontwikkeling.

**Comment by CathyDingemanse** [comment]
Er wordt idd aan gewerkt in de bewoning API. Geometrie wordt geleverd via de relatie met de BAG. Graag de bewoning API reviewen!
