### ISSUE TITLE
geaggregeerde persoonsinformatie

### ISSUE THREAD

**Issue by EmilBontje** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#347]
... voor het op de kaart afbeelden van demografische gegevens, zoals de gemiddelde leeftijd aantal personen per huishouden (indicator mogelijke misstanden, zoals uitkeringsfraude), etc. Mogelijke aggregaties zijn verblijfsobject, pand, postcodegebied, buurt en wijk. Als de gemeente beschikt over de persoonsgegevens dan kunnen deze overzichten eenvoudig worden aangemaakt, in het geval van Haal Centraal zal ook dit punt geadresseerd moeten worden, om te voorkomen, dat de gemeenten voor dit soort doeleinden toch weer een eigen dataset moeten opbouwen/onderhouden.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by CathyDingemanse** [comment]
Eens. Deze functionaliteit (BI etc.) komt in een latere fase aan bod. De huidige API richt zich op het bevragen van (een beperkt) aantal personen tbv van de primaire processen van gemeenten.
