### ISSUE TITLE
Plaast en land overlijden niet aanwezig in response

### ISSUE THREAD

**Issue by gertjanvanderkooij** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#359]
**Als ik volgende request van overleden persoon doe:**
https://www.haalcentraal.nl/haalcentraal/api/brp/ingeschrevenpersonen/999995108 
Dan ontbreken de overlijdensgegevens plaats en -land. 

Zou voor BSN 999995108 volgens de testset 'Rotterdam/Nederland' (0599/6030) moeten zijn.

**Comment by fsamwel** [comment]
De api (voor de API lab) gebruikt de GBA-V koppeling van gemeente Den Haag op basis van autorisatietabel Algemene gemeentetaken. Daar is er geen autorisatie voor overlijden land en plaats.

**Comment by JohanBoer** [comment]
@gertjanvanderkooij Is Frank's antwoord afdoende ? Mag dit issue gesloten worden ?

**Comment by gertjanvanderkooij** [comment]
Ja, kan gesloten worden.
