### ISSUE TITLE
Wat voor encoding type is er gebruikt in de api?

### ISSUE THREAD

**Issue by macedvisioned** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#362]
In de name velden bijv. naam__geslachtsnaam en naam__voornamen worden zowel westerse als cyrillische namen als wel Aziatische namen gebruikt. In de voorbeeld data van RVIG zie ik vreemde tekens die niet goed worden weergegeven. Misschien wordt wel UTF 8 gebruikt, maar beter is het om UTF 16 te gebruiken.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by fsamwel** [comment]
@macedvisioned Dank voor je melding. Er wordt inderdaad utf-8 gebruikt. Heb je voor mij een voorbeeld, een burgerservicenummer waarmee je dit geconstateerd hebt?

**Comment by macedvisioned** [comment]
Ik heb dit geconstateerd in het volgende test bsn nummer 999994669

**Comment by gertjanvanderkooij** [comment]
BRP = conform Teletex-tekenset (zie LO GBA).
Deze set wordt met UTF-8 prima weergegeven. 
Ik zie bij betreffend BSN geen vreemde zaken in spreadsheet testset.

**Comment by joeribekker** [comment]
@gertjanvanderkooij Wellicht bedoeld @macedvisioned dat het wel goed staat in de spreadsheet, maar niet in de API-response. Helaas kan ik het door een verlopen API key niet meer testen.

UTF-16 betekent overigens niet dat het meer of andere karakters aan kan dan UTF-8. UTF-8 kan alle karakters tonen en lijkt me prima als Content-Type encoding. Ik zie niet waarom UTF-16 daarom beter is of het genoemde probleem zou oplossen.

Zie: https://javarevisited.blogspot.com/2015/02/difference-between-utf-8-utf-16-and-utf.html

**Comment by macedvisioned** [comment]
OK, dan is het opgelost
