### ISSUE TITLE
Als gebruiker wil ik alleen buiten de eigen gemeente kunnen zoeken

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#369]
...zodat ik een persoon kan zoeken op naam plus geboortedatum.

Tijdens de migratieperiode, zolang de API wordt gerealiseerd door het gebruik van zowel een lokale bron (bijv. een gegevensmagazijn of burgerzakenapplicatie) als GBA-V, is een voor de hand liggende keuze primair te zoeken in de lokale database. Alleen wanneer daarin niks gevonden wordt, wordt buiten de gemeente gezocht. Dit kan betekenen dat wanneer een persoon (maar niet de juiste) binnen de gemeente gevonden wordt op basis van de zoekargumenten, de gewenste persoon van buiten de eigen gemeente niet gevonden wordt.

Dus is er behoefte aan om aan te kunnen geven dat alleen buiten de eigen gemeente, alleen in GBA-V, gezocht moet worden.

Oplossing: toevoegen van een zoekparameter waarmee gezocht wordt buiten de eigen gemeente. Bijvoorbeeld parameter verblijfplaats__gemeentevaninschrijving_ongelijk = {gemeentecode}. Of parameter buitengemeentelijk = {boolean}

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
Dit verzoek is al vroeg in dit project geopperd en behoorlijk bediscussieerd in #21. 
Als er een nieuw inzicht is voeg ik zonder probleem een boolean toe. 

@CathyDingemanse  daar hier sprake van ?

**Comment by CathyDingemanse** [comment]
Dit is geen issue die binnen de Haal Centraal RvIG API moet worden geadresseerd en opgelost. Ik zie dit als een "Haagse issue" ofwel eigen lokale migratieproblematiek. @fsamwel dit moeten wij voor Den Haag oplossen.
