### ISSUE TITLE
Import data in Mendix geeft onverwachte resultaten met href link

### ISSUE THREAD

**Issue by macedvisioned** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#375]
Als ik in Mendix een een json file importeer dan krijg ik een foutmelding bij de href string _links.
De error die ik krijg is de volgende (zie screenshot).
[https://d.pr/free/i/F593jH](url)

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
Wil je bij de volgende release candidatie checken of dit probleem nog steeds optreedt ? We hebben een aantal wijzigingen doorgevoerd op dit vlak.
