### ISSUE TITLE
Referentieimplementatie: Niet mogelijk om docker-omgeving op te starten.

### ISSUE THREAD

**Issue by warrantyvoids** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#379]
Voor het runnen van een docker-compose mist het image vngr/gemma-bip. Is deze potentieel niet gepublished?

Dit omdat we graag als leverancier eigen test-infra hebben voor het inrichten van een CI van eigen software en koppelingen.

**Comment by JohanBoer** [comment]
Deze implementatie was niet bedoeld om lokaal te kunnen draaien. In de referentie-implementatie die we in de loop van dit jaar gaan opleveren is het wel de bedoeling dat dat kan.
