### ISSUE TITLE
Link properties gedefinieerd als unnamed HalLinks

### ISSUE THREAD

**Issue by MelvLee** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#380]
Properties IngeschrevenPersoon_links.partnerHistorie,
IngeschrevenPersoon_links.verblijfplaatsHistorie,
IngeschrevenPersoon_links.verblijfstitelHistorie,
IngeschrevenPersoon_links.verblijfplaatsNummeraanduiding,
Ouder_links.ingeschrevenPersoon,
Kind_links.ingeschrevenPersoon,
Partner_links.ingeschrevenPersoon,
Reisdocument_links.ingeschrevenPersonen

zijn gedefinieerd als unnamed components.
Bij code generatie wordt door Ouder_links.ingeschrevenPersoon, Kind_links.ingeschrevenPersoon en Partner_links.ingeschrevenPersoon drie IngeschrevenPersoon classes gegenereerd met namen IngeschrevenPersoon1, IngeschrevenPersoon2 en IngeschrevenPersoon3.

In principe zijn deze unnamed components equivalent aan de HalLink component. Beter is om of de HalLink component te refereren en de description van de HalLink properties op te nemen in de description van de bijbehorende component of voor de ingeschrevenPersoon properties een super component te specificeren als 

    IngeschrevenPersoon_link:
      description: De ingeschreven persoon die ouder/kind/partner is van de opgevraagde
        persoon. Deze wordt alleen opgenomen wanneer de ouder/kind/partner een ingeschreven
        persoon is.
      allOf:
      - type: object
      - $ref: '#/components/schemas/HalLink'

en deze te refereren, zodat niet allemaal classes wordt gegenereerd met willekeurige namen

**Comment by JohanBoer** [comment]
- [ ] IngeschrevenPersoon_links.partnerHistorie,
- [ ] IIngeschrevenPersoon_links.verblijfplaatsHistorie,
- [ ] IIngeschrevenPersoon_links.verblijfstitelHistorie,
- [ ] IIngeschrevenPersoon_links.verblijfplaatsNummeraanduiding,
- [ ] IOuder_links.ingeschrevenPersoon,
- [ ] IKind_links.ingeschrevenPersoon,
- [ ] IPartner_links.ingeschrevenPersoon,
- [ ] IReisdocument_links.ingeschrevenPersonen

**Comment by fsamwel** [comment]
@MelvLee uit je e-mail van dinsdagavond begrijp ik dat deze nu correct is opgelost.

**Comment by MelvLee** [comment]
> @MelvLee uit je e-mail van dinsdagavond begrijp ik dat deze nu correct is opgelost.

Ja, het is nu correct opgelost
