### ISSUE TITLE
Code 1999 bij aangaan huwelijk in het buitenland?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#383]
In AangaanHuwelijk_Partnerschap staat over property plaats: "Als de plaats een gemeente in Nederland is dan gewoon de gemeentecode + gemeentenaam . Voor een plaats buiten Nederland is gemeentecode=1999 (RNI) en gemeentenaam de buitenlandse plaatsnaam of aanduiding."

Ik vind het heel onlogisch om voor een persoon die in een niet-Nederlandse gemeente is getrouwd, aan te geven dat deze in de RNI is getrouwd. Ik zou in deze gevallen gewoon code leeg laten. In feite is dan 1999 ook een "magische code" (naast 0000 voor onbekend), en het is niet conform Lo GBA.
Dat is ook niet nodig, want de gebruiker kan ook al aan de landcode afleiden dat het niet in Nederland is.

N.B. het woord "gewoon" vind ik hier ook een beetje vreemd

**Comment by fsamwel** [comment]
@MelvLee ben je het hiermee eens of is het juist handig dat hier de code 1999 gebruikt wordt?

**Comment by JohanBoer** [comment]
Voor een plaats buiten Nederland is de gemeentecode leeg en wordt de gemeentenaam de buitenlandse plaatsnaam of aanduiding.
