### ISSUE TITLE
Naam ouder_aanduiding wijzigen naar ouderAanduiding?

### ISSUE THREAD

**Issue by Hans2131** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#393]
# Impediment

@JohanBoer 

Ik ben bezig met een aantal naamwijzigingen voor de nieuwe specs, en nu kwam ik ouder_aanduiding tegen. Volgens mij wordt _ nergens gebruikt, moet dit dus ouderAanduiding worden?

**Comment by fsamwel** [comment]
mee eens. We gebruiken voor property namen camelCase, niet snake case.

**Comment by JohanBoer** [comment]
Deze wijziging heb ik in mijn bron-bestand doorgevoerd en zal dus uiteindelijk aangepast worden in de uiteindelijke release van de 1e versie.
