### ISSUE TITLE
Beschrijving voorletters in feature aanschrijfwijze niet compleet

### ISSUE THREAD

**Issue by Hans2131** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#394]
# Impediment

De beschrijving van de voorletters in feature 'aanschrijfwijze' komt niet overeen met de beschrijving in feature 'voorletters'. 

Mist: "Als één of meerdere voornamen uit één letter bestaan, dan volgt er na de letter geen ."

Mogelijk is een verwijzing naar voorletters feature ipv een beschrijving een goed idee?

**Comment by Hans2131** [comment]
Aanvullende vraag over de voorletters:

Moet de spatie aan het einde van voorletters zonder punten weg getrimd worden? Dus: J_P_ of J_P?

**Comment by fsamwel** [comment]
> Moet de spatie aan het einde van voorletters zonder punten weg getrimd worden?

Ja. Volgens mij met er alleen een spatie na een voorletter zonder punt worden gezet, wanneer er na die voorletter nog een voorletter volgt. Resultaat is dan gelijk aan trimmen spatie aan het eind.

Dus zowel in voorletters als in aanschrijfnaam wil je nooit een spatie aan het eind, en nooit twee spaties achter elkaar

**Comment by fsamwel** [comment]
opgelost in pull request #395
