### ISSUE TITLE
Als ontwikkelaar wil ik feature 'Aanhef' (naar voorbeeld van 'Aanschrijfwijze')

### ISSUE THREAD

**Issue by gertjanvanderkooij** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#398]
... zodat ik de provider-implementatie voor dit gegeven goed kan vormgeven.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [X ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [X ] testgevallen

**Comment by JohanBoer** [comment]
Is inmiddels gerealiseerd.

**Comment by JohanBoer** [comment]
Zie document van frank dat door de hoge raad is gereviewed #399 .
