### ISSUE TITLE
Als ontwikkelaar wil ik feature 'gerbuikInLopendeTekst' (naar voorbeeld van 'Aanschrijfwijze')

### ISSUE THREAD

**Issue by gertjanvanderkooij** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#399]
...zodat ik de provider-implementatie voor dit gegeven goed kan invullen.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [X ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [X ] testgevallen

**Comment by JohanBoer** [comment]
Deze is in #334 al beschreven. Duplicate.
