### ISSUE TITLE
Als ontwikkelaar wil ik feature 'thuiswonendKind' 

### ISSUE THREAD

**Issue by gertjanvanderkooij** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#400]
...zodat ik de provider-implementatie voor dit gegeven goed kan invullen.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [X ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [X ] testgevallen

**Comment by JohnRooijakkers** [comment]
Waar kan ik de definitie vinden van thuiswonendKind?

**Comment by JohanBoer** [comment]
Dit is niet éénduidig te definieren voor alle business-processen die afnemer zijn: 
- Als een moeder komt inwonen bij haar (volwassen) kind is er geen spraken van een thusiwonend kind maar een inwonende ouder.
- Als er sprak is van gescheiden ouders en het kind woont een aantyal dagen bij de ene ouder een aan aantal dagen bij de andere ouder is de vraag welke omgangsregeling bepaalt waar het een thusiwonend kind is. 
- Kind is ouder dan 18 cq 21 (voor verschillende business processen.
- Inwonend kind is getrouwd en het stel woont bij ouders in. 
- etc.......

Onze conclusie is dat wij dus geen indicatie thuiswonend kind kunnen opleveren.

**Comment by JohanBoer** [comment]
Definitie thuiswonend kind verwijderen uit de specificatie.
