### ISSUE TITLE
Als ontwikkelaar wil ik feature 'Leeftijd' 

### ISSUE THREAD

**Issue by gertjanvanderkooij** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#401]
... zodat ik de provider-implementatie voor dit gegeven goed kan invullen. Met name hoe om te gaan met geheel of deels onbekende geboortedatum.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [X] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [X] testgevallen

**Comment by CathyDingemanse** [comment]
Ik stel voor om de leeftijd niet terug te geven wanneer de geboortedatum (deels) onbekend is. 
De wijze waarop de leeftijd dan moet worden berekend, is voor iedere businessdomein, product of dienst anders.

**Comment by gertjanvanderkooij** [comment]
Eens voor de volledig onbekende geboortedatum ;-)

Voor de deels onbekende geboortedatum (dag en/of maand onbekend) kunnen we ook een keuze maken hoe de toekomstige Gouden API 'Bevraging BRP' die afleidt; dit zo te specificeren en te implementeren. 

Hiermee wellicht ook een trend te zetten voor anderen hoe hier mee om te gaan. Consumers hebben igv deels onbekende datum altijd zelf nog de keuze om een afwijkende afleiding te maken; bv. als hier voor specifieke regelgeving bestaat (Sociaal domein 'middelt' volgens mij). 
 

Keuze kan bijvoorbeeld zijn om de leeftijd in geval van een deels onbekende datum streng, soepel of middelend af te leiden.

Onder streng afleiden versta ik indien dag en maand onbekend: 
- de nulwaarden dag en maand vervangen door de maximale waarde (resp. 31 en 12)
- vervolgens leeftijd afleiden op basis van systeemdatum

Onder streng afleiden versta ik indien alleen dag onbekend: 
- de nulwaarde dag vervangen door de maximale waarde van betreffende maand/jaar (schrikkeldag)  
- vervolgens leeftijd afleiden op basis van systeemdatum

Onder soepel afleiden versta ik indien dag en/of maand onbekend:
- de nulwaarden dag en/of maand vervangen door de minimale waarde (01)  
- vervolgens leeftijd afleiden op basis van systeemdatum

Onder middelend afleiden versta ik indien dag en maand onbekend: 
- de nulwaarden dag en maand vervangen door de resp. waarden 01 en 07
- vervolgens leeftijd afleiden op basis van systeemdatum

Onder middelend afleiden versta ik indien alleen dag onbekend: 
- de nulwaarde dag vervangen door de waarde 14 (februari) of 15 (overige maanden)  
- vervolgens leeftijd afleiden op basis van systeemdatum

**Comment by JohnRooijakkers** [comment]
Welke peildatum wordt gehanteerd voor het bepalen van de leeftijd? Als ik bijvoorbeeld de gegevens op peildatum 1 januari 2018 opvraag, dan verwacht ik ook de leeftijd op die peildatum.

**Comment by fsamwel** [comment]
@JohnRooijakkers het gaat om de actuele gegevens. We hebben dus geen peildatum

@CathyDingemanse moet leeftijd ook worden berekend voor een overleden persoon? Zo ja is dat dan de leeftijd bij overlijden of de leeftijd die de persoon nu gehad zou hebben?

**Comment by CathyDingemanse** [comment]
> @JohnRooijakkers het gaat om de actuele gegevens. We hebben dus geen peildatum
> 
> @CathyDingemanse moet leeftijd ook worden berekend voor een overleden persoon? Zo ja is dat dan de leeftijd bij overlijden of de leeftijd die de persoon nu gehad zou hebben?

Voorlopig niet, omdat ik nog geen businessvraag heb geconstateerd.

**Comment by CathyDingemanse** [comment]
gereviewd en akkoord.
