### ISSUE TITLE
Als PO wil ik dat bewoningen kunnen worden geraadplegen door een unieke adresidentificatie op te geven in een pad (nummeraanduidingidentificatie of BRPadresidentificatie)

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#402]
...zodat ik een pad kan definieren voor het opvragen van het aantal bewoningen.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
Opvragen met de identificatiecodenummeraanduiding is u als pad gedefinieerd
