### ISSUE TITLE
indicatiegeheim (geheimhoudingPersoonsgegevens) ook op subresources?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#411]
We leveren geheimhoudingPersoonsgegevens (indicatie geheim) nu mee bij de resource ingeschreven persoon. Niet bij de daarbij horende subresources ouders, partners, kinderen en reisdocumenten.

Hoort de geheimhouding niet bij alle gegevens van de PL van een persoon? Dus ook bij de betreffende subresources?

Nu wordt de gebruiker bij het alleen raadplegen van een subresource niet geattendeerd op de geheimhouding. Zou dat niet wel moeten? Dus zou geheimhoudingPersoonsgegevens niet ook in alle subresources moeten zitten?

**Comment by CathyDingemanse** [comment]
Wat een lastige is dit. De geheimhouding hoort bij de persoon, maar als alleen naar de subresource wordt gevraagd, kunnen we niet ook (verplichte gegevens) van de resource leveren. Geheimhouding toevoegen aan de subresource is onnodig redundant. Omdat het een metagegeven betreft, kunnen we hier misschien een andere oplossing voor verzinnen. 
@ MelvinLee: misschien kunnen we metagegevens in een header opnemen? Wordt dit voldoende opgemerkt door ontwikkelaars?

**Comment by MelvLee** [comment]
Een header is een mogelijke oplossing maar is waarschijnlijk niet dekkend. Als er wordt gezocht en het zoekresultaat bevat 1 of meerdere personen met geheimhouding, dan kan met een header moeilijk worden gecommuniceerd welke personen in het zoekresultaat geheimhouding hebben. Wordt de geheimhoudingPersoonsgegevens attribuut eigenlijk teruggegeven als de consumer fields gebruikt en dit attribuut niet opgeeft in de fields?

**Comment by fsamwel** [comment]
@CathyDingemanse @Melvlee @JohanBoer dit speelt ook voor de historie-resources. Nemen we daarin ook geheimhoudingPersoonsgegevens (indicatie geheim) en opschortingBijhouding op? Zo ja, hoe?

**Comment by CathyDingemanse** [comment]
> Een header is een mogelijke oplossing maar is waarschijnlijk niet dekkend. Als er wordt gezocht en het zoekresultaat bevat 1 of meerdere personen met geheimhouding, dan kan met een header moeilijk worden gecommuniceerd welke personen in het zoekresultaat geheimhouding hebben. Wordt de geheimhoudingPersoonsgegevens attribuut eigenlijk teruggegeven als de consumer fields gebruikt en dit attribuut niet opgeeft in de fields?

Ik stel voor om dit te doen. Indicatie geheim is een metagegeven, en net als opgeschort iets wat je ALTIJD aan een consumer zou moeten meegeven, ook ongevraagd, om de ons allen bekende missers te voorkomen.

Voorstel: opnemen van een header (als waarschuwing dat er geheim of opgeschorte personen in het zoekresultaat zitten of het resultaat een persoon is met indicatie geheim of opgeschort) EN bij de persoon zelf een VERPLICHTE "alert" in de body opnemen (enum?). Dit om de reden die Melvin hierboven aangeeft.

**Comment by fsamwel** [comment]
Wanneer je een "alert" opneemt, waarvoor is de header dan nog nodig?

Ik vind vertrouwen op response headers riskant, omdat:
- developers dit makkelijk over het hoofd kunnen zien
- bijv. de gegenereerde java code van de API specs (vanuit Swagger) de headers niet specifiek leest
- response headers makkelijk kwijt kunnen raken in routering over service bus of api gateway

**Comment by fsamwel** [comment]
Waarom is het toevoegen van geheimhoudingPersoonsgegevens aan elke (sub) resource geen oplossing? Zijn daar nadelen aan?

> Geheimhouding toevoegen aan de subresource is onnodig redundant.

Dit is alleen redundant wanneer je de subresource embed. Is dat erg? In dat geval zijn bijvoorbeeld ook relaties in _links redundant.

**Comment by CathyDingemanse** [comment]
> Wanneer je een "alert" opneemt, waarvoor is de header dan nog nodig?
> 
> Ik vind vertrouwen op response headers riskant, omdat:
> 
> * developers dit makkelijk over het hoofd kunnen zien
> * bijv. de gegenereerde java code van de API specs (vanuit Swagger) de headers niet specifiek leest
> * response headers makkelijk kwijt kunnen raken in routering over service bus of api gateway

Laten we dit vragen op de API Lab. Ben benieuwd wat men handig vindt!

**Comment by JohanBoer** [comment]
Ik heb, zoals 15 dagen geleden voorgesteld, Het voorstel van Frank overgenomen en de subresources partner, kind en ouder voorzien van een element boolean  "geheimhoudingPersoonsgegevens.

**Comment by fsamwel** [comment]
@JohanBoer deze heb je nog niet op GitHub doorgevoerd zo te zien (dan kan ik het ook niet reviewen)

**Comment by fsamwel** [comment]
@JohanBoer deze moet dan ook worden toegevoegd aan Verblijfstitelhistorie en Verblijfplaatshistorie

**Comment by fsamwel** [comment]
idem voor reisdocument

**Comment by JohanBoer** [comment]
Bewoners en hoofdbewoners

**Comment by JohanBoer** [comment]
- [ ] Verblijfstitelhistorie 
- [ ] Verblijfplaatshistorie
- [ ] reisdocument
- [ ] Bewoners 
- [ ] hoofdbewoners

Aangepast, In pull request gezet. Misschien pas doorvoeren na de API-LAB ?

**Comment by fsamwel** [comment]
@JohanBoer 

> Aangezien deze wijzigingen niet meer geïmplementeerd worden voor komende dinsdag stel ik voor om ze ook pas na die tijd te activeren op Github.

in de implementatie voor de api-lab is dit al toegevoegd. Dus dat hoeft geen belemmering te zijn.

**Comment by CathyDingemanse** [comment]
> in de implementatie voor de api-lab is dit al toegevoegd. Dus dat hoeft geen belemmering te zijn.

Zo fijn om een helderziende in het team te hebben! Super!
