### ISSUE TITLE
Bewoning vs bewoners

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#415]
Naar mijn idee is de constructie voor bewoningen met bewoners op dit moment wat ongelukkig:
- je zoekt adressen, kan daar dus meerdere van vinden, terwijl de functionele bedoeling is voor één adres (nummeraanduiding) de bewoners te krijgen. Gebruiker moet dus eerst in de gevonden resultaten controle dat het juiste adres is gevonden
- bewoners worden nu alleen opgenomen met de expand-parameter, terwijl bewoners de essentie is van waar de resource voor is
- zonder expand=bewoners worden links opgenomen naar bewoners, die niet op te vragen zijn (bewoners is nu geen resource in de API.
- gegevens uit adreshouding (functie adres, datum aanvang) zijn verspreid over bewoningen en bewoners, terwijl ze allen horen in de verblijfplaats van de persoon (bewoner). Zie #315

Ik zou daarom willen pleiten voor:
- een resource bewoners i.p.v. bewoningen
- met alleen query-parameter identificatiecodenummeraanduiding (er wordt dan altijd maar één adres gevonden, gebruiker kan deze identificatiecode opzoeken in de BAG-API)
- als resultaat direct bewoners terug te geven
- begin- en einddatum geldigheid van de bewoning wordt bij de bewoner opgenomen binnen groep verblijfplaats (zelfde structuur als een ingeschreven persoon)
- functieAdres van de bewoning wordt bij de bewoner opgenomen binnen groep verblijfplaats (zelfde structuur als een ingeschreven persoon)

Bijvoorbeeld:
{
  "_embedded": {
    "bewoners": [
      {
        "burgerservicenummer": "555555021",
        "geboorte": {
          "datum": {
            "dag": 3,
            "datum": "1989-05-03",
            "jaar": 1989,
            "maand": 5
          },
          "land": {
            "code": "0301",
            "omschrijving": "Nederland"
          },
          "plaats": {
            "code": "0516",
            "omschrijving": "Rotterdam"
          }
        },
        "geslachtsaanduiding": "man",
        "naam": {
          "geslachtsnaam": "Vries",
          "voornamen": "Pieter Jan",
          "voorvoegsel": "de"
        },
        "verblijfplaats": {
          "datumAanvangAdreshouding": {
            "dag": 3,
            "datum": "1989-05-03",
            "jaar": 1989,
            "maand": 5
          },
          "datumIngangGeldigheid": {
            "dag": 3,
            "datum": "1989-05-03",
            "jaar": 1989,
            "maand": 5
          },
          "datumEindeGeldigheid": {
            "dag": 31
            "datum": "2003-10-31",
            "jaar": 2003,
            "maand": 10
          },
          "functieAdres": "woonadres"
        },
        "_links": {
          "ingeschrevenPersoon": {
            "href": "datapunt.voorbeeldgemeente.nl/api/resourcename/555555021"
          },
        }
      }
    ]
  },
  "_links": {
    "self": {
      "href": "datapunt.voorbeeldgemeente.nl/api/bewoners?identificatiecodenummeraanduiding=0518200000366054"
    }
  }
}

**Comment by CathyDingemanse** [comment]
Dit op initiatief van mij, en ben het hier dan ook helemaal mee eens. Dank Frank voor de uitgebreide beschrijving!

**Comment by JohanBoer** [comment]
Ik ben het met bijna alle argumenten van Frank eens behalve :

> * als resultaat direct bewoners terug te geven

Hier heb ik wat moeite mee vanuit de samenhang van gegevens. We gebruiken een identificatie van  een nummeraanduiding en krijgen daar de resource "bewoners" als antwoord terug. 
In de resource bewoner wordt wel koppeling tussen de verblijfplaats en de persoon vormgegeven, maar niet de koppeling met de nummeraanduiding.  

Volgens mij is dat vanuit een Rest-principe niet zuiver. Dan zou op zijn minst de identificatie-nummeraanduiding onderdeel uit moeten maken van de resource bewoner.  
Mijn voorstel : 
identificatienummeraanduiding opnemen bij de verblijfsplaats en als link in _links. 

![image](https://user-images.githubusercontent.com/18071357/64171767-ba9d7700-ce53-11e9-8c40-68efeb092664.png)

**Comment by JohanBoer** [comment]
Overigens was al eerder besloten om de geslachtsaanduiding te verwijderen, geboorteland en geboortedatum is geen behoefte aan. 

Vraag n.a.v. Franks voorbeeld : Zijn voorletters gewenst ? (Staan er nu nog wel in...)

**Comment by MelvLee** [comment]
Is er een reden dat bewoners niet mbv de path  '/bewoningen/{identificatienummeraanduiding}/bewoners' is op te halen?
/bewoners?identificatienummeraanduiding={identificatienummeraanduiding} voelt voor mij minder rest-ful aan.

**Comment by JohanBoer** [comment]
Dat is een nog betere optie Melvin. Als we dat doen, dan valt het argument weg om de nummeraanduiding op te nemen in de bewoner (die zit dan immers nog in de bewoning )
Ik ben het met je eens dat dat een nettere rest-ful aanpak is dan mijn voorgestelde oplossing.

**Comment by CathyDingemanse** [comment]
> Is er een reden dat bewoners niet mbv de path '/bewoningen/{identificatienummeraanduiding}/bewoners' is op te halen?

Het is omgekeerd. De noodzaak om dat wel te doen valt weg. Als er niet meer adressen (met bewoners) in het resultaat voorkomen, dan valt de noodzaak voor bewoningen (adressen+ hun bewoners) weg, en kunnen kunnen we alleen bewoners teruggeven waarvan het opgegeven adres een eigenschap is. M.a.w. de bewoningen voelt voor mij nu als een overbodig vehicle om bij de bewoners te komen. Laten we dan gewoon gelijk bewoners ophalen. 

> /bewoners?identificatienummeraanduiding={identificatienummeraanduiding} voelt voor mij minder rest-ful aan.

De nummersaanduiding is een zoekargument en geen identificatie van de bewoningen-resource, toch? Ik kan mij voorstellen dat we naast de nummeraanduiding ook verblijfsobjectidentificatie introduceren als tweede queryparameter.

**Comment by fsamwel** [comment]
> Is er een reden dat bewoners niet mbv de path '/bewoningen/{identificatienummeraanduiding}/bewoners' is op te halen

Dit leest als: er is een resource bewoningen, geïdentificeerd met identificatienummeraanduiding, die gerelateerde resource bewoners heeft. 
Het suggereert dus dat je ook collectie /bewoningen kunt raadplegen, en resource /bewoningen/{identificatienummeraanduiding}
Zoals Cathy aangeeft is er geen behoefte aan een resource bewoningen. Het gaat om bewoners, die je kan zoeken op de identificatienummeraanduiding van hun verblijfplaats. 

@JohanBoer 
> Ik ben het met bijna alle argumenten van Frank eens behalve : als resultaat direct bewoners terug te geven

Is dat opgelost door identificatienummeraanduiding op te nemen in bewoners.verblijfplaats? En heb je daarmee je bezwaar ook weggenomen? Of blijft er dan behoefte aan bewoningen?

> geboorteland en geboortedatum is geen behoefte aan.

Wil je niet basis identificerende gegevens van de bewoners hebben? Dus naam + geboortedatum?

**Comment by CathyDingemanse** [comment]
> Overigens was al eerder besloten om de geslachtsaanduiding te verwijderen, geboorteland en geboortedatum is geen behoefte aan.
> 
> Vraag n.a.v. Franks voorbeeld : Zijn voorletters gewenst ? (Staan er nu nog wel in...)

Jazeker! Die zijn erg gewenst bij digitale aanvragen, denk bijvoorbeeld aan meeverhuizers. Geboortedatum overigens toch opnemen als onderscheidend criterium wanneer door vernoeming dezelfde voorletters worden gebruikt.

**Comment by MelvLee** [comment]
Ik wist niet of er een design keuze was om het niet te doen via /bewoningen/{identificatienummeraanduiding}/bewoners. Ik weet niet of de bewoning die mogelijk nodig is voor #251 een andere bewoning zou zijn dan deze. Zo niet, dan zou het voor mij logisch zijn om de volgende path /bewoningen/{identificatienummeraanduiding}/verhuisbewegingen te gebruiken om de verhuisbewegingen voor een adres in een periode op te vragen.
Verder dacht ik dat het handig zou zijn om bewoningen te kunnen filteren op minimaal postcode en huisnummer en daarna door te navigeren naar bewoners. Maar als er geen behoefte is voor een bewoning, voldoet voor mij /bewoners?identificatienummeraanduiding={identificatienummeraanduiding}

**Comment by JohnRooijakkers** [comment]
Ik heb nog twee aanvullende vragen:
1. worden personen die ingeschreven zijn met een briefadres ook als bewoners verstrekt? (m.i. niet)
2. worden personen met "geheimhouding" ook als bewoner verstrekt? (m.i. alleen "dat info")

**Comment by CathyDingemanse** [comment]
> Ik heb nog twee aanvullende vragen:
> 
> 1. worden personen die ingeschreven zijn met een briefadres ook als bewoners verstrekt? (m.i. niet)

Ja, deze personen worden meegegeven, waarbij wordt vermeld of het een woon- of briefadres betreft. Bijvoorbeeld bij de WMO wil je het onderscheid kunnen maken dat men op een adres is ingeschreven, maar er niet woont (en dus geen hulp kunnen bieden in de huishouding). Tevens zijn de briefadressen belangrijk voor fraude ounderzoek.

> 2. worden personen met "geheimhouding" ook als bewoner verstrekt? (m.i. alleen "dat info")
Ja, de meeste afnemers (overheidspartijen) hebben hier recht op, met daarbij de indicatie dat dit niet aan derden mag worden verstrekt. Dit is echter een kwestie van autorisatie (B&W besluit) en kan in iedere gemeente anders kan zijn.

**Comment by JohanBoer** [comment]
Deze issue is met de huidige ontwikkeling op het bewoning endpoint achterhaald volgens mij.
