### ISSUE TITLE
Omschrijvingen Swagger verblijfplaatshistorie niet correct

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#416]
# Impediment

Ik was de verblijfplaatshistorie nog even aan het reviewen op Swagger, en zie daar de volgende omschrijving:

Peildatum:
De peildatum van de periode waarover de verblijfplaatshistorie wordt opgevraagd. Het resultaat bevat de verblijfplaats historie waarvan de begindatum voor op op de peildatum ligt en de eindatum na of op de peildatum ligt.

Moet dit niet zijn: 
De peildatum waarop de verblijfplaatshistorie wordt opgevraagd. Het resultaat bevat de verblijfplaats waar de persoon op de peildatum verbleef.

Bij geldig tot:
staat dezelfde tekst als bij geldig van (De begindatum van de periode waarover de verblijfplaatshistorie wordt opgevraagd. Het resultaat bevatde verblijfplaatshistorie waarvan de begindatum op of na de datumVan ligt)
Moet dit niet zijn:
De einddatum van de periode waarover de verblijfplaatshistorie wordt opgevraagd. Het resultaat bevat de verblijfplaatsen waarvan de einddatum op of voor de datumTot ligt.

Bij Geldigvan:
De begindatum van de periode waarover de verblijfsplaathistorie wordt opgevraagd. Het resultaat bevat de verblijfplaatsen waarvan de begindatum op of na de datumVan ligt.

**Comment by JohanBoer** [comment]
Ik heb ook de corresponderende velden bij verblijfstitels en partners aangepast. Bij verblijfstitels  overigens ook nog een DatumTotEnMet. Volgens mij is daar geen business-reden voor. Uit consistentie overwegingen heb ik daar ook DatumTot van gemaakt. 
@CathyDingemanse  Kan jij bevestigen dat de wijziging naar DatumTot ok is ?

De omschrijvingen bij bewoning pak ik aan bij de grondige herziening van bewoning en bewoners.

**Comment by CathyDingemanse** [comment]
> Ik heb ook de corresponderende velden bij verblijfstitels en partners aangepast. Bij verblijfstitels overigens ook nog een DatumTotEnMet. Volgens mij is daar geen business-reden voor. Uit consistentie overwegingen heb ik daar ook DatumTot van gemaakt.
> @CathyDingemanse Kan jij bevestigen dat de wijziging naar DatumTot ok is ?

Ik zou de formulering van de BRP aanhouden. We hebben eerder besloten dat consistentie (alle tot of tot en met) negatieve effecten kan hebben die groter zijn dat het opbrengst van consistentie. Dit moeten we echt samen met de bron aanpakken. 

> De omschrijvingen bij bewoning pak ik aan bij de grondige herziening van bewoning en bewoners.
Die gaan we morgen eerst bespreken.

**Comment by JohanBoer** [comment]
De omschrijvingen van deze parameters (inmiddels zijn dat geldigop, geldig van en geldigtotenmet geworden). Zijn generiek gehouden omdat deze parameters opgenomen zijn in de common.yaml. het is nu :

geldigop:  De peildatum van de periode waarover de resource wordt opgevraagd.
geldigvan:  De begindatum van de periode waarover de resource wordt opgevraagd.
geldigtotenmet  De einddatum van de periode waarover de resource wordt opgevraagd.
