### ISSUE TITLE
Error response objecten zijn niet efficient geïmplementeerd.

### ISSUE THREAD

**Issue by KayodeBakker** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#419]
# Impediment

Tijdens de vorige API-lab zijn de error response objecten veranderd om het beter te maken voor Java code generatie. Dit resulteert helaas alleen meerdere objecten met identieke object structuren waar alleen titel/omschrijving per attribuut verschilt. Hier zou je van verwachten een gedeelt object voor te gebruiken. Dit was voorheen wel het geval waar we 2 objecten hadden (1 voor validatie errors en 1 voor de rest), maar dus verandert wegens het bovengenoemde.

Wat we nu moeten realiseren is een overzicht van objecten die niet praktisch duplicaten van elkaar zijn, maar ook goed genereert voor bijv. Java code. Voordelen hiervan zijn bijv.:
- Bij aanpassingen hoeven we niet op verschillende plekken de aanpassing maken, maar op één
- Bij het genereren van de code en het in gebruik nemen hiervan zou een ontwikkelaar minder objecten hoeven te implementeren (Wat we ook als een voordeel van Haal Centraal aangeven)
- Beter leesbaarheid van objecten structuur

Besproken met @CathyDingemanse

**Comment by KayodeBakker** [comment]
@CathyDingemanse Ik kan geen labels toevoegen of mensen assignen. Zou jij dit kunnen doen voor mij? Mijn rechten zijn niet voldoende vermoed ik.

@MelvLee  Ik wilde jou iig assignen :)

**Comment by MelvLee** [comment]
@KayodeBakker, ik heb dat gezien en ik heb, denk ik, een oplossing voor gevonden. Ik heb de oplossing via pull-request #418 aangeboden.

**Comment by CathyDingemanse** [comment]
> # Impediment
> Tijdens de vorige API-lab zijn de error response objecten veranderd om het beter te maken voor Java code generatie. Dit resulteert helaas alleen meerdere objecten met identieke object structuren waar alleen titel/omschrijving per attribuut verschilt. Hier zou je van verwachten een gedeelt object voor te gebruiken. Dit was voorheen wel het geval waar we 2 objecten hadden (1 voor validatie errors en 1 voor de rest), maar dus verandert wegens het bovengenoemde.
> 
> Wat we nu moeten realiseren is een overzicht van objecten die niet praktisch duplicaten van elkaar zijn, maar ook goed genereert voor bijv. Java code. Voordelen hiervan zijn bijv.:
> 
> * Bij aanpassingen hoeven we niet op verschillende plekken de aanpassing maken, maar op één
> * Bij het genereren van de code en het in gebruik nemen hiervan zou een ontwikkelaar minder objecten hoeven te implementeren (Wat we ook als een voordeel van Haal Centraal aangeven)
> * Beter leesbaarheid van objecten structuur
> 
> Besproken met @CathyDingemanse

Wat een timing, dit issue van de foutmeldingen is opgelost met  #418!

**Comment by CathyDingemanse** [comment]
> @CathyDingemanse Ik kan geen labels toevoegen of mensen assignen. Zou jij dit kunnen doen voor mij? Mijn rechten zijn niet voldoende vermoed ik.
> 
> @MelvLee Ik wilde jou iig assignen :)

@MelvLee zou jij Kayo als reviewer willen toevoegen op 418?

**Comment by rubenvdlinde** [comment]
Een goede morgen, vraag vanuit de geïnteresseerde mee lezer hier. Waar staan deze deze nieuwe error objecten gedocumenteerd?

**Comment by JohanBoer** [comment]
> Een goede morgen, vraag vanuit de geïnteresseerde mee lezer hier. Waar staan deze deze nieuwe error objecten gedocumenteerd?

https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/master/api-specificatie/common.yaml

**Comment by KayodeBakker** [comment]
@JohanBoer @CathyDingemanse @fsamwel 
Dit is een opmerking dat ik heb geplaatst jaren terug en heeft geen relatie aan waar we nu mee bezig zijn. Is dit een opmerking waar jullie iets van willen documenteren? Zo niet dan sluit ik dit aangezien het niet meer relevant is.
