### ISSUE TITLE
Als PO wil ik dat partnerhistorie, verblijfplaatshistorie en verblijfstitelhistorie worden geimplementeerd als extensie van partner, verblijfplaats en verblijfstitel

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#420]
...zodat de laatste objecten kunnen worden hergebruikt (.....en sneller/tijdig kunnen worden geimplementeerd voor de API lab!).

**Acceptatiecriteria**
- partnerhistorie overerft alle eigenschappen van partner en wordt uitgebreid met beeindiging (datum, reden etc.)
- verblijfplaatshistorie overerft alle eigenschappen van verblijfplaats en wordt uitgebreid met datumTot 
- verblijfstitelhistorie overerft alle eigenschappen van verblijfstitel (hoeft wellicht niet te worden veranderd?)

Misschien kan #417 komen te vervallen als dit conform #418 kan worden uitgevoerd. 

**Definition of done**
- [ ] functionele specificatie
- [x] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by fsamwel** [comment]
de datumTot voor een verblijfplaats krijgt als description: "De datum vanaf wanneer de persoon niet meer op het adres verblijft."
@CathyDingemanse is deze omschrijving duidelijk genoeg?
@JohanBoer kan jij dit zo doorvoeren in de yaml?

@KayodeBakker dit betekent dat datumTot van een verblijfplaats = datumAanvangAdreshouding van de daarop volgende verblijfplaats. Wanneer in de registratie meerdere voorkomens van adres zijn met dezelfde datumAanvangAdreshouding maar verschillende datumIngangGeldigheid, dan wordt hiervoor één regel opgenomen in de response, met de laatste (meest recente) datumIngangGeldigheid en bijbehorende (o.a. adres-) gegevens

Bijvoorbeeld wanneer er een hernummering was op 1 november 2009:
| Categorie | datumAanvangAdreshouding | datumIngangGeldigheid | Adres |
| 08 | 2002-04-15 | 2009-11-01 | Hector Berliozplantsoen 31 |
| 58 | 2002-04-15 | 2002-04-15 | Hector Berliozplantsoen 39 |
| 58 | 1997-07-01 | 1997-07-01 | Johan in 't Veltstraat 4 |

Komen in de verblijfplaatshistorie twee regels:
"verblijfplaatsen": [
{
    "huisnummer": 31,
    "naamOpenbareRuimte": "Hector Berliozplantsoen",
    "datumAanvangAdreshouding": {
      "dag": 15,
      "datum": "2002-04-15",
      "jaar": 2002,
      "maand": 4
    },
    "datumIngangGeldigheid": {
      "dag": 1,
      "datum": "2009-11-01",
      "jaar": 2009,
      "maand": 11
    }
}, {
    "huisnummer": 4,
    "naamOpenbareRuimte": "Johan in 't Veltstraat",
    "datumAanvangAdreshouding": {
      "dag": 1,
      "datum": "1997-07-01",
      "jaar": 1997,
      "maand": 7
    },
    "datumIngangGeldigheid": {
      "dag": 1,
      "datum": "1997-07-01",
      "jaar": 1997,
      "maand": 7
    },
    "datumTot": {
      "dag": 15,
      "datum": "2002-04-15",
      "jaar": 2002,
      "maand": 4
    }
} ]

**Comment by CathyDingemanse** [comment]
> de datumTot voor een verblijfplaats krijgt als description: "De datum vanaf wanneer de persoon niet meer op het adres verblijft."
> @CathyDingemanse is deze omschrijving duidelijk genoeg?

Lijkt mij prima. Misschien nog aangeven dat wanneer men verblijfplaatshistorie zoekt op een peildatum die overeenkomt met zowel datumVan van adres X en datumTot van adres Y, dan Adres X wordt teruggegeven.
