### ISSUE TITLE
Moet geheimhoudingPersoonsgegevens worden opgenomen bij waarde false?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#421]
Moet geheimhoudingPersoonsgegevens worden opgenomen bij waarde false?

Bij een aantal indicatoren/booleans, zoals inOnderzoek, wordt het element alleen in de response opgenomen bij waarde true.

Bij geheimhoudingPersoonsgegevens  staat hierover nu niks expliciet beschreven in de specificaties. 

Moet geheimhoudingPersoonsgegevens altijd worden opgenomen (met true of false) of alleen wanneer er iets met geheimhouding is (geheimhoudingPersoonsgegevens = true)?

**Comment by JohanBoer** [comment]
Volgens mij is deze boolean alleen relevant als hij op "true" staat. Ik zou niet weten waarom je in dit geval een false wle zou meeleveren. Ergo, net zo behandelen als de andere indicatoren (hiervoor is geen wijziging in de OAS nodig.

**Comment by JohanBoer** [comment]
Johan neemt op dat een boolean niet opgenomen wordt als deze "false" is in de design decisions. Als dat gedaan is kan deze op "done"
