### ISSUE TITLE
Description bij Verblijfstitel klopt niet

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#430]
De description bij Verblijfstitel bevat:
> datumEindeGeldigheid: Datum waarop de geldigheid van de gegevens over de verblijfstitel is beeindigd.
datumIngangGeldigheid: Datum waarop de gegevens over de verblijfstitel geldig zijn geworden.
aanduiding : Verblijfstiteltabel, die aangeeft over welke verblijfsrechtelijke status de ingeschrevene beschikt.

datumIngangGeldigheid en datumEindeGeldigheid zijn hernoemd naar datumIngang en datumEinde.

Ook is attribuut datumOpneming toegevoegd

**Comment by JohanBoer** [comment]
Aangepast
