### ISSUE TITLE
Hergebruik van standaard parameters

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#431]
verschillende standaardparameters zitten in common.yamlm maar deze definities worden nog niet gebruikt in de API yaml(s). Dit betreft api-version, fields, expand. Deze worden in de API yaml(s) nog opnieuw gedefinieerd voor elke operatie.

Ook parameters geldigop, geldigvan en geldigtot zouden in common.yaml kunnen worden opgenomen, zodat ze niet elke keer opnieuw hoeven te worden gedefinieerd.

**Comment by JohanBoer** [comment]
Zowel de common.yaml als de openapi.yaml aangepast.
