### ISSUE TITLE
geldigvan, geldigtot en geldigop zijn verwarrende termen voor historie parameters

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#432]
De historie bevragingen hebben drie parameters voor het filteren op een periode of peildatum.

De naam van deze parameters (geldigvan, geldigtot en geldigop) zijn verwarrend, want ze betreffen niet de geldigheid (groep 85 in de BRP) van de resources. 

Partner
- Begin (AangaanHuwelijkPartnerschap datum = 06.10)
- Eind (OntbindingHuwelijk datum = 07.10)

Verblijfplaats
- Begin (datum aanvang adreshouding = 10.30)
- Eind (datum aanvang adreshouding van volgende nieuwe record als aanwezig is)

Verblijfstitel
- Begin (datumIngang = 39.30)
- Eind (datumEinde = 39.20)

Functioneel gezien gaat het om de begin- en einddatum van de periode die bevraagd wordt, dan wel de peildatum die bevraagd wordt.

Ik denk dat een duidelijker naam voor de parameters zou zijn:

- geldigvan: periodevan
- geldigtot: periodetot
- geldigop: peildatum

**Comment by JohanBoer** [comment]
Mee eens. Ik zie dat Melvin het al doorgevoerd heeft.

**Comment by fsamwel** [comment]
opmerking van Cathy: moet worden:
geldigvan: datumvan
geldigtot: datumtotenmet
geldigop: peildatum

@johan, kan jij dit aanpassen in de historie endpoints?

**Comment by fsamwel** [comment]
@JohanBoer 
Met #472 en #473 is peildatum weer geldigop geworden.
periodvan en periodetje zijn geldigvan en geldigtotenmet geworden i.p.v. datumvan en datumtotenmet.
Kan je de aanpassingen van dit issue ook meenemen? Nu is de OAS specificatie niet consistent met de features (of andersom). Alvast bedankt!

**Comment by fsamwel** [comment]
@JohanBoer kan je deze ook nog doorvoeren?

**Comment by JohanBoer** [comment]
Johan checked of dit overal en in alle descriptions consequent is doorgevoerd. Vooral bij bewoning.
