### ISSUE TITLE
in verblijfplaatshistorie ontbreekt link verblijfplaatsNummeraanduiding

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#437]
in verblijfplaatshistorie ontbreekt link verblijfplaatsNummeraanduiding. Die had ik wel verwacht, zodat de details van de verblijfplaats opgehaald kunnen worden uit de BAG.

**Comment by JohanBoer** [comment]
link naar nummeraanduiding wordt toegevoegd en de link naar de adresseerbaarobjectaanduiding wordt ook toegevoegd. 

@Melvin ; Uitzoeken of een selflink verplicht is bij het toepassen van HAL.

Nu hebben we een selflink opgenomen, maar geen identificatie voor de resource gedefinieerd en ook geen raadpleeg endpoint gedefinieerd. Dus of die laatse twee realiseren of de selflink verwijderen.

**Comment by JohanBoer** [comment]
Alhoewel volgens HAL een Self-link opgenomen zou moeten worden kiezen we ervoor om deze niet op te nemen als het endpoint geen business-behoefte is. Dit moet ook opgenomen worden in de design Desicions.

**Comment by JohanBoer** [comment]
Adresseerbaarobject en nummeraanduiding zijn toegevoegd bij verblijfplaatshistorie en de self-link voor verblijfsplaatshistorie verwijderd.

**Comment by fsamwel** [comment]
@JohanBoer 
> link naar nummeraanduiding wordt toegevoegd en de link naar de adresseerbaarobjectaanduiding wordt ook toegevoegd.

De link naar de nummeraanduiding zit er nu in, de link naar de adresseerbaarobjectaanduiding niet. Is dat een bewuste keuze geweest?

**Comment by JohanBoer** [comment]
@fsamwel 

Ik zie dit op de huidige repository 
![image](https://user-images.githubusercontent.com/18071357/69344134-2c28dc80-0c6f-11ea-9023-cf1f55820b58.png)

Kan jij mij aangeven wat jij denkt dat er ontbreekt ?

**Comment by fsamwel** [comment]
je hebt gelijk, heb denk ik verkeerd gekeken vanochtend.

**Comment by JohanBoer** [comment]
No worries. Ben sowieso heel blij dat je gedetailleerd meekijkt.
