### ISSUE TITLE
Aanpassen gemeenten resource

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#441]
Ik stel een aantal aanpassingen voor voor de Landelijke tabellen api.

- verwijderen parameters datumbegin, datumeinde en nieuwecode. Ik zie niet voor me hoe iemand een gemeente wil zoeken op de datum dat deze is opgevoerd of beëindigd
- description voor omschrijving toevoegen dat dit de naam van de gemeente is. ook melden dat dit hoofdletter ongevoelig is en wildcards worden ondersteund
- link "gemeenten" wijzigen in "overgegaanIn", anders is niet duidelijk wat dit is. in description van 
- attribuut nieuweCode verwijderen. Volgens mij heeft de genoemde gemeente niet een nieuwe code gekregen, maar is (meestal) de gemeente overgegaan in een andere gemeente (door samengaan van meerdere gemeenten). deze nieuwe gemeente is al opgenomen in _links. Je zou kunnen overwegen een groep "overgegaanIn" kunnen maken als waardetabel (met dus code én naam van de nieuwe gemeente).
- halpaginationlinks toevoegen aan common.yaml (zit er nu niet in, dus yaml voor landelijke tabellen is nu niet valide)
- response 404 toevoegen aan /tabellen/gemeenten/{code}
- response gemeente definiëren als extensie op Waardetabel (van ingeschreven personen api)

**Comment by JohanBoer** [comment]
> * attribuut nieuweCode verwijderen. Volgens mij heeft de genoemde gemeente niet een nieuwe code gekregen, maar is (meestal) de gemeente overgegaan in een andere gemeente (door samengaan van meerdere gemeenten). deze nieuwe gemeente is al opgenomen in _links. Je zou kunnen overwegen een groep "overgegaanIn" kunnen maken als waardetabel (met dus code én naam van de nieuwe gemeente).

Mijn idee was om een simpele API-ontsluiting te definieren om de tabellen te ontsluiten zoals die nu middels de PDF's worden ontsluiten. 
Nieuwe code is onderdeel van die tabel. Als we de betekenis en de samenhang van attributen willen doorgronden, dan moeten we met de beheerders van de tabellen gaan praten om zeker te weten dat we de juiste betekenissen doorvoeren. 


> * response gemeente definiëren als extensie op Waardetabel (van ingeschreven personen api)

Dit is voor nu een stap te ver naar mijn mening. Zie ook het argument hierboven. Daarbij wordt dit een aparte API lijkt mij.

**Comment by fsamwel** [comment]
@JohanBoer naam mijn idee maken we dit voor #333: "Als ontwikkelaar wil ik de gemeentecode/gemeentenaam-tabel uit een centrale bron halen, zodat ik deze niet zelf hoef te beheren"
Klein en simpel beginnen betekent naar mijn idee alleen opnemen waar om gevraagd is in de user story: gemeentecode en gemeentenaam. De rest is niet om gevraagd en zou ik dus weglaten, want maakt het moeilijker om te implementeren, levert meer (gegenereerde en te beheren) code op en moeilijker te doorgronden.
Vandaar dat ik ook denk dat de tabel (elke te ontsluiten tabel) gedefinieerd wordt met component Waardetabel: code + omschrijving.
Voordeel daarvan is hergebruik en een generieke, extreem eenvoudige oplossing voor alle (nu of eventueel later) te ontsluiten landelijke tabellen.

**Comment by fsamwel** [comment]
met mijn opmerking (zie hierboven) is niks gedaan. 

@CathyDingemanse We hebben nu alleen de tabel gemeenten ontsloten. Ik denk mij te herinneren dat jij ooit gezegd hebt dat alle GBA tabellen op deze manier ontsloten moeten worden.

Klopt dat en moet dat vóór het API-lab in december doorgevoerd zijn?

**Comment by JohanBoer** [comment]
> We hebben nu alleen de tabel gemeenten ontsloten. Ik denk mij te herinneren dat jij ooit gezegd hebt dat alle GBA tabellen op deze manier ontsloten moeten worden.

En wat zijn dan "alle" GBA-tabellen ?

**Comment by fsamwel** [comment]
> En wat zijn dan "alle" GBA-tabellen ?

Zie http://publicaties.rvig.nl/Landelijke_tabellen/Landelijke_tabellen_32_t_m_60_excl_tabel_35

**Comment by fsamwel** [comment]
Tabel 32 | Nationaliteitentabel 
Tabel 33 | Gemeententabel 
Tabel 34 | Landentabel
Tabel 36 | Voorvoegseltabel
Tabel 37 | Tabel Reden verkrijging/verlies Nederlanderschap
Tabel 38 | Tabel Adellijke titel/predikaat
Tabel 39 | Tabel Akteaanduiding
Tabel 41 | Tabel Reden ontbinding/nietigverklaring huwelijk/geregistreerd partnerschap
Tabel 48 | Tabel Nederlands reisdocument
Tabel 49 | Tabel Autoriteit van afgifte Nederlands reisdocument
Tabel 56 | Verblijfstiteltabel

Tabel 39 is denk ik niet relevant, we hebben ook geen aktegegevens opgenomen in de API
Tabel 49 is een wat afwijkende, deze bevat bijvoorbeeld B•••• Burgemeester van gecodeerd genoemde gemeente, die kan voorkomen als bijvoorbeeld B0518 wat betekent Burgemeester van 's-Gravenhage. Daar moeten we dus nog eens over nadenken hoe die ontsloten zou moeten worden.

**Comment by gertjanvanderkooij** [comment]
Als we er al meer doen, dan alleen voor elementen die we nu gekenmerkt hebben als 'Waardetabel'.

Tabel 36, 38, 39 vallen dan af.
Tabel 49 ook; eens met Frank.

**Comment by gertjanvanderkooij** [comment]
Vwb specificatie .(meegeven geldigheidperiode, opgegaan in) ... dit is geheel afhankelijk van gebruik. Ik kan me formulieren en apps voorstellen waarbij gegevens ingevoerd moeten worden; dan wil je voorkomen dat niet meer geldige waarden worden ingevoerd. Ergo ... wie is hier de consumer?

**Comment by JohanBoer** [comment]
> @JohanBoer naam mijn idee maken we dit voor #333: "Als ontwikkelaar wil ik de gemeentecode/gemeentenaam-tabel uit een centrale bron halen, zodat ik deze niet zelf hoef te beheren"
> Klein en simpel beginnen betekent naar mijn idee alleen opnemen waar om gevraagd is in de user story: gemeentecode en gemeentenaam. De rest is niet om gevraagd en zou ik dus weglaten, want maakt het moeilijker om te implementeren, levert meer (gegenereerde en te beheren) code op en moeilijker te doorgronden.

@Frank : opnemen waar om is gevraagd is ook de hele user-story lezen. Er is letterlijk naar de gehele tabel (historische data)  gevraagd in de acceptatiecriteria van #333. Dat is waarom ik deze opzet zo gemaakt heb. 

We kunnen natuurlijk besluiten dat we nog dit beperkter en developer-vriendelijker op gaan zetten. We kunnen de tabellen zo gaan ontsluiten dat die naadloos op de structuur passen die we binnen de OAS3 van ingeschreven_persoon hebben toegepast op basis van #281 , 

Dat is natuurlijk best een beslissing, want we gaan dan voorbij aan de wens in een user-story. Het lijkt mij dat we die even moeten bespreken (morgen lijkt mij een mooi moment). 

> We hebben nu alleen de tabel gemeenten ontsloten. Ik denk mij te herinneren dat jij ooit gezegd hebt dat alle GBA tabellen op deze manier ontsloten moeten worden.

Hier kan ik dan weer geen user-story bij vinden. Alleen van de tabellen 33 (#333 )en 38 (#336). 
We hebben echter besloten dat we AdelijkeTitelPredikaat niet gaan uitleveren, dus tabel 38 hoeft dan ook niet (door ons) ontsloten te worden. 

Het kan allemaal en ik vind het ook geen probleem, maar wel graag als we het goed doorgenomen hebben en duidelijk is wat we willen. Wat mij betreft maken we dus morgen afspraken over 
 - [ ] welke tabellen hebben we het over.
 - [ ] in welke vorm gaan we ze ontsluiten
 - [ ] wanneer moet dat klaar zijn.

**Comment by JanWillemKooi** [comment]
De tabellen zijn ook in csv beschikbaar.
http://publicaties.rvig.nl/Landelijke_tabellen/Landelijke_tabellen_32_t_m_60_excl_tabel_35/Landelijke_Tabellen_32_t_m_60_in_csv_formaat

**Comment by JohanBoer** [comment]
> [ ] in welke vorm gaan we ze ontsluiten

In de Common.yaml nemen we de waardetabel op met code en omschrijving. In de ingeschrevenpersoon wordt daarnaar geref-d. Ook in de landelijke tabellen API wordt naar die common.yaml verwezen en indien nodig wordt daarop extend.

> [ ] welke tabellen hebben we het over.

Tabel 32 | Nationaliteitentabel
Tabel 33 | Gemeententabel
Tabel 34 | Landentabel
Tabel 37 | Tabel Reden verkrijging/verlies Nederlanderschap
Tabel 41 | Tabel Reden ontbinding/nietigverklaring huwelijk/geregistreerd partnerschap
Tabel 48 | Tabel Nederlands reisdocument
Tabel 56 | Verblijfstiteltabel

> * wanneer moet dat klaar zijn.

Maandag. 

Functioneel : Default leveren we alleen actuele content en als je ook beëindigde waarde terug wilt krijgen dan kan daarvoor de query-parameter "inclusiefbeeindigd". 
Andere query-parameters zijn "code" en "omschrijving"

**Comment by JohanBoer** [comment]
Voor de landelijke tabellen kiezen wordt de "alternatieve variant" degene die we gaan gebruiken. Johan verwijdert de andere variant en we gaan binnen VNG voorstellen om deze versie breder te gaan gebruiken.  We gaan deze direct met de bevraging ingeschreven persoon vaststellen. 

Indien dit gedaan is mag deze in done.

**Comment by JohanBoer** [comment]
Aangepast.
