### ISSUE TITLE
zoeken op burgerservicenummer en inclusiefoverledenpersonen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#445]
We kunnen nu ook personen zoeken op burgerservicenummer. 

Hoe moet dit werken in combinatie met inclusiefoverledenpersonen?
Wanneer inclusiefoverledenpersonen niet is opgenomen of waarde false heeft, moet zoeken op burgerservicenummer dan alleen de persoon teruggeven wanneer deze leeft?

**Comment by KayodeBakker** [comment]
Voordat we hier aanpassingen voor gaan maken, zijn we zeker van het feit dat we burgerservicenummer als zoek parameter willen gebruiken? In #327 is het besluit gemaakt om de 404 error te ontwijken met name als reden dat als een burgerservicenummer wel zou bestaan en valide zou zijn, maar niet beschikbaar is in de registratie die er als bron onderhangt. Hoe vaak zou dit voorkomen en is dit niet een tijdelijke scenario voordat we voor binnen- en buitengemeentelijke personen een gezamelijke bron hebben?

Ik zou graag willen weten in welke casus dit vaak voorkomt en of dit niet, zoals met duplicate burgerservicenummers, een weinig voorkomende uitzonderingscasus is? Mochten we later toch op 1 bron komen te zitten en we backwards compatibility (geen breaking changes) ondersteunen dan kunnen we de burgerservicenummer als zoek parameter er niet meer uithalen terwijl de nut ervan niet meer bestaat. Op dat punt zou het logisch zijn om een fout te gooien op een invalide of niet bestaande burgerservicenummer.

Wat is hier het meest logische?

**Comment by JohanBoer** [comment]
De casus waarom deze zoek-parameter is toegevoegd is dat bij het opvoeren van een persoon in bv. een zaaksysteem (en dit geldt voor veel afnemers) een burgerservicenummer ingetikt wordt door de useren de consumer doet dan een check of dit een bestaand burgerservicenummer is ( en eventueel de naam tonen ter verificatie) .
Mocht er een tikfout gemaakt zijn in het bsn en bestaat deze niet, dan wil de consumer een lege array terugkrijgen en niet gedwongen zijn de doutafhandeling te doen.
