### ISSUE TITLE
Mogelijkheid tot zoeken op gegevens (rubrieken) zonder waarde

### ISSUE THREAD

**Issue by rudieschonenberg** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#446]
Het zou handig zijn om expliciet te kunnen zoeken naar personen waarbij een rubriek leeg is.
Dit wordt wel eens gebruikt bij het zoeken naar verblijfplaats gegevens (denk aan huisnummeraanduiding of huisletter)

Bij de gba-v bevraging is dit mogelijk door gebruik te maken van het uitschakelen van slim zoeken (zie Logisch Ontwerp 3.12 paragraaf C.7.3.2).

**Comment by JohanBoer** [comment]
Zoeken op lege waarden wordt niet ondersteund in deze API. 
We willen niet op basis van "magic strings" zoek acties ondersteunen.
