### ISSUE TITLE
Mogelijkheid tot zoeken met geboortedatum onbekend

### ISSUE THREAD

**Issue by rudieschonenberg** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#447]
Het is niet mogelijk om te zoeken met de parameter 'geboorte__datum' waarbij als waarde een geboortedatum onbekend wordt gebruikt (bijv. 1992-00-00 of 1992*). Bij de gba-v bevraging is dit wel mogelijk. Zie paragraaf I.2.7 van Logisch Ontwerp 3.12 (opname van datums)).

**Comment by CathyDingemanse** [comment]
Beste Rudie, kun je mij uitleggen waarom je dit nodig hebt, en op welke manier je deze functionaliteit wilt gebruiken?

**Comment by rudieschonenberg** [comment]
Beste Cathy,
Deze opmerking heb ik gemaakt tijdens de 2de API lab bijeenkomst. Hiermee wilde ik aangeven dat het momenteel (bij een GBA-V vraag) mogelijk is voor afnemers om te zoeken met alleen geboortejaar (dus bijv. 1992*).

Mocht een afnemer gebruik maken van de zoek parameter geboorte_datum, dan zullen daar (denk ik) nooit personen gevonden worden waarbij de maand of dag onbekend is.
In hoeverre dit ook echt wordt gebruikt door afnemers is me niet bekend.

**Comment by JohanBoer** [comment]
Het zoeken op een onbekende geboortedatum is geen business-vraag die wij in het veld zijn tegengekomen.
