### ISSUE TITLE
Woonplaats altijd opnemen bij verblijfplaats

### ISSUE THREAD

**Issue by wvnoortroxit** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#448]
Het lijkt erop dat de woonplaats bij de verblijfplaats alleen wordt teruggeven als die afwijkt van de gemeentenaam. 

Als applicatieontwikkelaar wil ik de woonplaats altijd terugkrijgen zodat ik die direct kan gebruiken om aan de eindgebruiker te tonen.

**Comment by CathyDingemanse** [comment]
Ja, deze moet altijd worden gevuld. Dit moet de provider oplossen (obv postcode huisnummer de woonplaats ophalen?).
