### ISSUE TITLE
Gebruik van uuid bij opvragen relaties

### ISSUE THREAD

**Issue by hansvandijk93** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#449]
Eén van de issues die bij een gesprek met @JohanBoer en een deelnemer van de laatste api lab naar boven kwam was het incorrecte gebruik van uuid bij het opvragen van een enkele relatie. Ik zie dit issue niet terugkomen in de lijst, dus ik voer hem alsnog op.

Op dit moment worden relaties (bijv kinderen) gesorteerd op een datum(bijv. geboortejaar) en wordt er een uuid gekoppeld op basis van volgorde. Dus het oudste kind is resource kinderen/1, ouder 1 is ouder/1 en de eerste actuele partner wordt partner/1.

Deze oplossing hebben we destijds gekozen omdat er geen uniek getal (uuid) kon worden gekoppeld aan een relatie. De gbav levert het niet, en wij kunnen ook geen persisterende uuid koppelen aan een resource.

Nu is de andere oplossing dat we het de paden met uuid niet langer aanbieden aan de afnemer omdat uuid technisch gezien nu simpelweg niet mogelijk is. Dat betekent dat een afnemer alle kinderen/partners/ouder ophaalt en zelf bepaald welke specifieke resource uit de lijst gebruikt wordt. 

@JohanBoer nog aanvullingen?

**Comment by JohanBoer** [comment]
Beschrijven dat dit risico nu bestaat. Als de consumer de identificatie van de partner opslaat en daar wordt 1 voor gebruikt dan zou in geval van een nieuwe partner in de toekomst een ander persoon onder dezelfde identificatie kunnen worden vastgelegd. 

De specificatie (met UUID) elimineert dit probleem,maar dat is nu niet implementeerbaar omdat de UUID niet gepersisteerd kan worden. 

Het beschrijven van dit issuie moet worden opgenomen in een aansluitdocument.

**Comment by JohanBoer** [comment]
UUID vervangen door ID (string)

**Comment by fsamwel** [comment]
@JohanBoer Er zitten nog enkele typefoutjes in de descripties bij de Ids:

In /ingeschrevenpersonen/{burgerservicenummer}/kinderen/{id}:
> description: "Deidentifiatie van het kind."

Hier moet een spatie bij tussen De en identificatie.

In /ingeschrevenpersonen/{burgerservicenummer}/partners/{id}:
> description: "Deidentifiatie van het kind."

Dit is de identificatie van de partner. En ook hier graag spatie na De
