### ISSUE TITLE
Als leverancier wil ik weten hoe we de gespecificeerde versionering (ondersteunen van verschillende versies in de header) technisch moeten ondersteunen

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#453]
...zodat de impact hiervan kan worden bepaald.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
Maak een beschrijving

**Comment by fsamwel** [comment]
@MelvLee @JohanBoer @CathyDingemanse we hebben afgesproken dat we alleen vragen om een major versie ondersteunen met de version header (dus niet een specifieke minor of patchversie).
Betekent dit dat we de version header kunnen definiëren als integer? Of moeten we voor de toekomst de mogelijkheid open houden ook vragen om een minor versie mogelijk te maken?

**Comment by JohanBoer** [comment]
Die afspraak om alleen de major versie in de header te communiceren klopt mijns inziens. 
Minor versies en patches zijn backward compatibel. 
Welk voordeel biedt het om de version-header als integer te definiëren ?

**Comment by fsamwel** [comment]
> Welk voordeel biedt het om de version-header als integer te definiëren ?

De makkelijkste en duidelijkste manier om te definiëren dat er alleen cijfers mogen worden opgegeven is definiëren als integer. Is semantisch ook het meest correct, want het gaat om een tel/volgnummer.

Voordeel van definiëren als string is dat we dan later backwards compatible kunnen gaan toestaan dat ook minor versie wordt opgegeven.

**Comment by MelvLee** [comment]
Ik ben het mee eens om de type van version header als een integer te definieren. Dan is het ook niet mogelijk om een minor versie op te geven. Ik verwacht niet dat we ooit een minor versie zullen opnemen. Voor een provider is het volgens mij niet mogelijk om daaraan te kunnen voldoen

**Comment by CathyDingemanse** [comment]
Het leveren van een minor versie op aanvraag is ongelofelijk complex voor de provider. Vooralsnog is het onduidelijk wat het een consumer oplevert. 
Conclusie die volgens mij door iedereen wordt gedeeld: alleen de mogelijkheid bieden major versies op te vragen, en deze als integer definiëren.

**Comment by CathyDingemanse** [comment]
Was ik te snel? :-) Sorry!

**Comment by JohanBoer** [comment]
Duidelijk, maar voordat we deze sluiten ga ik dat eerst nog even doorvoeren. Anders raakt hij uit beeld :)
