### ISSUE TITLE
Implementatie-issues 

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#455]
Feedback van Maarten van den Broek gekregen met de observatie dat er nu voor providers geen duidelijkheid is over de implementatie bij providers. Zijn stelling (of mijn interpretatie daarvan)  is dat er grote verschillen zijn tussen de gegevensmagazijnen als het gaat om de dataset die ze ondersteunen. 
Dat betekent dat het aantal mogelijk ingevulde elementen per provider-implementatie kan verschillen omdat verschillende gegevensmagazijnen de GBA-modellering meer of minder ondersteunen. En dat het dus niet duidelijk is wat de consumer kan verwachten.

Maarten stelt voor hier duidelijkheid over te verschaffen. Dat kan zijn door duidelijk te maken dat een providerimplementatie die nauwelijks gevulde elementen terug levert (kan leveren) ook een juiste implementatie van de standaard is. Een andere oplossing is om enkele profielen van de API-definieren met verschillende gegevenssets die dan minimaal ondersteund moeten zijn. 

Alternatief is om deze API alleen voor te schrijven op de GBA-systemen die wel de gegevens beschikbaar hebben om de response te vullen. 

Gaarne onderling discussie over dit onderwerp.

**Comment by mvdbro** [comment]
Dank voor deze goede samenvatting van ons gesprek

**Comment by koengillissen** [comment]
Interessant onderwerp. Ik heb wat vragen:
- Wie wordt er met de providers bedoeld? 
- Voor BRP maken wij nu gebruik nu  van een SOAP webservice van T&T vertrouwd verbonden. Voor HR van Yenlo. Zijn dat providers? 
- En levert Haal Centraal API enkel een API beschrijving of ook een referentie API op?
- En waar kan ik de referentie API's aanroepen?

**Comment by mvdbro** [comment]
Met providers heb ik partijen bedoeld die een implementatie bieden van de Haal Centraal API. Zo lang de BRP deze API niet centraal implementeert, zijn andere providers nodig, bijv. T&T of een implementatie op bestaande gegevensmagazijnen.

**Comment by JohanBoer** [comment]
> * En levert Haal Centraal API enkel een API beschrijving of ook een referentie API op?
> * En waar kan ik de referentie API's aanroepen?

Er zijn op dit ogenblik 2 referentie implementaties waarvan er 1 openbaar bereikbaar is.
Op haalcentraal.lostlemon.nl  is nu een referentieimplementatie beschikbaar die in opdracht van VNG is gerealiseerd. Doel van deze implementatie was primair om de specificatie te controleren op inmlementeerbaarheid. Er zitten een beperkt aantal testgevallen onder.

**Comment by koengillissen** [comment]
zijn  er concreet providers die deze API definite al implementeren? en wat is de status van deze API definitie?

**Comment by JohanBoer** [comment]
> zijn er concreet providers die deze API definite al implementeren? en wat is de status van deze API definitie?

In de gemeente Den Bosch is men bezig met een binnengemeentelijke implementatie van deze API voor de huwelijksplanner.  Ook de gemeente Den Haag maakt een binnengemeentelijke implementatie. Deze gemeentes hebben er voor gekozen om aan de slag te gaan terwijl de specificaties nog niet 100% stabiel zijn. Dat is een risico natuurlijk, maar wij verwachten geen hele grote wijzigingen meer op de specificaties. 

We brengen begin december een nieuwe release-candidate uit die op een API-lab op 10 december aan de tand gevoeld mag worden door gemeenten en leveranciers. Als daar geen impedements uitkomen zal dat de eerste versie worden.

**Comment by koengillissen** [comment]
Dank je Johan voor de reacties. Dat zijn eigen implementaties van Haal Centraal BRP die zelf direct op de BRP aansluiten via hun broker bijv. T&T of Yenlo? Moet ik het zo zien?

**Comment by CathyDingemanse** [comment]
Het Haal Centraal programma levert in principe voor ieder basisregistratie-domein een API op, aangeboden door de betreffende Landelijke Registratie (bronhouder of LV). Deze API wordt t.z.t. aangeboden door de RvIG aan gemeenten. Over wanneer dat gebeurt, en welke versie van de API door de RvIG zal worden aangeboden is nog niet zeker. Daarvoor is de RvIG nu een plan aan het opstellen, dat in januari aan onze stuurgroep wordt aangeboden. 
Omdat de RvIG API iig niet morgen klaar is, hebben de gemeente Den Haag en andere gemeenten er voor gekozen om deze API tijdelijk op het gegevensmagazijn of GBA systeem aan te bieden. Voordeel hiervan is dat de migratie van binnengemeentelijke afnemers al kan worden ingezet. Er hoeven geen nieuwe stuf koppelingen te worden gemaakt, en het aantal te migreren stuf koppelingen groeit niet meer.
Het is belangrijk om je te realiseren dat Haal Centraal niet als doelstelling heeft om een standaard te maken die door tig providers en op tig plekken wordt geïmplementeerd. Wij gaan als programma dus ook geen "gegevenssets" of andere criteria definiëren voor leveranciers om compliancy vinkjes te halen als provider van de API. Wel moedigen wij iedereen aan om in het kader van een snelle en voorspoedige migratie, vooruitlopend op de RvIG, de API te implementeren. Daarom is er een referentie-implementatie beschikbaar en zijn er features gedefinieerd waarin alle businesslogica en mappingsissues naar het LO GBA worden geadresseerd. Hoop dat je hier iets aan hebt!
