### ISSUE TITLE
indicatieHuwelijkPartnerschapBeeindigd ontbreekt in partnerhistorie

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#467]
Alle gegevens van ontbindingHuwelijkPartnerschap zijn mogelijk onbekend, zodat het mogelijk is dat een ontbonden huwelijk/partnerschap wordt opgenomen zonder ontbindingHuwelijkPartnerschap. De gebruiker weet dan niet dat het huwelijk is ontbonden.

Hiervoor zou dan in partnerhistorie indicatieHuwelijkPartnerschapBeeindigd moeten worden opgenomen.

**Comment by JohanBoer** [comment]
Ook bij verblijfstitelhistorie een vergelijkbare indicatie opvoeren voor als de datum-onbekend volledig onbekend is (die leveren we namelijkniet terwijl de verblijfstitel wel beëindigd is.

**Comment by fsamwel** [comment]
@JohanBoer indicatieHuwelijkPartnerschapBeeindigd is nu toegevoegd, maar de description bevat "verbintenis" die ik niet begrijp:
> indicatieHuwelijkPartnerschapBeeindigd:
          type: "boolean"
          description: "Indicatie of het huwelijk ontbonden is danwel het partnerschap beeindigd is.\
        \ verbintenis:\n* `True` - Huwelijk/Partnerschap is beeindigd."

Kan je dit wijzigen (verwijderen "verbintenis") naar:
> indicatieHuwelijkPartnerschapBeeindigd:
          type: "boolean"
          description: "Indicatie of het huwelijk ontbonden is danwel het partnerschap beeindigd is:\
        \ \n* `True` - Huwelijk/Partnerschap is beeindigd."

**Comment by JohanBoer** [comment]
Frank checkt, indien ok, dan naar done

**Comment by fsamwel** [comment]
> Ook bij verblijfstitelhistorie een vergelijkbare indicatie opvoeren voor als de datum-onbekend volledig onbekend is (die leveren we namelijkniet terwijl de verblijfstitel wel beëindigd is.

@JohanBoer dit was niet terecht. In het geval de datumEinde = 00000000 voor een verblijfstitel, dan is er geen einddatum bepaald en is deze dus nog (en voorlopig oneindig) geldig. Dus is het hier terecht dat 00000000 in de API komt als leeg.
Kan je de indicator indicatieVerblijfstitelBeeindigd verwijderen?

**Comment by JohanBoer** [comment]
> In het geval de datumEinde = 00000000 voor een verblijfstitel, dan is er geen einddatum bepaald en is deze dus nog (en voorlopig oneindig) geldig.

Hoi Frank, waarop baseer jij de bovenstaande stelling ? Uit het LO GBA haal ik dat bij 00000000 de einddatum onbekend is. Niet dat hij nog niet bepaald is. Dat zou kunnen betekenen dat de verblijfstitel wel een einddatum heeft, maar dat die niet bekend is. Dat heb je die indicatie volgens mij wel nodig.

Begrijp ik dat dan verkeerd ? 

 Ik haal hem overigens moeiteloos weg als jij ervan overtuigd bent dat jouw stelling klopt.

**Comment by fsamwel** [comment]
> Hoi Frank, waarop baseer jij de bovenstaande stelling ?

Ik heb dit nagevraagd bij een BRP specialist van gemeente Den Haag.

De datum einde (39.20) kan in de toekomst liggen. Deze wordt gevuld bij het toekennen van de verblijfstitel, wanneer het een verblijfstitel voor bepaalde tijd is. Maar hier kan dus ook 00000000 worden ingevuld, en dat gebeurt in de praktijk ook (zo begrijp ik). 
Uit het feit dat de einddatum is gevuld kan daarom niet worden geconcludeerd dat de verblijfstitel al is beëindigd. En kan in die situatie indicatieVerblijfstitelBeeindigd niet worden bepaald.

Die conclusie kan wel worden getrokken wanneer er een andere verblijfstitel is met een jongere ingangsdatum. In dat geval vullen we datumEindeGeldigheid met die ingangsdatum van de nieuwe verblijfstitel en is indicatieVerblijfstitelBeeindigd niet nodig.

**Comment by JohanBoer** [comment]
Top. Dankjewel. Duidelijk verhaal. 
Maar goed dat er specialisten zijn want dit is niet in de LO GBA documentatie terug te vinden. 

Ik verwijder de indicator indicatieVerblijfstitelBeeindigd.

**Comment by gertjanvanderkooij** [comment]
Mogelijk gaan we iets te snel!
@fsamwel 
Wil jij eens kijken naar testpersoon met BSN: 999990317. Stel dat de eerste drie rijen VBT's (de 60-ers) een 85.10 zouden hebben van '00000000' (wat volgens LO GBA mogelijk is); wat zou dan het eindresultaat in de API-response zijn?

NB. Wat ik bij de VBT ook lastig vind, is het feit dat via de code (39.10) wordt bepaald of een persoon geen verblijfstitel meer heeft; code 98 - Geen verblijfstitel (meer). Is dat consumer-friendly enough?

**Comment by fsamwel** [comment]
@gertjanvanderkooij 
> Stel dat de eerste drie rijen VBT's (de 60-ers) een 85.10 zouden hebben van '00000000' 

We kijken volgens mij niet naar 85.10, alleen naar 39.30 (datum ingang) en 39.20 (datum einde).

Wanneer er overlap is tussen verblijfstitels op basis van 39.20 en 39.30, dan wordt in de API de overlap opgelost. Dit is beschreven in de verblijfstitelhistorie:
> Er kan op enig moment in de tijd maximaal één verblijfstitel geldig zijn.
  Als de datum einde geldigheid van een verblijfstitel ligt na de ingangsdatum van een volgende verblijfstitel, dan wordt voor de eerste verblijfstitel datumEinde gevuld met de ingangsdatum van de volgende verblijfstitel.
  Als de datum einde geldigheid van een verblijfstitel leeg is en er is een volgende verblijfstitel, dan wordt voor de eerste verblijfstitel datumEinde gevuld met de ingangsdatum van de volgende verblijfstitel.
  Als er meerdere (historische) verblijfstitels zijn met dezelfde ingangsdatum, dan wordt alleen de meest de meest recente opgenomen in het antwoord. Dat is de meest recente datum opneming, of eerste/bovenste in GBA-V antwoord.
  Als er een verblijfstitel geldig is over de hele geldigheid van een eerder opgevoerde verblijfstitel, dan wordt alleen de meest recente opgenomen in het antwoord. Dat is de meest recente datum opneming, of eerste/bovenste in GBA-V antwoord.

Dus als in de registratie 39.20 (datum einde) gelijk is aan 00000000, en er is een actuele(re) verblijfstitel, dan wordt datumEinde van de historische verblijfstitel gevuld met 39.30 (datum ingang) van de volgende verblijfstitel.
Om dit te doen moeten de verblijfstitels eerst in de juiste volgorde worden geplaatst. Dit gebeurt eerst op 39.30, vervolgens op 86.10 (opneming), en desnoods op volgorde in het GBA-V antwoord (of in de database op technische sleutel o.i.d.).
Ik hoop trouwens dat dit alles alleen theoretisch is. De Nederlandse overheid bepaalt verblijfstitels, dus zou toch moeten weten tot wanneer een verblijfstitel geldig is en wanneer deze is geregistreerd.

**Comment by fsamwel** [comment]
> NB. Wat ik bij de VBT ook lastig vind, is het feit dat via de code (39.10) wordt bepaald of een persoon geen verblijfstitel meer heeft; code 98 - Geen verblijfstitel (meer). Is dat consumer-friendly enough?

In Lo GBA 3.11 zie in in §3.11.3 (intrekken verblijfstitel) en §3.11.4 (vervallen verblijfstitel) dat alleen groepen 85 en 86 worden gevuld. Blijkbaar kunnen we er niet op vertrouwen dat een verblijfstitel altijd wordt beëindigd door een verblijfstitel met aanduiding 98 op te voeren.

Ik zal de feature aanpassen met de volgende regels:
> Als voor een verblijfstitel groep 39 niet is gevuld, maar geldigheid (85.10) of opneming (86.10) wel, dan wordt deze niet opgenomen in het antwoord. Als de einddatum (39.20) van de voorgaande verblijfstitel leeg is, 00000000 of na de geldigheidsdatum van genoemde verblijfstitel ligt, dan wordt voor de voorgaande verblijfstitel als datumEinde de waarde in 85.10 van de lege verblijfstitel genomen.
>  
 > Als voor een verblijfstitel de aanduiding gelijk is aan 98 "geen verblijfstitel (meer)", dan wordt deze verblijfstitel niet opgenomen in het antwoord. Als de einddatum (39.20) van de voorgaande verblijfstitel leeg is, 00000000 of na de geldigheidsdatum van de verblijfstitel met aanduiding 98 ligt, dan wordt voor de voorgaande verblijfstitel als datumEinde de waarde in 39.30 (ingangsdatum) van de verblijfstitel met aanduiding 98 genomen.

Ik denk dat we daarmee bijna alle situaties hebben afgevangen van een historische of beëindigde verblijfstitel. Alleen wanneer in een verblijfstitel zonder groep 39 de geldigheid 85.10 gevuld is met 00000000, of in de verblijfstitel met aanduiding 98 de ingangsdatum 39.30 gevuld is met 00000000, kan het nog fout gaan.
@gertjanvanderkooij Betekent dit dat we daarvoor toch de indicatieVerblijfstitelBeeindigd nodig hebben? Of is dit zo theoretisch dat het niet voor zal komen?

N.B. ik heb ook in de feature gezet dat we de verblijfstitel 98 niet opnemen, omdat we in de API geen "magic strings" opnemen.

**Comment by gertjanvanderkooij** [comment]
> @gertjanvanderkooij Betekent dit dat we daarvoor toch de indicatieVerblijfstitelBeeindigd nodig hebben? Of is dit zo theoretisch dat het niet voor zal komen?

@fsamwel Theoretisch geval. Prima verfijning van feature zo; dit moet 'm zijn voor v1.0!
