### ISSUE TITLE
voorvoegsel in samengestelde namen anders voor Belgen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#469]
zie https://onzetaal.nl/taaladvies/hoofdletters-namen-nederland/

Voor personen met de Belgische nationaliteit moet het voorvoegsel worden opgenomen zoals die staat in de registratie, ongeacht de plek in de samengestelde naam.
Wanneer het gaat om het gebruik de naam van de (mogelijk Belgische) partner stel ik voor dat niet te doen, anders de partner altijd worden opgevraagd (nationaliteit staat niet in categorie 5)

**Comment by gertjanvanderkooij** [comment]
Is het afvragen op de Belgische nationaliteit hier wel de goede oplossingsrichting? Moeten we de vastlegging van voorvoegsels met hoofdletters in de BRP niet in alle gevallen respecteren; ongeacht of betreffende persoon de Belgische nationaliteit heeft of niet. 

Ik krijg de indruk dat [omschrijving op taaladvies] (https://onzetaal.nl/taaladvies/hoofdletters-namen-nederland/) dit Belgische gebruik meer als voorbeeld is genomen; niet als conditie.

**Comment by JohanBoer** [comment]
Dit issue zal in de "naam"- features moeten worden aangepast. 
Samenvatting, de regel om in specifieke situaties van een kleine letter een hoofdletter te maken blijft valide, maar van een geregistreerde hoofdletter gaan we geen kleine letters meer maken.
