### ISSUE TITLE
Als PO wil ik dat de verblijfsplaats (verblijfsobject, standplaats, ligplaats) wordt gewijzigd in adresseerbaar object identificatie 

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#475]
...zodat voor een BAG gegeven ook de BAG naam wordt gebruikt en consistentie van de Haal Centraal bevragen API's is geborgd. 

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by fsamwel** [comment]
dit gaat om het veld verblijfplaats.identificatiecodeVerblijfplaats. Zou dan verblijfplaats.adresseerbaarObjectIdentificatie

Naast de link _links.verblijfplaatsNummeraanduiding zou er ook een link naar het adresseerbaar object moeten zijn: _links.adresseerbaarObject

**Comment by JohanBoer** [comment]
Zowel bij Actueel als bij bewoning.
