### ISSUE TITLE
Als PO wil ik een design decision toevoegen t.a.v. Hall links en versies in de URL

### ISSUE THREAD

**Issue by JanWillemKooi** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#493]
zodat het denkproces n.a.v. de oplevering van de BRP referentie implementatie en de opmerkingen daarover meenemen in het project

**Comment by JanWillemKooi** [comment]
Toevoegen bij design decision:
We kiezen ervoor op alleen BAG -adressen te doen. Dat houdt in dat we de verblijfplaatsidentificatie als uniek id gebruiken. De resource bewoning wordt een uitbreiding extensie op Binnenlandsadres (zit nu in Actueel tillen we naar een commonBRP.YAML) En binnenlandsadres wordt via een @Ref opgehaald. 

Zie ook #475

**Comment by JohanBoer** [comment]
Deze design decision wordt een uitkomst van de API-lab. De vraag hoe we met HAL-links en of verwijzingen naar andere domeinen omgaan wordt voorgelegd aan de deelnemers van de APILAB van 10-12
