### ISSUE TITLE
In Partnerhistorie_links ontbreekt link naar ingeschreven persoon

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#497]
In Partnerhistorie_links zit nu een link self, geen link ingeschrevenPersoon

Ik had wel de link ingeschrevenPersoon verwacht

De link self is niet relevant, want er is geen endpoint waar dit naar zou kunnen verwijzen

**Comment by JohanBoer** [comment]
self-link verwijderd, Ingeschrevenpersonen link toegevoegd. 
Ook bij verblijfstitelhistorie de self-link verwijderd.

**Comment by fsamwel** [comment]
zie opmerking van mij en van Melvin in https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/pull/502#issuecomment-554783480:
De VerblijfstitelhistorieHal component kan worden verwijderd en alle links naar VerblijfstitelhistorieHal kan worden vervangen door Verblijfstitelhistorie.

**Comment by JohanBoer** [comment]
Frank checkt nog even of bovenstaande opmerking correct verwerkt is. Indien dat zo is dan kan deze direct op Done.
