### ISSUE TITLE
Reguliere expressie bsn veranderen naar ^[0-9]*$

### ISSUE THREAD

**Issue by hansvandijk93** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#499]
Op dit moment wordt voor burgerservicenummer drie requirements gebruikt:
- pattern: "^[0-9]{9}$"
- maxLength: 9
- minLength: 9

Hier ontstaat overlap omdat de lengte van de parameterwaarde nu gecheckt wordt door zowel de reguliere expressie als de min- en maxLength. Daardoor wordt voor onjuiste lengtes soms deze foutmelding getoond: "Waarde voldoet niet aan patroon ^[0-9]{9}$"

Mijn voorstel is om het patroon ^[0-9]{9}$ te veranderen naar ^[0-9]*$. De reguliere expressie is daarmee alleen verantwoordelijk voor het controleren van de juistheid van de individuele karakters.

Voor onjuiste lengtes wordt dan altijd deze foutmelding gegeven:
"Waarde is korter dan minimale lengte 9."

En deze alleen bij onjuiste karakters:
"Waarde voldoet niet aan patroon ^[0-9]*$"

Pas als iemand een fout karakter en een onjuiste lengte meegeeft, ontstaat er (terecht) weer overlap. De response houden we in dit geval consequent door alfabetische sortering en daarvan de eerste error te pakken.

Heb dit al overlegd met @fsamwel die het hiermee eens is. Moet dus worden aangepast in de specificaties.

**Comment by JohanBoer** [comment]
Done

**Comment by fsamwel** [comment]
@JohanBoer Het pattern dat nu is opgenomen is niet correct, de * ontbreekt.

pattern: "^[0-9]$" betekent dat er exact 1 cijfer moet zijn.
Dit moet worden pattern: "^[0-9]*$", dat betekent dat er 0 of meer cijfers moeten zijn
