### ISSUE TITLE
Niet altijd omschrijving bij nationaliteit

### ISSUE THREAD

**Issue by mjhcremer** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#521]
Bij de nationaliteit wordt altijd de code getoond,  maar niet altijd een omschrijving bij de code.
Bijvoorbeeld bij BSN 999993653 krijg je bij de nationaliteit alleen code 0399 zonder omschrijving terug.

**Comment by fsamwel** [comment]
Dit komt doordat code 0399 niet voorkomt in Tabel32 Nationaliteitentabel. Eigenlijk is dit dus niet valide data in de bron. Heeft er wellicht mee te maken dat dit komt uit de GBA-V proefomgeving.
