### ISSUE TITLE
Als medewerker Sociale Zaken wil ik dat ik per persoon het functieadres kan raadplegen (BewoningAPI)

### ISSUE THREAD

**Issue by kryban** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#522]
...zodat ik per persoon kan bepalen of de persoon het adres als woonadres of briefadres gebruikt.

**Acceptatiecriteria**
- functieadres behoort niet tot adres, maar tot bewoner op het adres 
- meerder bewoners van een adres moeten moeten verschillende functieadressen (t.o.v. elkaar) moeten kunnen hebben over een gegeven tijd. 
- een bewoner moet in een periode slechts 1  functieadres hebben. Er mag geen overlap zijn in functieadressen van 1 persoon.

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
Dee functionaliteit is nu meegenomen in de specificatie.
