### ISSUE TITLE
Wens: meerdere personen opvragen middels 1 call (bsn)

### ISSUE THREAD

**Issue by hbredewoud** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#525]
Bij bijvoorbeeld het inzien van een zaak, niet per betrokkene een call gemaakt hoeft te worden.

**Comment by JohanBoer** [comment]
Aanpassen dat de query parameter burgerservicenummer meerdere bsn's kan bevatten (bv comma separated).

**Comment by gertjanvanderkooij** [comment]
Bij het opstellen van de features even stilstaan bij de volgende situaties:
1) Hoeveel BSN's staan we toe? 
2) Als de zelfinstelbare limiet van de provider wordt overschreden, dan geen enkel antwoord?
3) Hoe is de afhandeling als we één of meerdere opgegeven BSN's niet kunnen vinden? Hoe weet ik als consumer welke ik mis?

**Comment by fsamwel** [comment]
> 3. Hoe is de afhandeling als we één of meerdere opgegeven BSN's niet kunnen vinden? Hoe weet ik als consumer welke ik mis?

Hangt denk ik af of we dit implementeren in de resource (/ingeschrevenpersonen/{burgerservicenummer} of in de collectie (/ingeschrevenpersonen?burgerservicenummer={burgerservicenummer}
In het eerste geval komt er een 404 wanneer een van de BSN's niet gevonden wordt, in het tweede geval denk ik dat je alleen terugkrijgt wat gevonden is (zonder verdere melding over niet-gevonden BSN's

**Comment by fsamwel** [comment]
> Als de zelfinstelbare limiet van de provider wordt overschreden, dan geen enkel antwoord?

Ik denk het wel. Als je definieert dat er een maximum is, levert dat een foutmelding. Zeker wanneer dit in de API specificaties wordt gedefinieerd, bijvoorbeeld:
      parameters:
        - in: path
          name: burgerservicenummer
          schema:
            type: array
            items:
              type: string
            maxItems: 100

Ik denk dat het maximale aantal ook wordt beperkt door de omvang van de uri. Wanneer je bijvoorbeeld 1000 BSN's opgeeft, is de uri meer dan 10000 tekens lang. Ik ben bang dat dit problemen geeft in de webserver of in netwerkcomponenten/

**Comment by fsamwel** [comment]
Voor zoekresultaten hebben we design decision ["Bij het zoeken van personen is er een maximum aantal resultaten"](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/master/docs/design_decisions.md#bij-het-zoeken-van-personen-is-er-een-maximum-aantal-resultaten).
Een gebruiker kan natuurlijk meer BSN's vragen dan als antwoord mogen worden teruggegeven, maar de API geeft dan een foutmelding. Dus ik denk dat de beperking van het maximaal aantal resultaten de natuurlijke grens aangeeft van het maximaal op te vragen BSN's.

**Comment by JohanBoer** [comment]
En hoe hoog moet dat maximum dan zijn. Deze functionaliteit is gevraagd vanuit het perspectief om bij een zaak alle betrokken personenen in 1 keer op te kunnen vragen. Het lijkt mij dat 20 dan een uitstekend maximum is, Maar ik hebt nauwelijks inhoudelijk ervaring met hoe zaken vastgelegd worden. Zijn er zaken die meer dan 20 betrokkenen kennen (die je ook in 1 keer op wil kunnen vragen).

**Comment by JohanBoer** [comment]
> Als die design decisin blijft staan, dan heeft de bovenstaande discussie geen impact op de specificatie.

Foute conclusie mijnerzijds. Inmiddels de query-parameter Burgerservicenummer als array gedefinieerd. Het is volgens mij niet juist om dit op de path-parameters te doen.
