### ISSUE TITLE
Als medewerker Sociale Zaken wil ik (indien van toepassing) eindedatum geldigheid zien in de nationaliteit van een persoon

### ISSUE THREAD

**Issue by kryban** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#526]
...zodat ik in staat ben met terugwerkende kracht een besluit te nenmen gebaseerd op de nationaliteit van een persoon.

**Acceptatiecriteria**
- entiteit nationaliteit bevat property DatumEindeGeldigheid
- tijdlijnen van nationaliteiten zijn op elkaar aangesloten

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
In de api worden alleen geldige actuele nationaliteiten getoond. Als de meest recente nationaliteit een eindedatum geldigheid heeft zal deze in het antwoord niet getoond worden. 

De feature actuele_gegevens moet uitgebreid worden van alle categoriën die niet geleverd worden als er een einddatum is toegevoegd.

**Comment by gertjanvanderkooij** [comment]
@CathyDingemanse 
Feature verduidelijkt, da's goed ter verduidelijking. Maar lees ik hier wellicht ook een extra businessbehoefte voor de Historie-bevraging? Naast Partners, Verblijfplaatsen, Verblijfstitels ook Nationaliteiten?

**Comment by kryban** [comment]
> @CathyDingemanse
> Feature verduidelijkt, da's goed ter verduidelijking. Maar lees ik hier wellicht ook een extra businessbehoefte voor de Historie-bevraging? Naast Partners, Verblijfplaatsen, Verblijfstitels ook Nationaliteiten?

Vanuit Social Zaken is het noodzakelijk te weten van- en tot wanneer een nationaliteit geldig is geweest, omdat nationaliteit rechtbepalend kan zijn.
Omdat uitkeringen met terugwerkende kracht toegekend kunnen worden, moet het recht ook met terugwerkende kracht bepaald kunnen worden, waardoor rechtbepalende componenten ook met terugwerkende kracht opgehaald moeten kunnen worden.

**Comment by CathyDingemanse** [comment]
@kryban @gertjanvanderkooij 
Da's duidelijk! Die gaan we toevoegen. 
@JohanBoer, zou jij een concept van deze uitbreiding op kunnen opleveren deze week van:

GET/ingeschrevenpersonen/{burgerservicenummer}/nationaliteithistorie

**Comment by JohanBoer** [comment]
> @JohanBoer, zou jij een concept van deze uitbreiding op kunnen opleveren deze week? Het gaat om:
> GET/ingeschrevenpersonen/{burgerservicenummer}/nationaliteithistorie

We hebben diverse API-Labs gedaan met de huidige endpoints. We zitten nu in de fase waarin we de specificatie als standaard willen laten vaststellen. Gaan we in deze fase nog een endpoint toevoegen ? Of zetten we deze op de eerstvolgende minor-release. 
Ik kan overigens best een voorstel hiervoor maken. Weet niet of dat vandaag nog lukt, maar dan zeker op maandag....

**Comment by JohanBoer** [comment]
Voorstel gemaakt voor nationaliteithistorie

**Comment by fsamwel** [comment]
@CathyDingemanse in gegevensmagazijnen wordt, voor zover ik weet, geen historie bijgehouden van nationaliteiten. Het GBA-V heeft voor Algemene Gemeentetaken geen autorisatie voor historie van nationaliteiten. Er is wel autorisatie voor categorie 04 (actuele nationaliteit), maar niet voor 54 (historische nationaliteiten).
Heeft het nu wel zin om al een nationaliteithistorie in de API op te nemen?

@JohanBoer en @CathyDingemanse in de BRP (Lo GBA) bestaat er geen attribuut voor datum einde van een nationaliteit. De enige manier waarop je kan bepalen dat een nationaliteit beëindigd is, is uit de categorie (54 i.p.v. 04) en het bestaan van een reden beëindigen nationaliteit. De reden beëindigen kan ook 000 Onbekend zijn, zodat in dat geval de gebruiker niet meer kan zien dat de nationaliteit is beëindigd. De datumEindeGeldigheid van de beëindigde nationaliteit zou dan afgeleid kunnen worden uit de datumIngangGeldigheid van de actuele nationaliteit. Maar dat is dubieus, omdat mensen een tijd lang dubbele nationaliteit kunnen hebben gehad.
Naar mijn idee moet dus attribuut datumEindeGeldigheid eruit en zou er een indicatieNationaliteitBeeindigd moeten zijn.

**Comment by CathyDingemanse** [comment]
> @CathyDingemanse in gegevensmagazijnen wordt, voor zover ik weet, geen historie bijgehouden van nationaliteiten. Het GBA-V heeft voor Algemene Gemeentetaken geen autorisatie voor historie van nationaliteiten. Er is wel autorisatie voor categorie 04 (actuele nationaliteit), maar niet voor 54 (historische nationaliteiten).
> Heeft het nu wel zin om al een nationaliteithistorie in de API op te nemen?

Jazeker. De implementatie gaat gepaard met een wetswijziging, die vooral volledig moet zijn in de voorbereiding. Voor de implementatie op het gegevensmagazijn is de response leeg als het er niet is.

> 
> @JohanBoer en @CathyDingemanse in de BRP (Lo GBA) bestaat er geen attribuut voor datum einde van een nationaliteit. De enige manier waarop je kan bepalen dat een nationaliteit beëindigd is, is uit de categorie (54 i.p.v. 04) en het bestaan van een reden beëindigen nationaliteit. De reden beëindigen kan ook 000 Onbekend zijn, zodat in dat geval de gebruiker niet meer kan zien dat de nationaliteit is beëindigd. De datumEindeGeldigheid van de beëindigde nationaliteit zou dan afgeleid kunnen worden uit de datumIngangGeldigheid van de actuele nationaliteit. Maar dat is dubieus, omdat mensen een tijd lang dubbele nationaliteit kunnen hebben gehad.
> Naar mijn idee moet dus attribuut datumEindeGeldigheid eruit en zou er een indicatieNationaliteitBeeindigd moeten zijn.

Helemaal eens!

**Comment by fsamwel** [comment]
@CathyDingemanse zie mijn later toegevoegde opmerking:
> Het bepalen van de historie in een periode of peildatum is daarom ook erg ingewikkeld. Dit kan haast niet zonder aan te nemen dat nationaliteiten naadloos op elkaar aansluiten. Ik weet niet hoe ik dan een nationaliteithistorie feature zou moeten schrijven die ook echt tot correcte gegevens leidt. Een nationaliteithistorie zonder periode of peildatum is dan wel mogelijk, maar legt de last voor het bepalen van de actuele nationaliteiten binnen de gewenste periode bij de consumer (ook niet echt fijn).

Heb je een idee hoe we hiermee om moeten gaan?

**Comment by fsamwel** [comment]
@JohanBoer ik het het vorige keer blijkbaar nog niet zo heel goed gereviewd... geheimhoudingPersoonsgegevens ontbreekt nog in nationaliteithistorie. Die zit wel in de andere histories.

**Comment by JohanBoer** [comment]
Het element datumEindeGeldigheid heb ik uit Nationaliteithistorie verwijderd.
Het element geheimhoudingPersoonsgegevens heb ik aan NationaliteitHistorie toegevoegd. 
Bij de eerstvolgende pull-request kan dit gereviewed worden

**Comment by fsamwel** [comment]
ik heb nog verder onderzocht hoe nationaliteit historisch in GBA-V/BRP zit. Je kan de datumEindeGeldigheid er wel in laten zitten. Die zou je kunnen vullen uit de ingang geldigheid van het actuele of historische voorkomen waarin de nationaliteit is beëindigd.

indicatieNationaliteitBeeindigd blijft wel nodig, omdat alle ingangsdata volledig onbekend kunnen zijn.

**Comment by fsamwel** [comment]
@gertjanvanderkooij en @CathyDingemanse de ingang geldigheid wordt in de BRP ook verhoogd bij het doorvoeren van een wijziging. Bijvoorbeeld als iemand sinds 1-1-2015 de Nederlandse nationaliteit heeft, maar op 25-10-2019 is de reden opname gewijzigd, dan staat in de actuele nationaliteit (04) als ingangsdatum 25-10-2019.
Ik zou vermoeden dat de gebruiker vooral (alleen) geïnteresseerd is in sinds wanneer de nationaliteit geldig is, niet sinds wanneer de overige gegevens van de nationaliteit geldig zijn geworden. Dus zou ik in dit geval zowel in de actuele bevraging als in de nationaliteithistorie voor deze persoon als datumIngangGeldigheid 1-1-2015 verwachten.
Klopt mijn redenatie? Of moeten we in nationaliteithistorie ook de historische voorkomens op gaan nemen (dus in dit geval een met datumIngangGeldigheid 1-1-2015 en een met datumIngangGeldigheid 25-10-2019, beide Nederlandse nationalteit)

**Comment by CathyDingemanse** [comment]
@mijns inziens terecht. We moeten er voor zorgen dat de ingangsdatum niet verkeerd kan worden geïnterpreteerd. Het gaat om het moment dat iemand de nationaliteit kreeg. Maar goed, graag nog even de blik van een domeindeskundige (@gertjanvanderkooij, graag feature reviewen). Frank zou jij de feature willen sturen naar @PaulBuik @Vrien de Geest?

**Comment by gertjanvanderkooij** [comment]
Fature gereviewed en OK!
Mogelijk nog situatie toevoegen met 'Onjuist verklaarde' categorie.

**Comment by fsamwel** [comment]
> Mogelijk nog situatie toevoegen met 'Onjuist verklaarde' categorie.

@gertjanvanderkooij Dank voor de review! Er zitten toch scenario's in voor onjuiste categorieën? Is er nog een specifieke situatie die nog niet getoond wordt?

**Comment by gertjanvanderkooij** [comment]
@fsamwel 
In feature wordt dit wel bij 3e scenario (bsn 999992806) genoemd, maar in de basisgegevens voor dit scenario zie ik geen rij met 84.10 (indicatie onjuist) terug. Wellicht straks even bellen?

**Comment by fsamwel** [comment]
@gertjanvanderkooij de laatste 2 scenario's gaan hierover. Deze betreffen de testpersonen 999992466 en 999992855. Daarvoor heb ik wel 84.10 genoemd.

**Comment by gertjanvanderkooij** [comment]
@fsamwel OK, dank. Heb ik blijkbaar niet de gehele feature overgehaald.
