### ISSUE TITLE
Veld aanduidingNaamgebruik opnemen in api

### ISSUE THREAD

**Issue by jarichypma** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#527]
Naar aanleiding van de afstemming met @JohanBoer op het API-lap vandaag.

In issue #337 is het veld aanduidingNaamgebruik uit de api verwijderd.
Is het mogelijk om dit veld terug te laten komen?
Voor nieuwe applicaties is de beschreven redenering om het veld te verwijderen goed te volgen. Voor 'legacy' applicaties zou het echter makkelijk zijn als dit veld wel aanwezig is.

In onze software (en ik vermoed ook andere) wordt dit veld namelijk nog wel gebruikt. 
Het ontbreken van dit veld zou aan onze kant de adoptie vertragen. Gezien het veld gewoon een basisgegeven uit de GBA is zou er volgens mij niks op tegen hoeven zijn om het alsnog op te nemen.

**Comment by jarichypma** [comment]
Vandaag kwam ik nog een reden tegen om dit veld op te kunnen halen. In het berichtenverkeer van de iStandaarden is dit veld ook gespecificeerd. Om het mee te geven moeten we het dus uit de basisregistratie op kunnen vragen.

Zie documentatie: https://informatiemodel.istandaarden.nl/2019/object.html?object=271604
Of voor het geval de link een keer wijzigt (wat nog wel eens gebeurt): https://informatiemodel.istandaarden.nl/ -> iWmo 2.x -> berichten -> WMO301 -> client -> naam -> CDT_VolledigeNaam -> naamGebruik

**Comment by kimvw** [comment]
Dit veld is ook aanwezig in het berichtenverkeer StUF0312WOZ naar de LV WOZ. Dus daaruit ook de wens om dit veld wel te hebben in de API.

**Comment by JohanBoer** [comment]
We gaan naamgebruik alsnog opnemen in de eerste release.

**Comment by JohanBoer** [comment]
Check of aanduiding naamgebruik op het goede niveau is aangebracht ( hoort deze niet in Naam of NaamPersoon. Ook camelcase (aanduidingNaamgebruik)

**Comment by JohanBoer** [comment]
AanduidingNaamgebruik toegevoegd aan het schemacomponentn NaamPersoon. Dat betekent dat alleen voor de ingeschreven persoon zelf het element aanduidingnaamgebruik is opgenomen.
