### ISSUE TITLE
parameter BSN toevoegen aan /haalcentraal/bewoningen 

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#533]
# Impediment

Het is niet mogelijk een bewoning te zoeken op basis van het BSN. Dit levert een geen of 1 unieke bewoning op.

**Comment by JohanBoer** [comment]
BSN opgenomen als query-parameter. In de beschrijving wel opgenomen dat de combinatie van burgerservicenummer met datumVan en datumTotEnMet tot meerder bewoningen kan leiden. Is dat ook gewenst ?
