### ISSUE TITLE
Overleden personen alleen opnemen in het resultaat tot aan de datum overlijden

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#534]
Nu staat er dat overleden personen worden meegenomen.

**Comment by JohanBoer** [comment]
BSN opgenomen als query-parameter

**Comment by JohanBoer** [comment]
Vorig commentaar hoorde bij issue #533.

Commentaar op dit issue: Beschrijving aangepast.
