### ISSUE TITLE
Als PO wil ik de expand parameter toevoegen aan bewoningen 

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#535]
...zodat een consumer in hetzelfde request (enkele kenmerken van) de ingeschreven persoon kan ophalen.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
Als ik een expand op deresource ingeschreven persoon opneem dan wordt ook de hele resource ingeschreven persoon opgenomen in die expand. Dat is best wel veel content. Wordt dit veel gebruikt ? Dat heeft behoorlijk impact op deze endpoint. Gaarne bespreken.

**Comment by JohanBoer** [comment]
We gaan dit uitwerken in een OAS. De bewoner groep wordt gestript que persoongegevens (Alleen datumtot, DatumAanvanggegevenshuishouding en functieadres blijft over ook bsn en indicatiegeheimhoudingpersoongegevens ) en de bewoner krijgt een _links en een _embedded met de ingeschreven persoon.

**Comment by JohanBoer** [comment]
> We gaan dit uitwerken in een OAS. De bewoner groep wordt gestript que persoongegevens (Alleen datumtot, DatumAanvanggegevenshuishouding en functieadres blijft over ook bsn en indicatiegeheimhoudingpersoongegevens ) en de bewoner krijgt een _links en een _embedded met de ingeschreven persoon.

De bewoner is een gegevensgroep en kan dus geen _links en en _embedded krijgen. Aangezien in zowel de groep bewoner als in de gelinkte resource ingeschrevenPersoon een BSN is opgenomen is toch de relatie tussen de bewonersgegevens en de persoonsgegevens te leggen.

**Comment by JohanBoer** [comment]
Vraag: Moet indicatieverblijfsplaatsInOnderzoek ook in de bewoner blijven (lijkt mij wel een goed idee, dus dat doe ik vooralsnog wel.

**Comment by JohanBoer** [comment]
Er zal een feature gemaakt moeten worden om de logica om tot de hoofdbewoner te komen te beschrijven !!

**Comment by gertjanvanderkooij** [comment]
> Ik heb ook bij de hoofdbewoner de gegevens van de ingeschrevenPersoon als embedded resource opgenomen.

Je hebt mogelijk een reactie gemist vwb Hoofdbewoner; zie issue #523 #477

**Comment by gertjanvanderkooij** [comment]
> Vraag: Moet indicatieverblijfsplaatsInOnderzoek ook in de bewoner blijven (lijkt mij wel een goed idee, dus dat doe ik vooralsnog wel.
Eens!

**Comment by JohanBoer** [comment]
> Ik heb ook bij de hoofdbewoner de gegevens van de ingeschrevenPersoon als embedded resource opgenomen.
> 
> Er zal een feature gemaakt moeten worden om de logica om tot de hoofdbewoner te komen te beschrijven !!

De hoofdbewoner is inmiddels verwijderd.

**Comment by fsamwel** [comment]
> De bewoner is een gegevensgroep en kan dus geen _links en en _embedded krijgen. 

@JohanBoer staat in de HAL specificaties dat dit niet mag? Volgens mij hebben we dit de vorige keer expliciet besproken en was de conclusie dat dit wel mag.
Wanneer de gebruiker in de link de BSN moet opzoeken om te weten welke link relevant is, verlies je dan niet de relevantie van de link? En maak je het dan niet extra moeilijk voor de gebruiker?

**Comment by JohanBoer** [comment]
> @JohanBoer staat in de HAL specificaties dat dit niet mag? Volgens mij hebben we dit de vorige keer expliciet besproken en was de conclusie dat dit wel mag.
> Wanneer de gebruiker in de link de BSN moet opzoeken om te weten welke link relevant is, verlies je dan niet de relevantie van de link? En maak je het dan niet extra moeilijk voor de gebruiker?

Nu je het aangeeft kan ik me die discussie ook weer herinneren. Thanks, was me ontschoten.  Ik ga dat alsnog zo doorvoeren.

**Comment by JohanBoer** [comment]
> Je hebt mogelijk een reactie gemist vwb Hoofdbewoner; zie issue #523 #477

Klopt Gert Jan, De kerstvakantie heeft er goed ingehakt....... Ik heb inmiddels alsnog de hoofdbewoner verwijderd.
