### ISSUE TITLE
beschrijvingen bewoningen zijn niet correct

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#536]
bij get/haalcentraal/bewoningen/{identificatiecodenummeraanduiding}

is:
"Het ophalen van de gegevens van een enkele Bewoning.
Een bewoning is een VERBLIJFPLAATS waar op enig moment daadwerkelijk minimaal 1 INGESCHREVEN PERSOON is ingeschreven.
Op basis van de identificatiecodenummeraanduiding de bewoning geretourneerd inclusief gegevens over de bewoners van het betreffende adres."

Moet worden:
Het raadplegen van een Bewoning
Een bewoning is een verblijfplaats waar minimaal 1 persoon is ingeschreven.
Op basis van de identificatiecodenummeraanduiding retourneert Bewoning de personen die op de verblijfplaats zijn ingeschreven.

**Comment by JohanBoer** [comment]
Aangepast
