### ISSUE TITLE
Als PO wil ik dat bij bewoning wordt vermeld dat verblijfplaats voor de persoon een woonadres of een briefadres is. 

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#537]
...zodat een consumer kan achterhalen of de persoon er daadwerkelijk woont, of dat het de verblijfplaats is van een andere persoon of een instelling (de zogenoemde briefadresgever). 

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
Dit is bij de bewoner geïmplementeerd. Dezelfde bewoning (adres) kan voor de ene bewoner een woonadres zijn en voor de ander een briefadres.
