### ISSUE TITLE
Als PO wil ik dat "verloop"nader wordt gedefinieerd

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#538]
...zodat ik als consumer begrijp wat de de betekenis is van de kengetallen.

**Acceptatiecriteria**
- "bewoningsduur" is de gemiddelde duur van de bewoning van het adres in maanden in de opgegeven periode
  "inVerhuizingen": het aantal keren dat een alleenstaande of gezin naar het adres is verhuisd binnen de opgegeven periode
  "uitVerhuizingen": het aantal keer dat een alleenstaande of gezin van het adres naar een ander adres is verhuisd binnen de opgegeven periode

- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
Aangepast

**Comment by fsamwel** [comment]
Voor implementatie moeten we precies weten hoe bewoningsduur wordt berekend. Ik zie twee soorten berekening:
1. er wordt gerekend met het aantal maanden in de opgegeven periode dat er gewoond is
2. er wordt voor de bewoners die in de periode op het adres hebben gewoond hoeveel maanden ze op het adres hebben gewoond

Bijvoorbeeld als iemand van 1-10-2017 tot 1-6-2019 op een adres heeft gewoond, en bewoning wordt gevraagd van 1-1-2018 t/m 31-12-2018, dan is bewoningsduur in het eerste geval gelijk aan 12 en in het tweede geval gelijk aan 19.

@CathyDingemanse hoe moet bewoningsduur worden berekend?

Ook kan voor bewoningsduur per persoon worden afgerond op hele maanden, dan wel gerekend met hele maanden, dan wel niet afgerond (rekenen met dagen als 1/30ste van een maand).

Dus als iemand van 15-03-2018 tot 06-09-2019 op het adres heeft gewoond en bewoning wordt gevraagd 1-1-2018 t/m 31-12-2018, is dan bewoningsduur (voor deze bewoner):
- 7 (elk deel van de maand wordt als hele maand gerekend)
- 5 (alleen hele maanden worden gerekend)
- 6 (16 dagen + 5 maanden + 5 dagen = 5,7)

**Comment by fsamwel** [comment]
Ook moeten we kiezen hoe om te gaan met onbekende datums. Dus hoe moet de bewoningsduur worden berekend wanneer voor een bewoner de datum aanvang adreshouding volledig onbekend is?

Ik stel ook voor om voor gedeeltelijk onbekende datums op dezelfde manier te redeneren als we voor de historie gedaan hebben. Dus als alleen jaar van de datum aanvang bekend is, aannemen dat de persoon er vanaf 1 januari van dat jaar gewoond heeft.

**Comment by CathyDingemanse** [comment]
Eens. Anders kan het 

> Voor implementatie moeten we precies weten hoe bewoningsduur wordt berekend. Ik zie twee soorten berekening:
> 
> 1. er wordt gerekend met het aantal maanden in de opgegeven periode dat er gewoond is
> 2. er wordt voor de bewoners die in de periode op het adres hebben gewoond hoeveel maanden ze op het adres hebben gewoond
> 
> Bijvoorbeeld als iemand van 1-10-2017 tot 1-6-2019 op een adres heeft gewoond, en bewoning wordt gevraagd van 1-1-2018 t/m 31-12-2018, dan is bewoningsduur in het eerste geval gelijk aan 12 en in het tweede geval gelijk aan 19.
> @CathyDingemanse hoe moet bewoningsduur worden berekend?


Ik kies voor berekening 2. Het gaat er om of we te maken hebben met een duiventil of niet. Daar mag de gevraagde periode op zich geen verklarende factor in zijn. 
> 
> Ook kan voor bewoningsduur per persoon worden afgerond op hele maanden, dan wel gerekend met hele maanden, dan wel niet afgerond (rekenen met dagen als 1/30ste van een maand).
> 
> Dus als iemand van 15-03-2018 tot 06-09-2019 op het adres heeft gewoond en bewoning wordt gevraagd 1-1-2018 t/m 31-12-2018, is dan bewoningsduur (voor deze bewoner):
> 
> * 7 (elk deel van de maand wordt als hele maand gerekend)
> * 5 (alleen hele maanden worden gerekend)
> * 6 (16 dagen + 5 maanden + 5 dagen = 5,7)

Variant 3 (6 maanden).

**Comment by fsamwel** [comment]
bewoningsduur kan een sterk vertekend beeld geven wanneer ook de bewoning voor en na de periode wordt meegerekend, bijvoorbeeld wanneer eerst een bewoner heel lang op het adres staat ingeschreven en er daarna heel veel in- en uitverhuizingen (korte bewoning) is. Het lang wonen verdoezelt dan de korte bewoning erna.
Ook wanneer alleen bewoning binnen de periode wordt meegeteld kan een vertekend beeld ontstaan.
Het is niet duidelijk hoe de bewoningsduur moet worden berekend om als aanvullende informatie te dienen bovenop in- en uitverhuizingen. Daarom kan de bewoningsduur worden verwijderd
