### ISSUE TITLE
Als ontwikkelaar wil ik een melding krijgen als ik een foutieve waarde voor de parameter api-version meegeef in het GET ingeschrevenpersonen bericht

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#540]
...zodat er alleen valide waardes worden meegestuurd.

Tijdens het API-Lab van 10 december j.l. kon ik een bericht insturen met de waarde 'integer' voor deze parameter.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by CathyDingemanse** [comment]
@Kayo en @Johan @Frank, zouden jullie dit kunnen uitzoeken?

**Comment by fsamwel** [comment]
volgens de specificaties mag dat niet, api-version is gedefinieerd als integer, dus zou string 'integer' niet moeten accepteren. Het probleem zit dus niet in de api specificatie, maar in de implementatie.
Voor zover ik weet is deze parameter nog niet geïmplementeerd, omdat we nu alleen versie 1 hebben.
