### ISSUE TITLE
Het opnemen van Hal-links die domeinoverstijgend verwijzen

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#541]
Uit de API-lab is een gemengde response gekomen op de vraag of Hal-links gebruikt gaan worden. 
Evenveel reacties waren er voor wel of geen gebruik, maar de overgrote meerderheid gaf aan "misschien in de toekomst"

Onze conclusie daarop is dat we de Hal-Links niet gaan verwijderen, maar dat we voor die developers die de Hal-links niet gaan gebruiken nemen we de identifier van de gerelateerde resource als element op.

- [x] Leg dit vast in de design decisions
- [ ] Neem reisdocumentnummer als element op bij ingeschreven persoon.
- [ ] Neem burgerservicenummer als element op in het reisdocument.

**Comment by JohanBoer** [comment]
Johan loopt de API spec door om id's van de domeinoverstijgende resources op te nemen in de  content van de ingeschreven Persoon.

**Comment by JohanBoer** [comment]
Array reisdocumentnummer toegevoegd aan Ingeschreven persoon
Verblijfplaatsnummeraanduiding als ID opgenomen
Ouders, kinderen partner en historie niet opgenomen als id. Zijn geen unieke identifiers beschikbaar.

**Comment by fsamwel** [comment]
één lullig detail: het reisdocumentnummer is opgenomen, maar in property "reisdocument". Moet beter "reisdocumentnummers" zijn (dus aangeven dat het alleen het nummer bevat, en in meervoud)

**Comment by JohanBoer** [comment]
Is inmiddels aangepast in de BRP
