### ISSUE TITLE
Definitie HAL link type property niet juist?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#543]
In common.yaml is gedefinieerd;
```
    HalLink:
      description: De Link Object zoals gespecificeerd in https://tools.ietf.org/html/draft-kelly-json-hal-08#section-5
      type: object
      required: 
        - href
      properties:
        href:
          $ref: "#/components/schemas/Href"
        type:
         description: "Met dit element wordt aangegeven in welk domein de resource te vinden is waarnaar deze link verwijst. Voorbeelden daarvan zijn *BAG*, *BRP*, *BRK*, *HR*. "
         type: string
         example: "BAG" 
```

In de [HAL specificatie](https://tools.ietf.org/html/draft-kelly-json-hal-08#page-5) is het type property gedefinieerd als:
5.3.  type

   The "type" property is OPTIONAL.

   Its value is a string used as a hint to indicate the media type
   expected when dereferencing the target resource.

Ik denk bij media type aan iets heel anders dan aan een domein, zoals BAG, BRP of BRK. Daar zou ik eerder verwachten bijvoorbeeld "application/json".

**Comment by MelvLee** [comment]
We kunnen ipv type de type property gebruiken:
5.7.  title

   The "title" property is OPTIONAL.

   Its value is a string and is intended for labelling the link with a
   human-readable identifier (as defined by [RFC5988]).

https://learning.oreilly.com/library/view/RESTful+Web+Clients/9781491921890/ch04.html#hal_response_tps_api bevat voorbeelden voor de title property

**Comment by fsamwel** [comment]
zie pull request
