### ISSUE TITLE
Request header parameter en response header onterecht zelfde gedefinieerd

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#549]
In de specificaties worden nu zowel de request header api-version als de response header api-version gedefinieerd als een integer. Dit is alleen terecht voor de request header, aangezien we hebben besloten dat je alleen mag vragen om een major versie.

Nu is in common.yaml #/components/headers/api_version ten onrechte gedefinieerd als integer. Dit moet een string zijn. Example is dan "1.0.0" i.p.v. 1.

**Comment by JohanBoer** [comment]
Het is voor mij een kleine moeite om dit aan te passen. Echter deze header wordt ook door de Kadaster-API gebruikt. Daarbij verandert de betekenis ook. Nu wordt er in de description gesproken over alleen de major versie. 
Ik ben het overigens wel met je eens dat je in de respons de exacte patch versie geretourneerd wilt hebben. 
Ik voer de wijziging door en hoop dat er nergens een issue ontstaat (Kadaster, implementatie Den Haag  etc...)
