### ISSUE TITLE
bewoners ingeschrevenpersonen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#552]
Bewoners._embedded.ingeschrevenpersonen moet zijn ingeschrevenPersoon

**Comment by fsamwel** [comment]
@JohanBoer heb je hier iets aangepast? Zo te zien in het niet opgelost. 

Bewoner_embedded {
  **ingeschrevenpersonen**	IngeschrevenPersoonHal{...}
}

**Comment by JohanBoer** [comment]
Deze wijziging staat nog in de Pull-request. #556 Ik zal dee pull-request nu mergen. Ik heb jouw opmerkingen verwerkt en Cathy reviewed liever niet op een Pull request.
