### ISSUE TITLE
Verloop zonder _links is geen hal+json maar json

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#553]
de response op het verloop endpoint is geen json hal (er zit geen _links of _embedded in). Dus moet bij het endpoint de response worden gedefinieerd als  application/json i.p.v. application/hal+json

**Comment by JohanBoer** [comment]
Volgens mij hebben we dit vrijdag besproken. Melvin gaf aan dat de _links en de _embedded in hal+json optioneel zijn. 
Het is dus niet fout om hier application/hal+json te gebruiken

Blijft de vraag over wat in het gebruik door consumers het meest gewenst is. 
@MelvLee , Kan jij aangeven wat de voorkeur heeft ?

**Comment by MelvLee** [comment]
Ik denk dat het beter is om het nu al toe te voegen, want als we het later nodig hebben en dan pas toe zouden voegen, dan moeten de content type wijzigen en op dat moment is het een breaking change

**Comment by JohanBoer** [comment]
Ik interpreteer jou antwoord als een keuze om nu al hal+json to te passen. Klopt dat ?

**Comment by MelvLee** [comment]
ja, dat lijkt mij het beste

**Comment by JohanBoer** [comment]
Dan hoeft hier verder niets aan aangepast te worden. Ik zet de issue op done.
