### ISSUE TITLE
Swagger geeft foutmeldingen op bewoningen api

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#558]
Als ik de bewoningen api open in de [Swagger petstore](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/Bewoning/openapi.yaml) krijg een een flink aantal keren dezelfde foutmelding: "Resolver errorCannot read property '0' of undefined"

**Comment by fsamwel** [comment]
vreemd genoeg krijg ik geen foutmelding hierop in de Swagger editor...

**Comment by JohanBoer** [comment]
Misschien een tijdelijke hickup in de petstore. Als ik nu de link aanklik krijg ik geen errors.

**Comment by fsamwel** [comment]
@JohanBoer  ik krijg in Safari (op Mac) een andere melding: "Resolver error
undefined is not an object (evaluating 'm[b]')"
Op Firefox krijg in na dezelfde handeling "Resolver error
m is undefined"

Deze melding(en) krijg ik na het openklikken van schema component BewoningHal (dus niet direct bij het openen van de Swagger pagina).

**Comment by JohanBoer** [comment]
Dit heeft me even spitten gekost, maar ik denk dat ik het probleem gevonden heb. Nu nog een oplossing... 

Wij hebben in de bewoning een array van bewoners opgenomen. Bij die bewoners hebben we Hal_links en _embedded opgenomen in de overtuiging dat dat kon. In de Hal draft staat nergens dat dat verboden is om HAL links bij een groep op te nemen. 

Als ik echter de ref             $ref: "#/components/schemas/BewonerHal" vervang door             $ref: "#/components/schemas/Bewoner"  (regel 226)  dan is het probleem dat je hier schetst weg. 

Mijn vermoeden is dat Swagger er niet tegen kan dat we HAL-links en embedde opgenomen hebben in een groep. 

Ik ga erover nadenken hoe dit op te lossen, maar is sta absoluut open voor suggesties,

**Comment by JohanBoer** [comment]
Nog even doorgespit. Het blijkt met name op dat niveau het embedden van de ingeschrevenPersoon te ijn dat een probleem oplevert. Als ik de _embedded weghaal is het issue ook weg.

**Comment by fsamwel** [comment]
@JohanBoer ik geloof dat het probleem daar zit, maar niet in een interpretatie van HAL en _embedded in een gegevensgroep. Wanneer ik het element xxx noem (i.p.v. _embedded), krijg ik dezelfde fouten.
Andersom, wanneer ik in BewonerHal _embedded laat verwijzen ($ref) naar bijv. Bewoner_links dan krijg ik de fouten niet. 
Mijn conclusie is dat het niks te maken heeft met het "embedded", maar wel iets met wat (ingeschreven persoon) en hoe gerefereerd wordt.

Als ik in Bewoner_embedded property ingeschrevenPersoon refereert naar IngeschrevenPersoon i.p.v. naar IngeschrevenPersoonHal krijg ik geen foutmelding.
De melding die we krijgen (en het feit dat verschillende browsers verschillende foutmeldingen tonen) doet vermoeden dat er een fout zit in de Swagger javascript code. Daarmee zijn we nog niet klaar, want Swagger is voor ons en de gebruikers een belangrijk medium, dus moeten we zorgen dat het probleemloos werkt. Hebben we (VNG) een betaald plan voor SwaggerHub zodat hier support op kan zijn?

**Comment by fsamwel** [comment]
Nog een andere constatering: genereren code voor Python geeft foutmelding. Idem voor csharp.

**Comment by fsamwel** [comment]
Paar optimalisaties aan de bewoners (die bovenstaande problemen helaas niet oplossen): verwijderen dubbele declaraties in bewoners die al in ingeschrevenpersonen zitten.
- AanduidingBijHuisnummer_enum
- SoortAdres_enum
- Burgerservicenummer

In de bewoners kan hiervoor verwezen worden naar de ingeschrevenpersonen yaml.

Ook zou ik IngeschrevenPersoonHal in de bewoners hernoemen naar bijv. BewonerPersoonHal. Dan is er helemaal geen overlap meer in componenten tussen ingeschrevenpersonen en bewoners.

**Comment by MelvLee** [comment]
Ik weet niet of het handig is om in een gegevensgroep _links en _embedded toe te voegen. Een gegevensgroep is geen resource en ik interpreteer uit de json hal spec dat _links en _embedded properties zijn die je toevoegt aan een resource.

Ik zou het ook verwarrend vinden omdat je dan op verschillende niveaus zou kunnen embedden. Als ik expand doe op een resource dan verwacht ik het in de _embedded property van de resource en niet in de _embedded property van een gegevensgroep van de resource.

Verder introduceren we met deze constructie een coupling tussen een resource en een HAL variant van een andere resource. Het wordt dan niet makkelijk om een niet-HAL variant van de bewoning API te maken.

Code generatie met nswag werkt wel met de geresolvede versie. Maar ik zie wel dat een aantal classes twee keer (HalLink, datumonvolledig en een aantal enums) worden gegenereerd

**Comment by JohanBoer** [comment]
Dit probleem is geëlimineerd door de pull request die Melvin heeft ingediend.
