### ISSUE TITLE
Inventariseer alle te ondernemen acties voor het vaststellen van versie 1.0.0.

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#564]
- [ ] Hoe wordt er gepubliceerd (op de Haal Centraal- pagina's op de site )
- [ ] Moet dit ergens op Gemma-online landen
- [ ] Hoe worden de leveranciers / gemeenten op de hoogte gebracht  (mailing).
- [ ] Toelichten hoe we de door-ontwikkeling vormgeven
- [ ] Betrokkenheid RVIG formuleren. 
- [x] Hoe publiceren we versie 1.0.0. (Branche op github ?)
- [ ] Hoe organiseren we feedback tijdens de reactie-periode (Github issues ?)
- [ ] Reactie periode is 1 maand na publicatie (opnemen in mail + website)

**Comment by JohanBoer** [comment]
Houdt ook rekening met het vaststellen van de het hergebruik van component, hoe de commeon.yaml wordt toegepast etc. (huidige vraagstukken bij de BAG). 

Denk ook na over het scheiden van ingeschreven persoon en bewoning en reidocumenten. Moeten aparte API's ook een eoigen repository hebben ? Check met Robert en Michiel hoe Beheer hier tegenaan kijkt.

**Comment by michielverhoef** [comment]
>  Hoe publiceren we versie 1.0.0. (Branche op github ?)

Voor het publiceren van een versie kun je een release aanmaken.  Voor een voorbeeld van hoe het er dan uit komt te zien: https://github.com/VNG-Realisatie/gemma-zaken/releases

**Comment by melsk-r** [comment]
Samen met Michiel ben ik tot een aantal wedervragen en opmerkingen gekomen aan de hand waarvan jullie hier zelf meer duidelijkheid over kunnen scheppen.

- Vraag jezelf af of er een reden is om de resources los van elkaar in aparte API's aan te bieden. Bijvoorbeeld omdat een of enkele van de resources in een geheel andere context ook een rol speelt.
Indien dat het geval is dan zou dat een reden kunnen zijn om aparte API's aan te bieden.
- Daarnaast dien je jezelf af te vragen of je de resources apart van elkaar wil kunnen doorontwikkelen. Ook dat kan een reden zijn om aparte API's aan te bieden.

Als resources zo sterk aan elkaar gekoppeld zijn dat als een van de entiteiten wijzigt dit gevolgen heeft voor andere entiteiten dan is dat een aanwijzing dat de resources bij elkaar in 1 API gehouden moeten worden.
Realiseer je daarnaast goed dat je bij splitsing van de resources over meerdere API's je ook de Referentie Implementatie moet splitsen.

Voor een aantal andere eisen voor het in beheer nemen van API standaarden verwijs ik nog naar de [API beheer repository](https://github.com/VNG-Realisatie/api-beheer) en specifiek naar [de checklist voor het in beheer nemen van een standaard](https://github.com/VNG-Realisatie/api-beheer/blob/master/checklist_inbeheer_nemen.md).
