### ISSUE TITLE
Als API gebruiker wil ik dat de reisdocumenten in een aparte API zit

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#565]
zodat bij het afsplitsen van BRP en reisdocumenten in aparte registraties de API kan blijven gelden zonder breaking change.

**Acceptatiecriteria**
- [x] API specificatie gemaakt voor reisdocumenten
- [x] reisdocumenten endpoint en schemacomponenten verwijderd uit ingeschrevenpersonen specificaties
- [x] link naar reisdocumenten specs in readme en napi-specificatie/readme

**Comment by fsamwel** [comment]
@JohanBoer kan jij de resolved versie voor reisdocumenten toevoegen, zodra de "normale" OAS is goedgekeurd?

**Comment by JohanBoer** [comment]
Is gedaan. Pull request gemerged ook direct gemerged.
