### ISSUE TITLE
versie van de API: in uri of request header?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#566]
Wanneer besloten is (landelijke API strategie) om het major versienummer in de uri op te nemen, dan is de request header api-version niet meer relevant. Die moet dan verwijderd worden.

**Comment by fsamwel** [comment]
@CathyDingemanse is het nu definitief besloten voor deze api dat we het versienummer in de uri opnemen? M.a.w. akkoord om dit issue door te voeren (voor vaststellen van release 1.0.0)?

**Comment by CathyDingemanse** [comment]
Ja, nu is definitief besloten dat we het versienummer in de URI opnemen en ons conformeren aan de API strategie.

**Comment by fsamwel** [comment]
@JohanBoer haal jij de request header api-version uit de verschillende API specs?

**Comment by melsk-r** [comment]
> Ja, nu is definitief besloten dat we het versienummer in de URI opnemen en ons conformeren aan de API strategie.

Het is volgens mij nog niet aangepast in de werkversie van de API strategie (ik neem tenminste aan dat het daar als eerste aangepast zou moeten worden) en ik zie ook geen PR staan waarin dat gebeurd is.

**Comment by melsk-r** [comment]
Het versienummer in de URI bevat overigens niet dezelfde informatie als de request header api-version.
In de URI is alleen de major versie opgenomen en in de request header api-version zowel de major als de minor en de patch. Zou dat een reden kunnen zijn api-version toch te handhaven?

**Comment by melsk-r** [comment]
> Het is volgens mij nog niet aangepast in de werkversie van de API strategie (ik neem tenminste aan dat het daar als eerste aangepast zou moeten worden) en ik zie ook geen PR staan waarin dat gebeurd is.

Excuses, ik zie het nu wel staan. Bovenstaande opmerking blijft echter van toepassing.

**Comment by fsamwel** [comment]
@melsk-r 
> In de URI is alleen de major versie opgenomen en in de request header api-version zowel de major als de minor en de patch. Zou dat een reden kunnen zijn api-version toch te handhaven?

We hebben er voor gekozen alleen major versie aan te bieden. Anders moet de provider elke oude minor en patchversie blijven hosten.
