### ISSUE TITLE
server verwijzing referentie implementatie klopt niet

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#568]
In de OAS zit een verwijzing naar de referentie-implementatie:
```
servers:
  - description: "Referentie-implementatie"
    url: https://www.voorbeeldgemeente.nl/api/bevragingen_ingeschreven_personen
```

De url hierin is niet correct. Naar mijn idee moet deze worden verwijderd (de referentie-implementatie die is gemaakt is niet in sync met de huidige versie van de API specificaties).

De server "SwaggerHub API Auto Mocking" kan wel blijven staan.

Dit betreft alle 4 de OAS specs.:
- [x] bevraging-ingeschreven-persoon
- [x] bewoning
- [x] landelijke tabellen
- [x] reisdocumenten

**Comment by fsamwel** [comment]
is het voor de API lab niet wenselijk ook de url van de API-lab implementatie toe te voegen?

https://www.haalcentraal.nl/haalcentraal/api/brp

**Comment by JohanBoer** [comment]
Check in de BRK en BAG hoe de apikey in de definitie is opgenomen en neem die ook in de specs op (Security schemes)
