### ISSUE TITLE
Burgerservicenummer is niet uniek en kan dus geen identifier zijn van een persoon

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#57]
Burgerservicenummer is niet uniek. Sommige burgerservicenummers zijn dubbel uitgegeven. Blijkt ook uit testset van GBA waarin een burgerservicenummer twee keer voorkomt voor verschillende personen.

Dan kan het burgerservicenummer ook niet de identifier zijn voor een enkele persoon.

Dus moet endpoint /ingeschrevennatuurlijkpersonen/{burgerservicenummer} worden gewijzigd.

Voorstel hiervoor uuid te gebruiken.

Dit wordt in API strategie ook als best practice aanbevolen:

> UUID’s
> Het wordt aanbevolen om voor resources die een vertrouwelijk karakter hebben het concept van een UUID (Universally-Unique IDentifier) te gebruiken.

Dan wordt endpoint /ingeschrevennatuurlijkpersonen/{uuid}

We moeten dan wel nadenken hoe dit voor clients moet werken. Bijvoorbeeld een app die op vanuit van digid het burgerservicenummer wil gebruiken om de gegevens van de ingelogde persoon te tonen. Hiervoor moet dan de zoekfunctie gebruikt worden. Maar wellicht wil je niet toestaan dat een burger de zoekfunctie voor personen gebruikt en alleen maar één persoon terug mag krijgen?

**Comment by ehotting** [comment]
BSN niet uniek? Ik zou de API gebruiken om zo'n probleem z.s.m. te verhelpen, dus door een fraaie foutcode terug te geven ipv deze uitzondering als op te lossen probleem bij de techniek neer te leggen. Dubbel BSN? Constraint says no, ga maar fixen.

**Comment by JohanBoer** [comment]
![image](https://user-images.githubusercontent.com/18071357/46524027-d38a5a80-c887-11e8-8ac8-6b6dbbbca152.png)

Op de website van het RVIG. Dit ondersteund de insteek die Eelco hier geeft.

**Comment by dennisdewit81** [comment]
Ik ben het eens met Eelco, we moeten ons niet laten leiden door uitzonderingen op de regels bij het bedenken van de techniek. Dit is juist één van de valkuilen van StUF geweest.

**Comment by mmjvdlinden** [comment]
Hoi Allen, 
De testset GBA-v bevat alle mogelijke uitzonderingen. Echter deze: BSN komt bij meerdere personen voor, slaat helemaal nergens op, zie ook bericht van Johan. Een BSN is uniek voor een persoon. Laat je hierdoor dus niet afleiden ;)

**Comment by ehotting** [comment]
Overigens is UUID nog steeds een goed idee, zolang BSN maar uniek is en je er ook zonder belemmeringen op kunt zoeken

**Comment by fsamwel** [comment]
Duidelijk, we beschouwen BSN als uniek en daarmee als identifier van een persoon.

gebruik UUID is niet mogelijk, want die komt niet voor in de registraties (bronnen)
