### ISSUE TITLE
Hernoemen waardetabel naar waardelijst

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#571]
Om consistentie en hergebruik met BRK mogelijk te maken hernoemen component Waardetabel in common.yaml naar Waardelijst.

Dus ook in BRP api verwijzigingen aanpassen

**Comment by JohanBoer** [comment]
Inmiddels diverse aanpassingen doorgevoerd.

**Comment by fsamwel** [comment]
is inmiddels weer teruggedraaid
