### ISSUE TITLE
Gebruik fields parameter verplichten?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#58]
Vanuit AVG mag een basisregistratie alleen gegevens leveren waarvoor er doelbinding is. Maar de basisregistratie kent niet de autorisaties van de gebruiker. Je wil dan niet toestaan dat een gebruiker alle gegevens opvraagt.

Voorstel is om daarom het gebruik van de fields parameter te verplichten. Analoog aan verbieden van expand=true.

N.B. Op dit moment blijken er voor StUF vraagberichten veel leveranciers scope="alles" te gebruiken (luie developers). Dit willen we m.i. niet voor de API toestaan.

**Comment by dennisdewit81** [comment]
In mijn ogen is het volgende wenselijk:: 
Indien je de vraag om gegevens wil inperken als consumer (performance-wise) t.o.v. je autorisatie dan gebruik je Fields.

-
Uitleg: 

Het volgende herken ik Frank: _"Op dit moment blijken er voor StUF vraagberichten veel leveranciers scope="alles" te gebruiken (luie developers). Dit willen we m.i. niet voor de API toestaan."._ 
Ontwikkelaars willen graag een koppeling opleveren en vinden het (veelal) niet interessant WAT er over de lijn gaat, of het is op dat moment nog niet geheel duidelijk welke attributen gewenst zijn en men wil de technische lijn al realiseren. 

Juist om deze reden zou ik ervoor kiezen om Fields toch niet te verplichten, het verplichten van Fields brengt sowieso met zich mee dat het meer tijd kost om een verbinding te maken (en dat willen we juist niet!). Daarnaast kun je door Fields te verplichten niet afdwingen dat er op voorhand wordt nagedacht over welke attributen noodzakelijk zijn voor de afnemer. Indien de gegevensbehoefte bij een afnemer nog onbekend is kan een ontwikkelaar namelijk dan ook gekozen worden om gewoon wat willekeurige Fields op te nemen.  

Ik vind dat het juist ook van toegevoegde waarde indien je als consumer je Fields niet op hoeft te geven.
Het autorisatiemechanisme (dat conform doelbinding is ingericht) zorgt uiteindelijk ervoor dat enkel de gegevens worden teruggeven waar autorisatie voor is, of er nu Fields zijn gedefinieerd door de consumer of niet.

**Comment by fsamwel** [comment]
Conclusie: Fields parameter hoeft niet verplicht te worden
