### ISSUE TITLE
aanduidingBijHuisnummer verwijderen uit bewoning

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#580]
Bewoningen gaan alleen over BAG-adressen, de identificatiecodeNummeraanduiding is immers de sleutel. Dan mag aanduidingBijHuisnummer niet voorkomen.

**Comment by fsamwel** [comment]
@CathyDingemanse ben je het hiermee eens? Dan verwijder ik aanduidingBijHuisnummer uit de bewoners

**Comment by CathyDingemanse** [comment]
Prima.
