### ISSUE TITLE
Hoe werkt bewoning bij niet-BAG adressen en zoeken op burgerservicenummer?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#581]
Bewoning kan worden gevraagd op burgerservicenummers.

Nu kan een persoon een bepaalde tijd een niet-BAG adres gehad hebben. Verwachten we van de API dat deze ook de medebewoners op die niet-BAG-adressen toont? 
Of verwachten we dat de API dan voor een deel van de gevraagde periode geen bewoning toont?

**Comment by fsamwel** [comment]
@CathyDingemanse hoe denk jij hierover?

**Comment by CathyDingemanse** [comment]
Dat ligt er aan hoeveel dat is. Ik zou voor iedere implementatie deze afweging apart maken. Voor Den Haag: niet laten zien. Den Haag de koppeling met BAG adressen in de BRP al behoorlijk lang op orde.
