### ISSUE TITLE
/haalcentraal/ verwijderen uit url bewoningen 

### ISSUE THREAD

**Issue by hansvandijk93** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#583]
Op dit moment bevat de specificatie van de bewoning API de volgende paden
- /haalcentraal/bewoningen
- /haalcentraal/bewoningen/{identificatiecodenummeraanduiding}

Dit is niet consistent met de andere specificaties, om twee redenen:

Url is anders, voorbeeld brp api:  /haalcentraal/api/brp/ingeschrevenpersonen. Dus de url moet voor bewoningen dan /haalcentraal/api/bewoningen zijn. (Update: volgens Cathy moet bewoning los van BRP bevraagbaar zijn, dus dan is dit de url)

Bij andere specificaties is alleen het laatste deel van het pad in de specificaties opgenomen. Dat zou betekenen dat voor bewoningen alleen de volgende paden aanwezig moeten zijn:
- bewoningen
- bewoningen/{identificatiecodenummeraanduiding}

Is het misschien nuttig om in alle specificaties voortaan het volledige pad vanaf haalcentraal op te nemen? Nu staat de BRP en Bewoning api in dezelfde map, dan is behalve dat de bestanden gescheiden zijn, niet af te leiden of ze nu bij elkaar horen. Door de paden te specificeren is de context van een pad direct duidelijk:
- /haalcentraal/api/brp/ingeschrevenpersonen
- /haalcentraal/api/bewoningen/{identificatiecodenummeraanduiding}
- /haalcentraal/api/brk/kadastraalonroerendezaken
- /haalcentraal/api/hr/maatschappelijkeactiviteiten/{kvkNummer}
- etc.

Dit voordeel geldt ook voor consumer, die kunnen zo een geleverd base-path (bijv. https://www.haalcentraal.nl/haalcentraal/api/) zonder twijfel matchen met de verschillende varianten in de specificatie.

Enige nadeel is dat wanneer we haalcentraal/api ooit veranderen in een andere variant, dit in alle specificaties moet worden aangepast. Mogelijk is dit op te lossen met een globale variabele in elke specificatie?

**Comment by fsamwel** [comment]
@hansvandijk93 ik denk dat /haalcentraal/ uit de endpoint definitie moet, zoals dat ook niet in de andere api delen zit.

De verschillende delen zijn bewust in andere api specificaties gestopt. Het zijn andere api's, met een eigen versiebeheer. Bijvoorbeeld voor reisdocumenten is voorzien dat dit ooit uit de BRP gaat en is daarom in een eigen api gestopt. Naar mijn idee zal een provider de verschillende api's in verschillende basis url's leveren, en dus niet allemaal onder /haalcentraal/api/brp. Wij kunnen op dit moment denk ik niet voorschrijven hoe dat basispad eruit moet zien, anders dan de basisstructuur zoals die in de api/uri strategie staat beschreven. De manier waarop dit binnen de gemeente aan binnengemeentelijke gebruikers wordt aangeboden kan ook weer anders zijn dan de url waarop de basisregistratie ze aanbiedt. Dus ik zou alleen het deel van het endpoint/de url beschrijven binnen de API, kortom alleen de resource-naam of het resource pad.

Ik maak een pull request om /haalcentraal eruit te halen.
