### ISSUE TITLE
Links in BewoningHal moet HalLink naar ingeschrevenpersonen bevatten

### ISSUE THREAD

**Issue by hansvandijk93** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#584]
Op dit moment heeft een BewoningHal in zijn _embedded een lijst met de bewoners als ingeschrevenpersoon op het moment dat daar met expand om gevraagd wordt.

Deze personen moeten ook standaard al als HalLink te vinden zijn onder de _links attribuut van BewoningHal.

Dit geeft de afnemer de mogelijkheid om elke bewoner los op te halen als ingeschreven persoon. Dit is bijvoorbeeld nodig als hij de ouders/partners/kinderen van een persoon wil hebben. Die krijgt hij niet mee (ook geen link) in de _embedded, daar is het type van de resource namelijk IngeschrevenPersoon en niet IngeschrevenPersoonHal.

**Comment by fsamwel** [comment]
ik heb pull request ingediend om dit toe te voegen
