### ISSUE TITLE
Definitie tabelwaarden gewijzigd - is dat gewenst?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#590]
Vanuit het BRK API project is besloten om Waardetabel om te noemen naar Waardelijst. Daarmee is niet alleen de componentnaam gewijzigd, maar ook de inhoud daarvan. In plaats van properties code en omschrijving is het gewijzigd naar properties code en waarde.

Is dit werkelijk gewenst voor BRP? Is waarde hier duidelijk? Ik denk dat het eigenlijk de omschrijving is die hoort bij de code-waarde.

Ook hebben we hier nu last van, omdat de applicaties die al gemaakt zijn hierdoor gewijzigd moeten worden. Dit betreft zowel de BRP-bevragingen API als de landelijke tabellen API.

**Comment by CathyDingemanse** [comment]
Ik denk dat we hier geen halszaak van moeten maken. Genericiteit is geen doel op zich. Als domein A tabellen gebruikt en domein B en C waardelijsten, lijkt mij dat geen probleem. Dit doorzetten gaat een hoop tijd kosten begrijp ik. Terugdraaien!
