### ISSUE TITLE
Hoe omgaan met onvolledige datums?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#6]
Er kunnen op twee manieren onvolledige datums nodig zijn:
1. Bij het zoeken (query parameter in de request url)
2. In het antwoord

In RSGB-bevragingen v1.0 wordt hier op twee verschillende manieren mee omgegaan:
1. in de query parameter is het één string met format 'dd-mm-jjjj', 'mm-jjjj' of 'jjjj'.
2. in het antwoord is het een gegevensgroep met drie elementen dag, maand en jaar

Bij RSGB-bevragingen wordt de keuze echter niet beschreven bij design decisions, maar dit zijn wel keuzes die verantwoord moeten worden.

Ik zou er voor willen pleiten om één consistente oplossing te kiezen voor beide situaties.
Ik zou ook willen pleiten om meer aan te sluiten op het "normale" datumformaat, dus niet 'dd-mm-jjjj', maar 'jjjj-mm-dd'

**Comment by joeribekker** [comment]
Wij (gemma-zaken) kiezen hier om de DSO te volgen en [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) te gebruiken.

Zoiets als onvolledige datums moet naar mijn mening niet bestaan 😅 op het niveau van vastlegging. Bevragen kan natuurlijk wel op bijvoorbeeld alleen een jaar maar hier zijn naar mijn weten geen gestandaardiseerde formaten voor. Wij hanteren "<attribuut>__year" en/of "<attribuut>__month" om op delen van datums/tijden te filteren (dit vertaald zich niet helemaal toevallig heel fijn naar SQL).

**Comment by fsamwel** [comment]
@Joeri, dank voor het delen hiervan. Voor datums gebruiken wij in principe ook ISO8601 zoals de API strategie voorschrijft. Maar daarin heb ik geen beschrijving van hoe je onvolledige datums kunt opnemen.
Voor personen is een onvolledige datum een realiteit. Er wonen in Nederland mensen die niet hier geboren zijn, en waarvan alleen het geboortejaar bekend is. 

Jij stelt dus voor om voor het zoeken op geboortedatum de zoekparameters geboortedatum_year, geboortedatum_month en geboortedatum_day te gebruiken, die dan voor zoeken op een volledige geboortedatum alle drie moeten worden ingevuld? Worden ook in het zoekresultaat deze drie elementen opgenomen (i.p.v. één element geboortedatum)?

**Comment by fsamwel** [comment]
Besproken in projectoverleg 21 september.
Ten behoeve van het ondersteunen van onvolledige datums, wordt de geboortedatum in het responsebericht een gegevensgroep "geboorte" met 4 properties:
- geboortejaar: date-fullyear
- geboortemaand: date-month
- geboortedag: date-mday
- geboortedatum: date

Deze velden zijn gedefinieerd in ISO8601-typen.
Als er een volledige geboortedatum is, worden alle 4 velden ingevuld, anders alleen de bekende delen.

Melvin controleert de eenvoud van implementatie van deze oplossing (met redundante geboorte-properties).

**Comment by joeribekker** [comment]
Ik begrijp de noodzaak voor onvolledige datums en er moet een design keuze gemaakt worden.

Zelf opteer ik voor 2 properties:

* geboortedatum: date
* precisieGeboortedatum: enum(dag=standaard, maand, jaar)

Bij het ontbreken van de dag (precisie=maand) vul je toch een geboortedatum in, maar dan voor het ontbrekende deel 1. Dus April 2018, wordt 01-04-2018. In het geval van het ontbreken van dag en maand (precisie=jaar) wordt het 01-01-2018.

Dit maakt berekeningen met de geboortedatum mogelijk EN eenduidig. Wanneer is iemand namelijk 18 jaar als de maand niet bekend is? Op de manier die Frank beschrijft is dit ambigu, in het geval dat er wel een aanname op de dag is gedaan (eerste dag van de maand), is het voor iedereen duidelijk.

Tegelijkertijd blijft het ook duidelijk dat er sprake is van minder precisie.

**Comment by joeribekker** [comment]
Hmmm, ik zag dat dit issue ook al letterlijk is verwerkt als design keuze aan de hand van Franks laatste comment: https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/commit/127486d092e58e1d5ec2b8f0c3ece5a21c80540b#diff-0cbfc51c3dd2d8dda1ac6fea95b35912R138

Dit terwijl het blijkbaar nog gechecked moet worden (door Melvin) en het issue nog open staat. De relatie tussen issues en de master-branch is zo niet meer consistent. En uiteraard vind ik er ook wat van 😅

**Comment by joeribekker** [comment]
Onvolledige datums topic besproken met Martijn van der Linden op het Fieldlab. Hij is Senior Specialist Burgerzaken geweest bij Nijmegen en lid van de Commissie Persoonsinformatievoorziening.

Hij gaf o.a. aan dat eigenlijk het voorstel wat ik eerder deed, ook wordt aangehouden op landelijk niveau door o.a. DUO en de Belastingdienst. Hij had 2 aanvullingen:

1. De standaard maand is juli, dus bij een onbekende dag en maand, wordt de datum 01-07-[JAAR].
2. De combinatie van precisie en datum, zou eigenlijk ook nog een consistente weergave moeten hebben, nu wordt defacto standaard 00 gebruikt voor onbekende delen van de datum.

Dit pleit voor 3 properties:
* geboortedatum: date
* geboortedatumPrecisie: enum(dag=standaard, maand, jaar)
* geboortedatumWeergave: string(8)

Een voorbeeld waarbij alleen het jaar bekend is, wordt dan:
* geboortedatum: 01-07-1983
* geboortedatumPrecisie: jaar
* geboortedatumWeergave: 00-00-1983

Deze laatste is dus geen geldige datum om mee te rekenen, maar maakt in 1 oogopslag duidelijk wat er aan de hand is. Denk dat we het laatste veld ook moeten opnemen als read-only.

**Comment by CathyDingemanse** [comment]
Mijns inziens is tweaken met brongegevens (en zeker BRP gegevens!) niet verstandig, maar los je problemen als "kun je niet mee rekenen" client side op door client side te manipuleren als dat nodig is. De manier van manipulatie is afhankelijk van de businessbehoefte.

**Comment by joeribekker** [comment]
Dit is volgens mij een mooie kans om de interpretatie van data strak te trekken, anders houden we de inconsistente situatie zoals het nu is, maar dan in een REST API. Data wordt met deze oplossing ook niet aangepast (geen tweaken). Jammer als we deze kans laten liggen.

Als je  besluit vast staat kan het ticket worden gesloten.

**Comment by JohanBoer** [comment]
In het LO GBA staat een paragraaf over het rekenen met datums: 

_Bij een vergelijking van datums is het mogelijk om alleen het jaartal of het jaartal en de
maand van een bepaalde datum in een vergelijking te betrekken. Welk deel van de datum
in de vergelijking betrokken moet worden, is afhankelijk van de waarde van het rechterlid
van de vergelijking.
Indien het rechterlid een waarde jjjj0000 bevat, wordt alleen het jaartal in de vergelijking
betrokken. Indien het rechterlid een waarde jjjjmm00 bevat, wordt alleen het jaartal en de
maand in de vergelijking betrokken. Indien het rechterlid een waarde jjjjmmdd of 00000000
bevat wordt de gehele waarde in de vergelijking betrokken.
Als voorbeeld beschouwen we de volgende voorwaarderegel: 01.03.10 GD1 19.89.30 -
0035. Stel de persoon in kwestie is op 19580427 geboren en het is vandaag 19930426. De
vergelijking verloopt dan als volgt:
19580427 GD1 19930426 - 0035
19580427 GD1 19580000
1958 GD1 1958
ONWAAR
De persoon voldoet niet aan de voorwaarderegel. Ter completering van het voorbeeld
beschouwen we de volgende voorwaarderegel: 01.03.10 GD1 19.89.30 - 00350000. We
nemen dezelfde persoon en dezelfde dag van vandaag. De vergelijking verloopt nu als
volgt:
19580427 GD1 19930426 - 00350000
19580427 GD1 19580426
WAAR
De persoon voldoet nu wel aan de voorwaarderegel._

Volgens het LO GBA mag er dus niet met een ingevulde datumwaarde gerekend worden als ik dit goed interpreteer en dat is de functionele beschrijving van de basisregistratie personen.

**Comment by JohanBoer** [comment]
Mijn vraag is nog wel of we deze oplossing nu op alle datums gaan toepassen of op een selectie van datums. Hoe kan ik bepalen op welke datums het toegestaan is om een mogelijk onvolledige datum te registreren.

**Comment by CathyDingemanse** [comment]
Heb het nagevraagd bij de burgerzaken expert. Geheel tegen de verwachting in heb ik het volgende antwoord gekregen. Onvolledige datums kunnen ook voorkomen bij:
- huwelijk(sluiting) en beëindiging en Partnerschap, 
- Datum inschrijving  
- Datum aanvang adreshouding 
- Datum aanvang adres buitenland.

**Comment by gertjanvanderkooij** [comment]
Geldt bv. ook voor Datum overlijden, Datum ingang geldigheid (voor zover gebruikt bij het vullen van 'GeldigVanaf/GeldigTotEnMet; bij Nationaliteit?) Datum ingang familierechtelijke betrekking, Ingangsdatum verblijfstitel, Datum einde verblijfstitel, ...

Als iemand mij de volledige lijst van gegevenselementen zoals deze door de API worden geleverd kan aanreiken, dan zal ik de datums die cf. LO GBA (deels) onvolledig kunnen zijn hierop aangeven.

**Comment by fsamwel** [comment]
De lijst zie je in https://petstore.swagger.io/?url=https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/openapi.yaml#/ onder models >> IngeschrevenNatuurlijkPersoon

Maar in essentie is LO GBA de basis en zou de api definitie één op één moeten overeenkomen hiermee. (Uiteraard wel als een technische vertaling naar yaml/json en sommige categorieën zijn een relatie geworden, maar voor de opgenomen attributen maakt dit niet uit)
> zal ik de datums die cf. LO GBA (deels) onvolledig kunnen zijn hierop aangeven
Heel graag, je kan je daarbij dus puur baseren op de LO GBA attributen.

**Comment by JohanBoer** [comment]
Nu doorgevoerd voor de volgende datums : 

datumHuwelijkssluiting_aangaanGeregistreerdPartnerschap
datumOntbindingHuwelijk_geregistreerdPartnerschap
datumInschrijvingInGemeente
geldigVan (bij verblijfsplaats)
geboortedatum
datumOverlijden
geldigVan(veblijfstitel, ouder_relatie, kind_relatie)
geldigTotenMet(verblijfstitel , ouder_relatie, kind_relatie)

geboortedatum (Ander natuurlijk persoon)
overlijdensdatum (Ander natuurlijk persoon)

OOk in de "historie"is dit opgenomen voor de betreffende velden. Uitbreiden is geen probleem.

**Comment by gertjanvanderkooij** [comment]
Ik heb de YAML even nagelopen (quickscan) en heb gebruik datums en definities in GBA nog even nagekeken. Zie bijgaand attachment. 

In attachment ook nog aanvullende vragen/opmerkingen n.a.v. quickscan. Deze niet als aparte issues op Github opgenomen. @JohanBoer / @fsamwel ; indien relevant willen jullie dit dan doen? 

Indien niet issue-waardig, wel graag feedback voor mijn begrip; bv. via extra kolom in xls, hierna upload?

[InventarisatieDeelsOnbekendeDatums.xlsx](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/files/2539817/InventarisatieDeelsOnbekendeDatums.xlsx)

**Comment by fsamwel** [comment]
Maarten vd Broek geeft aan dat de gekozen oplossing voor ongeldige datum onhandig is, vooral omdat het minder mooi leesbaar in de json (als ontwikkelaar maakt het weinig uit). Blaast veld op naar groep met 4 velden, terwijl 99% van de datums wel volledig zijn. Voorgestelde oplossing: string met "YYYY-MM-DD", "YYYY-MM" of "YYYY".

**Comment by fsamwel** [comment]
Johan, kan je de inventarisatie van Gert Jan (https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/issues/6#issuecomment-435160115) in InventarisatieDeelsOnbekendeDatums.xlsx verwerken

**Comment by JohanBoer** [comment]
Inventarisatie van GertJan is verwerkt. Zie in de bijgaande spreadsheet voor Vragen. Ik heb niet alles kunnen verwerken en er staan enkele vragen open. 
[20181112InventarisatieDeelsOnbekendeDatums.xlsx](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/files/2608372/20181112InventarisatieDeelsOnbekendeDatums.xlsx)

**Comment by JohanBoer** [comment]
Check is uitgevoerd. 

Representatie van onbekende datum is de datum niet opnemen in het antwoord. Zie reactie van Cdingemanse op [Geonovum/KP-APIs#18](https://github.com/Geonovum/KP-APIs/issues/18)
