### ISSUE TITLE
embedded ingeschreven persoon bij bewoning bevat geen _links

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#600]
Bewoning_embedded bevat een property ingeschrevenPersonen die gevuld wordt met items IngeschrevenPersoon.

Dit betekent dat het geen _links bevat. Dit zou ik hier wel verwachten.

N.B. het is terecht dat er geen _embedded in zit. Je kan dus niet de huidige IngeschrevenPersoonHal hergebruiken uit de actuele bevragingen.

N.B. ik zou bij Bevraging-Ingeschreven-Persoon in IngeschrevenPersoonHal alleen _links toevoegen, en een extra component maken die de _embedded toevoegt. Je kan dan ook in bewoningen de IngeschrevenPersoonHal hergebruiken.

**Comment by JohanBoer** [comment]
Ik heb voor een andere oplossing gekozen die geen invloed heeft op bevraging ingeschreven persoon, maar wel hergebruik maakt van ingeschrevenpersoon_links. Volgens mij bereiken we daar ook de gewenste uitkomst mee.

**Comment by JohanBoer** [comment]
Zie pull request #608
