### ISSUE TITLE
Links naar documentatie historische bevragingen werken niet (meer?)

### ISSUE THREAD

**Issue by sgort** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#601]
# Impediment
Ik ben voor implementatie Waardepapieren op zoek naar specificatie Verblijfplaatshistorie. De links alhier naar historische bevragingen (zie https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/tree/master/api-specificatie/Bevraging-Historie en Swagger link https://petstore.swagger.io/?url=https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/Bevraging-Historie/openapi.yaml) werken niet.

**Comment by fsamwel** [comment]
@JohanBoer het gaat om de links op https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/tree/master/api-specificatie. Haal jij deze weg?

@sgort de historische bevragingen zijn opgenomen in de algemene bevragingen

[Open API Specificaties en JSON schema](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/tree/master/api-specificatie/Bevraging-Ingeschreven-Persoon) | [Swagger](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/master/api-specificatie/Bevraging-Ingeschreven-Persoon/openapi.yaml) |
-- | --

**Comment by JohanBoer** [comment]
Done
