### ISSUE TITLE
Als beheerder van een begraafplaats wil ik een overleden persoon op kunnen vragen

### ISSUE THREAD

**Issue by PatrickCastenmiller** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#607]
...zodat ik een referentie kan opnemen in mijn begraafplaatsregister in plaats van het kopiëren van de persoonsgegevens.

Het gaat er om dat historische personen (in het verleden overleden personen) nu niet kunnen worden opgevraagd. Als hiervoor wel een service beschikbaar is, kunnen we in de begraafplaatsregistratie blijven verwijzen en is het voldoende om het BSN op te nemen. De begraafplaatsregistratie bevat daarmee de verblijfplaats van de overleden persoon.

**Acceptatiecriteria**
- [ ] 
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
Via de zoek-mogelijkheid is het nu al mogelijk om de gegevens van een ingeschreven persoon op te halen waarbij in het endpoint /ingeschrevenpersonen ook de parameter "inclusiefoverledenpersonen"kan worden aangevinkt. 

In de resourcedefinitie is de overlijdensdatum ook opgenomen.
@CathyDingemanse : Dit is mogelijk een business case om ook overleden personen op te kunnen vragen met de endpoint /ingeschrevenpersonen/{burgerservicenummer}

**Comment by CathyDingemanse** [comment]
> @CathyDingemanse : Dit is mogelijk een business case om ook overleden personen op te kunnen vragen met de endpoint /ingeschrevenpersonen/{burgerservicenummer}

Ik dacht eigenlijk dat dat al zo was (anders zou de API niet restful zijn), maar zie idd in de desciptions iets anders staan. We hoeven niks aan de specs te wijzigen lijkt het, iig geen breaking change, want in het antwoord van /ingeschrevenpersonen/{burgerservicenummer} staat:

 },
  "overlijden": {
    "indicatieOverleden": true,
    "datum": {
      "dag": 3,
      "datum": "1989-05-03",
      "jaar": 1989,
      "maand": 5
    },
    "land": {
      "code": "6030",
      "omschrijving": "Nederland"
    },
    "plaats": {
      "code": "6030",
      "omschrijving": "Nederland"
    },
    "inOnderzoek": {
      "datum": true,
      "land": true,
      "plaats": true,
      "datumIngangOnderzoek": {
        "dag": 3,
        "datum": "1989-05-03",
        "jaar": 1989,
        "maand": 5
      }
    }
  },

Alleen de description veranderen. Kwestie van doen dus... ?

**Comment by fsamwel** [comment]
@JohanBoer waaruit concludeer je dat het ophalen van een overleden persoon op burgerservicenummer niet zou kunnen? Ik zie nergens in de specificaties zoiets staan. Dat hebben we alleen bij zoeken van personen gedaan, waar je default alleen levende personen krijgt.

De implementatie in Den Haag is in ieder geval ook zo, daar kan je op ingeschrevenpersonen/{burgerservicenummer} gewoon een overleden persoon opvragen.

**Comment by JohanBoer** [comment]
Ik denk dat ik de stelling van @PatrickCastenmiller gecombineerd heb met het feit dat je bij zoeken default alleen levende ingeschreven personen geretourneerd krijgt. 

Ik kan inderdaad nergens in de specificaties vinden dat met de API geen overleden personen op te vragen zijn, dus dit is dan helemaal geen issue. 

Blijft de vraag open waarom @PatrickCastenmiller wel de conclusie heeft getrokken dat overleden personen niet opgevraagd kunnen worden.

**Comment by PatrickCastenmiller** [comment]
De bedoeling van mijn userstorie was om een functionele vraag te formuleren. HIerbij heb ik onvoldoende onderzocht of dit al mogelijk was (mijn aanname was dat dit niet kon, omdat we het nooit doen).

Als ik de discussie goed begrijp, is het gewoon mogelijk om overleden personen op te vragen via Haal Centraal en is het daarmee mogelijk om vanuit het begraafplaatsregister een referentie naar de overleden persoon in de BRP.

Blijft een overleden persoon voor altijd in de BRP staan?
