### ISSUE TITLE
Schiedam wil voor digitale uittreksels Haal Centraal BRP API via NLX gebruiken

### ISSUE THREAD

**Issue by sgort** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#618]
maar kan nu tijdens de (door)ontwikkeling van haar oplossing geen gebruik maken van NLX omdat er geen inway beschikbaar is / neergezet is voor NLX.

Verzoek om deze belemmering weg te nemen en het mogelijk te maken de demo van Haal Centraal API via NLX te benaderen.

PS
Het gaat hier overigens niet alleen over Schiedam. De idee is om landelijk een digitaal uittreksel toegankelijk te maken voor ALLE burgers in Nederland. Onafhankeliijk van de gemeente waar men woont. De voorhoede gemeentes zijn:

- Haarlem
- Harderwijk
- Rotterdam
- Schiedam

**Comment by sgort** [comment]
@CathyDingemanse any update en/of bericht hieromtrent?

**Comment by CathyDingemanse** [comment]
Het aanbieden van de API's via NLX is buiten scope van Haal Centraal. Om een HC API te kunnen gebruiken is een NLX inway niet randvoorwaardelijk. De API's worden ontsloten conform de eisen die zijn geformuleerd in de NL API Strategie. Dit wil natuurlijk helemaal niet zeggen dat het niet kan of niet gebeuren zal, het is gewoon geen onderdeel van de opdracht. 
Het is aan de aanbieder van een HC API om een (extra) endpoint aan te bieden via een NLX inway.

**Comment by sgort** [comment]
Dank je wel. Helder. Consequentie is dan dat de huidige test API (ie de eigen implementatie die ook tijdens API lab wordt gebruikt) niet te testen is icm NLX. Correct?
