### ISSUE TITLE
InternalServerError ?

### ISSUE THREAD

**Issue by sgort** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#625]
# Impediment

Ik maak dankbaar gebruik van Haal Centraal in een demonstrator voor keten derdenbeslag die ik aan het maken ben. Sinds gisteravond verschijnt een internalservererror zodra ik een GET request ingeschreven Natuurlijk Persoon doe.

![image](https://user-images.githubusercontent.com/25812095/81265823-ff615980-9043-11ea-9297-1bc7be2d63f7.png)

**Comment by gertjanvanderkooij** [comment]
@melsk-r @JohanBoer 
Inderdaad graag jullie aandacht voor gemeld impedement. Ik maak bij gelegenheid ook dankbaar gebruik van deze testfaciliteit.  

Aanvullende informatie:
De BRP Bewoning- en Tabellen-API werken wel goed.

**Comment by JohanBoer** [comment]
Issue wordt opgepakt.

**Comment by fsamwel** [comment]
@sgort en @gertjanvanderkooij het issue is opgelost, de API doet het weer

**Comment by sgort** [comment]
Super. Ga het gelijk proberen.

**Comment by sgort** [comment]
Werkt idd weer goed! Ik sluit de issue.

**Comment by sgort** [comment]
Dag @JohanBoer , het probleem is weer terug. Zelfde als hierboven.

```
{
    "type": "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_InternalServerError",
    "title": "Interne server fout.",
    "status": 500,
    "detail": "Onverwachte fout bij zoeken op: Burgerservicenummer Policy Falsified",
    "instance": "https://www.haalcentraal.nl/haalcentraal/api/brp/ingeschrevenpersonen?burgerservicenummer=999994669",
    "code": "serverError"
}
```

**Comment by fsamwel** [comment]
@sgort misschien een tijdelijke storing geweest bij het GBA-V (die onderwater aangesproken wordt door de API). Bij mij werkt het nu gewoon.

**Comment by sgort** [comment]
Yep. Check alhier leert dat het werkt. :+1:
