### ISSUE TITLE
soortVerbintenis in _embedded van partner niet in voorbeeldimplementatie

### ISSUE THREAD

**Issue by OnnoLogchies** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#628]
Ik gebruik de voorbeeld implementatie van HaalCentraal regelmatig om de werking van de API uit te pluizen.
Nu valt me op dat het veld soortVerbintenis niet meegegeven wordt in de partner relatie. Ook bij de historische relatie zie ik het niet terugkomen. 
Is dit een bug in de implementatie of doe ik iets fout waardoor ik hem niet terugkrijg?

Een voorbeeld is: `https://www.haalcentraal.nl/haalcentraal/api/brp/ingeschrevenpersonen/999991139?expand=partners`

**Comment by fsamwel** [comment]
Hallo @OnnoLogchies dit klopt. De voorbeeldimplementatie gebruikt onderwater de GVA-V service. Deze wordt gebruikt op basis van tabel 35 Algemene Gemeentetaken. Je krijgt in de voorbeeldimplementatie dus alleen gegevens waarvoor een gemeente voor buitengemeentelijke personen is geautoriseerd. Dat is helaas een beperking van de voorbeeldimplementatie. 
De voorbeeldimplementatie is eigenlijk gebouwd voor gemeente Den Haag als tijdelijke migratievoorziening tot RvIG de API kan leveren. Daarin worden binnengemeentelijke personen opgehaald uit het gegevensmagazijn en buitengemeentelijke personen uit het GBA-V. De HaalCentraal voorziening is een kopie daarvan, op een externe server, zonder toegang tot het Haagse gegevensmagazijn (heeft iets met security te maken).

**Comment by OnnoLogchies** [comment]
Dank je voor de terugkoppeling, ik begrijp de beperking. Wel jammer
