### ISSUE TITLE
Zoeken overleden personen op BSN werkt niet

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#629]
Aangedragen door Centric:

als ik een vraag stel met alleen een BSN en de parameter ‘inclusiefoverledenpersonen=true’ dan krijg ik de volgende foutmelding retour:

Request: {{baseUrl}}/ingeschrevenpersonen?burgerservicenummer=999993562&inclusiefoverledenpersonen=true

Response:
{
    "type": "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_BadRequest",
    "title": "Minimale combinatie van parameters moet worden opgegeven.",
    "status": 400,
    "detail": "Voor zoeken naar overleden personen moet minimaal de geslachtsnaam in combinatie met de gemeente van inschrijving worden opgegeven.",
    "instance": "https://www.haalcentraal.nl/haalcentraal/api/brp/ingeschrevenpersonen?burgerservicenummer=999993562&inclusiefoverledenpersonen=true",
    "code": "paramsCombination"
}

We gebruiken het endpoint  https://www.haalcentraal.nl/haalcentraal/api/brp.

**Comment by JohanBoer** [comment]
Als ik deze bevraag zonder de parameter inclusiefoverledenpersonen krijg ik gewoon een response. Dat betekent dat de betreffende persoon niet is overleden. 
Het gebruiken van de parameter inclusiefoverledenpersonen zou exact dezelfde response tot gevolg moeten hebben.

**Comment by fsamwel** [comment]
Dit is een bug en wordt opgelost voor de implementatie in Den Haag. De haalcentraal.nl/API-lab server wordt voor zover ik weet nog niet beheerd, dus daar wordt het waarschijnlijk niet opgelost.

**Comment by CathyDingemanse** [comment]
Is een autorisatiekwestie. Ligt aan proefomgeving aurorisatie op GBA-V.
