### ISSUE TITLE
Vanuit Angular of browser krijgen we CORS policy meldingen, graag preflight willen accepteren

### ISSUE THREAD

**Issue by shazada** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#630]
# Impediment
We krijgen nu het volgende issue:
https://stackoverflow.com/questions/56579632/angular-interceptor-modify-headers-change-request-method/56579763#56579763

We willen namelijk direct vanaf de GUI (webbrowser) de API bevragen i.p.v. een Backend API omdat het toch JSON is en snel zou moeten kunnen werken.
We lopen echter tegen CORS meldingen aan en komen niet verder.
Volgens de stackoverflow issue zou preflight geaccepteerd moeten worden.

**Comment by sergei-maertens** [comment]
Is dit handig? Als je met API keys, dan wil je toch niet dat die keys in de browser van eindgebruiker uit te lezen zijn? En mocht er niet met API keys maar met NLX gewerkt worden bijvoorbeeld, dan moet je sowieso naar de eigen backend om je outway te bereiken.

**Comment by shazada** [comment]
Aha goed punt, ja we hebben nu een proxy gemaakt aan de backend die dit vanaf de frontend doorstuurd.
Maar dat API keys had ik niet aan gedacht, thanks!
