### ISSUE TITLE
vanuitVertrokkenOnbekendWaarheen altijd in response, ongeacht true of false?

### ISSUE THREAD

**Issue by Robkromwijk** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#632]
Het attribuut 'vanuitVertrokkenOnbekendWaarheen' is een boolean. De waarde van dit attribuut is een afgeleide van het attribuut 'landVanwaarIngeschreven'. Als deze waarde "0000" heeft, dan is 'vanuitVertrokkenOnbekendWaarheen' true.

Het attribuut 'vanuitVertrokkenOnbekendWaarheen' wordt altijd in de response teruggegeven, ongeacht de waarde "true" of "false". De specificaties is daar niet expliciet over.
https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/eeefd22c035825b37a3fc592817f91f674172c09/api-specificatie/Bevraging-Ingeschreven-Persoon/openapi.yaml#L1586

Bij attribuut 'indicatieVestigingVanuitBuitenland' staat wel expliciet dat alleen waarde "true" wordt teruggegeven in de response.
https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/eeefd22c035825b37a3fc592817f91f674172c09/api-specificatie/Bevraging-Ingeschreven-Persoon/openapi.yaml#L1564

Mijn vraag is of 'vanuitVertrokkenOnbekendWaarheen' ook alleen bij waarde "true" in de response zou moeten zitten. Zeker omdat de waarde in relatie is met attribuut 'landVanwaarIngeschreven', die niet altijd in de response zit.

**Comment by OnnoLogchies** [comment]
Dit geldt ook voor het attribuut 'geheimhoudingPersoonsgegevens'. Er staat niet benoemd dat alleen 'true' teruggegeven wordt, echter ik verwacht wel dat het nu zo geïmplementeerd is in de voorbeeldimplementatie.
https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/eeefd22c035825b37a3fc592817f91f674172c09/api-specificatie/Bevraging-Ingeschreven-Persoon/openapi.yaml#L1036

Is het niet zo dat een boolean met 'false' nooit in de API response zit?

**Comment by CathyDingemanse** [comment]
Klopt @OnnoLogchies! 
Wij doen niet aan booleans "= false". Reden is dat de berichten dan enorm groot worden met allemaal irrelevante informatie. Ook doen wij niet aan magic strings (null waardes e.d.). Vuistregel is: als het relevant of aan de orde is krijg je het altijd in een eenvoudig en duidelijke response. Is het niet relevant of aan de hand, dan zit het niet in de response.

**Comment by CathyDingemanse** [comment]
> Ik zie in issue #421 trouwens voor dit specifieke element ook een issue, echter in de design decisions kom ik geen besluit tegen.

Zie: https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/master/docs/design_decisions.md
DD5.9 Properties die gebruik maken van Booleans worden alleen geretourneerd als de waarde 'true' is
In diverse situaties worden booleans opgenomen als er sprake is van indicatoren. Deze booleans worden alleen geretourneerd als de waarde van de boolean ook informatief is. Dit soort properties worden dus alleen opgenomen als de waarde van de Boolean 'true' is.

**Comment by OnnoLogchies** [comment]
Dank je voor de link naar deze design decisions! Er zit er ook een in de docs folder van de BRP bevragen API, daar had ik gekeken.

**Comment by OnnoLogchies** [comment]
Dit issue kan worden gesloten wat ons betreft, is beantwoord.
