### ISSUE TITLE
Vraag: welke testdata is er beschikbaar op haalcentraal.lostlemon.nl

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#635]
Om deze testomgeving te kunnen gebruiken moet je filter-parameters gebruiken, maar ik zie nergens een overzicht van welke testdata er effectief opgenomen is. Dat maakt het gebruik van de testomgeving niet praktisch. Is er een overzicht van elke data hierin vervat it?

**Comment by joeribekker** [comment]
Mijn oog viel op: https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/master/docs/getting-started.md

**Comment by sergei-maertens** [comment]
Helder!
