### ISSUE TITLE
Aanhef en aanschrijfwijze bij geslachtsaanduiding 'onbekend'

### ISSUE THREAD

**Issue by Robkromwijk** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#636]
Bij het bepalen van de juiste aanhef en aanschrijfwijze worden gebruik gemaakt van het attribuut geslachtsaanduiding.

https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/master/features/aanhef.feature
https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/master/features/aanschrijfwijze.feature

In de genoemde use stories bij de feature wordt uitgegaan dat de geslachtsaanduiding altijd 'man of 'vrouw' is, maar 'onbekend' is ook een toegestane waarde. Of 'onbekend', omdat de gebruiker niet gerechtigd is voor dit attribuut.

Wat is de aanhef bij geslachtsaanduiding 'onbekend'?
Mijn voorstel zou zijn in de geslachtsaanduiding, dan niet te gebruiken. Dus "Geachte de Vries"

Wat is de aanschrijfwijze bij geslachtsaanduiding 'onbekend'?
Geslachtsaanduiding wordt niet direct gebruikt in de aanschrijfwijze, dus ik voorzie geen probleem. "W. de Vries".
Lijkt mij wel goed om geslachtsaanduiding 'onbekend' expliciet in de feature voorbeelden te noemen.

**Comment by fsamwel** [comment]
Bij de (tijdelijk) implementatie voor Den Haag hebben we dan heer/mevrouw gebruikt.

Bijvoorbeeld /ingeschrevenpersonen/999991310:
"aanhef" : "Geachte heer/mevrouw Debrabandere",
"gebruikInLopendeTekst" : "de heer/mevrouw Debrabandere"

Maar weglaten had ook gekund. toevoegen aan feature is inderdaad goed voorstel.

**Comment by Robkromwijk** [comment]
"heer/mevrouw" is inderdaad ook een optie. Misschien nog wel netter, dan zonder.

Kan een burger ook bewust geslachtsaanduiding 'onbekend' kiezen? In zo'n geval kan ik mij voorstellen dat deze persoon ook niet met "heer/mevrouw" aangeschreven wilt worden. Alleen dat is op basis van de data niet te achterhalen.

**Comment by fsamwel** [comment]
@gertjanvanderkooij Kan een burger ook bewust geslachtsaanduiding 'onbekend' kiezen?

Of gebruiken we geslachtsaanduiding onbekend alleen wanneer echt onduidelijk is wat het geslacht is?

Ik had in Den Haag begrepen (als ik het me goed herinner, is al tijdje geleden) dat daar onbekend niet voorkomt bij ingeschreven personen (wel bij ouders en partners).

**Comment by gertjanvanderkooij** [comment]
Oorspronkelijk inderdaad alleen in gebruik als na geboorte niet kon worden vastgesteld wat het geslacht van het kind was.

Momenteel is er veel te doen rondom de registratie van het geslacht en lijken er mogelijkheden te zijn/komen voor neutrale registratie van het geslacht. Zie ook [Onderzoek geslachtsregistratie](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwj7wuTxg7frAhUDx4UKHdO2D4oQFjAAegQIBhAB&url=https%3A%2F%2Fwww.rijksoverheid.nl%2Fbinaries%2Frijksoverheid%2Fdocumenten%2Fkamerstukken%2F2020%2F07%2F03%2Fbijlage-2-eindrapport-onderzoek-geslachtsregistraties%2Fbijlage-2-eindrapport-onderzoek-geslachtsregistraties.pdf&usg=AOvVaw2XXdpEFMkUAcJYXb1sqftx

De HUP GBA v3.3, paragraaf 5.8 Geslachtswijziging) beschrijft de registratie van 'Onbekend' nu ook als één van de mogelijkheden; voorheen was hier alleen de keuze voor hetzij 'Man' hetzij 'Vrouw'.

@fsamwel 
Verificatie bij gemeentelijke BRP-specialisten is aanbevolen.
