### ISSUE TITLE
verwijderen x-rate-limit

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#641]
de API bevat x-rate-limit headers en response 429.

Aangezien het gebruik van de BRP strak gereguleerd is met autorisatie en doelbinding zie ik het nut hier niet van in.

Deze kunnen wat mij betreft worden verwijderd, ook uit de reisdocumenten, bewoning en tabellen

**Comment by fsamwel** [comment]
@CathyDingemanse @MelvLee mee eens?

**Comment by CathyDingemanse** [comment]
Jazeker, dat is niet aan de orde hier.

**Comment by fsamwel** [comment]
ik ga ook response codes 409 (conflict) en 410 (gone) verwijderen. Snap niet wanneer die zouden moeten komen.

**Comment by fsamwel** [comment]
idem voor 415

**Comment by fsamwel** [comment]
https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bewoning/pull/6

**Comment by fsamwel** [comment]
https://github.com/VNG-Realisatie/Haal-Centraal-Reisdocumenten-bevragen/pull/4
