### ISSUE TITLE
Als ontwikkelaar wil ik duidelijke versie/status aanduiding in de API specificatie

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#642]
... zodat er geen verwarring ontstaat over versies.

Zo staat er 1.0.0 als versie nummer in de [openapi.yaml](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/commit/c1e9d644864db364a82eee1bc89baa6401678492#diff-fed98705329423c87af9e228fe9d09b6L8) maar wordt zonder versie wijziging wel de API specificatie [gewijzigd](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/commit/c1e9d644864db364a82eee1bc89baa6401678492#diff-fed98705329423c87af9e228fe9d09b6L58-L60).

Als de postfix `-dev` wordt opgenomen (dus `1.0.0-dev`) vind ik dit acceptabeler maar nu lijkt het alsof versie 1.0.0 is uitgegeven. Ook kan in de README expliciet worden gemaakt wat de status is van deze versie om verwarring te voorkomen.

**Acceptatiecriteria**
- [ ] De OAS of de README maken duidelijk welke versie deze API specificatie betreft en wat de status er van is

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by CathyDingemanse** [comment]
Beste Joeri, we zijn er mee bezig.

**Comment by JohanBoer** [comment]
Inmiddels is er een release "versie 1.0.0"uitgebracht. Ontwikkelingen vinden plaats in de "develop" en  feature branches. Daar zullen we het versie-nummer aanpassen. Volgens ons is hiermee de verwarring opgelost. 

Meen eens dat ik deze issue close ?

**Comment by joeribekker** [comment]
Gefeliciteerd met deze release!

Wat mij betreft is het zo prima (werken met tags). Dit maakt het zeer duidelijk, ticket mag dicht.

**Comment by CathyDingemanse** [comment]
Dank Joeri. Jij heel veel succes gewenst met jullie implementatie!
