### ISSUE TITLE
Als API consumer wil ik dat de API specificatie op een vaste locatie staat

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#643]
...zodat mijn client niet stuk gaat door verplaatsen van de API spec.

In https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/commit/9335b8a92487b80ec06814399d49bccabc134c3b zijn de API specs in een andere map-structuur geplaatst, waardoor mijn client stuk is.

Idealiter wil je dat die API spec natuurlijk ergens te vinden is op https://www.haalcentraal.nl/haalcentraal/api/brp/openapi.json conform de [landelijke API strategie](https://geonovum.github.io/API-Designrules/#api-51)

Ik pas voor nu de OAS referentie aan gepinned op een commit, maar verwijzen naar github is sowieso niet handig hiervoor.

**Comment by sergei-maertens** [comment]
Is hier nog enige voortang in/over?

Dit belemmert namelijk onze implementaties die idealiter self-discovering zijn.

**Comment by JohanBoer** [comment]
Op het moment dat jij naar deze commit verwees was de BRP-persoon-bevragen API nog in ontwikkeling (ruim 2 jaar terug).

Sinds die tijd hebben we enkele versies gepubliceerd en die als releases vastgelegd (op github.) De tags die aan deze releases gekoppeld zijn wijzigen niet. Als je dus nu naar een release verwijst loop je niet het risico dat de specificatie wijzigt. Dit zijn vaste locaties waar je op mag vertrouwen dat er geen wijzigingen meer plaatsvinden. 
De laatste versie die implementatierijp was en die we gepubliceerd hebben wat v1.3.1 

Ook zijn er 2 beta-versies van v2.0.0 opgenomen in de releases, maar de definitieve v2.0.0 versie is nog niet gepubliceerd.

Is dit een antwoord op jouw vraag ? Ik kan niet zo goed inschatten of hiermee de belemmering die je noemt is opgelost.

**Comment by sergei-maertens** [comment]
Dank, dat zou voldoende moeten zijn!

Ik denk dat we destijds inderdaad naar de master/main branch moesten verwijzen bij gebrek aan tags.
