### ISSUE TITLE
Als afnemer wil ik identificaties van partners/ouders/kinderen in de 'juiste' volgorde bij een ingeschrevene hebben

### ISSUE THREAD

**Issue by Robkromwijk** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#645]
De _links bij een ingeschreven naar partners/ouders/kinderen bevatten identificaties naar de endpoints "ingeschrevenpersonen/{burgerservicenummer}/partners/{id}"
"ingeschrevenpersonen/{burgerservicenummer}/ouders/{id}"
"ingeschrevenpersonen/{burgerservicenummer}/kinderen/{id}"

"partners": [
   {
      "href": "{url}/ingeschrevenpersonen/230193730/partners/1"
      },
     {
       "href": "{url}/ingeschrevenpersonen/230193730/partners/2"
     }
  ]

Ik heb gezocht naar specificaties, die de volgordelijkheid van de identificaties bepalen. Welke partner/ouder/kind krijgt id=1, welke id=2 etc.
Is dit gespecificeerd en zo ja, waar kan ik deze specificaties vinden?
Of is het id betekenisloos en is elke volgorde goed?

**Comment by fsamwel** [comment]
dit is niet gespecificeerd. In de implementatie die nu gemaakt is wordt meestal id=1, id=2, enz. gebruikt, maar volgens specificaties kan de id van alles zijn (gedefinieerd als string). Het nummer en de volgorde waarin de partners zijn opgenomen hebben geen functionele betekenis.

**Comment by Robkromwijk** [comment]
Commentaar voldoende om endpoints voor partners/ouders/kinderen te realiseren
