### ISSUE TITLE
Features die ook in common staan verwijderen.

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#652]
Verander dan ook de betreffende verwijzing in de OAS3. Check ook of er verwijzingen in de BAG of BRK naar deze features staan.

**Comment by JohanBoer** [comment]
Expand.feature verwijderd, fields.feature verwijderd, foutafhandeling.feature verwijderd, wildcard.feature verwijderd.
OAS3 aangepast met verwijzingen (alleen voor wildcard.feature waren er verwijzingen aanwezig).

In BAG en BRK zijn er geen verwijzingen naar de wildcard.feature. Voor expand en fields wordt in de BAG en de BRK al naar de common verwezen. Er staan geen verwijzingen naar foutafhandeling.feature in de yaml's.

**Comment by fsamwel** [comment]
> Er staan geen verwijzingen naar foutafhandeling.feature in de yaml's

Dat is denk ik terecht. De foutafhandeling feature richt zich op de provider

**Comment by JohanBoer** [comment]
> Dat is denk ik terecht. De foutafhandeling feature richt zich op de provider

Klopt, mee eens. Was bedoeld als een constatering van een feit.
