### ISSUE TITLE
Linter geeft warning op ontbreken van een - tag

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#653]
We hebben besloten op bij de BRP "actueel" bevragingen de tags weg te laten omdat dit niets toevoegen (Alle endpoints gaan over actuele bevragingen van ingeschreven personen).

Nu geeft de Lint-validatie een warning op het ontbreken van de tags. In OAS3 zijn tags optioneel. 

Mijns inziens moet deze check uit de Lint-validatie verwijderd worden.  

@fsamwel & @MelvLee : Zijn jullie het daar mee eens ?

**Comment by fsamwel** [comment]
Dit is denk ik geen check die wij hebben toegevoegd, zit er standaard al in. @MelvLee kan je die ook uitzetten?

Het feit dat de validatie standaard een warning geeft, kan wel een indicatie zijn dat het in de community belangrijk gevonden wordt, ergens voor. @MelvLee heb jij een idee waarvoor dit belangrijk kan zijn? Code generatie? Of andere tools?

**Comment by MelvLee** [comment]
De checks kunnen worden uitgezet. Op dit moment zijn twee checks uitgezet omdat die een error geven.

Wat ik tot nu toe heb kunnen vinden is dat tags wordt gebruikt om paths te groeperen. Wat code genereren betreft, NSwagStudio gebruikt hem om class namen uit de tags te genereren, maar dan moet het expliciet worden aangegeven

**Comment by melsk-r** [comment]
Let even op! in #650 komt Frank terug op het besluit om tags te verwijderen. Als je ze niet plaatst wordt in Swagger automatisch 'default' geplaatst wat er niet zo mooi uitziet. 
Ik weet alleen niet of dat ook zou betekenen dat de checks hier weer aangezet moeten worden.

**Comment by fsamwel** [comment]
> Ik weet alleen niet of dat ook zou betekenen dat de checks hier weer aangezet moeten worden.

Ik denk dat ze weer aangezet kunnen worden.
