### ISSUE TITLE
NaamOpenbareRuimte vervalt door hergebruik BAG-adres

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#659]
In het BAG-adres komt geen naamOpenbareRuimte voor. Dat is in het BAG-adres "straat". Als we dit doorvoeren dan moet ook de parameter verblijfplaats__naamOpenbareRuimte vervangen worden door verblijfplaats__straat. 

@fsamwel @MelvLee @CathyDingemanse @melsk-r : Hoe gaan we her mee om ?
Nog een breaking change voor consumers in ontwikkeling.

**Comment by MelvLee** [comment]
Je kan straat als parameter toevoegen en naamOpenbareRuimte laten staan, maar markeren als deprecated. Dan kan het in een toekomstige versie worden verwijderd

**Comment by melsk-r** [comment]
Is het wijzigen van de content van 'Verblijfplaats' op zich niet ook al een breaking change?
Zo ja, waarom accepteren we die wel en accepteren we deze niet?

**Comment by JohanBoer** [comment]
Zie ook 

Voegen we die ook toe? Daar hebben we geen feature voor. Nice to have, die we altijd nog kunnen toevoegen op een later moment.

Originally posted by @fsamwel in #650 (comment)

**Comment by JohanBoer** [comment]
Er komt een feature om de vulling te beschrijven.

**Comment by fsamwel** [comment]
> Er komt een feature om de vulling te beschrijven.

bedoel je deze? #649

**Comment by fsamwel** [comment]
@JohanBoer waarom heb je dit issue op mijn naam gezet? Wil je dat ik de specificaties aanpas op de query parameter verblijfplaats__naamOpenbareRuimte?

**Comment by JohanBoer** [comment]
> @JohanBoer waarom heb je dit issue op mijn naam gezet? Wil je dat ik de specificaties aanpas op de query parameter verblijfplaats__naamOpenbareRuimte?

Nee hoor, dit ging om die feature die je met #649 hebt aangemaakt.
