### ISSUE TITLE
Vraag: Klopt het dat gemeente_deel (08.10.20) nergens gebruikt wordt?

### ISSUE THREAD

**Issue by pimotte** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#660]
Puur ter controle, ik kan me goed voorstellen dat het inderdaad niet gevraagd wordt in een proces.

**Comment by fsamwel** [comment]
klopt, deze wordt nergens gebruikt

**Comment by pimotte** [comment]
Dank!
