### ISSUE TITLE
Als medewerker Belastingzaken wil weten of ouders, kinderen en partners nog leven

### ISSUE THREAD

**Issue by Robkromwijk** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#666]
...zodat ik de hoogte van toeslagen en heffingen kan bepalen.

Toevoegen van indicatieoverleden en overlijden aan ouders/kinderen/partners

Voor het bepalen van de hoogte van toeslagen en heffingen is het van belang om te weten of ouders/kinderen/partners nog leven.

In de definitie van ouders en kinderen staat "Wanneer een ouder of kind is overleden geldt deze nog steeds als actueel. Een overleden ouder of kind (met indicatie onjuist leeg) wordt dus opgenomen in het antwoord."
https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/master/features/partners_ouders_kinderen.feature#L19

Echter, indicatieoverleden en overlijden is niet opgenomen bij partners/ouders/kinderen
https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/master/specificatie/openapi.yaml#L763
https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/master/specificatie/openapi.yaml#L807
https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/master/specificatie/openapi.yaml#L849

Dit is wel een gewenste functionaliteit.

**Comment by fsamwel** [comment]
Dit heeft te maken met verantwoording van het raadplegen van persoonsgegevens.

In de subresource kinderen en ouders zitten alleen gegevens die eigenlijk bij de persoon horen. Dus de relatie van de persoon naar de ouders en kinderen. Dan krijg je alleen identificerende gegevens van die gerelateerde persoon.

Andere niet-identificerende gegevens van de ouder of het kind kan je opvragen door specifiek de gegevens van die ouder of kind op te vragen m.b.v. het burgerservicenummer in de ouders of kinderen subresource. Dat wordt vervolgens geregistreerd als het opvragen van gegevens van die persoon (die ouder of dat kind).
