### ISSUE TITLE
Descriptions v1.0.0.

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#667]
- [x] /ingeschrevenpersonen (met beschrijving: "vindt personen")

- [x] Wordt:
Zoek personen met één van de onderstaande verplichte combinaties van parameters en vul ze evt. aan met parameters uit de andere combinaties. Default krijg je personen terug die nog in leven zijn, tenzij je de inclusiefoverledenpersonen=true opgeeft. 
Gebruik de fields parameter als je alleen specifieke velden in het antwoord wil zien, zie functionele specificaties fields-parameter. Gebruik de expand parameter als je het antwoord wil uitbreiden met (delen van) de gerelateerde resources kinderen, ouders of  partners, zie functionele specificaties expand-parameter.

- [x] 1. Persoon
- geboorte__datum
- naam__geslachtsnaam (minimaal 2 karakters, wildcard toegestaan )

- [x] 2. Persoon
- verblijfplaats__gemeenteVanInschrijving
- naam__geslachtsnaam (minimaal 2 karakters, wildcard toegestaan )

- [x] 3. Persoon
- burgerservicenummer

- [x] 4. Postcode
- verblijfplaats__postcode
- verblijfplaats__huisnummer

- [x] 5. Straat
- verblijfplaats__straat (minimaal 2 karakters, wildcard toegestaan )
- verblijfplaats__gemeenteVanInschrijving
- verblijfplaats__huisnummer

- [x] 6. Adres
verblijfplaats__nummeraanduidingIdentificatie

**Comment by CathyDingemanse** [comment]
/ingeschrevenpersonen {burgerservicenummer} (met beschrijving: "levert een persoon")

wordt: 
Raadpleeg een (overleden) persoon. Gebruik de fields parameter als je alleen specifieke velden in het antwoord wil zien, zie functionele specificaties fields-parameter. Gebruik de expand parameter als je het antwoord wil uitbreiden met (delen van) de gerelateerde resources kinderen, ouders of partners, zie functionele specificaties expand-parameter.

**Comment by CathyDingemanse** [comment]
Bevragingen ingeschreven personen
 1.0.0 
OAS3
https://raw.githubusercontent.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/develop/specificatie/openapi.yaml
Wordt:
API voor het zoeken en raadplegen van actuele ingeschreven personen uit de BRP (inclusief RNI), hun kinderen, partners en ouders. Bij een beëindigd partnerschap of huwelijk wordt de partner niet geretourneerd.

**Comment by CathyDingemanse** [comment]
/ingeschrevenpersonen/{burgerservicenummer}/kinderen/{id}
Raadpleeg de kinderen van een persoon.

**Comment by CathyDingemanse** [comment]
/ingeschrevenpersonen/{burgerservicenummer}/ouders/{id}
Raadpleeg een ouder van een persoon.

​/ingeschrevenpersonen​/{burgerservicenummer}​/ouders
Raadpleeg de ouders van een persoon

**Comment by CathyDingemanse** [comment]
/ingeschrevenpersonen/{burgerservicenummer}/partners/{id}
Raadpleeg de partner van een persoon.

​/ingeschrevenpersonen​/{burgerservicenummer}​/partners
Raadpleeg de actuele partners van een persoon. Partners uit beëindigde huwelijken of partnerschappen worden niet geretourneerd.

**Comment by CathyDingemanse** [comment]
Ingeschreven persoon
Description "Gegevens over de ingeschreven persoon." weghalen. Geen description dus

Datum eerste inschrijving:
Description weghalen. Geen description dus.

Datum onvolledig (common)
Biedt mogelijkheid om ook datums die voor een deel bekend zijn uit te wisselen. 
bij dag: is gevuld als de dag van de datum of de hele datum bekend is.
bij maand: is gevuld als de maand van de datum of de hele datum bekend is.
bij jaar: is gevuld als het jaar van de datum of de hele datum bekend is.
bij datum: Datum conform date definitie. Is gevuld als de volledige datum bekend is.

Geheimhouding persoonsgegevens:
Gegevens mogen niet worden verstrekt aan derden/ maatschappelijke instellingen.

Geslachtsaanduiding:
Geeft aan dat de persoon een man of vrouw is, of dat het geslacht (nog) onbekend is.

Leeftijd:
Leeftijd in jaren op het moment van bevragen.

Kiesrecht:
Description weghalen, geen description.

europeesKiesrecht
Geeft aan of persoon een oproep moet ontvangen voor verkiezingen voor het Europees parlement.

uitgeslotenVanKiesrecht
description weghalen, Geen description

datumUitsluitingEuropeesKiesrecht: 
De datum waarop uitsluiting voor deelname aan verkiezingen voor het Europees parlement niet meer van toepassing is, als er sprake is van uitsluiting voor bepaalde tijd.

datumUitsluitingKiesrecht: 
De datum waarop uitsluiting voor deelname aan verkiezingen niet meer van toepassing is, als er sprake is van uitsluiting voor bepaalde tijd.

NaamPersoon
description weghalen, Geen description

Geslachtsnaam
De achternaam van een persoon, zonder voorvoegsels, adellijke titels of predikaat

Voorletters:
De voorletters van de persoon, afgeleid van de voornamen.

Voornamen:
De verzameling namen voor de geslachtsnaam, gescheiden door spaties.

Voorvoegsel
geen description

NaamInOnderzoek:
Geeft aan of gegevens over de naam in onderzoek zijn. Zie de functionele specificaties

Aanhef
Kun je gebruiken als aanhef in een brief gericht aan persoon.

Aanschrijfwijze
Samengestelde naam die je kunt gebruiken in de communicatie met de persoon.

gebruikInLopendeTekst
Naam van persoon die je kunt gebruiken als je in lopende tekst (bijvoorbeeld in een brief) aan persoon refereert.

Aanduidingnaamgebruik:
De manier waarop de geslachtsnaam van persoon en partner van persoon moet worden verwerkt in de manier waarop persoon wil worden aangesproken: 
gebruik alleen de eigen naam - E
gebruik de eigen naam voor de partnernaam  - N
gebruik alleen de partnernaam - P
gebruik de partnernaam voor de eigen naam - V
De aanduiding naamgebruik is verwerkt in Aanhef, Aanschrijfwijze en gebruikInLopendeTekst.

inOnderzoek, PersoonInonderzoek
Geeft aan welke gegevens van de persoon in onderzoek zijn. 
         Description bij de boolean burgerservicenummer en geslachtsaanduiding weghalen.

**Comment by JohanBoer** [comment]
> Aanduidingnaamgebruik:
> De manier waarop de geslachtsnaam van persoon en partner van persoon moet worden verwerkt in de manier waarop persoon wil worden aangesproken:
> gebruik alleen de eigen naam - E
> gebruik de eigen naam voor de partnernaam - N
> gebruik alleen de partnernaam - P
> gebruik de partnernaam voor de eigen naam - V
> De aanduiding naamgebruik is verwerkt in Aanhef, Aanschrijfwijze en gebruikInLopendeTekst.

Bedoel je hier 
'eigen' - E - gebruik alleen de eigen naam

De enumeratiewaarde is in dit geval 'eigen' lijkt me goed om die ook terug te laten komen in de description.

**Comment by CathyDingemanse** [comment]
> 
> Bedoel je hier
> 'eigen' - E - gebruik alleen de eigen naam
> 
> De enumeratiewaarde is in dit geval 'eigen' lijkt me goed om die ook terug te laten komen in de description.

Ja, sorry, was lekker aan het wijzigen, even vergeten dat het een enumeratiewaarde was :-).

**Comment by CathyDingemanse** [comment]
Nationaliteit
Geen description
datumIngangGeldigheid en nationaliteit: beiden geen description
redenOpname : de reden op grond waarvan persoon de nationaliteit gekregen heeft

waardetabel: geen description


NationaliteitInOnderzoek
Geeft aan welke gegevens over de nationaliteit in onderzoek zijn. Zie de functionele specificaties
descriptions bij aanduidingBijzonderNederlanderschap, nationaliteit, redenOpname weghalen

**Comment by CathyDingemanse** [comment]
geboorte

Gegevens over de geboorte van de persoon, de ouder, de echtgenoot/geregistreerd partner, de eerdere echtgenoot/geregistreerd partner of het kind.
- datum : datum waarop de persoon is geboren.
- land : land waar de persoon is geboren
- plaats : plaats waar een persoon is geboren. Voor een plaats buiten Nederland is gemeentecode=1999 (RNI). De gemeentenaam is de buitenlandse plaatsnaam of aanduiding.


Bij land en plaats: descriptions bij waardetabel en description bij omschrijving weghalen.

GeboorteInOnderzoek:
Geeft aan welke gegevens over de geboorte van de persoon in onderzoek zijn. Zie de functionele specificaties. 

Descriptions bij de booleans weghalen.

**Comment by CathyDingemanse** [comment]
Opschorting bijhouding:

reden: de reden waarom de bijhouding van de PL is opgeschort.
datum: de datum waarop de bijhouding van de persoonslijst is gestaakt.

Bij de enumeratiewaarde R: 
pl_aangelegd_in_de_rni - R: opgeschort omdat persoon is ingeschreven in het Register Niet Ingezeten (RNI).

**Comment by CathyDingemanse** [comment]
overlijden:
Gegevens over het overlijden van de persoon.
datum : datum waarop de persoon is overleden.
land : land waar de persoon is overleden
plaats : de plaats waar de persoon is overleden. Voor een plaats buiten Nederland is gemeentecode=1999 (RNI). De gemeentenaam de buitenlandse plaatsnaam of aanduiding.

indicatie overleden:
Deze indicatie geeft aan dat iemand is overleden (waarde true), ongeacht of de overlijdensdatum bekend is.

**Comment by CathyDingemanse** [comment]
verblijfplaats

Gegevens over het verblijf of de woonlocatie van een persoon.

datumAanvangAdreshuishouding : de datum van aangifte of ambtshalve melding van verblijf en adres.
datumIngangGeldigheid : datum waarop de gegevens over de verblijfplaats geldig zijn geworden.
datumInschrijvingInGemeente: bij inschrijving op grond van een verhuisaangifte door de burger is dit de aangiftedatum. Bij inschrijving op grond van een geboorteakte is dit de geboortedatum. Bij ambtshalve inschrijving is dit de datum waarop de betrokkene schriftelijk van het voornemen van ambtshalve opneming mededeling is gedaan.
datumVestigingInNederland : datum van inschrijving in Nederland
landVanWaarIngeschreven : het land waar de persoon verbleef voor (her)vestiging in Nederland.
gemeenteVanInschrijving : de gemeente waar de persoon verblijft en is ingeschreven. De code kan voorloopnullen bevatten.



descriptions van huisnummer, huisletter, huisnummertoevoeging, postcode woonplaats weglaten.

Adresseerbaar object identificatie 
de verblijfplaats van de persoon een kan een ligplaats, een standplaats of een verblijfsobject zijn. 

AanduidingBijHuisnummer:
De aanduiding die wordt gebruikt voor adressen die geen straatnaam en huisnummeraanduidingen hebben

nummeraanduidingIdentificatie
Unieke identificatie van een nummeraanduiding (en het bijbehorende adres) in de BAG.

Woonadres:
het adres waar de persoon woont. 
Briefadres:
het adres van een andere persoon of van een instelling (de zogenoemde briefadresgever). Met dit adres van de briefadresgever is de persoon zonder woonadres toch bereikbaar voor de overheid. 

indicatieVestigingVanuitBuitenland 
Geeft aan dat de ingeschreven persoon zich vanuit het buitenland heeft ingeschreven. 


locatiebeschrijving 
Een omschrijving van de ligging van een object.


korteNaam 
de officiële openbareruimtenaam uit de Basisregistratie Gebouwen en Adressen (BAG) of een verkorte versie. 


vanuitVertrokkenOnbekendWaarheen 
Geeft aan dat de persoon is teruggekeerd uit een situatie van "vertrokken onbekend waarheen"

**Comment by JohanBoer** [comment]
> * [x]  /ingeschrevenpersonen/{burgerservicenummer}/kinderen/{id}
>   Raadpleeg een kind van een persoon.
> * [x]  ​/ingeschrevenpersonen​/{burgerservicenummer}​/kinderen
>   Raadpleeg de kinderen van een persoon

Bij  _/ingeschrevenpersonen {burgerservicenummer} (met beschrijving: "levert een persoon")_  kies je voor levert en hier voor Raadpleeg. Is dat bewust ? Ik zou verwachten dat je in beide situaties hetzelfde werkwoord gebruikt.

**Comment by JohanBoer** [comment]
> * Datum onvolledig (common)
>   Biedt mogelijkheid om ook datums die voor een deel bekend zijn uit te wisselen.
>   bij dag: is gevuld als de dag van de datum of de hele datum bekend is.
>   bij maand: is gevuld als de maand van de datum of de hele datum bekend is.
>   bij jaar: is gevuld als het jaar van de datum of de hele datum bekend is.
>   bij datum: Datum conform date definitie. Is gevuld als de volledige datum bekend is

Deze zit in Common.yaml. De huidige beschrijvingen hebben we tijdens het BRK-traject opgenomen. 
Wil je deze weer aanpassen ? Lijkt mij dat we dit niet bij iedere API opnieuw gaan doen... Maar als je het graag wil kan het natuurlijk wel.

**Comment by CathyDingemanse** [comment]
> Bij _/ingeschrevenpersonen {burgerservicenummer} (met beschrijving: "levert een persoon")_ kies je voor levert en hier voor Raadpleeg. Is dat bewust ? Ik zou verwachten dat je in beide situaties hetzelfde werkwoord gebruikt.
> En zullen we ze allemaal met kleine letters of allemaal met hoofdletters starten ?

eens. Zullen we het zo doen: 
- als het gaat om een collectie: levert
- als het gaat om een unieke resource met padparameter: raadpleeg
- start overal met een hoofdletter

**Comment by JohanBoer** [comment]
> * [ ]  waardetabellen reden opname en nationaliteit: geen 

Hiervoor geldt hetzelfde als voor de datumOnvolledig. Dat wordt dan ook een aanpassing in common.yaml.

**Comment by JohanBoer** [comment]
> * descriptions van huisnummer, huisletter, huisnummertoevoeging, postcode woonplaats weglaten.

Deze worden hergebruikt (middels een $ref verwijzing) vanuit de BAG. Ik veronderstel dat je niet de BAG wilt aanpassen ?

**Comment by CathyDingemanse** [comment]
> > * descriptions van huisnummer, huisletter, huisnummertoevoeging, postcode woonplaats weglaten.
> 
> Deze worden hergebruikt (middels een $ref verwijzing) vanuit de BAG. Ik veronderstel dat je niet de BAG wilt aanpassen ?

nee idd niet!

**Comment by CathyDingemanse** [comment]
gezagsverhouding:
Gegevens over het gezag over de persoon.


indicatieCurateleRegister
Geeft aan dat de ingeschrevene onder curatele is gesteld.

IndicatieGezagMinderjarige_enumstring
geeft aan wie het gezag heeft over de minderjarige persoon.
ouder1 - 1
ouder2 - 2
derden - D
ouder1_en_derde - 1D
ouder2_en_derde - 2D
ouder1_en_ouder2 - 12

inOnderzoek | GezagsverhoudingInOnderzoek
Geeft aan welke gegevens van de gezagsverhouding in onderzoek zijn. Zie de functionele specificaties.

descriptions bij booleans indicatieCurateleRegister indicatieGezagMinderjarige weglaten.

**Comment by CathyDingemanse** [comment]
Verblijfstitel
Gegevens over de verblijfsrechtelijke status van de persoon.

datumEinde: Datum waarop de geldigheid van de gegevens over de verblijfstitel is beëindigd.
datumIngang: Datum waarop de gegevens over de verblijfstitel geldig zijn geworden.
aanduiding : Verblijfstiteltabel die aangeeft wat de verblijfsrechtelijke status van de persoon is. 

descriptions bij waardetabel aanduiding weghalen

VerblijfstitelInOnderzoek
Geeft aan welke gegevens over de verblijfstitel in onderzoek zijn.

**Comment by CathyDingemanse** [comment]
Partner:
Gegevens over een gesloten huwelijk/geregistreerd partnerschap van de persoon.

SoortVerbintenis:
Soort verbintenis die bij de burgerlijke stand is ingeschreven:
- huwelijk - H
- geregistreerd_partnerschap - P

Naam en geboorte: zie ingeschreven persoon.

PartnerInOnderzoek:
Geeft aan welke gegevens over het huwelijk of het partnerschap in onderzoek zijn. Zie de functionele specificaties

AangaanPartnerschap:
Gegevens over de voltrekking van het huwelijk of het aangaan van het geregistreerd partnerschap.

datum : De datum waarop het huwelijk is voltrokken of het partnerschap is aangegaan.
land : Het land waar het huwelijk is voltrokken of het partnerschap is aangegaan.
plaats : Als de plaats een gemeente in Nederland is dan gewoon de gemeentecode + gemeentenaam . Voor een plaats buiten Nederland is de gemeentecode leeg en wordt de gemeentenaam de buitenlandse plaatsnaam of aanduiding.


AangaanHuwelijkInonderzoek: MOET DIT NIET ZIJN AANGAANHUWELIJKPARTNERSCHAPINONDERZOEK?
Geeft aan welke gegevens over het voltrekken van het huwelijk of aangaan van het partnerschap in onderzoek zijn. Zie de functionele specificaties

Geheimhouding persoonsgegevens:
Geeft aan dat de persoonsgegevens op verzoek van de persoon niet aan bepaalde derden worden verstrekt.

**Comment by CathyDingemanse** [comment]
Kind
Gegevens over een kind van de persoon.

KindInOnderzoek
Geeft aan of de gegevens over het kind van de persoon in onderzoek zijn. Zie de functionele specificaties

**Comment by CathyDingemanse** [comment]
Ouder
Gegevens over een ouder van de persoon.

datumIngangFamilierechtelijkeBetrekking : 
De datum waarop de familierechtelijke betrekking is ontstaan. Het gaat om een familieverhouding die door het familierecht wordt erkend, bijvoorbeeld uit geboorte, tijdens of binnen 306 dagen na ontbinding van het huwelijk, erkenning, adoptie en gerechtelijke vaststelling van het vaderschap.

Ouderaanduiding:
OuderAanduiding_enumstringAanduiding 
geeft aan om welke ouder het gaat volgens de BRP:
ouder1 - 1
ouder2 - 2

Naam
Gegevens over de naam van de ouder
description AdellijkeTitelPredikaat: zie kind.

**Comment by CathyDingemanse** [comment]
descriptions gelden ook ook halcollectie en halcollectie embedded etc.

**Comment by CathyDingemanse** [comment]
Naam wijzigen: 
Bevragingen Ingeschrevn Personen wordt:
Bevragen Ingeschreven Personen

Description:
API voor het bevragen van ingeschreven personen uit de basisregistratie personen (BRP), inclusief de registratie niet-ingezeten (RNI). Met deze API kun je personen zoeken en actuele gegevens over personen, kinderen, partners en ouders raadplegen.
Gegevens die er niet zijn of niet actueel zijn krijg je niet terug. Heeft een persoon bijvoorbeeld geen geldige nationaliteit, en alleen een beëindigd partnerschap, dan krijg je geen gegevens over nationaliteit en partner.

**Comment by melsk-r** [comment]
>     * [x]  ​/ingeschrevenpersonen​/{burgerservicenummer}​/partners
>       Raadpleeg de actuele partners van een persoon. Partners uit beëindigde huwelijken of partnerschappen worden niet geretourneerd.

Als je de partners uit beëindigde huwelijken of partnerschappen niet retourneert is er dan wel sprake van het 'raadplegen van de actuele **partners**'? 

Kan je meerdere actuele partners hebben? Of moet de tekst 

> 'Raadpleeg de actuele partner van een persoon. Partners uit beëindigde huwelijken of partnerschappen worden niet geretourneerd.'

zijn?

**Comment by JohanBoer** [comment]
> * description adellijketitel/perdikaat weghalen! Zit niet in subresource!

Deze opmerking bij Partner kan ik niet plaatsen.

**Comment by CathyDingemanse** [comment]
> > ```
> > * [x]  ​/ingeschrevenpersonen​/{burgerservicenummer}​/partners
> >   Raadpleeg de actuele partners van een persoon. Partners uit beëindigde huwelijken of partnerschappen worden niet geretourneerd.
> > ```
> 
> Als je de partners uit beëindigde huwelijken of partnerschappen niet retourneert is er dan wel sprake van het 'raadplegen van de actuele **partners**'?
> 
> Kan je meerdere actuele partners hebben? Of moet de tekst
> 
> > 'Raadpleeg de actuele partner van een persoon. Partners uit beëindigde huwelijken of partnerschappen worden niet geretourneerd.'
> 
> zijn?

Ja er kunnen meer actuele partners zijn :-).

**Comment by CathyDingemanse** [comment]
> > * description adellijketitel/perdikaat weghalen! Zit niet in subresource!
> 
> Deze opmerking bij Partner kan ik niet plaatsen.
> 
> Na wat verder lezen wel. De groep Naam wordt hergebruikt dus ook de beschrijving bij geslachtsnaam. Als ik de zin over de adelijke titels weghaal dan staat deze ook niet bij de ingeschrevenpersoon er bij zoals in jouw 7e commentaarblok bij naampersoon is aangegeven.

lekker weghalen, adellijke titel en predicaat zit ook niet in persoon.
