### ISSUE TITLE
adellijketitelPredikaat vind ik terug bij kind, maar niet bij persoon

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#672]
bug?

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by fsamwel** [comment]
dit gaat over de description, want in de resource (in schemacomponent Naam) zit geen veld adellijketitelPredikaat. 

Moet dus denk ik alleen in de description worden opgelost

**Comment by CathyDingemanse** [comment]
Is geen bug. Ik sluit m.
