### ISSUE TITLE
review descriptions 1.0.0

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#677]
Typo's:

- [x] geheimhoudingPersoonsgegevens 
Indicatie geheimGegevens mogen niet worden verstrekt aan derden / **maatschappelijke** instellingen.

- [x] geslacht
Geeft aan dat de persoon een man of vrouw is, of dat het geslacht (nog) onbekend is**.:**

- [x] Datum onvolledig:
Gegevens over **de** datums die mogelijk niet volledig zijn (de weghalen)

- [x] Excuses voor de volgende, ik heb het niet consistent gespecificeerd.... Sorry! Alleen deze zinnen als description opnemen (de rest weghalen):
Als de dag van de datum bekend is wordt dit element gevuld, ook als de volledige datum bekend is.
Als het jaar van de datum bekend is wordt dit element gevuld, ook als de volledige datum bekend is.
Als de maand van een datum bekend is wordt dit element gevuld, ook als de volledige datum bekend is
Als de volledige datum bekend is wordt de datum gevuld die in de date definitie past. 

- [x] De descriptions bij de booleans in NaamInOnderzoek staan er nog. Volgens mij kun je die weghalen omdat de description bij huppeldepupInOnderzoek aangeeft _welke_ gegevens in onderzoek zijn.

- [ ] de description van waardetabel staat er nog bij reden nationaliteit en redenopname, geboorteland en geboorteplaats, land overlijden, plaats overlijden, lgemeenteVanInschrijving en LandWaarvanIngeschreven, land, verblijfstiteltabel, 
evenals die bij de bijbehorende omschrijving. Voegt mijns inziens weinig toe....

- [x] geboorte: plaats
plaats : plaats waar een persoon is geboren, graag van maken: 
plaats : plaats waar de persoon is geboren

- [x] Opschorting bijhouding: wordt:
reden: de reden waarom de bijhouding van persoonsgegevens is gestaakt.
datum: de datum waarom de bijhouding van persoonsgegevens is gestaakt.

- [x] overlijden:
plaats : plaats waar de persoon is overleden.

- [x] Indicatie overleden
Geeft aan dat iemand is overleden (waarde true), ongeacht of de overlijdensdatum bekend is.

Verblijfplaats:
- [x] landVanWaarIngeschreven : het land waar de persoon woonde voor (her)vestiging in Nederland.
- [x] datumInschrijvingInGemeente: bij inschrijving op grond van een verhuisaangifte door de burger is dit de aangiftedatum. Bij inschrijving op grond van een geboorteakte is dit de geboortedatum. Bij ambtshalve inschrijving is dit de datum waarop het voornemen van ambtshalve opneming schriftelijk aan de persoon is medegedeeld.

- [x] Typo punt en dubbele punt bij aanduidingBijHuisnummer:
De aanduiding die wordt gebruikt voor adressen die geen straatnaam en huisnummeraanduidingen hebben**. :**

- [x] IndicatieCurateleRegister: Geeft aan dat de persoon onder curatele is gesteld.

- [x] Verblijfstitel:
aanduiding : Verblijfstiteltabel die aangeeft over welke verblijfsrechtelijke status de persoon beschikt.

- [x] OuderInOnderzoek:
staat nu: Indicators over het in onderzoek zijn van gegevens over de aangaan van het huwelijk van de INGESCHREVEN PERSOON. Zie de functionele specificaties
Moet zijn: Geeft aan welke gegevens van de de ouder in onderzoek zijn. 
Ook beschrijving van booleans moeten weg.

- [x] Bij Kind
geheimhouding persoonsgegevens:
is nog steeds: 
Een aanduiding die aangeeft dat gegevens wel of niet verstrekt mogen worden. 
Indien true: op verzoek van deze persoon is het verstrekken van gegevens over deze persoon aan bepaalde derden niet toegestaan.
Moet worden:
Gegevens mogen niet worden verstrekt aan derden/ maatschappelijke instellingen.

- [x] Partner:
 - bij geboorte land en plaats en aangaanhuwelijk plaats en land nog beschrijving bij de waardetabellen en booleans
- er staan nog descriptions bij de booleans bij partnerInOnderzoek
- bij geheimhoudingpersoonsgegevens staat nog de oude description. Moet worden: Gegevens mogen niet worden verstrekt aan derden/ maatschappelijke instellingen.

**Comment by JohanBoer** [comment]
@CathyDingemanse 

> * de description van waardetabel staat er nog bij reden nationaliteit en redenopname, geboorteland en geboorteplaats, land overlijden, plaats overlijden, lgemeenteVanInschrijving en LandWaarvanIngeschreven, land, verblijfstiteltabel,
>   evenals die bij de bijbehorende omschrijving. Voegt mijns inziens weinig toe....

De bovenstaande opmerkingen spreekt de volgende tegen : 

> * [ ]  geboorte: plaats
>   plaats : plaats waar een persoon is geboren, graag van maken:
>   plaats : plaats waar de persoon is geboren

> * overlijden:
>   plaats : plaats waar de persoon is overleden.

> * [ ]  landVanWaarIngeschreven : het land waar de persoon woonde voor (her)vestiging in Nederland.

> * [ ]  Verblijfstitel:
>   aanduiding : Verblijfstiteltabel die aangeeft over welke verblijfsrechtelijke status de persoon beschikt.

Dit zijn allemaal verwijzingen ($ref) naar een waardetabel. Bij de properties zelf kan ik dan geen specifieke description opnemen. 
Daar geeft de linter-validatie een fout op en al zou hij dat nbiet doen, dan worden deze descriptions niet getoond in de SwaggerUI. 

Dus de keuze is of opnemen in de description van het betreffende component of niet opnemen.

**Comment by JohanBoer** [comment]
> * Datum onvolledig:
>   Gegevens over **de** datums die mogelijk niet volledig zijn (de weghalen)
> * [x]  Excuses voor de volgende, ik heb het niet consistent gespecificeerd.... Sorry! Alleen deze zinnen als description opnemen (de rest weghalen):
>   Als de dag van de datum bekend is wordt dit element gevuld, ook als de volledige datum bekend is.
>   Als het jaar van de datum bekend is wordt dit element gevuld, ook als de volledige datum bekend is.
>   Als de maand van een datum bekend is wordt dit element gevuld, ook als de volledige datum bekend is
>   Als de volledige datum bekend is wordt de datum gevuld die in de date definitie past.

Voor deze herstel actie heb ik een release van de common verwijderd, deze wijzigingen doorgevoerd en de release opnieuw aangemaakt.
