### ISSUE TITLE
Genderneutrale aanschrijving wanneer geslachtsaanduiding onbekend

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#683]
In de features aanhef en gebruik_in_lopende_tekst is nu geen afhandeling beschreven voor de situatie dat geslachtsaanduiding is onbekend (in huidige Lo-GBA heeft dan 04.10 waarde "O"). Dit moet worden ingevuld.

Ook is de situatie mogelijk dat een persoon een geslachtsverandering heeft ondergaan, maar de adellijke titel of het predicaat niet is (mee)gewijzigd.
Dan kan iemand met (aangepast) geslacht man worden aangeschreven met "jonkvrouw" en "Hoogwelgeboren vrouwe".

Zie ook https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/issues/674#issuecomment-707757865:
> Wanneer een persoon van geslacht is gewijzigd: adellijke titel en predicaat omvormen op basis van geslachtsaanduiding

Wanneer een persoon een genderneutrale aanduiding heeft (geslacht onbekend),
dan geen adellijke titel of predicaat gebruiken.
en voor de aanhef dezelfde logica toepassen (uit de Amsterdam gids) als bij personen zonder adellijke titel: Hoogwelgeboren P. A. van Haringa toe Slooten.

**Comment by fsamwel** [comment]
@CathyDingemanse hoe bedoel je dit:

> en voor de aanhef dezelfde logica toepassen (uit de Amsterdam gids) als bij personen zonder adellijke titel: Hoogwelgeboren P. A. van Haringa toe Slooten.

Volgens mij wordt "Hoogwelgeboren" niet op deze manier gebruikt in combinatie met de naam.

De formele aanhef voor adellijke personen bestaat eigenlijk uit twee regels, waarvan wij nu de eerste regel leveren als aanhef, en de tweede regel is de aanschrijfwijze:

De hoogwelgeboren vrouwe
A.B.C. barones van Dedem

De aanhef in de resource bevat dus niet de naam, want die hoort op de tweede regel.
Wil je hiervan afwijken bij de genderneutrale variant? Dus dan wel de naam toevoegen? Waarom in dat geval niet de eerste regel toepassen (bij aanduiding onbekend geen adellijke titel gebruiken). Dus in je voorbeeld i.p.v."Hoogwelgeboren P. A. van Haringa toe Slooten" wordt dat "Geachte P. A. van Haringa toe Slooten".

**Comment by CathyDingemanse** [comment]
Ok, het wordt "Geachte P.A. van Haringa toe Slooten".
