### ISSUE TITLE
Moeten resources tegelijk opgenomen worden in _embedded en _links indien de resource in ?expand= opgenomen?

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#686]
In een scenario over `expand` wordt in de documentatie aangegeven dat als `?expand=partners` wordt meegegeven, partners worden opgenomen (als resource) in `_embedded`. Tot zo ver logisch, maar er staat tevens dat partners (als link) *ook nog* in `_links` wordt opgenomen.

Hoewel de [HAL specificatie](https://tools.ietf.org/html/draft-kelly-json-hal-08) dit niet uitsluit heb ik het eigenlijk nog nooit gezien. Meestal is het of `_embedded`, of `_links`, niet allebei tegelijk. Is dit een bewuste keuze?

Het betreft dit scenario: https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/master/features/expand.feature#L84

**Comment by fsamwel** [comment]
We hebben het nu zo gedefinieerd dat gebruik van expand geen invloed heeft op de inhoud van de resource, inclusief _links. Expand heeft alleen invloed op de inhoud van de gerelateerde subresources die in _embedded kunnen worden meegeleverd.

Dus wanneer je zonder gebruik van expand in de resource _links krijgt, krijg je dat met gebruik van expand ook.

In het scenario is geprobeerd dat duidelijk te maken (o.a.) in het voorbeeld (scenario), waar bij expand=partners,kinderen in _embedded alleen partners en kinderen zijn meegeleverd, maar in _links ook de link naar de ouders wordt geleverd.

**Comment by joeribekker** [comment]
Prima, ik wilde zeker weten dat dat de bedoeling was. Het scenario was verder duidelijk.
Moeten we onze JSON-HAL library even aanpassen :)

Bedankt!
