### ISSUE TITLE
Waarom in het Nederlands?

### ISSUE THREAD

**Issue by THETCR** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#694]
Uit absolute nieuwsgierigheid, waarom überhaupt code/bestandsnamen in het Nederlands schrijven?
Het eindresultaat is een mix van Engels en Nederlands. Ik begrijp deze keuze niet en ben nu wel nieuwsgierig naar de beweegredenen.

**Comment by fsamwel** [comment]
ik weet niet zeker of ik goed begrijp wat je bedoelt met "code/bestandsnamen", maar de taalkeuze in de API is zo dat voor begrippen uit het domein Nederlands wordt gebruikt. Dus alle BRP domeinbegrippen zijn dus in het Nederlands opgenomen. 

Vertalen van deze begrippen (properties en componenten in de specificaties) en de descriptions daarbij is denk ik risicovol (als Nederlanders de Nederlandse begrippen gaan vertalen naar het Engels en vervolgens andere Nederlanders dat gaan terugvertalen naar het Nederlands om het begrip te begrijpen).
Hoe vertaal je bijvoorbeeld nummeraanduidingIdentificatie? "numberDesignationIdentification"? en herkent iemand dan nog dat het om een BAG nummeraanduiding gaat?
De verschillende enumeraties zouden dan ook kunnen worden vertaald, maar waarden uit tabellen (zoals nationaliteit) kunnen we weer niet vertalen. En uiteraard omschrijvingen (zoals die vooral in de BAG en BRK API's zitten) zijn uiteraard ook niet vertaald. Dan krijg je de situatie dat in het antwoord een deel in het Engels is en een deel in het Nederlands.
Dus wat we ook kiezen, altijd is een deel Nederlands en een deel Engels. We kunnen niet 100% Nederlands, we kunnen alleen de grens bepalen van hoeveel Nederlands en hoeveel Engels.
Onze keuze was daarom de content, dus begrippen en inhoud in het Nederlands op te nemen, en bepaalde technische parameters (fields, expand en json HAL elementen) te gebruiken zoals die internationaal veel gebruikt worden.

We sluiten hiermee ook aan bij de NL API strategie API design rule [API-17](https://docs.geostandaarden.nl/api/API-Designrules/#api-17-publish-documentation-in-dutch-unless-there-is-existing-documentation-in-english-or-there-is-an-official-english-glossary-available).

**Comment by melsk-r** [comment]
In deze context is ook de API design rule [API-04](https://docs.geostandaarden.nl/api/API-Designrules/#api-04-define-interfaces-in-dutch-unless-there-is-an-official-english-glossary) van de NL API strategie van belang lijkt mij.
