### ISSUE TITLE
Als gemeente wil ik ingeschreven personen kunnen zoeken op geslachtsnaam

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#7]
...zodat de gegevens van een persoon kan vinden.

**Acceptatiecriteria**
- [x] Het is mogelijk te kiezen om ook of juist geen overleden personen terug te krijgen
- [x] Het is mogelijk te kiezen om ook of juist geen niet-ingezeten terug te krijgen
- [x] Het is mogelijk te zoeken (filteren) op de volgende eigenschappen van de persoon:
       * geslachtsnaam
       * geboortedatum
       * voornamen
       * voorvoegselGeslachtsnaam
       * geslachtsaanduiding
       * geboorteplaats
- [x] Bij het zoeken/filteren op geslachtsnaam mag een wildcard worden gebruikt  
- [x] Bij het zoeken/filteren op voornamen mag een wildcard worden gebruikt
- [x] Bij het zoeken/filteren op geboortedatum mag een onvolledige datum worden gebruikt

**Definition of done**
- [ ] functionele specificatie
- [x] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by fsamwel** [comment]
Dit wordt geïmplementeerd in een endpoint /ingeschrevennatuurlijkpersonengeslachtsnaam

**Comment by JohanBoer** [comment]
voortschrijdend inzicht heeft ons doen besluiten deze functionaliteit op de endpoint / ingeschrevenpersonen te ontsluiten.
