### ISSUE TITLE
Hoe zoeken op alleen ingezetenen?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#70]
Nu is parameter inclusiefnietingezetenen opgenomen bij het zoeken op naam. Default worden alleen ingezetenen gezocht.
Ook is parameter gemeenteVanInschrijving opgenomen. Hiermee kan alleen binnen de eigen gemeente worden gezocht.
Is dit de gewenste oplossing voor de functionele vraag? Is het dus nodig om te kunnen kiezen tussen:
1.  Zoeken van alleen ingezetenen van de eigen gemeente
2. Zoeken van ingezetenen in de eigen en andere gemeenten, maar geen niet-ingezetenen
3. Zoeken van alle ingeschreven personen incl. niet-ingezetenen

**Comment by fsamwel** [comment]
Is het  niet voldoende om te kunnen kiezen tussen:
1. Alleen ingezetenen van de eigen gemeente.
2. Alle ingeschreven personen.

In dat geval kan netjes RESTful worden gezocht met gemeenteVanInschrijving.

**Comment by CathyDingemanse** [comment]
Dat lijkt mij wel. Helemaal eens.

**Comment by fsamwel** [comment]
Beslissing (23 november): 
geen parameter inclusiefnietingezetenen, want gemeentevaninschrijving
