### ISSUE TITLE
Links naar Swagger en Redoc geven 404

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#709]
De links naar Swagger en Redoc in de Readme geven een 404 not found.
Het gaat bijvoorbeeld om de link https://vng-realisatie.github.io/Haal-Centraal-BRP-bevragen/swagger-ui/

**Comment by JohanBoer** [comment]
Inmiddels aangepast. Er zat een trailing  / in de URL. Nu weggehaald.

**Comment by melsk-r** [comment]
Wil je dfat ik hier nog iets mee doe? Volgens mij heb je het probleem zelf al opgelost. Review lijkt me niet nodig.
