### ISSUE TITLE
Als medewerker leerplicht wil ik van kinderen met verzuim weten wie de ouders zijn en waar zij wonen

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#720]
...zodat ik kan handhaven in het kader van de leerplichtwet

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by BramWithaar** [comment]
Op basis van GBA/BRP kun je bij mijn weten niet vaststellen of een ouder die in de BRP als ouder geregistreerd staat wel zeggenschap heeft over een kind. Dat wordt bijgehouden in het gezagsregister, door rechtbanken.
(hier zijn we tegenaan gelopen met de BRP verstrekkingen naar de IRMA app)

**Comment by CathyDingemanse** [comment]
Beste Bram, dank voor je opmerking, en je hebt gelijk. De BRP is hier idd niet de enige bron!

**Comment by BramWithaar** [comment]
om het fijn te houden: wij hebben geen via een API raadpleegbare bron gevonden voor dit soort gegevens (de rechtbanken faxen soms nog resultaten naar gemeenten). Als het hier wel lukt zou dat mooi zijn :-)

**Comment by CathyDingemanse** [comment]
Hahaa! Zou willen dat ik je kon helpen, maar we zijn op dit moment helaas gebonden aan de bron die we hebben (BRP). Ik maak een issue op de backlog!
