### ISSUE TITLE
Als API consumer wil ik graag een releasebeleid/afspraak waarin de API backwards compatible is bij major updates (breaking changes)

### ISSUE THREAD

**Issue by jacobversteeg** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#741]
zodat bij introductie van een nieuwe versie ook de voorgaande versie ondersteunt blijft (backwards compatible), waardoor ik als leverancier voldoende gelegenheid heb aanpassingen door te voeren aan de consumer kant.

**Comment by JohanBoer** [comment]
Wij doen er veel aan om breaking changes te voorkomen. In principe worden nieuwe releases waarin functionaliteit wordt toegevoegd, maar waarin geen breaking changes voorkomen uitgebracht als minor releases. 

Een breaking change leidt tot een major release.  Als de consumer het deel van de API gebruikt waar deze breaking change in voorkomt leidt dat helaas tot backward incompatibility. 

@jacobversteeg geeft dit meer duidelijkheid over ons releasebeleid ?
