### ISSUE TITLE
Privacy - BSN als path parameter of in de body(?)

### ISSUE THREAD

**Issue by tdonker** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#751]
Bij het raadplegen van een persoon kan het BSN nummer als path parameter worden meegegeven in de URL. Is dit vanuit privacy oogpunt verstandig? Immers, URL's kunnen worden opgeslagen in caches, logfiles en dat zou betekenen dat het BSN nummer op een plek komt waar het niet thuis hoort. Om dit te voorkomen zou het BSN nummer in de payload (body) van een POST operatie kunnen worden opgenomen i.p.v. als path parameter in de URL van de GET.

**Comment by fsamwel** [comment]
Zie #172.

Dit onderwerp is ook besproken in het kader van de landelijke API strategie. Zie https://github.com/Geonovum/KP-APIs/issues/219. Daar was de conclusie dat het risico dat je beschrijft afhangt van de context waarin de API wordt gebruikt. 

Deze Haal Centraal API's is niet ontworpen om bijvoorbeeld direct aan te roepen vanuit mobile devices of websites. Binnengemeentelijk of tussen bijvoorbeeld RvIG en een gemeente (of andere overheidsdienst) kan de infrastructuur wel zo worden ingericht dat opslaan in caches of logfiles niet gebeurt.
