### ISSUE TITLE
Update postman variables to correct format

### ISSUE THREAD

**Issue by shea-maykinmedia** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#763]
I hope it's okay to write this in English.

I saw that your postman collections here https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/tree/develop/test use `:variableName` as the syntax for variable names but postman expects the format to be `{{variableName}}`.  As far as I know postman doesn't support the `:variableName` syntax though please let me know if I am wrong.

With the proper variable name synax it makes it much easier to run the collection since one would only need to set up an environment and fill in the necessary variables to run the whole collection.

**Comment by MelvLee** [comment]
Hi @shea-maykinmedia, Postman uses :variablename as placeholder for path parameters. You can find more info about this in the [Postman documentation](https://learning.postman.com/docs/sending-requests/requests/#sending-parameters). It is possible to use a environment or global variable as input for a path parameter. See ![image](https://i0.wp.com/makeseleniumeasy.com/wp-content/uploads/2019/08/image-2.png?w=959)
