### ISSUE TITLE
Als PO wil ik een SDK kunnen leveren aan pilotgemeenten die deze afgeleide BRP gegevens client side afleidt

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#766]
...zodat hun afnemers gebruik kunnen maken van de gegevens Aanschrijfwijze, Aanhef, Gebruik in lopende tekst, Voorletters en Leeftijd en RvIG de API binnen de huidige wettelijke kaders kan aanbieden (zie #765)

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by fsamwel** [comment]
we maken geen sdk maar leveren een proxy
