### ISSUE TITLE
onjuiste description bij overlijden en geboorte plaats

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#777]
N.a.v. e-mail @gertjanvanderkooij: In de API-spec (YAML) wordt in de tekst bij de attributen nog onderscheid gemaakt in de afhandeling van geboorte- en overlijdensplaats vs. de huwelijk/gp-plaats:
 
Geboorte/Overlijdensplaats …
“Plaats waar de persoon is overleden. Voor een plaats buiten Nederland is gemeentecode=1999 (RNI) en gemeentenaam de buitenlandse plaatsnaam of aanduiding.”
 
Huwelijk/GP-plaats …
“Als de plaats een gemeente in Nederland is dan gewoon de gemeentecode + gemeentenaam. Voor een plaats buiten Nederland is de gemeentecode leeg en wordt de gemeentenaam de buitenlandse plaatsnaam of aanduiding.”

De description bij overlijden en geboorte is niet correct. Ook hier gebruiken we niet de "magische" code 1999 met een specifieke afwijkende betekenis, maar alleen echte codes van echte gemeentes.
Hier moet dus de beschrijving worden (bijvoorbeeld bij overlijden): “Plaats: Gemeente waar de persoon is overleden. Is de persoon overleden buiten Nederland, dan wordt de code niet opgenomen en is naam de buitenlandse plaatsnaam of aanduiding.”

De description in AangaanHuwelijkPartnerschap kan denk ik ook beter. Vooral het deel "is dan gewoon" is een beetje vreemd (of té gewoon?). Als het zo gewoon is (de gegevens zijn opgenomen met een waarde), hoef je dat ook niet te vermelden
Ik stel voor: "Plaats: De gemeente waar het huwelijk is voltrokken of het partnerschap is aangegaan. Voor een plaats buiten Nederland is de code leeg en wordt de naam de buitenlandse plaatsnaam of aanduiding."

**Comment by fsamwel** [comment]
@CathyDingemanse eens met de voorgestelde descriptions of heb je een beter voorstel?

**Comment by JohanBoer** [comment]
Dan wacht ik ook nog even met de wijzigingen voor v1.2.0 definitief te maken zodat deze descriptions daarin meekunnen.

**Comment by CathyDingemanse** [comment]
Is de code leeg of wordt er geen code geretourneerd? In het laatste geval:
“Plaats: Gemeente waar de persoon is overleden. Is de persoon overleden buiten Nederland, dan bevat het antwoord alleen een buitenlandse plaatsnaam of aanduiding.

Plaats: De gemeente waar het huwelijk is voltrokken of het partnerschap is aangegaan. Voor een plaats buiten Nederland bevat het antwoord een buitenlandse plaatsnaam of aanduiding."

**Comment by fsamwel** [comment]
@JohanBoer weet jij waarom dit issue nog op Review staat? Dit is denk ik al doorgevoerd in de specificaties.

**Comment by JohanBoer** [comment]
> @JohanBoer weet jij waarom dit issue nog op Review staat? Dit is denk ik al doorgevoerd in de specificaties.

Klopt
