### ISSUE TITLE
Als PO vraag ik mij af wat de toegevoegde waarde van de raadpleeg endpoints ouders, kinderen en partners met identificatie

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#795]
zodat we deze kunnen opnemen zoals ze zijn: eigenschappen van de persoon.

We hebben dit gedaan om eea RESTful te maken, maar dit blijkt bij nader inzien niet restful te zijn:
- een partner die "ex partner" wordt krijgt een andere ID. Met d eID van de vorige actuele partner, krijg je nu een nieuwe actuele partner (ander persoon)
-  kind met ID1 is de oudste, en het kind met de hoogste ID is de jongste (waar ik geen consequenties aan kan verbinden)
-  ouder1 kan de volgende keer met dezelfde ID een andere ouder krijgen. 
- geheimhouding wordt "dubbel" worden verstrekt, terwijl dit niet op de gerelateerde persoon van toepassing is.

Voorstel: maak dit depricated. Vanuit de businessvraag is er geen noodzaak voor deze endpoints. 
Laten we bespreken of we niet ook de subresources op een evolvable manier kunnen omzetten naar gegevensgroepen. 

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by fsamwel** [comment]
De problemen met de uri (id) van de relaties spelen alleen bij implementaties die nu worden gemaakt en bijvoorbeeld GBA-V als bron gebruiken. Daarin zit geen unieke identificatie en dus moet er iets gekunsteld worden (zoals gebruik volgorde van kinderen in het antwoord of ouder1/ouder2). Ik denk dat bij een implementatie door RvIG dat geen probleem meer is, want zij kunnen wel een unieke en permanente resource identificatie persisteren.

Neemt niet weg dat ik ook niet meer kan bedenken waarom we voor personen de ouders, partners en kinderen als aparte (sub) resources hebben gedefinieerd. In de design decisions staat hier niks over. 
Wel vind ik discussie hierover in https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/issues/92.

**Comment by JohanBoer** [comment]
Release 1.2.0 is 13 dagen geleden al aangemaakt. Deze wijziging kunnen we dus ook niet meer in 1.2 opnemen maar in 1.3.
Door de endpoints deprecated te maken en de ouders, kinderen en partners als gegevensgroepen op te nemen zal dit vooralsnog non-breaking kunnen.

**Comment by JohanBoer** [comment]
We hebben besloten om de subresources voor ouders, kinderen en partners te verwijderen en deze gegevens onder te brengen in de resource "ingeschrevenpersoon" als gegevensgroepen. Dat betekent ook dat de endpoints voor ouders, kinderen en partners deprecated worden verklaard.
