### ISSUE TITLE
Als medewerker Schuldhulpverlening/Geldzaken wil ik inzicht in de verblijfplaats en verblijfstitel bij een vreemde nationaliteit

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#797]
...zodat ik kan onderzoeken of de registratie klopt, evt. kan terugmelden en/of helpen bij correctie, zodat iemand toch recht heeft op wettelijke schuldhulpverlening.  

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
Volgens mij leveren we deze functionaliteit nu.
