### ISSUE TITLE
Als medewerker van de gemeente wil ik de mogelijkheid hebben met zoekmethode op postcode en huisnummer verder te verfijnen op huisletter en huisnummertoevoeging (indien aanwezig)

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#800]
...zodat het aantal gevonden personen minimaal is.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by fsamwel** [comment]
@CathyDingemanse deze heb je assignet aan o.a. mij. Verwacht je dat we hier nog iets aan moeten doen? De API ondersteunt dit al

**Comment by CathyDingemanse** [comment]
Sorry, assignen is verkeerd gegaan.

**Comment by CathyDingemanse** [comment]
zie parametercombinaties.feature.

**Comment by fsamwel** [comment]
@CathyDingemanse deze staat op v1.2, maar dit zit al in de API dit al sinds v1.0.0 (en ook al in v0.9.0)
