### ISSUE TITLE
aanduidingBijHuisnummer opnemen in adresregel1?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#803]
De feature [adres](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/master/features/adres.feature) beschrijft dat de eerste adresregel wordt gevuld met straat (11.10) + huisnummer (11.20)+ huisletter (11.30) + huisnummertoevoeging (11.40).

Hierin wordt aanduidingBijHuisnummer (mogelijke waarde "tegenover" of "bij" niet genoemd.

Daarmee vormen adresregel1 en adresregel2 een correct adres dat overeenkomt met de nummeraanduidingIdentificatie en adresseerbaarObjectIdentificatie), maar geven ze niet op de juiste manier de verblijfplaats van de persoon aan. 

@CathyDingemanse Moet aanduidingBijHuisnummer ook worden toegevoegd aan adresregel1? Zo ja hoe?

Bijvoorbeeld GBA-V proefomgeving persoon met BSN 999990482 (zoals het nu wordt teruggegeven door de API):
    "verblijfplaats": {
        "korteNaam": "1e Exloërmond",
        "aanduidingBijHuisnummer": "tegenover",
        "straat": "1e Exloërmond",
        "huisnummer": 3,
        "postcode": "9573PA",
        "woonplaats": "Borger-Odoorn",
        "adresregel1": "1e Exloërmond 3",
        "adresregel2": "9573PA Borger-Odoorn"
    },

Ik zie verschillende opties:
1. niet opnemen in adresregel1, het is eigenlijk een adresregel0
2. opnemen aan het begin van adresregel1: "tegenover 1e Exloërmond 3"
3. opnemen aan het einde van adresregel1: "1e Exloërmond 3 tegenover",

**Comment by fsamwel** [comment]
ehm, dit issue is onterecht. In GBA-V proefomgeving zit blijkbaar data die volgens Lo GBA niet is toegestaan. aanduidingBijHuisnummer mag niet voorkomen bij een BAG adres en is daarom niet opgenomen in de adres feature. 

In de adres feature staat bij een niet-BAG adres wel:
> wordt verblijfplaats.adresregel1 gevuld met straat (11.10)+ huisnummer (11.20)+ huisletter (11.30) + huisnummertoevoeging (11.40) + aanduidingBijHuisnummer (11.50)

**Comment by CathyDingemanse** [comment]
Sluiten dan maar?
