### ISSUE TITLE
Als gebruiker van de API krijg ik een foutmelding

### ISSUE THREAD

**Issue by jeroenriemens** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#804]
# Impediment
Als ik de voorbeeld-API gebruik krijg ik bij alle personen die ik bevraag de volgende melding:
{
    "type": "https://docs.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?#System_Net_HttpStatusCode_InternalServerError",
    "title": "Interne server fout.",
    "status": 500,
    "detail": "Onverwachte fout bij raadplegen op burgerservicenummer: Policy Falsified",
    "instance": "https://www.haalcentraal.nl/haalcentraal/api/brp/ingeschrevenpersonen/999990639",
    "code": "serverError"
}

is er ergens iets verandert of gaat er hier iets helemaal fout?

**Comment by fsamwel** [comment]
op dit moment wordt er onderhoud uitgevoerd op de onderliggende infrastructuur. Ik vermoed dat dit de oorzaak is van deze fout. Ik verwacht dat dit later op de dag zal zijn opgelost

**Comment by fsamwel** [comment]
@jeroenriemens probleem is opgelost. de API doet het weer
