### ISSUE TITLE
Als medewerker parkeren heb ik het A-nummer van een persoon nodig

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#805]
...zodat ik deze in mijn processen kan gebruiken.

A-nummer wordt bij heel veel processen binnen de gemeente Den Haag nog gebruikt. Onder andere bij parkeren.
In IDHB toonde we deze in eerste instantie ook niet, maar is toen toch op verzoek geplaatst. Deze moet nu dus ook nog beschikbaar zijn

**Comment by fsamwel** [comment]
@CathyDingemanse destijds hebben we vol overtuiging de conclusie getrokken dat het A-nummer door niemand gebruikt wordt. Ik krijg nu van de functioneel beheerders van IDHB door dat het A-nummer daar op verzoek juist is toegevoegd.

**Comment by CathyDingemanse** [comment]
Ja het is me wat. Ik heb er nog eentje: #782 
We gaan het toch opnemen. Het is niet anders.
