### ISSUE TITLE
Privacy: gebruik van google, jsdeliver et al

### ISSUE THREAD

**Issue by ryanbnl** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#807]
# Impediment

Van een privacy oogpunt wil je liever je fonts/scripts zelf hosten ipv "gratis" cloud hosting gebruiken. Want die scripts wordt door google etc gebruikt om mensen te tracken, en je moet ze volgens de GDPR opnemen in je voorwaardes, cookiewall et cetera.

**Comment by fsamwel** [comment]
@melsk-r @MelvLee is dit nu volledig opgelost door weghalen van de gegenereerde code? Of zit dit ook in de fonts die we gebruiken in de GitHub pages? Dat laatste kunnen we oplossen, toch?

**Comment by melsk-r** [comment]
Ik durf hier eerlijk gezegd niets over te zeggen. @MelvLee kan jij dit inschatten?

**Comment by MelvLee** [comment]
@melsk-r, Ik heb een p.r. hiervoor gemaakt

**Comment by JohanBoer** [comment]
@MelvLee Is dit nu afgehandeld ? Ik kan niet zien welke PR je bedoelt en of die gemerged is.

**Comment by MelvLee** [comment]
Ja, dat is uitgevoerd in de jekyll-theme-haal-centraal repo. Zie: https://github.com/VNG-Realisatie/jekyll-theme-haal-centraal/commit/e4261e67cad711a75a6834ec6af4a2bbf1c0557f
