### ISSUE TITLE
Taak: Ga na of komma separated strings in example verwijderd kan worden.

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#819]
In regel 75 van openapi.yaml staat:

> example: 999993653,999991723,999995078

De betreffende property is een array en we willen dat in de example gereflecteerd zien door daarin een komma separated string op te nemen, echter dit is per definitie geen correcte yaml code. 
Om de oas:lint validatie toch niet te laten falen, is daarom in het bestand .spectral.yml de regel 'oas3-valid-oas-parameter-example: off' toegevoegd waarmee die regel is uitgezet. Nadeel daarvan is dat het uitzetten van deze rule voor de hele repo geldt en er wordt nu dus nergens gecheckt of deze fout zich in yaml bestanden voordoet.

Ga na of het niet beter is deze fout te fixen zodat we de rule in de .spectral.yml weer kunnen verwijderen en de gehele yaml weer gecheckt wordt op deze fout.

**Comment by melsk-r** [comment]
Ik zie dat ik in de vaart van het corrigeren van de lint workflow op alle repo's de .spectral.yml al gecorrigeerd heb.
Mogelijk dat dat weer ongedaan gemaakt moet worden als we in het example toch graag de uitdrukking van de array willen behouden.

**Comment by JohanBoer** [comment]
Eigenlijk vind ik dat we de example aan moeten passen. Als er geen valide manier is om een juist example te geven van meerdere waarden bij een query-parameter die als array gedefinieerd is dan moeten we het maar met 1 waarde doen. 
Het komma-gescheiden example geeft in ieder geval een foute voorbeeld URL.

**Comment by fsamwel** [comment]
example zit niet meer in yaml bij parameter burgerservicenummer. @melsk-r checkt of spectra.yaml aangepast moet worden.

**Comment by melsk-r** [comment]
spectral.yaml hoeft niet aangepast te worden. Zoals gezegd is de regel 'oas3-valid-oas-parameter-example: off' eerder, 9 april 2021, al weer verwijderd waardoor er vanaf dat moment al weer gewoon gecheckt wordt op juistheid van de yaml.
Dat was geen probleem aangezien vooraf al de genoemde regel:

> example: 999993653,999991723,999995078

was gewijzigd in:

> example: ["999993653","999991723","999995078"]

Ik sluit daarom dit issue.
