### ISSUE TITLE
Als medewerker Samenlevingszaken wil ik "mijn clienten" selecteren uit de BRP

### ISSUE THREAD

**Issue by JohnRooijakkers** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#823]
...zodat ik conform Common Ground principes client gegevens kan gebruiken zonder deze vast te leggen in mijn sociaal domein applicatie (m.u.v. de unieke sleutel van deze client in de BRP).

**Acceptatiecriteria**
- Een client is een persoon die is ingeschreven in de BRP en in mijn verzorgingsgebied (n gemeenten) verblijft of heeft verbleven.
- Ik wil alle clienten selecteren die een inkomensvoorziening hebben of gehad hebben (filter)
- Ik wil de gevonden clienten sorteren op tenaamstelling (samenstelling van geslachtsnaam evt van partner, voorletters etc).
- Ik wil geen gegevens ontvangen van personen die niet tot mijn doelgroep behoren (ivm privacy)

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by fsamwel** [comment]
Hallo @JohnRooijakkers, de BRP weet niet welke cliënten een inkomensvoorziening hebben of hebben gehad. Dat zit in een andere bron. Ik denk dat je personen met inkomensvoorziening binnen een verzorgingsgebied in die bron zou moeten selecteren. Wat de BRP API vervolgens kan is een lijst burgerservicenummers (uit de inkomensvoorziening bron) de benodigde persoonsgegevens ophalen.

Is dat een oplossing voor de user story?

**Comment by JohnRooijakkers** [comment]
Hi @fsamwel,
Dit vereist dan een gecombineerde bevraging en dus selectie (join) over twee bron applicaties. Als ik de Common Ground principes goed begrijp is dit via één API (binnen de bron in het sociaal domein) niet mogelijk. Deze user story is overigens op ieder gemeentelijk subdomein van toepassing.
Mijn gedachte gaat naar een oplossing waarbij de BRP een API aanbiedt waarmee toepassingen (bv een sociaal domein applicatie) indicaties bij een object (bv persoon) kunnen plaatsen en verwijderen. Hiermee kan de user story naar mijn mening wel worden gerealiseerd.
Wat is het standpunt vanuit het BRP project hierover? Iets dergelijks kent de BRP uiteraard al voor landelijke afnemers.
Groeten, John.

**Comment by CathyDingemanse** [comment]
Een client is een persoon die is ingeschreven in de BRP en in mijn verzorgingsgebied (n gemeenten) verblijft of heeft verbleven.
Ik wil alle clienten selecteren die een inkomensvoorziening hebben of gehad hebben (filter)
Ik wil de gevonden clienten sorteren op tenaamstelling (samenstelling van geslachtsnaam evt van partner, voorletters etc).
Ik wil geen gegevens ontvangen van personen die niet tot mijn doelgroep behoren (ivm privacy)

**Comment by CathyDingemanse** [comment]
Ha @JohnRooijakkers! Voordat we de vraag beantwoorden wil ik graag goed begrijpen wat de behoefte is.  
Je zegt:
> 
> * Ik wil alle clienten selecteren die een inkomensvoorziening hebben of gehad hebben (filter)
> * Ik wil de gevonden clienten sorteren op tenaamstelling (samenstelling van geslachtsnaam evt van partner, voorletters etc).

Waarom wil een (gesorteerd) bestand van alle (voormalig) clienten en wat wil je er mee doen?

**Comment by CathyDingemanse** [comment]
@JohnRooijakkers, ik wil ook deze wens of aanbeveling graag goed begrijpen.

> Mijn eigen gedachte gaat naar een oplossing waarbij de BRP een API aanbiedt waarmee toepassingen (bv een sociaal domein applicatie) indicaties bij een object (bv persoon) kunnen plaatsen en verwijderen. Hiermee kan de user story naar mijn mening wel worden gerealiseerd.

Het zetten van indicatie bij een persoon, kunnen we doen voor aantal doelen:
- het ontvangen van een notificatie, bijvoorbeeld dat er een specifieke (voor jouw proces relevante) gebeurtenis heeft plaatsgevonden
- state transfer (gebeurtenis, met daarbij de wijziging van de gegevens waartoe deze gebeurtenis heeft geleid (bijvoorbeeld om te kunnen synchroniseren)
- het terugvinden van deze gebeurtenis in een eventlog van deze persoon bijvoorbeeld. (bijvoorbeeld om iets in het verleden te corrigeren, met consequenties in het eigen proces vanaf het correctietijdstip). De eventlog kan worden gebruikt voor "replay".

Kun je aangeven wat jemet jouw suggestie wilt bereiken in het kader van het sociaal domein? Op welke manier is dit gerelateerd aan jouw eerdere vraag naar een clientenbestand? Dank!!

**Comment by JohnRooijakkers** [comment]
@CathyDingemanse, vind je het goed om eerst even telefonisch contact te hebben? Dan kunnen we de cases bespreken. Daarna kunnen we onze conclusies hier bij de story plaatsen.

**Comment by CathyDingemanse** [comment]
Is goed! Heb je m'n nummer?

**Comment by JohnRooijakkers** [comment]
@CathyDingemanse, Heb ik niet. Ik heb je een connectie verzoek gestuurd via LinkedIn. Dan kunnen we via PM onze nummers uitwisselen en een geschikt moment kiezen voor telefonisch contact. Alvast bedankt daarvoor.

**Comment by CathyDingemanse** [comment]
Dank John voor het gesprek van zojuist! Afegesproken is dat jij een of meer echte user stories inbrengt voor de selectie op de BR die jij voor ogen hebt, zodat ik het gesprek kan aangaan met andere gebruikers en de BRs met de juiste argumenten op zak. Alvast dank!

**Comment by JohnRooijakkers** [comment]
@CathyDingemanse, binnen het sociaal domein denk ik bijvoorbeeld aan deze user stories:
- Als casemanager wil ik de casusdossiers selecteren van mijn cliënten waarvan de naam begint met “Jans”, die geboren zijn op 12-06-1992 of die wonen op een adres met een postcode 1234AB en huisnummer 1a, zodat ik de client die me belt (met deze gegevens) kan helpen (en daarvoor heb ik zijn casus dossier nodig).
- Als consulent wil ik zien welke cliënten met een WMO voorziening wonen in het bejaardentehuis aan de Beatrixstraat, zodat ik hun cases kan bespreken met de directie van dat tehuis waarmee ik vandaag een afspraak heb.
- Als wijkteam medewerker wil ik een overzicht van alle cliënten met een vervoersvoorziening die wonen in wijk Centrum zodat ik aan hen kan melden dat op Koningsdag het centrum voor autoverkeer is afgesloten.
- Als beleidsmedewerker wil ik alle cliënten jonger dan 27 jaar met een inkomensondersteuning aanschrijven omdat zij als gevolg van nieuw beleid mogelijk recht hebben op een toelage.
Vanuit privacy (en performance) oogpunt lijkt het mij niet wenselijk om eerst alle personen in de BRP te selecteren die aan bepaalde persoonskenmerken voldoen en die vervolgens te filteren op aanwezigheid en kenmerken binnen mijn taakveld.

Dit overzicht is slechts een voorbeeld en uiteraard niet volledig. Ik heb ook aan mijn collega's binnen andere domeinen gevraagd om scenario's aan te leveren, maar daarop nog geen reactie ontvangen.

**Comment by EddyvandeWerken** [comment]
Er is persoons-/klantinformatie nodig om in een applicatie een proces te kunnen uitvoeren. In de HaalCentraal gedachte haal je die informatie op bij de (centrale)bron.
Op het moment dat er een bepaalde gebeurtenis is met deze persoon en/of mutaties in gegevens wil de applicatie dat ‘weten’ omdat dit invloed kan hebben op het proces.
Je hebt dus altijd iets van een ‘notificatie’ nodig. Op basis van die notificatie bepaal je dan in je applicatie welke actie daar op moet volgen.
Omdat je niet in heel NL geïnteresseerd bent zou je dit ergens moeten bijhouden/abonneren. In de huidige standaarden doet een distributiecomponent dat voor inwoners in combinatie met de VOA voor niet-inwoners.
HaalCentraal ziet voor het abonneren een rol voor de “BRP-Update-API”  GitHub - VNG-Realisatie/Haal-Centraal-BRP-Update-API
Niet helemaal duidelijk wat de status/voortgang daar van is.
 
Tegelijkertijd is er een ‘werkgroep’ o.l.v. de VNG, die een manier/standaard onderzoekt om op basis van “gebeurtenissen”/events te kunnen werken, al dan niet in combinatie met mutaties.
Daarin zien zij een mogelijke rol voor een ‘distributie/makelaar’-component Notificatieservices · Grenzeloos samenwerken (pleio.nl)

**Comment by JohnRooijakkers** [comment]
@EddyvandeWerken, allereerst bedankt voor reactie.

Daarop mijn reactie en aanvulling:
- Ik ken het notificatiemechanisme en dit wordt gebruikt voor kennisgevingen over “life events” zodat die processen in taakapplicaties kunnen triggeren. Op dit moment worden deze notificaties (ook) gebruikt voor het synchroniseren van redundant binnen taakvelden opgeslagen basisgegevens. Deze kennisgevingen worden getriggerd vanuit de basisregistratie via de notificatiecomponent en verwerkt door de taakapplicatie.
- Waar ik (ook) naar op zoek ben is de mogelijkheid om binnen raadpleegfuncties, gegevens te selecteren over “mijn objecten”.
Dit zijn de objecten (bv personen in de BRP) die binnen mijn taakveld relevant zijn als object (bv clienten in het sociaal domein). Deze vragen worden getriggerd vanuit de taakapplicatie en verwerkt (beantwoord) door de basisregistratie.

Jouw (terechte) opmerking over het kunnen vastleggen/aanduiden van de objecten waarover je genotificeerd wil worden, onderschrijf ik. Hetzelfde geldt in mijn optiek dus ook voor de objecten waarover je informatie wil opvragen.

**Comment by CathyDingemanse** [comment]
@JohnRooijakkers het lijkt er op dat dit issue meer een architectuurvraag behelst, zoals ook @EddyvandeWerken al aangeeft. Ik denk dat dit idd buiten de scope van haal Centraal valt. De RvIG voert slechts een wettelijke taak uit. De voorgestelde oplossing is geen onderdeel daarvan en maakt ook geen onderdeel uit van het experimenteerartikel. 
Jouw vraag moet worden beantwoord door @VNG-Realisatie/archi-gemma-team.

**Comment by EddyvandeWerken** [comment]
@CathyDingemanse , Je verwijst naar een team, waar ik blijkbaar geen toegang toe heb. Bestaat dit team en zo ja, ken jij een ingang bij VNG om hier toegang tot te vragen?

**Comment by michielverhoef** [comment]
@EddyvandeWerken, dit is een team binnen github.  Deze teams worden gebruikt om rechten op repositories in te regelen. 

Als ik het zo snel zie zijn dit de reguliere leden van het team architecten bij VNG Realisatie en zij zijn bereikbaar via gemmaonline@vng.nl

**Comment by CathyDingemanse** [comment]
> @EddyvandeWerken, dit is een team binnen github. Deze teams worden gebruikt om rechten op repositories in te regelen.
> 
> Als ik het zo snel zie zijn dit de reguliere leden van het team architecten bij VNG Realisatie en zij zijn bereikbaar via [gemmaonline@vng.nl](mailto:gemmaonline@vng.nl)

Inderdaad, thnx Michiel!

**Comment by JohnRooijakkers** [comment]
@CathyDingemanse en @EddyvandeWerken,
Gezien het (verplichte) gebruik van de BRP voor het uitvoeren van publieke en maatschappelijke taken, vind ik het vreemd en ongewenst dat deze vraag buiten scope van Haal centraal wordt geplaatst. Ik ben het wel eens met de stelling dat deze vraag generiek is voor alle basisregistraties, dat daarvoor een generieke oplossing vanuit archi-gemma-team moet komen en dat deze oplossing wordt toegepast binnen iedere basisregistratie. Daarom zal ik dit issue melden aan het archi-gemma-team en hen vragen dit in behandeling te nemen.
