### ISSUE TITLE
inOnderzoek lastig in gebruik om te tonen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#827]
In onderzoek is nu zo opgezet dat bij het in onderzoek staan van een hele categorie of hele groep alle velden uit die categorie of groep in onderzoek staan.

Door deze vertaling moet een gebruiker:
- terugvertalen naar de oorspronkelijke categorie of groep wanneer getoond moet worden wat er onderzocht wordt
- doorvertalen naar afgeleide gegevens wanneer getoond moet worden wat er mogelijk onjuist is

Bijvoorbeeld  de hele categorie 3 (ouder2) is in onderzoek. De gebruiker krijgt dan:
```
                "inOnderzoek": {
                    "burgerservicenummer": true,
                    "datumIngangFamilierechtelijkeBetrekking": true,
                    "geslachtsaanduiding": true
                },
                "naam": {
                    "inOnderzoek": {
                        "voornamen": true,
                        "voorvoegsel": true,
                        "geslachtsnaam": true
                    }
                },
                "geboorte": {
                    "inOnderzoek": {
                        "datum": true,
                        "plaats": true,
                        "land": true
                    }
                }
```

Hoe moet de client aan een gebruiker tonen wat er aan de hand is? Opsommen van alle gegevens die in onderzoek staan geeft een lange lijst aan gegevens die in onderzoek staan (in bovenstaand voorbeeld 9). Dat ziet er vreselijk uit op het scherm en vertelt niet wat er echt aan de hand is, namelijk er zijn twijfels of dit wel een ouder is van de persoon.

Ook per gegeven een indicatie (icoon o.i.d.) tonen is niet goed bruikbaar, bijvoorbeeld wanneer niet voornamen, maar voorletters worden getoond, niet geboortedatum, maar leeftijd, niet geslachtsnaam maar aanschrijfwijze, enz. De client developer moet dan uitzoeken welke gegevens zijn afgeleid, en van welke gegevens.

Het is in code ook niet af te leiden dat de hele categorie of groep in onderzoek staat, want mogelijk wordt niet de hele in onderzoek geleverd i.v.m. autorisatie van de gebruiker (client kent de autorisatie niet) of door gebruik van fields (t.b.v. dataminimalisatie wil je voorkomen dat gegevens alleen worden gevraagd om onderzoek af te leiden).

Kunnen en willen we hier nog iets aan doen? Bijvoorbeeld:
- toevoegen van toelichting, zoals ook in BAG gedaan is 
- toevoegen van indicatoren voor afgeleide gegevens
- toevoegen van indicatoren voor categorieën en groepen

**Comment by JohanBoer** [comment]
Als je wilt dat er geautomatiseerd actie ondernomen kan worden dan zou je volgens mij voor de 2e en 3e optie moeten gaan (toevoegen van indicatoren voor afgeleide gegevens en voor categorieën en groepen.)

Als je kiest voor het toevoegen van een toelichting kan je weliswaar de gebruiker informeren, maar geen geautomatiseerde actie inzetten. Het ligt er dus een beetje aan wat je de consumer-developers aan opties wilt bieden. Misschien moet je wel alledrie de opties invulling geven zodat consumer-developers zelf kunnen kiezen.

**Comment by fsamwel** [comment]
@JohanBoer dit issue gaat vooral over het tonen aan een gebruiker. Voor geautomatiseerde afhandeling (ik neem aan dat je daarmee bedoelt berekeningen maken of beslissingen via algoritme nemen) denk ik dat je met het huidige ontwerp een heel eind komt. Alleen bepaalde afgeleide gegevens kunnen dan nog fout gaan (samengestelde naam en adresvelden zal men denk ik niet gebruiken in een algoritme):
- met fields vragen om leeftijd geeft geen geboorte.inOnderzoek
- met fields vragen om indicatieOverleden geeft geen overlijden.inOnderzoek
- met fields vragen om indicatieVestigingVanuitBuitenland, vanuitVertrokkenOnbekendWaarheen, vertrokkenOnbekendWaarheen geeft geen verblijfplaats.inOnderzoek
