### ISSUE TITLE
Als afnemer wil ik de enumeratiewaarden in gebruikersvriendelijke teksten willen zien

### ISSUE THREAD

**Issue by KayodeBakker** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#828]
...zodat er niet allerlei conversies hoeft plaats te vinden om dit mooi leesbaar te maken. Niemand heeft wat aan halfbakken omschrijvingen zoals 'pl_aangelegd_in_de_rni' waar het eigenlijk 'persoonslijst aangelegd in de RNI' had moeten zijn. 

**Acceptatiecriteria**
- Enumeratiewaarden krijgen een gebruikersvriendelijke tekst

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

Let op. Ditzelfde geldt eigenlijk ook voor andere registraties.

**Comment by KayodeBakker** [comment]
Ontvangen van Frank Samwel rondom het vraagstuk van de conversie:
![image](https://user-images.githubusercontent.com/47184630/129027359-e0e8b6ce-e7f8-4286-8a6e-62f5e980dff2.png)


Let op. Dit is wederom alleen BRP. Dit vraagstuk hangt ook rond bij anderen zoals de BRK.

**Comment by KayodeBakker** [comment]
Deze issue lijkt ook deels te worden besproken bij #685

**Comment by MelvLee** [comment]
@KayodeBakker, voor mijn begrip ben ik benieuwd hoe je zonder conversie code de string waarden uit een enum definitie wil halen. In OAS kan bijv. "geregistreerd partnerschap" als enum waarde worden opgegeven, maar in .NET wordt afhankelijk van de code generator de volgende code voor enum waarde gegenereerd:

```
  [EnumMember(Value = "geregistreerd partnerschap"}]
  geregistreerd_partnerschap=...
```

Volgens mij kan je de Value property van een EnumMember attribuut namelijk alleen middels reflectie uitlezen.

**Comment by CathyDingemanse** [comment]
@Kayo, jij wil graag een goede omschrijving hebben. Daarnaast: 
- kun je aan de enum in OAS geen description of naam toevoegen. 
- hebben we in de BAG wel enums met spaties (in code krijg je enums met underscores ipv spaties)
- en kunnen alle code generatoren een mapping maken van _ naar spatie op de wijze zoals Melvin hierboven aangeeft voor .NET. Melvin heeft dit onderzocht voor Python, Java, .NET en JavaScript.

Conclusie is dan dat je code moet schrijven (om transformatie informatie uit te lezen). Klopt deze analyse, of zien wij wat over het hoofd?

**Comment by CathyDingemanse** [comment]
> @KayodeBakker , jij wil graag een goede omschrijving hebben. Daarnaast:
> 
> * kun je aan de enum in OAS geen description of naam toevoegen.
> * hebben we in de BAG wel enums met spaties (in code krijg je enums met underscores ipv spaties). Dat is idd een beetje slordig/ niet consistent :-).
> * en kunnen alle code generatoren een mapping maken van _ naar spatie op de wijze zoals Melvin hierboven aangeeft voor .NET. Melvin heeft dit onderzocht voor Python, Java, .NET en JavaScript.
> 
> Conclusie is dan dat je code moet schrijven (om transformatie informatie uit te lezen). Klopt deze analyse, of zien wij wat over het hoofd?

**Comment by KayodeBakker** [comment]
Effectief zouden we willen dat er nette omschrijvingen voor enumeraties beschikbaar zijn. Er zijn al veel discussies geweest binnen de OpenAPI standaard voor het realiseren daarvan, maar voorlopig nog geen concrete acties ondernomen. Of dit nu gerealiseerd wordt op die manier of d.m.v. een extra string attribuut per enum er naast (zodat het geen breaking change is) is om het even.

Het probleem is met name dat alle afnemers van de API nu dit zelf moeten gaan oplossen in de eigen applicatie. Logischer is het om dit op te lossen in de API zelf, maar dat gaat niet dankzij de opzet van de enumeraties.

@MelvLee Die value kan je wel gebruiken bij een json converter. Dankzij een generatie tool zal de enum zoals in de specs worden opgenomen in de EnumMember. Ik weet niet hoe dit voor andere tools zou zijn, maar als de enum values in de specs de nette schrijfwijze hebben dan zou dat op zichzelf al een oplossing kunnen zijn.

**Comment by JohanBoer** [comment]
@KayodeBakker @CathyDingemanse  Met de huidige opzet van de enums in OpenAPI  aangevuld met de punten zoals Frank die eerder heeft beschreven denk ik dat hier nu geen verbetering in aan gaan brengen. Zie ik dat goed ? 
Zetten we deze issue dan op de backlog of gaan we hem sluiten ?

**Comment by MelvLee** [comment]
Wat is de afspraak als er nieuwe enums wordt geïntroduceerd? Wat mij betreft gaan we gebruiksvriendelijke teksten gebruiken. Dit omdat:

- de BAG al gebruiksvriendelijke teksten als enum waarden gebruikt
- de code generatoren die ik heb getest/gebruiken (OpenApi Generator en NSwag) hiermee om kunnen gaan. Ook in Java en Python en JavaScript
- de BRP 1.0 nog moet worden geïmplementeerd, dus kunnen we het daar veranderen voordat met de implementatie wordt gestart
- voor de BRK een major change in de pipeline zit. Kunnen we dit dan ook direct meenemen

**Comment by melsk-r** [comment]
Een reactie op de punten van Frank:

Ad1. Voor BRK 2.0 is dit zoals Melvin stelt inderdaad geen beletsel. Als we dit in BRP gaan wijzigen dan zou dat in principe ook versie 2.0 op moeten leveren. Het is immers niet Backwards compatible of de API nu al geïmplementeerd is of niet. Is het echter handig om nu al met een versie 2.0 te komen of gaan we in dit geval gewoon wat minder strikt om met de regels die we onszelf hier opleggen en publiceren we gewoon 1.1?
Voor de andere HC API's zouden we moeten wachten op de gelegenheid dat we daarvoor een 2.0 versie gaan publiceren.

Ad2. Melvin geeft aan dat codegeneratoren om kunnen gaan met beter leesbare enumeraties. Of dat ook betekent dat deze tekstens ook gebruiksvriendelijk zijn is de vraag.
Als je met gebruiker de eindgebruiker van de applicatie bedoelt dan is daarop het antwoord denk ik 'ja'. Als je daarmee de ontwikkelaars bedoelt en uitgaat van code generatie dan geldt hetzelfde. Het maakt de ontwikkelaar dan denk ik niet uit hoe de enumeraties er uit zien zolang de enumeratiewaarde maar uniek is. Als code generatie echter niet aan de orde is maar code handmatig wordt geklopt dan denk ik dat het minder gebruiksvriendelijk is en ook foutgevoeliger. In hoeverre moeten we rekening houden met dat scenario?

Ad3. Hier heeft Frank wel een punt denk ik. Code moet wel zo eenvoudig mogelijk interpreteerbaar blijven. Ik schat in dat het daarbij vooral gaat om de lengte van de enumeratiewaarden, spaties in de enumeraties zullen in de code immers wel vertaald worden naar bijv. underscores. Deze eis stelt dus een eis aan de lengte van de enumeraties. Het scheelt nogal in de code of je daar 'eigen_partner' gebruikt of 'gebruik_de_eigen_naam_voor_de_partnernaam'.

Ad5. Ik ben het eens met Frank dat de aan de eindgebruiker te tonen tekst erg afhankelijk kan zijn van de context. Lijkt me ook dat dit deel van de code juist vaak handmatig wordt ingeklopt.

Ad6. Het is inderdaad de vraag of de API specificatie niet oneigenlijk gebruikt wordt.

**Comment by JohanBoer** [comment]
@KayodeBakker 

Onderstaande is de conclusie uit de teambespreking van vorige week. 

We trekken die Issue-tekst even uit elkaar in 2 delen :

1.	Als afnemer wil ik de enumeratiewaarden in gebruikersvriendelijke teksten willen zien zodat er niet allerlei conversies hoeft plaats te vinden om dit mooi leesbaar te maken. 
2.	Niemand heeft wat aan halfbakken omschrijvingen zoals 'pl_aangelegd_in_de_rni' waar het eigenlijk 'persoonslijst aangelegd in de RNI' had moeten zijn.

T.a.v. 1. Het is niet de doelstelling geweest om gebruikersvriendelijke enumeratie-waarden te formuleren, maar developers vriendelijke enumeratue-waarden. 
Aangezien de enumeratie-waarden door consumer-software voor verschillende doelen kunnen worden gebruikt zullen we nooit aan alle wensen kunnen voldoen om enumeratiewaarden  (of uitingen op basis van de enumeratie-waarden)
Zo vorm te geven dat ze in alle gevallen zonder conversie toepasbaar zijn. We mogen van de consumer-developer verwachten dat die de vertaling maakt naar hoe de enumeratiewaarde specifiek voor zijn toepassing aan de gebruiker gepresenteerd wordt. 
Waar nodig en mogelijk wordt er in de description van de enumeratie (ook nu al) een toelichting gegeven op de enumeratiewaarden (als dat beter kan horen we graag jouw aanbevelingen. Dat is een non-breaking documentaie-change. )

t.a.v. 2. Heb je groot gelijk. De betreffende enumeratiewaarde is cryptisch en voldoet niet aan de doelstelling zoals die bij 1 is benoemd. 

Aangezien we het hier wel over een breaking change hebben zullen we het wijzigen van enumeratiewaarden in beter begrijpelijke waarden op de backlog zetten zodat we dat mee kunnen nemen bij de eerst volgende major-release.

Voor nieuwe API’s overwegen we zeer serieus om ons aan extension API-66 van de landelijke API strategie te conformeren (Use UPPER_SNAKE_CASE for enumeration values)

**Comment by KayodeBakker** [comment]
@JohanBoer 
Wat als we nou een extra attribuut toevoegen per enum? Dan kunnen we de enums zelve laten zoals ze zijn (los van optimalisatie in leesbaarheid later), maar dan hebben we ook een omschrijving ernaast staan.
Ik zit dan te denken iets in de richting als het volgende waar RedenOpschortingBijHouding_enum even het voorbeeld is:

``` yaml
    OpschortingBijhouding:
      type: object
      properties:
        reden:
          $ref: '#/components/schemas/RedenOpschortingBijhouding_enum'
        datum:
          $ref: '#/components/schemas/DatumOnvolledig'
          description: de datum waarop de bijhouding van de persoonsgegevens is gestaakt.
        redenOmschrijving:
          type: string
          description: Omschrijving van enumeratie waarde van reden.
          example: "persoonslijst aangelegd in de RNI"  
```

Als afnemer hoef je dan alsnog geen zorgen te maken over het moeten vertalen en de partij die het implementeert hoeft dan geen rare sprongen en overrides ergens te plaatsen om deze omschrijving te plaatsen aangezien het onderdeel uitmaakt van de API. Dus dan maakt de implementatie partij een methode per enum die deze vertaling uitvoert.

Mocht er een geval zijn, zoals ik al eerder van Frank heb vernomen, waar bijv. een partij de geslacht enumeratie gebruikt en zaken als 'man' en 'vrouw' liever vertalen naar 'meneer' en 'mevrouw' dan is dat aan hun om dit te overriden en dan zou ik zeggen dat je doelbewust hebt geprobeerd de afnemer te helpen, maar ze ook de ruimte geeft om het zelf te bepalen. Er zijn immers meer afnemers die de standaard omschrijving willen dan een variant erop.

Dit zou in principe geen breaking change zijn en makkelijker te implementeren zijn dan een random hoek in de code wat niks met de API te maken heeft en waar alle afnemers dit zelf moeten bepalen.

**Comment by KayodeBakker** [comment]
@JohanBoer Heb jij nog tijd gehad om over mijn laatste opmerking na te denken?

**Comment by fsamwel** [comment]
@CathyDingemanse wordt dit dus in versie 2.0 doorgevoerd? (tegelijk met aanscherping parameters en toevoegen POST operaties)? @JohanBoer maak jij hier een pull request voor?

**Comment by CathyDingemanse** [comment]
> @CathyDingemanse wordt dit dus in versie 2.0 doorgevoerd? (tegelijk met aanscherping parameters en toevoegen POST operaties)? 

Yes.

**Comment by KayodeBakker** [comment]
Even voor mijn duidelijkheid. Wat is nu wat concreet wordt voorgesteld?

**Comment by fsamwel** [comment]
oplossen door enumeratiewaarden als waardentabellen te ontsluiten. zie pull request #865 en issues #856 en #858
