### ISSUE TITLE
Beschrijving van parameter geboorte__plaats is onduidelijk voor binnengemeentelijke plaats

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#831]
De beschrijving bij geboorte__plaats is "Gemeentenaam of een buitenlandse plaats of een plaatsbepaling, die aangeeft waar de persoon is geboren"

Moet een binnengemeentelijke plaats niet gezocht worden met gemeentecode (net als gemeenteVanInschrijving)? (in Den Haag is het nu geïmplementeerd dat er gezocht kan worden met gemeentecode)

**Comment by JohanBoer** [comment]
Bij het design is er op zich geen rekening mee gehouden dat hier een gemeente-code ingevuld wordt. Vooral omdat het ook een buitenlandse geboorteplaats of plaatsaanduiding kan zijn. 

Je zou er voor kunnen kiezen om ook de gemeentecode te accepteren als valide waarde van de parameter. Dan moet de beschrijving van de parameter aangepast worden. 

Bij een gemeenteVanInschrijving is het altijd een Nederlandse gemeente, daarom hebben we daar voor de gemeentecode gekozen. 

Jouw voorstel betekent dat de provider eerst moet checken of de betreffende parameter gevuld is met een gemeentecode en zo niet, dan moet gaan zoeken op de string van de ingevulde geboorteplaats. Dat kan natuurlijk zo afgesproken worden, maar dat hebben we niet gedaan.  Vanuit de specificatie gezien is het een kleine wijziging (alle de description van de parameter aanpassen) Voor de consumer is het non-breaking (additionele functionaliteit) 

Voor de provder zal dit wel een dingetje zijn lijkt mij. 

Als deze wens er is kunnen we hem bij de volgende minor versie meenemen.

**Comment by fsamwel** [comment]
eigenlijk is het denk ik nu wel goed gespecificeerd. Het is veel duidelijker en makkelijker voor een gebruiker om gewoon een plaatsnaam in te kunnen vullen, dan dat er expliciet moet worden gekozen tussen een Nederlandse gemeente of een plaats in het buitenland.

Het is alleen op https://www.haalcentraal.nl/haalcentraal/api/brp/ingeschrevenpersonen anders geïmplementeerd, daar zal bijvoorbeeld geboorte__plaats=Utrecht niks vinden en geboorte__plaats=0344 wel.

@KayodeBakker dit is denk ik een issue dat in jullie implementatie moet worden aangepast.

**Comment by KayodeBakker** [comment]
@fsamwel Dit kan ik wel aanpassen, maar bij het begin van de BRP API implementatie had ik hier al voor gewaarschuwd. De keuze was gemaakt omdat de GBA-V geen bevraging mogelijkheid heeft op geboorte plaats op omschrijving, alleen maar in code vorm. Dit was toen algemeen door besproken en geaccepteerd.

Als ik dit zou aanpassen, betekent dit wel dat elk request waar een parameter in zit wat een waarde tabel is, dat we eerst de landelijke tabellen API moeten bevragen om de conversie te krijgen. Niet alleen maak je dan een afhankelijkheid op een andere service, maar performance technisch is dit ook niet wenselijk.
