### ISSUE TITLE
Features uri-templating en self-links definitief?

### ISSUE THREAD

**Issue by hvdijk-p5** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#844]
Zijn deze twee features al definitief?
- https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.3.0/features/uri-templating.feature
- https://raw.githubusercontent.com/VNG-Realisatie/Haal-Centraal-common/v1.3.0/features/self-links.feature

Uri templating schrijft het gebruik van templates voor voor onder andere de hostnames in de HalLinks. In de Den Haag implementatie is dit nu niet zo geïmplementeerd, de links worden daar met hostname teruggegeven. De hostnames voor de verschillende api zijn ook voor alle links hetzelfde omdat dezelfde web applicatie ook consumers voor de externe api's zoals de BAG implementeert.

Feature self links schrijft het gebruik van relatieve links voor, al wordt in het midden gelaten of dit 'kan' of 'moet'. 

Voor de Den Haag implementatie is dit nu geen issue, echter wordt dit voor de Rvig implementatie wel belangrijk. Bij implementatie met hostnames moet dit geconfigureerd en dus beheerd worden:
- hostname van de Brp Api zelf (voor de self links). De web app draait in een container die mogelijk niet zoveel weet van de context waar het in draait. Dat betekent dat een in een proxy of gateway geconfigureerde hostname niet automatisch in de api beschikbaar is en dus als setting mee moet worden gegeven bij deployment.
- De hostnames van de externe api's die worden gebruikt in de HalLinks.

De vraag is dus, geeft de BRP api een response met of zonder hostnames in de HalLinks? Willen jullie hier verder over nadenken? Ik kan me voorstellen dat jullie Rvig hier bij betrokken moet worden. 

Op dit moment implementeer ik de Rvig versie met hostnames, ik hoor graag of ik dit moet veranderen of dat de specs worden aangepast.

**Comment by fsamwel** [comment]
misschien eerst/vooral een vraag voor @MelvLee. Wat verwachten we voor:
- self link
- BRP interne links (bijv. van BRP bevragen naar BRP historie)
- Externe links (naar BAG adres)

**Comment by MelvLee** [comment]
> misschien eerst/vooral een vraag voor @MelvLee. Wat verwachten we voor:
> 
>     * self link
> 
>     * BRP interne links (bijv. van BRP bevragen naar BRP historie)
> 
>     * Externe links (naar BAG adres)

Uit feedback van consumer is gebleken dat het niet handig is als er zowel relatieve als absolute uri's voorkomen in de payload. Dit maakt de te implementeren mapping logica in API Gateways complexer. Zie issue [899](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/899) bij BRK repo. Ik zou zelfde afspraak als bij BRK hanteren, dus geen relatieve urls gebruiken

**Comment by fsamwel** [comment]
> geen relatieve urls gebruiken

kan ik dat vertalen naar de conclusie: geen uri templating gebruiken voor base url's en altijd absolute uri's? Of is alleen de tweede conclusie nog terecht en moeten we nog iets zeggen over base url van links van BRP naar BAG adressen?

**Comment by MelvLee** [comment]
> > geen relatieve urls gebruiken
> 
> kan ik dat vertalen naar de conclusie: geen uri templating gebruiken voor base url's en altijd absolute uri's? Of is alleen de tweede conclusie nog terecht en moeten we nog iets zeggen over base url van links van BRP naar BAG adressen?

uri templating voor base urls heeft volgens mij geen zin als relatieve urls niet gewenst is. Ook dit zou de mapping logica voor API gateways complexer maken

**Comment by fsamwel** [comment]
dan moeten de features hierover denk ik worden aangepast, toch?

**Comment by hvdijk-p5** [comment]
Als we geen templating gebruiken voor base urls moet er volgens mij antwoord komen op de volgende vragen:

- Wijzigingen in de base urls van zowel de self als externe api's. Wat betekent dit voor een live api? Hoe vaak kan dit voorkomen? Hoe moet dit worden beheerd, zijn dit bijvoorbeeld settings bij deployment, of moeten urls live kunnen worden aangepast?

- Komt het in de praktijk voor dat een api onder verschillende gateways/urls wordt ontsloten? In item [899](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/899) wordt onder andere gesproken over een interne en externe tunnel met elk een eigen baseurl. Kan iets dergelijks ook in de praktijk voor productie versies van een haalcentraal api voorkomen?

**Comment by fsamwel** [comment]
> Komt het in de praktijk voor dat een api onder verschillende gateways/urls wordt ontsloten? In item 899 wordt onder andere gesproken over een interne en externe tunnel met elk een eigen baseurl. Kan iets dergelijks ook in de praktijk voor productie versies van een haalcentraal api voorkomen?

Het komt denk ik voor bij elke gebruiker dat deze achter een API gateway zit. Dus elke eindgebruiker moet andere urls gebruiken dan de urls van RvIG. Hun API gateway moet/kan de vertaling doen, zowel in het doorrouteren van requests als in het aanpassen van urls in de response.

**Comment by JohanBoer** [comment]
Melvin en Cathy gaan een gesprek aan met API-Gateway specialisten om de URI-templating feature te bespreken.

**Comment by fsamwel** [comment]
voorstel staat in PR #866

**Comment by JohanBoer** [comment]
@MelvLee @fsamwel Is deze issue (en de URI-templating feature) nog relevant met de keuze om POST in te zetten voor bevraging en HAL te laten vallen ? Volgens mij zitten er nu in ieder geval in BRP-bevragen geen links meer naar gerelateerde objecten.

**Comment by fsamwel** [comment]
ik denk dat deze gesloten kan worden
