### ISSUE TITLE
features voor ouders, partners en kinderen niet consistent met geslachtswijziging feature

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#845]
Bijv. in ouders.feature staat: "Wanneer de ouder een ingeschreven persoon is, levert de sub-resource ouders de actuele gegevens van de ouder(s) zoals die op de PL van de betreffende ouder staan (dus NIET zoals ze in categorie 02/52 Ouder1 of 03/53 Ouder2 staan)."

In geslachtswijziging.feature wordt beschreven dat voor geslachtsaanduiding de registratie van de PL van de gevraagde persoon (niet van de ouder/(ex)partner/kind) moet worden gebruikt.

Ik denk dat het verkeerd staat beschreven in de features voor ouders, partners en kinderen en voor hun gegevens alleen in de PL van de gevraagde persoon mag worden gekeken. Anders zou je ook moeten protocolleren dat de PL van de gerelateerde (ouder/partner/kind) is geraadpleegd.

@CathyDingemanse vergis ik mij en ben ik vreselijk in de war of staat het inderdaad helemaal fout in de features voor ouders, partners en kinderen?

**Comment by CathyDingemanse** [comment]
Je hebt gelijk, het staat verkeerd beschreven. Er mag alleen in de PL van de gevraagde persoon worden gekeken.

**Comment by JohanBoer** [comment]
Zie PR #848
