### ISSUE TITLE
Warning response header foutief gebruik volgens HTTP standaarden

### ISSUE THREAD

**Issue by KayodeBakker** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#849]
Sinds de ouders/kinderen/partners paden deprecated zijn geworden, hebben ze allemaal een warning response header staan in de specificaties. Deze dient de gebruiker te informeren, maar de header name is 'warning'. Deze heeft specifieke richtlijnen en zal voor problemen veroorzaken bij implementaties.

Zie [w3 protocols voor de uitleg](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.46) en [Mozilla voor de syntax](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Warning).

Hier staat duidelijk dat een bepaalde syntax verplicht is en het voorgestelde waarde in de specificaties voldoet hier niet aan. Tevens voldoen geen van de voorstellen bij de Mozilla pagina voor onze casus. Dit betekent voor de partij dat de implementatie maakt dat er expliciet geen validatie moet plaatsvinden op de response header value. Dit zou wel moeten gebeuren.

**Comment by fsamwel** [comment]
@KayodeBakker voor de implementatie voor RvIG gaan we een v2.0 uitleveren, omdat er ook parameters aangescherpt moeten worden. In de v2.0 release zullen deze endpoints verwijderd zijn, niet meer depricated. Dus is daar ook geen warning nodig.

Mogelijk moet je in de tijdelijke implementaties (bijv. bij gemeente Den Haag) wel de warning gaan geven, maar bij RvIG denk ik niet. De voorbeeldwaarde voor de warning is volgens mij overgenomen van de NL API strategie: https://docs.geostandaarden.nl/api/API-Strategie-ext/#the-warning-response-header

**Comment by JohanBoer** [comment]
Voor versie 2.0 is dit geen issue omdat er geen deprecated endpoints. Hoe we omgaan met warnings en de gevolgen voor versioning en de API-lifecycle moeten nog uitgewerkt worden. Dit kan door dit als issue bij de landelijke API-strategie te beleggen.

**Comment by KayodeBakker** [comment]
Dat is in principe prima. Het ging inderdaad meer om de melding van hoe om te gaan met een warning header op deze manier.
