### ISSUE TITLE
Kinderen die levenloos zijn geboren hebben een leeftijd

### ISSUE THREAD

**Issue by hvdijk-p5** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#853]
Op een PL kunnen kinderen voorkomen die levenloos zijn geboren. Deze kinderen hebben voor '09.89.10 Registratie betrekking' de waarde "L". Op dit moment houd de API geen rekening met deze gevallen, en wordt er ongeacht dit gegeven altijd een leeftijd meegegeven.

Dit kan ook voorkomen voor kinderen die zijn overleden, maar dit is minder eenvoudig op te lossen omdat een kind van de pl lijst van een ander persoon komt.

Moet voor kinderen die levenloos zijn geboren de leeftijd worden meegegeven? Wat gebeurt er als er geen autorisatie is op 09.89.10, is meegeven van leeftijd dan oke?

Is een indicatie 'levenloos' bij groep Geboorte misschien een mogelijke feature?

(@fsamwel ik dacht ik maak nog even een issue aan over wat we over de telefoon bespraken)

**Comment by fsamwel** [comment]
Ik zie dat in de autorisatietabel voor gemeente Den Haag (algemene gemeentetaken) 35.95.14 Bijzondere betrekking verstrekken de waarde 0 heeft. Deze kinderen worden dus niet verstrekt voor algemene gemeentetaken.

Voor gebruikers die deze kinderen wel mogen krijgen moet leeftijd niet worden geleverd. Ik zal dit toevoegen aan de feature leeftijd.

**Comment by fsamwel** [comment]
@CathyDingemanse vraagt na of en waarvoor dit gegeven nodig is

**Comment by fsamwel** [comment]
levenloos geboren kinderen worden voorlopig niet geleverd door de Haal Centraal BRP API, omdat er geen afnemers zijn met autorisatie daarvoor. Tot dat moment heeft een scenario daarover dus geen zin. dit daarom ook uit PR #854 verwijderd
