### ISSUE TITLE
geslachtsaanduiding uitbreidbaar maken

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#856]
geslachtsaanduiding is nu gedefinieerd als enumeratie met 3 mogelijke waarden (man, vrouw, onbekend).

de opties voor geslachtsaanduiding kunnen wellicht uitbreiden, bijvoorbeeld de 'X' variant.

uitbreiden van het aantal mogelijke waarden voor geslachtsaanduiding zou nu tot een breaking change leiden. Dat kan voorkomen worden wanneer we geslachtsaanduiding definiëren als waardentabel.

voordeel: dynamisch uitbreidbaar zonder breaking change
nadeel: gebruikers die geslachtsaanduiding enumeratiewaarde gebruiken om te vertalen naar een omschrijving hebben probleem bij toevoegen nieuwe waarde. bijvoorbeeld "vrouw" naar "mevrouw" of "dochter"

**Comment by CathyDingemanse** [comment]
Met een waardentabel kun je toch net zo goed die vertaling maken? Voordeel is dat je dat landelijk voor iedereen beschikbaar (en hetzelfde) kunt neerzetten.

Ik vind het nog steeds een goed idee. Doen!

**Comment by JohanBoer** [comment]
Tabel introduceren (in de landelijke tabellen API) --> Ontwerp-sessie plannen

**Comment by fsamwel** [comment]
wordt opgelost met PR #867 (enums naar waardenlijsten)
