### ISSUE TITLE
Verduidelijken algoritme geslachtsnaam

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#86]
Het algoritme voor het samenstellen van de geslachtsnaam moet verder verduidelijkt worden:
* De tabel voor toepassen van aanduiding aanschrijving is niet opgenomen

**Comment by fsamwel** [comment]
In LO GBA wordt alleen gesproken over voornamen. Moeten de voorletters worden afgeleid uit de voornamen? Zo ja hoe? (wordt bijvoorbeeld Theo afgekort naar "T." of "Th."?)

**Comment by fsamwel** [comment]
In de tekst staat voorbeeld "jonkheer H. graaf van Hagenaar tot Haaglanden"
Hoe komen we daartoe? Kan één persoon tegelijk een titel en een predikaat hebben?

**Comment by CathyDingemanse** [comment]
Ja, zie ook https://nl.wikipedia.org/wiki/Predicaat_(titel)

**Comment by gertjanvanderkooij** [comment]
> In LO GBA wordt alleen gesproken over voornamen. Moeten de voorletters worden afgeleid uit de voornamen? Zo ja hoe? (wordt bijvoorbeeld Theo afgekort naar "T." of "Th."? hoe wordt dubbele naam naar initialen omgezet, bijvoorbeeld Anne-Fleur wordt "A. F." of "AF." of "A.-F." of "A-F."?)

Ja, de voornamen moeten worden afgeleid. Er is mij geen officiële norm bekend voor voornamen; nu worden in GBA-systemen (bv. voor de vervaardiging van uittreksels oid) de volgende afleidingsregels toegepast:

1) Alleen de voornamen gescheiden door een spatie leiden tot een voorletter. Jouw voorbeeld 'Anne-Fleur' krijgt als voorletter dus de 'A'; 'Anne Fleur' zonder verbindingsstreepje wordt 'A.F..' 

2) Voor het bepalen van de voorletter wordt de in gebruik zijnde tekenset GBA is van toepassing (zie LO GBA 3.10 II Teletex (blz. 390). Sinds LO 3.10 is hierin nu ook de vertaling naar de UTF8-codering opgenomen. Zie ook de opmerking dat de 'Hollandse IJ' niet als apart teken in de GBA wordt ondersteund. Ijsbrand leidt dus tot voorletter 'I'. Dit in tegenstelling tot wat hierover op Wikipedia wordt vermeld [https://nl.wikipedia.org/wiki/Voorletter]

3) Er gelden geen afwijkende regels voor namen als 'Theodorus', 'Christiaan' oid. Als voorletter wordt hier alleen de eerste letter van de voornaam genomen; dus resp. de 'T' end e 'C'. Dit in tegenstelling tot wat hierover op Wikipedia wordt vermeld. 

4) In het afgeleide veld worden de voorletters opgenomen gescheiden door een punt; vulling van de rubriek Voornamen met 'Frank Simon Jos-Willem' leidt dus tot de volgende inhoud van de afgeleide rubriek Voorletters: 'F.S.J.'

5) Indien de rubriek Voornamen is gevuld met de standaardwaarde '.' (punt), dan wordt geen extra (scheidings)punt toegevoegd; de inhoud van de rubriek Voorletters is na afleiding dan '.'  

Ik nodig anderen uit tot aanvulling/aanscherping van deze afleidingsregels.

**Comment by fsamwel** [comment]
> Ja, kennelijk wel, zie ook https://nl.wikipedia.org/wiki/Predicaat_(titel). Het voorbeeld met de jonkheer is idd niet juist.

Welk voorbeeld met de jonkheer bedoel je dat niet juist is? Het voorbeeld in het [algoritme](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen/blob/master/api-specificatie/Aanschijfwijze%20opstellen.md) of een voorbeeld in bovenstaande tabel?

**Comment by fsamwel** [comment]
Het model laat nu maar één adelijke titel/predicaat toe, dus wordt het hebben van zowel een predicaat als een adelijke titel nu niet ondersteund, tenzij het automatisch uit de adelijke titel moet worden afgeleid.

Zoals het op [wikipedia](
https://nl.wikipedia.org/wiki/Predicaat_(titel)) staat:
> Adel met als titel prins, hertog, groothertog of aartshertog voert tevens een predicaat
Dit is nu niet uitgewerkt in het beschreven algoritme (en ook niet op de wikipediapagina zelf). Welk predicaat wordt hiervoor gezet?

**Comment by CathyDingemanse** [comment]
> Klopt onderstaande tabel als uitwerking/interpretatie van het algoritme?
> met:
> 
> * VL = voorletters
> * VV = voorvoegselGeslachtsnaam
> * GN = geslachtsnaam
> * VP = voorvoegselGeslachtsnaam partner
> * GP = geslachtsnaam partner
> * AT = adelijke titel
> * PK = predikaat
> ..........
>

Mooi overzicht! Superduidelijk, en met een paar toevoegingen helemaal BDD :-).
Voor zover ik kan beoordelen klopt dit, m.u.v. 
>
PK | - | V | PK VL VP GP-VV GN | Jonkheer H. van der Veen-van Hoogh
>

Want:
Niet-adellijke echtgenotes van ridders en jonkheren voeren geen adellijk equivalent.
zie https://nl.wikipedia.org/wiki/Titre_de_courtoisie 
Misschien ook de riddertitel apart in het overzicht opnemen

**Comment by CathyDingemanse** [comment]
> > Ja, kennelijk wel
> 
> Het model laat nu maar één adelijke titel/predicaat toe, dus wordt het hebben van zowel een predicaat als een adelijke titel nu niet ondersteund, tenzij het automatisch uit de adelijke titel moet worden afgeleid.
> 
> Zoals het op [wikipedia](https://nl.wikipedia.org/wiki/Predicaat_(titel)) staat:
> 
> > Adel met als titel prins, hertog, groothertog of aartshertog voert tevens een predicaat
> 
> Dit is nu niet uitgewerkt in het beschreven algoritme (en ook niet op de wikipediapagina zelf). Welk predicaat wordt hiervoor gezet?
>
De Hoge Raad van Adel in Nederland noemt acht predicaten:
Zijne Majesteit / Hare Majesteit
Zijne Koninklijke Hoogheid / Hare Koninklijke Hoogheid
Zijne Hoogheid / Hare Hoogheid
jonkheer/ jonkvrouw

M.u.v. jonkeheer/jonkvrouw wordt deze gevoerd door getitelde adel. Dit is dan onderdeel van de aanspreekvorm 
https://nl.wikipedia.org/wiki/Aanspreekvorm 
Deze aanspreekvorm is geen onderdeel van de BRP. Als je deze toch wilt hanteren, moet je dat eigenlijk ook doen voor het hoger onderwijs, geestelijkheid etc. Ik stel voor om deze buiten scope te plaatsen.

**Comment by fsamwel** [comment]
Conclusie: we hanteren geen combinatie van predicaat en adelijke titel.

**Comment by fsamwel** [comment]
> PK | - | V | PK VL VP GP-VV GN | Jonkheer H. van der Veen-van Hoogh
> Want:
> Niet-adellijke echtgenotes van ridders en jonkheren voeren geen adellijk equivalent.
> zie https://nl.wikipedia.org/wiki/Titre_de_courtoisie

De hier bedoelde situatie is dat de persoon zelf een predicaat heeft (1e kolom), de partner heeft geen titel/predicaat (2e kolom). Dit gaat dus niet over een hoffelijkheidstitel, maar een eigen predicaat.

Die situatie zit in de tabel in:
- | PK | V | VL VP GP-VV GN | A. van Hoogh-van der
Daarin is het predicaat van de partner niet overgenomen.

Of begrijp ik je verkeerd? Gebruikt iemand zijn/haar eigen predicaat niet wanneer deze de naam van de partner voert (al dan niet gevolgd door de eigen naam, Aanduiding Aanschrijving P of V)?

**Comment by fsamwel** [comment]
>      Gebruikt iemand zijn/haar eigen predicaat niet wanneer deze de naam van de partner voert (al dan niet gevolgd door de eigen naam, Aanduiding Aanschrijving P of V)?
> klopt!

Dan moet dit worden toegevoegd aan de beschrijving, want daar haal ik deze regel niet uit.
In de tabel wordt het dan:
PK | - | V | PK VL VP GP-VV GN | H. van der Veen-van Hoogh

**Comment by fsamwel** [comment]
Hetzelfde geldt dan -neem ik aan- voor deze situatie in de tabel waarbij het predicaat van de persoon niet wordt getoond:

PK | - | P | VL VP GP | H. van der Veen

**Comment by CathyDingemanse** [comment]
> Conclusie: we hanteren geen combinatie van predicaat en adelijke titel.

klopt
