### ISSUE TITLE
Endpoint "ingeschreven personen" hernoemen naar "personen"

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#862]
**Beschrijf de verbetering**
Een heldere beschrijving van wat we zouden kunnen verbeteren, waarom deze verbetering van belang is en evt. hoe we dit zouden kunnen realiseren.

**Comment by JohanBoer** [comment]
Wat is de overweging om deze endpoints te hernoemen ? We ontsluiten hier de BRP en de RNI. Met een endpoint personen zou je de indruk kunnen wekken dat daar ook personen opgevraagd kunnen worden die niet in de BRP of in de RNI voor kunnen komen. 

Of is dat juist de extra functionaliteit die je mogelijk wilt maken op dit endpoint (wat zou kunnen als je niet meer de BSN, maar bv. een UUID als identificerend item opneemt ). Uit welke registratie komen die persoonsgegevens dan  ?

Ik heb geen discussie voorbij horen komen waarin bovenstaande is besproken of voorgesteld. De gewenste heldere beschrijving kan dus niet van mij komen omdat ik blijkbaar wat achtergrond-infromatie mis

**Comment by MelvLee** [comment]
Ik weet niet meer wat de precieze reden was toen dit is besloten, maar ik kan mij wel voorstellen dat ingeschrevenpersoon als naam/endpoint wel te specifiek kan zijn. Is een persoon die is geëmigreerd (als ik immigreer moet ik mij uitschrijven) of is overleden ook een ingeschreven persoon?, Deze staan toch ook in de BRP? Of betekent ingeschreven zijn dat de persoon staat in de BRP en RNI?

**Comment by JohanBoer** [comment]
Goede overweging. Die persoon staat inderdaad in de BRP als ingeschreven persoon. Weliswaar niet actueel, maar wel in de historie.  De kern van het bevragen van de BRP en de RNI is dat je mensen kan bevragen die daar zijn of waren ingeschreven. 

Bij een endpoint "Personen" zou ik verwachten dat ook een buitenlands persoon als eigenaar van een Nederlands WOZ-object relevant is voor de gemeente en dus daar opvraagbaar moet zijn. 

Het wijzigen kan altijd maar, zoals eerder gezegd,  de argumentatie voor deze wijziging heb ik niet voorbij horen komen en ik ben er niet van overtuigd dat dit een verbetering is.
@CathyDingemanse @fsamwel @melsk-r  Kennen jullie de argumentatie ? Hoe zien jullie dit ?
