### ISSUE TITLE
verwijderen gegenereerde code voor consumers

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#863]
Dit beheren we niet langer, aangezien consumers vaak net andere versies hebben e.d. 

**Beschrijf de verbetering**
Een heldere beschrijving van wat we zouden kunnen verbeteren, waarom deze verbetering van belang is en evt. hoe we dit zouden kunnen realiseren.

**Comment by melsk-r** [comment]
@CathyDingemanse De folder met de gegenereerde code had ik al eerder verwijderd. Ik zie alleen dat in deze repo onder 'Actions' nog steeds de action 'generate-sdks' staat.

@MelvLee Kan jij dat verklaren? Ik heb in de folder '.github/workflows/' het yaml bestand 'generate-sdks.yml' verwijderd en bij de andere repo's (bijv. BRK) was dat voldoende om deze action te laten verdwijnen.
Overigens heb ik in package.json nog even wat scripts m.b.t. codegeneratie laten staan (die wilde ik op een later moment verwijderen) maar dat heb ik in de andere repo's ook gedaan.

Kan jij trouwens ook uitleggen waarom ik in een aantal repo's onder 'Actions' nu ook ineens de action 'pages-build-deployment' zie staan. Die stond daar volgens mij ook niet eerder.

**Comment by MelvLee** [comment]
> @MelvLee Kan jij dat verklaren? Ik heb in de folder '.github/workflows/' het yaml bestand 'generate-sdks.yml' verwijderd en bij de andere repo's (bijv. BRK) was dat voldoende om deze action te laten verdwijnen. Overigens heb ik in package.json nog even wat scripts m.b.t. codegeneratie laten staan (die wilde ik op een later moment verwijderen) maar dat heb ik in de andere repo's ook gedaan.

Ik denk dat dit komt omdat er nog andere branches zijn waar de generate-sdks.yml nog zit. Bijv. de a_nummer branch. Ik denk dat als alle branches geen copy meer hebben van dit bestand dat de action ook wordt verwijderd.

> 
> Kan jij trouwens ook uitleggen waarom ik in een aantal repo's onder 'Actions' nu ook ineens de action 'pages-build-deployment' zie staan. Die stond daar volgens mij ook niet eerder.

Dit is de workflow waarmee GitHub Pages wordt gepubliceerd. Zie [artikel](https://github.blog/changelog/2021-12-16-github-pages-using-github-actions-for-builds-and-deployments-for-public-repositories/) van GitHub hierover

**Comment by melsk-r** [comment]
> Dit is de workflow waarmee GitHub Pages wordt gepubliceerd. Zie [artikel](https://github.blog/changelog/2021-12-16-github-pages-using-github-actions-for-builds-and-deployments-for-public-repositories/) van GitHub hierover

Klopt maar die workflow staat [hier](https://github.com/VNG-Realisatie/jekyll-theme-haal-centraal/tree/master/.github/workflows) gedefinieerd niet in deze repository, ook niet in de andere branches.

**Comment by MelvLee** [comment]
> > Dit is de workflow waarmee GitHub Pages wordt gepubliceerd. Zie [artikel](https://github.blog/changelog/2021-12-16-github-pages-using-github-actions-for-builds-and-deployments-for-public-repositories/) van GitHub hierover
> 
> Klopt maar die workflow staat [hier](https://github.com/VNG-Realisatie/jekyll-theme-haal-centraal/tree/master/.github/workflows) gedefinieerd niet in deze repository, ook niet in de andere branches.

Dat is niet zo. De GitHub Pages workflow van elke repo wordt geënabled via de GitHub Pages setting. De gh-pages-rebuild.yml in de jekyll-theme-haal-centraal repo is bedoeld om in 1 keer de GitHub Pages workflow van alle Haal Centraal repo's te triggeren. Deze workflow is destijds geïmplementeerd omdat:
1. het (nog) niet mogelijk is om de GitHub Pages workflow van een repo handmatig op te starten. Deze wordt alleen getriggered door commits naar de docs (geconfigureerd in de GitHub Pages setting pagina) folder
2. je dit niet handmatig voor alle Haal Centraal repo's wil doen als er een aanpassing is gemaakt in de template in de jekyll-theme-haal-centraal repo

**Comment by MelvLee** [comment]
> > Deze workflow is destijds geïmplementeerd omdat:
> > 
> > 1. het (nog) niet mogelijk is om de GitHub Pages workflow van een repo handmatig op te starten. Deze wordt alleen getriggered door commits naar de docs (geconfigureerd in de GitHub Pages setting pagina) folder
> > 2. je dit niet handmatig voor alle Haal Centraal repo's wil doen als er een aanpassing is gemaakt in de template in de jekyll-theme-haal-centraal repo
> 
> Klopt helemaal.
> 
> > Dat is niet zo. De GitHub Pages workflow van elke repo wordt geënabled via de GitHub Pages setting. De gh-pages-rebuild.yml in de jekyll-theme-haal-centraal repo is bedoeld om in 1 keer de GitHub Pages workflow van alle Haal Centraal repo's te triggeren.
> 
> Maar dan zou je toch zeggen dat ik de workflow in de folder '.github/workflows' terug zou moeten kunnen vinden, dat is echter niet zo. Daarnaast is het vreemd dat ik betreffende action 'pages-build-deployment' alleen in deze repo zie. Je zou verwachten dat ik hem dan ook in de andere repo's zou moeten zien.

Ik zie de action nu ook bij BAG, BRK, WOZ  en BRP Bewoning. Ik heb niet meer verder gekeken bij de andere Haal Centraal repo's, maar ik verwacht dat ze daar ook te zien zijn of binnen zeer korte tijd. Ik weet het niet zeker, maar ik denk dat hier een deployment strategie achter zit. Het lijkt mij niet handig en is waarschijnlijk ook niet te realiseren in zo'n groot systeem als GitHub dat nieuwe functionaliteit met een big bang en tegelijk op alle servers wordt gedeployed.

Dat je de definitie file niet in de `.github/workflows' folder zie, zal ook onderdeel zijn van GitHub's deployment strategie. In de GitHub artikel staat het volgende `... in the future this will enable us to give you the ability to fully customize your pages build and deployment workflow...`. Op dit moment is het dus nog niet mogelijk om die workflow aan te passen. Als GitHub het workflow definition bestand nu al toevoegt aan de worflows folder, dan is de workflow wel aan te passen en is die ability nu beschikbaar en niet in de toekomst. Ik denk dat dit dus de reden is dat het bestand nog niet zichtbaar is.

**Comment by melsk-r** [comment]
Ok, dat klinkt wel plausibel. Ik zie inderdaad dat er nu meer repo's zijn waar deze action aanwezig is.
