### ISSUE TITLE
BRP bevragen wordt BRP-Personen-Bevragen

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#886]
**Beschrijf de verbetering**
BRP bevragen is eigenlijk de BRP Persoon API. Kunnen we BRP Bevragen API als verzamelnaam hanteren en de BRP bevragen API veranderen in BRP Persoon? Meenemen in v2.0 (breaking).

**Comment by fsamwel** [comment]
@CathyDingemanse twijfel je hier nog over of is dit een beslissing? Ik ben het er trouwens helemaal mee eens

**Comment by CathyDingemanse** [comment]
@fsamwel, nee ik twijfel niet. Graag doorvoeren! @JohanBoer kun jij daar voor zorgen? Dank!

**Comment by JohanBoer** [comment]
@CathyDingemanse Wil je dat alleen in de API-naam doorgevoerd zien of wil je ook de repository hernoemen ?

**Comment by fsamwel** [comment]
@JohanBoer ik denk ook de repo. Met BRP-bevragen bedoelen we alle BRP API's samen (persoon, historie, reisdocumenten, bewoning, tabellen). Daarnaar wordt verwezen in verschillende documenten voor het aansluiten op deze API's. het is dan verwarrend wanneer één van die API's, of één van de repositories die naam heeft.

**Comment by CathyDingemanse** [comment]
> @CathyDingemanse Wil je dat alleen in de API-naam doorgevoerd zien of wil je ook de repository hernoemen ?

@Johan, Idd ook de repo. Frank heeft het hierboven goed verwoord, BRP-bevragen is een verzamelnaam.

**Comment by JohanBoer** [comment]
De naam van de API is Bevragen Ingeschreven Persoon. (En als we #868 doorvoeren dan is het Bevragen Persoon). In de specificatie komt de term BRP-bevragen dus alleen voor als repository verwijzing. 
Daarnaast is onze documentatie doorspekt met de term BRP-bevragen (en waarschijnlijk met wisselende betekenis. 

Dit hernoemen (en de documentatie op orde brengen) is nogal een klus, maar die staat volgens mij de acties van Melvin met de stap naar het polymorfisme niet in de weg. Ik stel voor die twee parallel uit te voeren.

**Comment by JohanBoer** [comment]
@CathyDingemanse : De API-naam die nu in de specificatie is gebruikt is Bevragen Personen (dus zonder BRP prefix) . In deze issue wordt er gesproken over BRP-Persoon. Verder zijn de varianten BRP-Bevragen-Persoon en BRP-Persoon-Bevragen voorbij gekomen. 

Welke gaat het worden ?   Dan kan ik dat consistent doorvoeren.
