### ISSUE TITLE
Als PO wil ik geen Personal Identifiable Information in de URI

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#887]
...zodat privacy gevoelige en tot personen herleidbare  informatie niet in (access) logs (van client en server) terecht kan komen
EN door onbevoegden kan worden ingezien.

_Threat type_
Information Disclosure: ongeautoriseerde toegang tot data 

_Threat:_
Zoeken van personen met PII (Personal Indentifiable Information)
Voor het zoeken van personen wordt een GET requests gebruikt, waardoor identificerende gegevens in de url komen te staan. Bij de volgende zoek paden is dit het geval:
* geboortedatum en geslachtsnaam
* gemeentevaninschrijving en geslachtsnaam
* één of meerdere burgerservicenummers

_Countermeasures:_
gebruik POST ipv GET zodat de zoek parameters in de body van de request kunnen worden gestopt.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by fsamwel** [comment]
opgelost. alle PII worden alleen in POST requestbody opgegeven. endpoint met GET en PII in queryparameter of pathparameter zijn vervallen in v2.0
