### ISSUE TITLE
Documentatie van gebruik waardelijsten toevoegen

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#890]
Voeg per waardelijst die een enum vervangt de documentatie welke waardelijst dat dan is en eventueel een korte toelichting op de betekenis van het element.

**Comment by JohanBoer** [comment]
Gaan we ook voorschrijven hoe de tabellen genoemd worden die nu als landelijke tabel beschikbaar zijn.
Ik weet niet wat de uiteindelijke tabelnaam van bv "Adellijke Titel/Predikaat" straks gaat worden. Ik kan daarop vooruitlopen, maar als er andere keuzes worden gemaakt klopt deze documentatie niet meer.

**Comment by fsamwel** [comment]
> Gaan we ook voorschrijven hoe de tabellen genoemd worden die nu als landelijke tabel beschikbaar zijn.

Dit zijn de landelijke tabellen zoals die er nu zijn (op https://www.haalcentraal.nl/haalcentraal/api/landelijke_tabellen/tabellen)
```
        {
            "tabelidentificatie": "Nationaliteiten",
            "omschrijving": "Nationaliteiten"
        },
        {
            "tabelidentificatie": "Gemeenten",
            "omschrijving": "Gemeenten"
        },
        {
            "tabelidentificatie": "Landen",
            "omschrijving": "Landen"
        },
        {
            "tabelidentificatie": "Reden_Beeindigen_Huwelijk",
            "omschrijving": "Reden ontbinding nietigverklaring huwelijk geregistreerd partnerschap"
        },
        {
            "tabelidentificatie": "Reden_Nationaliteit",
            "omschrijving": "Reden opnemen - beeindigen Nationaliteit"
        },
        {
            "tabelidentificatie": "Nederlands_Reisdocument",
            "omschrijving": "Nederlands Reisdocument"
        },
        {
            "tabelidentificatie": "Verblijfstitel",
            "omschrijving": "Verblijfstitel"
        }
```

**Comment by fsamwel** [comment]
zie P.R. #893
