### ISSUE TITLE
Als PO wil ik dat gemeenten request parameters kunnen gebruiken om responses te beperken conform de rechten van afnemers

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#902]
...zodat aan het criterium van dataminimalisatie (bij de bron) kan worden voldaan.

_Threat type:_
Information Disclosure

_Threat:_
de response bevat personen of PII (Personal Identifiable Information) waarvoor men niet is geautoriseerd.

_Countermeasure:_
Input parameters aan het request toevoegen waarmee de response kan worden beperkt conform de rechten van afnemers.
Intermediate endpoints/proxy's van gemeenten kunnen deze queryparameter gebruiken om de response te beperken conform de rechten van hun afnemers.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by melsk-r** [comment]
Enkele vraagjes:
1. Waarom worden hier specifiek intermediate endpoints/proxy's van gemeenten genoemd als voorzieningen die de response kunnen beperken? Dat kan het endpoint zelf toch ook al doen als de parameters in het request zitten.
2. Verder ben ik benieuwd naar de query parameters waar we aan denken en de waarden die deze kunnen hebben i.r.t. issue #887.

**Comment by fsamwel** [comment]
Waar hebben we het hier over met "Input parameters aan het request toevoegen waarmee de response kan worden beperkt conform de rechten van afnemers."?
- beperken van geleverde soorten gegevens in de response (oplossing: fields parameter)
- beperken van gevonden resources in de response (oplossing bijvoorbeeld gemeenteVanInschrijving parameter)

**Comment by fsamwel** [comment]
dit is een epic. #903 en #904 zijn de user stories die hieronder vallen

**Comment by fsamwel** [comment]
gesloten want beide user stories zijn in v2.0 toegevoegd
