### ISSUE TITLE
Als PO wil ik dat gemeenten de fields parameter kunnen gebruiken om de gegevensset in de response te beperken conform de autorisatie van afnemers

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#903]
...zodat door afnemers aan het criterium van dataminimalisatie bij de bron kan worden voldaan
EN afnemers gedwongen worden de response te beperken tot wat men op het moment van bevragen nodig heeft 
EN gemeenten de mogelijkheid wordt geboden om de gegevensset in de response te beperken conform de rechten van afnemers

_Threat type:_
Information Disclosure

_Threat:_
de response bevat PII (Personal Identifiable Information) waarvoor men niet is geautoriseerd.

_Countermeasure:_
De fields parameter wordt een verplichte input parameter.
Intermediate endpoints/proxy's van gemeenten kunnen deze parameter gebruiken om de response te beperken conform de autorisatie van de vragende gemeentelijke afnemer.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by melsk-r** [comment]
Waarom worden hier specifiek intermediate endpoints/proxy's van gemeenten genoemd als voorzieningen die de response kunnen beperken? Dat kan het endpoint zelf toch ook al doen als de parameters in het request zitten.

**Comment by fsamwel** [comment]
> Waarom worden hier specifiek intermediate endpoints/proxy's van gemeenten genoemd als voorzieningen die de response kunnen beperken? Dat kan het endpoint zelf toch ook al doen als de parameters in het request zitten.

Op basis van gebruikte parameters mag de provider niet bepalen welke velden geleverd mogen worden, de parameters filteren alleen welke resources (personen) geleverd worden. Daarvoor is de fields parameter.

Het gaat hier om gemeenten als afnemer en die moeten heel veel verschillende taken en processen uitvoeren met heel verschillende autorisaties. De autorisaties zijn voor gemeenten daarom heel breed (uitgebreid) en voor binnengemeentelijke personen zelfs 100%. Het gaat hier dus niet om de autorisaties van de gemeente als afnemer, maar om de beperktere autorisaties van een client (proces) binnen de gemeente. De provider (RvIG) kent die niet, een intermediate endpoint/proxy of de client zelf kent die.

**Comment by melsk-r** [comment]
> Op basis van gebruikte parameters mag de provider niet bepalen welke velden geleverd mogen worden, de parameters filteren alleen welke resources (personen) geleverd worden. Daarvoor is de fields parameter.

Die begrijp ik, het gaat mij ook alleen om die fields parameters. Mijn gedachte was dat als de fields parameters aan de provider geleverd worden dat de provider al niet meer aanlevert dan gevraagd.

> Het gaat hier om gemeenten als afnemer en die moeten heel veel verschillende taken en processen uitvoeren met heel verschillende autorisaties. De autorisaties zijn voor gemeenten daarom heel breed (uitgebreid) en voor binnengemeentelijke personen zelfs 100%. Het gaat hier dus niet om de autorisaties van de gemeente als afnemer, maar om de beperktere autorisaties van een client (proces) binnen de gemeente. 

Deze begrijp ik ook. Een gemeente heeft binnen haar organisatie meerdere medewerkers die als afnemer van gegevens fungeren. Elke medewerker heeft echter een andere verantwoordelijkheid en mag op basis van die verantwoordelijkheid bepaalde gegevens inzien. Een provider weet niets van die binnengemeentelijke autorisaties en levert gewoon alle gegevens die hij aan een gemeente mag leveren (100% in geval van de eigen inwoners, minder in geval van inwoners van andere gemeenten).

> De provider (RvIG) kent die niet, een intermediate endpoint/proxy of de client zelf kent die.

De provider levert dus 100% van de gegevens (van een inwoner) aan een intermediate endpoint/proxy en deze draagt zorg voor het filteren. Maar als een intermediate endpoint/proxy weet welke gegevens een afnemer wel of niet mag zien dan kan hij op die basis toch al filteren waarom heeft hij de query parameter fields dan nog nodig?
