### ISSUE TITLE
Als PO wil ik geen Uniform Resource Identifier met een BSN

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#910]
...zodat geen privacy gevoelige en tot personen herleidbare  informatie in (access) logs (van client en server) terecht komt 
En door onbevoegden kan worden ingezien.

_Threat type_
Information Disclosure: ongeautoriseerde toegang tot data 

_Threat:_ 
Raadplegen van een persoon met Burgerservicenummer
Voor het raadplegen van een persoon wordt het burgerservicenummer gebruikt als pad parameter waardoor een identificerend gegeven in de url komt te staan.
Uit de audit PWC:  "_Tot slot wordt (hoewel geen bijzonder categorie persoonsgegeven) conform de Uitvoeringswet AVG aan het burgerservicenummer wel een soortgelijke gevoeligheid toegekend._"

_Countermeasures:_
1. Vervang de BSN door een UUID. Voordeel is zijn dat we onze consumers de mogelijkheid bieden om niet het BSN op te slaan maar een UUID. Ander voordeel is dat we discoverability kunnen handhaven. Dit voordeel is binnen dezelfde API echter marginaal (ouders, partners, kinderen). 
2. Verwijder de GET endpoint en gebruik het POST zoek-endpoint ipv GET zodat het burgerservicenummer in de body van het request kan worden gestopt. Maak het mogelijk om bij dit zoek-type in plaats van de "persoon beperkt" de hele persoon te retourneren. Voordeel hiervan is dat consumer niet een extra request hoeft te doen door een bij hem/haar bekend persoon "te zoeken met BSN" en vervolgens "te raadplegen met UUID". Belangrijk bijkomend voordeel is dat RvIG niet voorafgaand aan de implementatie een nieuw nummer aan de GBA-V hoeft toe te voegen.

Gekozen is voor optie 2. Het GET endpoint met UUID kan altijd op een later moment evolvable worden toegevoegd. Bijvoorbeeld door consumers die hiervan graag gebruik willen maken in de request header te laten aangeven van het nieuwe endpoint gebruik te willen maken. Consumers die geen toegevoegde waarde zien, blijven het POST endpoint gebruiken. 

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by gertjanvanderkooij** [comment]
Ik lees "Gekozen is voor optie 1" ... er is toch gekozen voor de POST-constructie (optie 2)?

**Comment by melsk-r** [comment]
Issue #861 en issue #887 zijn hiermee gerelateerd. Uit #887 maak ik op dat idd een POST willen gaan gebruiken. In #861 staat nog een GET genoemd maar ik neem aan dat dat deel van #861 komt te vervallen. Wat overblijft is dat we in een POST geen bsn op gaan nemen in de requestbody of zie ik dat verkeerd?

**Comment by fsamwel** [comment]
> Dit voordeel is binnen dezelfde API echter marginaal (ouders, partners, kinderen).

En daarnaast binnen de set aan BRP API's ook: verwijzen van een persoon naar BRP historie, of vanuit BRP bewoning naar BRP bevragen (ophalen gegevens van een bewoner).

**Comment by fsamwel** [comment]
> Voordeel hiervan is dat consumer niet een extra request hoeft te doen door een bij hem/haar bekend persoon "te zoeken met BSN" en vervolgens "te raadplegen met UUID". Belangrijk bijkomend voordeel is dat RvIG niet voorafgaand aan de implementatie een nieuw nummer aan de GBA-V hoeft toe te voegen.

Ik zie ook als voordeel dat in het hele stelsel van basisregistraties het burgerservicenummer wordt gebruikt als identificerend gegeven. En daardoor ook in procesapplicaties die iets met persoonsgegevens doen. Kiezen voor een UUID in de URI voor een persoon zou grote (dure) consequenties hebben voor alle basisregistraties die iets met personen doen (bijv. BRK, WOZ en HR). 
Is dit een voordeel voor voor optie 2 of een nadeel van optie 1?

"Nadeel" van optie 2 is dat raadplegen van personen in de API niet meer eenvoudig/standaard kan op een RESTful manier, dus met een GET request.

Hiermee komt de BRP API ook verder van de andere Haal Centraal API's te staan. De consistentie in ontwerp keuzes tussen de BRP API en andere Haal Centraal API's neemt hier sterk mee af:
- We laten hiermee REST als API stijl vallen en bewegen meer richting een GraphQL-like API stijl.
- We laten HAL-json los, die heeft geen zin wanneer er geen GET mogelijk is in de BRP API's, zou alleen nog voor de link naar adressen (BAG API) relevant zijn.

**Comment by fsamwel** [comment]
> Wat overblijft is dat we in een POST geen bsn op gaan nemen in de requestbody of zie ik dat verkeerd?

@melsk-r juist wel een bsn in een POST requestbody

**Comment by fsamwel** [comment]
de endpoints met burgerservicenummer in de uri zijn verwijderd. alle privacygevoelige persoonsgegevens worden voor zoeken in de requestbody (POST) opgenomen
