### ISSUE TITLE
Als PO wil ik een strakkere specificatie van validatieregels voor input parameters

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#911]
...zodat provider input parameters beter kan valideren ( beter inputvalidatie)
EN het injecteren van  SQL of scripts in de request of het verhogen van de load op de server moeilijker/ bij voorkeur onmogelijk wordt.

_Threat type:_
* Spoofing. Voordoen als iemand anders
* Tampering. Modificeren van data (in transit)
* Repudiation. Verwijderen van audit log
* Information Disclosure. Toegang tot data waarvoor niet is geautoriseerd
* Denial of Service. Beperken toegang tot data
* Elevation of Privilege. Toegang tot data waarvoor niet is geautoriseerd

_Threat:_
Te ruim gespecificeerde validatieregels voor input parameters
De meeste string parameters (v1.3) accepteren ook niet-alfanummerieke karakters. Nummers als string parameters accepteren ook niet-nummerieke karakters. Dit maakt het mogelijk om SQL of scripts te injecteren in de request of om de load op de server te verhogen.
Voorbeelden:
* de naam__geslachtsnaam query parameter is gespecificeerd als een string van maximaal 400 karakters
* de verblijfplaats__nummeraanduidingIdentificatie query parameter is gespecificeerd als een string van maximaal 16 karakters

_Countermeasures:_
Validatieregels strakker specificeren. Voorbeelden:
* naam__geslachtsnaam query parameter specificeren als een string van minimaal 3 en maximaal 100 van alleen de volgende karakters: a-zA-Z'- en diakrieten
* verblijfplaats__nummeraanduidingIdentificatie queryparameter specificeren als een string van precies 16 cijfers

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by fsamwel** [comment]
> naam__geslachtsnaam query parameter specificeren als een string van minimaal 3 en maximaal 100 van alleen de volgende karakters: a-zA-Z'- en diakrieten

Wat is de toegevoegde waarde van minimaal 3 voor deze thread? Hiermee is deze parameter niet meer te gebruiken voor geslachtsnamen van 2 letters. Ik begrijp niet hoe een invoer van 1 of 2 letters in een parameter risicovol is, daar past in ieder geval een script in.

**Comment by fsamwel** [comment]
is doorgevoerd op de parameters in de request body
