### ISSUE TITLE
Als PO wil ik dat Rate Limiting headers worden opgenomen in de definitie

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#912]
...zodat de kans op Denial of Service wordt geminimaliseerd.

Rate Limiting headers zijn gespecificeerd in de Haal Centraal Common:
https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/master/api-specificatie/common.yaml#L43  

_Threat type:_
Denial of Service. Beperken toegang tot data

_Threat:_
Geen rate limit opgenomen in de specificatie

_Countermeasures:_
Rate limiting opnemen in de specificaties

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by CathyDingemanse** [comment]
In welke versie is dit toegevoegd (in HC common yaml?)

**Comment by melsk-r** [comment]
Al meteen in versie 1.0.0.

**Comment by JohanBoer** [comment]
Rate limiting is opgenomen in de V2.0 versie
