### ISSUE TITLE
Als PO wil ik een strakkere specificatie van de validatieregels voor de response payload (outputvalidatie)

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#913]
...zodat de client de output beter kan valideren (betere outputvalidatie)
EN de kans op het hacken van de client als gevolg van een server hack kleiner wordt.

_Threat type:_
* Spoofing. Voordoen als iemand anders
* Tampering. Modificeren van data (in transit)
* Repudiation. Verwijderen van audit log
* Information Disclosure. Toegang tot data waarvoor niet is geautoriseerd
* Denial of Service. Beperken toegang tot data
* Elevation of Privilege. Toegang tot data waarvoor niet is geautoriseerd

_Threat:_
Te ruim gespecificeerde validatieregels voor eigenschappen van personen in de payload
Veel definities zijn niet-alfanummeriek. Nummers zijn soms ook niet-nummerieke karakters. Voorbeelden:
- de naam.geslachtsnaam is gespecificeerd als een string van maximaal 400 karakters
- de verblijfplaats.nummeraanduidingIdentificatie is gespecificeerd als een string van maximaal 16 karakters
Dit maakt het mogelijk om SQL of scripts te injecteren in de payload van de response. Dit maakt bijvoorbeeld cross site scripting mogelijk, waarbij de client naar een andere site wordt geleid door bijvoorbeeld javascript in strings te accepteren. 

_Countermeasures_
De specificatie moet clients de mogelijkheid bieden om de output zo veel mogelijk te valideren, door de validatieregels voor de response strakker te specificeren. Voorbeeld:
- naam.geslachtsnaam specificeren als een string van minimaal 3 en maximaal 100 van alleen de volgende karakters: a-zA-Z'- en diakrieten
- verblijfplaats.nummeraanduidingIdentificatie parameter specificeren als een string van precies 16 cijfers.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by fsamwel** [comment]
Deze user story is m.i. een gevalletje uitruilen tight coupling tegen security risico. We kunnen het antwoord strak specificeren door in het informatiemodel van de bron te kijken hoe dit gespecificeerd wordt. Zodra er nu iets in de bron wijzigt, heeft dit direct breaking changes tot gevolg in de API.
Bijvoorbeeld wanneer de maximale lengte van geslachtsnaam vergroot wordt van 400 naar 500.

In het voorbeeld van de nummeraanduidingIdentificatie is dat ook nog tight coupling met een ander domein (BAG).

**Comment by fsamwel** [comment]
In de tekst worden voorbeelden naam__geslachtsnaam en verblijfplaats__nummeraanduidingIdentificatie genoemd. Dit zijn requestparameters, geen responseproperties. Dan zou ik ze naam.geslachtsnaam en verblijfplaats.nummeraanduidingIdentificatie noemen.

> naam__geslachtsnaam specificeren als een string van minimaal 3 en maximaal 100 van alleen de volgende karakters: a-zA-Z'- en diakrieten

Dit betekent dat de geslachtsnaam met 2 letters "Os" niet geleverd mag worden? Dit is strenger dan het LO GBA . 

En in de maximale lengte is het weer minder streng. Het LO zegt: Lengte 1-200

**Comment by fsamwel** [comment]
Kunnen we de string specificaties op een manier doen die het risico van tight coupling/breaking changes minimaliseert?

Bijvoorbeeld niet een veld verblijfplaats.nummeraanduidingIdentificatie, maar verblijfplaats.adresIdentificatie, en die een pattern geven die alleen a-zA-Z0-9 en - toestaat? (dan zou een UUID er ook nog in passen, maar geen enkel script). 

Gelukkig hebben we in de BRP geen enkel toelichtsveld (vrije tekst over meerdere regels), dus we kunnen zonder specifiek te zijn over maximale lengte of alleen cijfers toch de veiligheid vergroten (scripting en injection voorkomen) met alleen een beperking op tekens (a-zA-Z0-9' - spatie en diacrieten).

**Comment by fsamwel** [comment]
Hoe staat de wijziging die we gedaan hebben op het vervangen van enumeraties (ultieme vorm van specificatie mogelijke waarden) door waardetabellen (vrije code/omschrijving combinatie)? Dat hebben we gedaan t.b.v. evolvability, maar is veel minder strakke specificatie. Ik verwacht niet dat gebruikers elke waarde gaan valideren in de BRP tabellen API.

**Comment by CathyDingemanse** [comment]
> Deze user story is m.i. een gevalletje uitruilen tight coupling tegen security risico. We kunnen het antwoord strak specificeren door in het informatiemodel van de bron te kijken hoe dit gespecificeerd wordt. Zodra er nu iets in de bron wijzigt, heeft dit direct breaking changes tot gevolg in de API. Bijvoorbeeld wanneer de maximale lengte van geslachtsnaam vergroot wordt van 400 naar 500.
> 
> In het voorbeeld van de nummeraanduidingIdentificatie is dat ook nog tight coupling met een ander domein (BAG).

Klopt. Dit is een voorbeeld. Wat is concreet je voorstel t.a.v de 2.0.0 yaml?

**Comment by CathyDingemanse** [comment]
> > naam__geslachtsnaam specificeren als een string van minimaal 3 en maximaal 100 van alleen de volgende karakters: a-zA-Z'- en diakrieten
> 
> Dit betekent dat de geslachtsnaam met 2 letters "Os" niet geleverd mag worden? Dit is strenger dan het LO GBA .
> 
> En in de maximale lengte is het weer minder streng. Het LO zegt: Lengte 1-200

Dit is een voorbeeld, geen specificatievoorstel. Zie yaml.

**Comment by CathyDingemanse** [comment]
> Deze user story is m.i. een gevalletje uitruilen tight coupling tegen security risico. We kunnen het antwoord strak specificeren door in het informatiemodel van de bron te kijken hoe dit gespecificeerd wordt. Zodra er nu iets in de bron wijzigt, heeft dit direct breaking changes tot gevolg in de API. Bijvoorbeeld wanneer de maximale lengte van geslachtsnaam vergroot wordt van 400 naar 500.
> 
Het is een kwestie van zo strak als mogelijk. Je zult iets moeten definiëren en ik vind deze persoonlijk niet heel erg kansrijk als voorbeeld voor een breaking change.


> In het voorbeeld van de nummeraanduidingIdentificatie is dat ook nog tight coupling met een ander domein (BAG).
Hoezo tight coupling? Het BAG domein gaat hierover en dit is de specificatie.

**Comment by CathyDingemanse** [comment]
> Kunnen we de string specificaties op een manier doen die het risico van tight coupling/breaking changes minimaliseert?
> 
> Bijvoorbeeld niet een veld verblijfplaats.nummeraanduidingIdentificatie, maar verblijfplaats.adresIdentificatie, en die een pattern geven die alleen a-zA-Z0-9 en - toestaat? (dan zou een UUID er ook nog in passen, maar geen enkel script).
> 

adresIdentificatie betekent toch iets anders in de BAG Bevragen API dan de verblijfplaats.adresIdentificatie in de BRP context? De BRP is volgend hierin.

**Comment by fsamwel** [comment]
> > > naam__geslachtsnaam specificeren als een string van minimaal 3 en maximaal 100 van alleen de volgende karakters: a-zA-Z'- en diakrieten
> > 
> > 
> > Dit betekent dat de geslachtsnaam met 2 letters "Os" niet geleverd mag worden? Dit is strenger dan het LO GBA .
> > En in de maximale lengte is het weer minder streng. Het LO zegt: Lengte 1-200
> 
> Dit is een voorbeeld, geen specificatievoorstel. Wat is concreet jouw voorstel t.a.v de 2.0.0 yaml?

Concreet zou ik geen maximale lengte opnemen, en een minimale lengte 1.
Het pattern wordt dan zoiets: ^[a-zA-Z0-9À-ÿ' '\-\']+$

Bij locatiebeschrijving, adresregel1, adresregel2, adresregel3 en waardetabel.omschrijving (voor plaatsnaam) iets uitgebreider: ^[a-zA-Z0-9À-ÿ' '\-\'º\:\;\,\.]+$

**Comment by fsamwel** [comment]
>> In het voorbeeld van de nummeraanduidingIdentificatie is dat ook nog tight coupling met een ander domein (BAG).
>
>Hoezo tight coupling? Het BAG domein gaat hierover en dit is de specificatie.

Dat is precies mijn punt. Wanneer het Kadaster in haar grote wijsheid om voor haar moverende redenen beslist om voortaan letters op te nemen in de nummeraanduidingIdentificatie, of deze te verlengen naar 18 cijfers, dan **moet** de BRP API ook worden aangepast en is dit voor de BRP API een **breaking change**.
Een ogenschijnlijk kleine aanpassingen aan de BAG betekent dan kosten voor alle gebruikers van persoonsgegevens. Ik zou dat willen voorkomen.

Als je de controle op een valide nummeraanduidingIdentificatie echt zou willen doen (zonder deze in BAG te controleren), zou het pattern worden: ^[0-9]{4}20[0-9]{10}$
Dus aangeven dat de 1e 4 cijfers een gemeentecode is, posities 5 en 6 is "20" om aan te geven dat het een nummeraanduiding is. Hoe gedetailleerder je dit specificeert, hoe strakker je je aan het BAG domein vastketent.

**Comment by fsamwel** [comment]
> > Kunnen we de string specificaties op een manier doen die het risico van tight coupling/breaking changes minimaliseert?
> > Bijvoorbeeld niet een veld verblijfplaats.nummeraanduidingIdentificatie, maar verblijfplaats.adresIdentificatie, en die een pattern geven die alleen a-zA-Z0-9 en - toestaat? (dan zou een UUID er ook nog in passen, maar geen enkel script).
> 
> adresIdentificatie betekent toch iets anders in de BAG Bevragen API dan de verblijfplaats.adresIdentificatie in de BRP context? De BRP is volgend hierin.

Op dit moment zijn alle domeinen van basisregistraties behoorlijk strak aan elkaar gekoppeld. Dus BRK volgt BRP in de definitie van burgerservicenummer, BRP volgt BAG in de definitie van nummeraanduiding(identificatie) en ligplaats, standplaats of verblijfsobject(identificatie). Dat dit in de informatiemodellen zo gedaan is, hoeft toch niet te betekenen dat de API dat ook moet doen? 

Of je het veld ook adresIdentificatie noemt is niet zo belangrijk. Mocht in de toekomst de BAG beslissen de nummeraanduidingIdentificatie af te schaffen en te vervangen door bijvoorbeeld een "identificatiecodeAdressering" (ik noem maar wat), dan kunnen we in onze API nummeraanduidingIdentificatie depricated maken en het nieuwe gegeven toevoegen.
Erger is het wanneer de bestaande identificatie wordt gewijzigd (ook letters) of uitgebreid (langer). Dan kunnen we het niet zo eenvoudig deprecaten, want het blijft hetzelfde gegeven.

**Comment by fsamwel** [comment]
> > ^[a-zA-Z0-9À-ÿ' '-'"º:;,.]+$
> 
> Waarom neem je
> 
> `'-'`
> 
> op in het pattern. Waarom niet eenvoudig
> 
> `^[a-zA-Z0-9À-ÿ' "º:;,.]+$`
> 
> ?

Dat is de schuld van GitHub. Ik heb '\\-\\' ingetypt (met backslashes), en GitHub toont '-' (zonder de backslash)

**Comment by melsk-r** [comment]
Ah je wil de hyphen ook opnemen.
Je wil dus eigenlijk het volgende willen doen

`^[a-zA-Z0-9À-ÿ' '\-\'"º:;,.]+$`

Maar waarom dan de

`\\'`

opnemen, het volgende moet dan volstaan

`^[a-zA-Z0-9À-ÿ' \-"º:;,.]+$`

**Comment by JohanBoer** [comment]
Deze strakkere validatieregels zijn nu opgenomen in de specificatie voor v2.0 (develop)
