### ISSUE TITLE
Als PO wil ik het aantal combinaties van inputparameters verkleinen

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#915]
...zodat de attack surface van de API kleiner wordt

_Threat type:_
Denial of Service. Beperken toegang tot data

_Threat:_
Het vinden van een kwetsbaarheid door manipulatie van combinaties van verschillende inputparameters

_Countermeasures:_
Beperken van het aantal mogelijke combinaties van inputparameters door vaste combinaties van queryparameters voor te schrijven. 

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by fsamwel** [comment]
Als het doel is om belastende vragen te voorkomen, moet je dan niet juist kijken naar minimale parametercombinaties die op zichzelf geen beperkte resultaat set leveren (en waardoor niet-geïndexeerde aanvullende parameters in deze combinatie veel belasting geven)?

Wanneer de minimale parametercombinatie van een zoekingang al een redelijk beperkte resultaatset oplevert, is het gebruik van aanvullende parameters die niet geïndexeerd zijn in die combinatie niet zo schadelijk. De query haalt dan eerst de geïndexeerde combinatie op en gaat alleen daarbinnen op de overige parameters filteren.

- zoeken op geslachtsnaam + gemeenteVanInschrijving kan heel veel personen leveren, zeker wanneer in geslachtsnaam een wildcard wordt gebruikt. Hier zou je bijvoorbeeld ook voornamen kunnen verplichten.
- zoeken op straat + huisnummer + gemeenteVanInschrijving met een wildcard in straat kan veel resultaten geven, bijvoorbeeld bij "burg*" of "*straat". Is dit een belangrijke zoekingang om naast postcode+huisnummer te hebben? Ook is deze combinatie op dit moment nog niet geïndexeerd op GBA-V (en trouwens ook niet in het gegevensmagazijn van Den Haag), omdat wij op naam openbare ruimte zoeken i.p.v. op straatnaam.
- gebruik van inclusiefOverledenPersonen niet overal toestaan, bijvoorbeeld alleen bij zoeken op geslachtsnaam+geboortedatum en nummeraanduidingIdentificatie+geboortedatum
- gebruik van parameter geboorteplaats heroverwegen of beperken. Deze is relatief complex, want kan zowel een gemeentecode (die eerst uit landelijke tabel moet worden opgehaald) als een buitenlandse plaats/locatie bevatten. En is relatief ingewikkeld voor een gebruiker, want moet deze 100% identiek invullen. Ook is deze verwacht ik nog niet geïndexeerd. is dit een parameter waar echt om gevraagd is?

**Comment by fsamwel** [comment]
Aan de andere kant betekent invulling geven aan deze user story dat de van functionaliteit ten de BRP API v2.0 beperkter is dan de functionaliteit van v1.3 en beperkter dan de functionaliteit van de GBA-V webservice en beperkter dan de functionaliteit van StUF BG vraagberichten op een gegevensmagazijn. Is dat acceptabel/wenselijk?

Kan je dit niet ook oplossen met rate limiting, beperken van het aantal zoekvragen en het strak instellen van een remote query time out?

**Comment by fsamwel** [comment]
besproken. rate limiting (https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/issues/912), beperken van het aantal zoekvragen en het strak instellen van een remote query time out zijn geen vervanging van beperken van zoekmogelijkheden. Dit moet allemaal.

**Comment by JohanBoer** [comment]
Inmiddesl haaft dit vorm gekregen middels de verschillende type requestbodies in de specificatie van v2.0 (develop)
