### ISSUE TITLE
Als PO wil ik dat de response op een zoekvraag uitsluitend noodzakelijke gegevens bevat voor selectie van een te raadplegen persoon 

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#916]
...zodat aan het criterium van dataminimalisatie wordt voldaan/ niet meer gegevens worden geleverd dan nodig is

_Threat type:_
Information Disclosure. Toegang tot data waarvoor niet is geautoriseerd

_Threat:_
De response op de zoekvraag levert de volledige resource "persoon" (al dan niet gefilterd), ook alle gegevens van personen die in het zoekresultaat voorkomen, maar waarvoor geen doelbinding is.

_Countermeasures:_
Beperk de persoonsgegevens  in het zoekresultaat tot de gegevens die nodig zijn voor selectie van de te raadplegen persoon waarvoor wel doelbinding is.

**Acceptatiecriteria**
- Bij alle zoekpaden wordt persoonBeperkt geretourneerd, met uitzondering van zoeken met BSN
- PersoonBeperkt bevat alleen gegevens die gebruikt voor selectie van een persoon

**Comment by melsk-r** [comment]
Is dit issue niet gelijk aan issue #903?

**Comment by fsamwel** [comment]
> Is dit issue niet gelijk aan issue https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/issues/903?

@melsk-r Nee. #903 gaat over gebruik van de fields parameter t.b.v. autorisatie. Dat is vrijwillig en door de client te bepalen. 

Deze user story gaat over het maximale resultaat dat kan worden gevraagd, zodat je afdwingt dat zoeken nooit wordt gebruikt voor het raadplegen van andere gegevens dan wat noodzakelijk is voor het vaststellen welke persoon geraadpleegd moet worden. Het zoekresultaat is dus vrijwel altijd veel beperkter dan de autorisatie van een gebruiker.
Een gebruiker kan bijvoorbeeld geautoriseerd zijn voor het zien van gegevens over de kinderen van een persoon. Maar je wilt niet dat zoeken van een persoon direct al gegevens over de kinderen van alle gevonden personen levert.

Denk daarbij aan verantwoording van gebruik van de API, waarbij anders gekeken wordt naar de personen die "toevallig" gevonden zijn in een zoekvraag en een persoon die geraadpleegd wordt. Wanneer ik bijvoorbeeld zou willen weten welke nationaliteit jij hebt, is het niet uit te leggen dat ik daarvoor ook de nationaliteit van je broer en tante geleverd krijg. Dus moet ik eerst zoeken (op "melsk*" en gemeenteVanInschrijving) en dan de juiste persoon (jou) selecteren en daar de nationaliteit van opvragen. De "schade" aan ten onrechte getoonde gegevens (van je broer en tante) is dan beperkt tot minder gevoelige en voor dit doel noodzakelijke gegevens. Bovendien blijkt dan uit de protocollering welke persoon ik echt wilde raadplegen en welke gegevens ik van die persoon heb geraadpleegd.

**Comment by fsamwel** [comment]
is gedaan, zoeken met iets anders dan een burgerservicenummer geeft een beperkt antwoord met alleen naam, adres, geboortedatum/leeftijd en geslachtsaanduiding, verder niks
