### ISSUE TITLE
Als PO wil ik dat uit de protocollering kan worden opgemaakt of een persoon in het antwoord op een zoekvraag is voorgekomen of dat een persoon geraadpleegd is

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#917]
...zodat bevragingen beter kunnen worden getoetst aan de doelbindingseis 
EN het AVG burgerrapport informatiever wordt.

**Acceptatiecriteria**
- Bij zoeken op BSN wordt de persoon geretourneerd
- Bij de andere zoekpaden wordt persoonBeperkt geretourneerd.

**Comment by melsk-r** [comment]
Zoeken op BSN willen we volgens mij n.a.v. issue #861 gaan verhinderen, toch?

**Comment by fsamwel** [comment]
> Zoeken op BSN willen we volgens mij n.a.v. issue https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/issues/861 gaan verhinderen, toch?

@melsk-r #861 gaat over het mogelijk maken een persoon te raadplegen zonder bsn, maar met een Uri zonder bsn (zie ook #910). Wanneer we dus een GET operatie leveren op een URI zonder bsn, dan kunnen gebruikers de relatie naar een persoon opslaan in de vorm van die uri en hoeven ze dus geen bsn meer op te slaan. 

Dit gaat dus puur om het toevoegen van een extra mogelijkheid en zegt volgens mij niks over het verbieden van een andere mogelijkheid, namelijk het ophalen van een persoon met bsn. 

Voorlopig is het burgerservicenummer zowel in de BRP als in alle andere basisregistraties en systemen die relaties naar personen opslaan hét identificerende gegeven, dus is het verhinderen om een persoon op burgerservicenummer op te zoeken niet aan de orde.

**Comment by fsamwel** [comment]
@CathyDingemanse in de acceptatiecriteria staat dat deze varianten worden geleverd. Is het voor de protocollering niet vooral belangrijk dat in het request en in de response eenvoudig is te herkennen welke van de twee het is?

Iemand zou namelijk ook op burgerservicenummer kunnen zoeken en met fields de response beperken tot exact wat in persoonBeperkt zit. Het gaat er dus om dat in zowel het request als in de response eenvoudig herkenbaar is of het gaat om zoeken of om raadplegen.

Dat lossen we in de response op door op het hoogste niveau in de response een type te melden, waaruit blijkt welke zoek- of raadpleegvraag gesteld is.

@MelvLee zouden we daarbij ook in elke gevonden persoon onderscheid kunnen maken tussen type "Persoon" en type "PersoonBeperkt"?

**Comment by MelvLee** [comment]
> @MelvLee zouden we daarbij ook in elke gevonden persoon onderscheid kunnen maken tussen type "Persoon" en type "PersoonBeperkt"?
Ja, in elk persoon is terug te zien of het een Persoon is of een PersoonBeperkt.

**Comment by gertjanvanderkooij** [comment]
Mogelijk dat protocollering en verwerkingenlogging elkaar hier raken ...  

Bij Verwerkingenlogging is er voor gekozen om in de meest uitgebreide verschijning van een Verwerkingsactiviteit ook een Actienaam op te nemen; deze kan dan bv. Zoeken, Raadplegen, Bijhouden Persoon zijn. Mee te geven door de Afnemer.

Wat willen we bereiken met het onderscheid? Is het uberhaupt zuiver te krijgen? In hoeveel processen is de uitkomst van Zoeken (PersoonBeperkt) mogelijk voldoende voor verder verloop van het proces; is Zoeken eigenlijk direct Raadplegen? Andere situatie ... stel dat ik voor het raadplegen van de bewoningssituatie Zoek op Postcode/Huisnummer; ben ik dan aan het Zoeken of aan het Raadplegen? Er is er maar 1 die het weet ... de afnemer zelf.

**Comment by CathyDingemanse** [comment]
@gertjanvanderkooij ik lees ook nog iets anders in jouw commentaar, nl. het meegeven van doelbinding in de request, de zgn. Actienaam. Dat is mijn inziens wel heel grofmazig, kan in een IAM systeem + verwerkingsregister veel fijnmaziger worden bijgehouden.
