### ISSUE TITLE
aanschrijfwijze type ipv twee losse aanschrijfwijze properties

### ISSUE THREAD

**Issue by MelvLee** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#918]
Op dit moment zijn aanschrijfwijze en regelVoorafgaandAanAanschrijfwijze gedefinieerd als twee losse properties. Dat betekent dat je met fields beide moet opgeven om de aanschrijfwijze voor een persoon op te halen. Je hebt ze immers beide nodig igv personen met een adellijke titel/predikaat.

Voorstel: definieer aanschrijfwijze als een type zodat je met fields=aanschrijfwijze beide gegevens tegelijk kan opvragen. Een aanschrijfwijze response ziet er dan als volgt uit:

```
{
  "aanschrijfwijze": {
     "tekst": "....",
     "voorafgaandTekst": ""
  }
}
```

Er is hier voor tekst als property naam gekozen omdat in statische programmeertalen een property niet dezelfde naam mag hebben als zijn class.

**Comment by fsamwel** [comment]
of als array?

**Comment by fsamwel** [comment]
In welke vorm gaan we dit nu opnemen? Een paar overwegingen:

De twee velden van aanschrijfwijze zijn eigenlijk de adresregel1 en adresregel2 van een briefadressering (en de adresregels 1 t/m 3 in verblijfplaats zijn eigenlijk adresregels 3, 4 en 5). Dus je zou ook in plaats van "tekst" en "voorafgaandTekst" ook bijv. "regel1" en "regel2" kunnen doen, dan wel een array (al dan niet met volgnummer). 

Voordeel van een array is dat een gebruiker gewoon alle regels die ontvangen worden onder elkaar kan plaatsen, zonder kennis te hoeven hebben van de benodigde volgorde, betekenis of inhoud. Dat lijkt me ook het meest evolvable, mochten we voor andere groepen in de toekomst nog een andere of extra regel aan de aanschrijfwijze willen toevoegen.

Aan de andere kant kan ik me ook situaties voorstellen dat een gebruiker alleen de aanschrijfwijze wil gebruiken zonder de voorafgaandTekst, om de naam op een andere plek dan de adressering te tonen. In dat geval moet de gebruiker zeker weten in welk element het echte naamdeel zit (en niet de formele aanschrijving) en is een array wellicht niet het handigst. 

Voor gebruikers zijn de namen "tekst" en "voorafgaandTekst" denk ik niet zo beschrijvend, toont niet echt wat het is. Voorstel: "naam" en "aanspreekvorm".

**Comment by fsamwel** [comment]
is doorgevoerd
