### ISSUE TITLE
Vragen m.b.t. aanschrijfwijze.feature

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#919]
Ik heb aanschrijfwijze.feature nog eens doorgenomen en heb naar aanleiding daarvan enkele vragen en enkele mogelijke verbeteringen.

### Algemeen
Het is me niet duidelijk hoe het feature 'aanschrijfwijze.feature' zich verhoudt tot 'aanhef.feature'.
Ik krijg echter het idee dat de tweede gebruik maakt van het resultaat van de eerste. De vraag is dan echter of je in de praktijk nu bijv. geen dubbele titel vermeldingen krijgt aangezien je in beide het gebruik van titels en predicaten regelt.

Als dat klopt kan je dan niet beter een aanschrijfwijze.feature maken waarin je titels en predicaten buiten beschouwing laat. In aanhef.feature gebruik je aanschrijfwijze vervolgens en laat je het samenstellen van de aanschrijfwijze buiten beschouwing. 
In aanhef.feature moet je dan wel iets als 'De aanschrijfwijze worden opgenomen zoals beschreven in aanschrijfwijze.feature.' opnemen.

### Regel 5 t/m 8
Wellicht op de e.o.a. wijze aangeven dat deze feature alleen geldt als type 'RaadpleegMetBurgerservicenummer' is.

### Regel 22
Ik neem aan dat je hier bedoelt 'Zie de tabel "Voorbeelden: met voorvoegsel" hieronder.'.

### Regel 24
Ik neem aan dat je hier bedoelt 'Zie de tabel "Voorbeelden: zonder voorvoegsel" hieronder.'.

**Comment by melsk-r** [comment]
Wellicht heeft #918 nog invloed op hoe hiermee om te gaan.

**Comment by melsk-r** [comment]
Ok, wachten we dat af.

**Comment by fsamwel** [comment]
@melsk-r aanschrijfwijze is inmiddels aangepast en de pull request is doorgevoerd naar develop. Zijn hiermee je vragen beantwoord? Of moeten we nog iets met dit issue doen?

**Comment by melsk-r** [comment]
De enige vraag die ik nog heb gaat over regel 10 in 'aanschrijfwijze.feature'. Daar staat:

> Bij personen met een adellijke titel of predikaat bevat de aanschrijfwijze ook de aanschrijfvorm.

Met name het woordje 'aanschrijfvorm' roept vraagtekens op. 
Is dit een schrijffout en moet die eigenlijk 'aanspreekvorm' zijn?
Zo niet, waar wordt dan beschreven hoe 'aanschrijfvorm' zijn waarde krijgt?

**Comment by fsamwel** [comment]
moet inderdaad aanspreekvorm zijn
