### ISSUE TITLE
hoe omgaan met voorvoegsels in namen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#922]
In Nederland is het gebruikelijk dat het voorvoegsel in kleine letters wordt geschreven, behalve wanneer het het begin van de naam is. Bijvoorbeeld "W. de Vries" en "de heer De Vries".
In België is dat anders, daar wordt het voorvoegsel altijd met een hoofdletter geschreven.

In de BRP kan het voorvoegsel met alleen kleine letters worden opgenomen, of ook met hoofdletters.

Hoe moeten we hiermee omgaan in de aanhef, aanschrijfwijze en gebruikInLopendeTekst?

Overwegingen:
- consequent leveren naam volgens gangbaar gebruik in Nederland
- leveren naam zoals de persoon graag aangesproken wil worden: dus opnemen voorvoegsel zoals geregistreerd

Hoe denken jullie hierover?

**Comment by melsk-r** [comment]
Enkele nadelen die ik zo vlug zie bij beide methodes zijn:

**Volgens gangbaar gebruik in Nederland**
* Geen mogelijkheid om het voorvoegsel in de correspondentie toch op te laten nemen zoals gewenst;
* Voor Nederlanders misschien niet zo'n probleem (het is hier immers een gebruik) maar de aanschrijving van buitenlanders die naar Nederland komen wijzigt wellicht naar een voor hen ongewenste wijze. Moeilijk in te schatten hoe gevoelig dit kan liggen;

**Zoals geregistreerd**
* Indien fout geregistreerd dan kost het relatief veel moeite dit te laten wijzigen. Dat je het kan laten wijzigen is echter weer een voordeel t.o.v. de andere methode;

**Comment by fsamwel** [comment]
afgesproken dat we dit gebruiken zoals geregistreerd, dus als met hoofdletters geschreven dan ook met hoofdletters opnemen in aanschrijfnamen
