### ISSUE TITLE
kan ouderaanduiding niet beter wel een enumeratie zijn?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#938]
bij het omzetten van enumeraties naar Waardetabel (combinatie code + omschrijving) is dat ook doorgevoerd op ouderAanduiding.

Hier is dit m.i. niet zo logisch omdat:
1. de code (1 of 2) geen mogelijke waarde is in de bron: voorkomen in categorie 2 vertaalt naar code 1 , categorie 3 vertaalt naar code 2
2. de omschrijving ook niet echt voor mensen duidelijk en leesbaar is: wat betekent "ouder1" of "ouder2"?
3. er nauwelijks een evolvability issue kan ontstaan hierop: er is een directe koppeling met twee categorieën in de bron

**Comment by melsk-r** [comment]
Mag ik je beargumentatie zo interpreteren dat de 3 argumenten die je opsomt tevens 3 criteria zijn waaraan een waardenlijst binnen Haal Centraal altijd moet voldoen? Kunnen we dat als een Design Decision zien?

> 1. de code (1 of 2) geen mogelijke waarde is in de bron: voorkomen in categorie 2 vertaalt naar code 1 , categorie 3 vertaalt naar code 2

Zeg je hiermee dat een waardenlijst alleen waarden kan bevatten die in de bron voorkomen? Is dat een algemeen aanvaard gegeven en geldt dat ook voor alle andere waardenlijsten die we geïntroduceerd hebben?

> 2. de omschrijving ook niet echt voor mensen duidelijk en leesbaar is: wat betekent "ouder1" of "ouder2"?

Waarom is dit een argument om er een enumeratie van te maken?

> 3. er nauwelijks een evolvability issue kan ontstaan hierop: er is een directe koppeling met twee categorieën in de bron

Lijkt me misschien nog wel het beste argument om er toch maar een enumeratie van te maken. Tenminste als met 'ouder1' en 'ouder2' de natuurlijke ouders wordt bedoeld. Zo niet dan kan je niet helemaal uitsluiten dat er ooit nog eens een 'ouder3' en 'ouder4' wordt geïntroduceerd.

**Comment by fsamwel** [comment]
> Zeg je hiermee dat een waardenlijst alleen waarden kan bevatten die in de bron voorkomen?

Nee. ik zeg hiermee i.c.m. het volgende punt dat ik het nut niet zie van het opnemen van zowel code als omschrijving voor dit gegeven. 

> Waarom is dit een argument om er een enumeratie van te maken?

De keuze om een waardetabel te gebruiken in plaats van een enumeratie is gebaseerd op twee argumenten:
1. evolvability: je kan waarden toevoegen zonder breaking change
2. code + omschrijving: de code kan gebruikt worden in softwarecode, de omschrijving getoond worden aan een gebruiker

Ik zie hier geen zinvol onderscheid tussen de code en de omschrijving.
En ik zie geen potentieel evolvability issue omdat het gegeven geen betekenis heeft in de echte wereld (ben jij in jullie gezin ouder1 of ouder2?), maar alleen een afgeleide uit de registratie. Het gegeven is dus per definitie tightly coupled.

**Comment by MelvLee** [comment]
De waarden 1 en 2 worden wel gebruikt in indicatieGezagMinderjarige om aan te geven welke ouder gezag heeft. Is het niet handig voor consistentie om deze gelijk te houden bij ouderaanduiding? Ik heb er niets tegen om een enum te gebruiken, maar ik vraag mij af of het niet verwarrend is om voor ouderaanduiding de enum waarden 'ouder1' en 'ouder2' te gebruiken en die komen niet overeen met de ouder1 en ouder2 waarden (=code) in indicatieGezagMinderjarige.
Is het definieren van ouderaanduiding als string met pattern ^1|2$ niet een optie? Hiermee kan je ook aangeven dat de waarden beperkt zijn.

**Comment by fsamwel** [comment]
wat is het voordeel van een pattern boven een enumeratie?

**Comment by fsamwel** [comment]
besproken. wordt pattern. voordeel is dat bij code genereren enumeratie naar constante wordt vertaald. code "1" krijgt dan waarde 0 en code "2" krijgt dan waarde 1. Dat kan verwarrend werken en fouten veroorzaken.
