### ISSUE TITLE
hoe opnemen onbekende nationaliteit?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#945]
```
    Scenario: de persoon heeft een onbekende nationaliteit
      Gegeven het systeem heeft een persoon met de volgende gegevens
      | naam                | waarde    |
      | burgerservicenummer | 999993367 |
      En de persoon met burgerservicenummer '999993367' heeft een nationaliteit met de volgende gegevens
      | naam                  | waarde   |
      | nationaliteit         | 0000     |
      | redenOpname           | 311      |
      | datumIngangGeldigheid | 00000000 |
      Als personen wordt gezocht met de volgende parameters
      | naam                | waarde                              |
      | type                | RaadpleegMetBurgerservicenummer     |
      | burgerservicenummer | 999993367                           |
      | fields              | burgerservicenummer,nationaliteiten |
      Dan heeft de persoon met burgerservicenummer '999993367' een nationaliteit met alleen de volgende gegevens
      | naam                  | waarde        |
      | type                  | Nationaliteit |
      | redenOpname           | 311           |
      | datumIngangGeldigheid |               |
```

Is dit hoe we de nationaliteit willen terugkrijgen? Dus type "Nationaliteit", maar er is geen nationaliteit?
Of zullen we hier een type "OnbekendNationaliteit" voor toevoegen?
Of moet deze nationaliteit niet worden geleverd wanneer nationaliteit zelf geen waarde heeft?

**Comment by JohanBoer** [comment]
Ik ben voor een type OnbekendNationaliteit. Dan communiceer je daadwerkelijk wat er in de registratie staat, maar niet middels een magical string. 
Overigens zou de datumingangGeldigheid hier met een type OnbekendDatum moeten worden geleverd

**Comment by CathyDingemanse** [comment]
Eens met Johan. Ik ben nog op zoek naar het verschil tussen nationaliteit onbekend en geen nationaliteit (stateloos). Ik ga dit bespreken met RvIG.

**Comment by gertjanvanderkooij** [comment]
Zie uitleg op bv. https://www.rotterdam.nl/wonen-leven/nationaliteit-registreren/ 
Voor registratie van Staatloos is aparte code in Nationaliteiten-tabel (32) opgenomen (0492).

**Comment by CathyDingemanse** [comment]
Duidelijk! Dat wordt dus NationaliteitOnbekend. Ik begrijp dat voor Staatloos een eigen waarde is gedefinieerd.

**Comment by JohanBoer** [comment]
Dit is in de nationaliteiten.feature opgelost die in #950 is aangeboden.

**Comment by JohanBoer** [comment]
De feature is gemerged en in branch develop gechecked dat NationaliteitOnbekend is opgenomen in de OAS3.
