### ISSUE TITLE
datumVan ontbreekt in Locatie

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#955]
In Locatie en LocatieInOnderzoek ontbreekt datumVan. Deze moet voorkomen want ook bij een locatiebeschrijving moet er een adreshouding zijn opgenomen

**Comment by JohanBoer** [comment]
Gecontroleerd in de branch Develop: Zowel in Locatie als in LocatieInOnderzoek is de datumVan opgenomen.
