### ISSUE TITLE
inconsistente naamgeving onbekend type

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#958]
ouders: OnbekendOuder
partners: OnbekendPartner
kinderen: OnbekendKind
verblijfplaats: VerblijfplaatsOnbekend
nationaliteit: NationaliteitOnbekend (#950)

Dus bij ouders, partners en kinderen staat Onbekend ervoor, en bij verblijfplaats en nationaliteit (toegevoegd in P.R. #950) staat Onbekend erachter.

Dit is nogal cosmetisch, maar zou het niet nog mooier zijn als we hier consequent in zijn?

**Comment by melsk-r** [comment]
Ik ben het met je eens Frank.
Persoonlijk zou ik er dan voor kiezen om 'Onbekend' aan het eind te plaatsen.
