### ISSUE TITLE
Is de description van 'Nationaliteit' component in 'nationaliteit.yaml' correct?

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#968]
In het component 'Nationaliteit' in 'nationaliteit.yaml' staat als description:

`* **redenOpname** : De reden op grond waarvan de persoon de nationaliteit gekregen heeft.`

Het veld 'redenOpname' wordt echter gedefinieerd in 'AbstractNationaliteit'. Ik kan me desondanks voorstellen dat je in de description van 'Nationaliteit' iets opneemt over de property 'redenOpname', nl. een description die specifiek geldt voor de context 'Nationaliteit'.
Ik zou dan echter ook in 'BehandeldAlsNederlander' en 'VastgesteldNietNederlander' een specifieke description verwachten tenzij alleen in 'redenOpname' moet worden voorzien in de context van 'Nationaliteit'. In dat geval moet er waarschijnlijk iets over in de nationaliteit.feature worden beschreven.

**Comment by fsamwel** [comment]
klopt, bij BehandeldAlsNederlander en VastgesteldNietNederlander zou eigenlijk ook een description voor redenOpname opgenomen moeten worden. Ik vraag me wel af wat deze description toevoegt (ook bij nationaliteit). De reden opname is de reden dat je het gekregen hebt...

**Comment by melsk-r** [comment]
Wellicht de description bij 'redenOpname' dan wat aanpassen, bijv.:

`* **redenOpname** : De reden op grond waarvan de persoon de nationaliteit gekregen heeft, als Nederlander behandelt wordt of juist als NietNederlander is vastgesteld.`

**Comment by fsamwel** [comment]
de omschrijving "reden ... gekregen heeft" voegt weinig toe aan naam veld "redenOpname"
