### ISSUE TITLE
gemeenteVanInschrijving in VerblijfplaatOnbekend is ten onrecht een string

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#975]
In Adres, Locatie en VerblijfplaatsBuitenland is gemeenteVanInschrijving gedefinieerd als een waardetabel.
In VerbrlijfplaatsOnbekend is gemeenteVanInschrijving gedefinieerd als string voor de gemeentecode. Dat is niet terecht (ik zou echt niet kunnen bedenken waarom dat hier anders moet zijn dan op de andere plekken). Hier moet gemeenteVanInschrijving ook een fabelwaarde zijn.

**Comment by MelvLee** [comment]
> ook zit in verblijfplaats.inOnderzoek voor VerblijfplaatsOnbekend ook gemeenteVanInschrijving. Bij de andere verblijfplaats-typen zit gemeenteVanInschrijving niet in inOnderzoek. gemeenteVanInschrijving kan niet in onderzoek staan.

Ik begrijp deze opmerking niet. gemeenteVanInschrijving komt bij alle verblijfplaats inonderzoek types voor. Moet het gemeenteVanInschrijving veld bij alle inOnderzoek types weg?

**Comment by fsamwel** [comment]
> > ook zit in verblijfplaats.inOnderzoek voor VerblijfplaatsOnbekend ook gemeenteVanInschrijving. Bij de andere verblijfplaats-typen zit gemeenteVanInschrijving niet in inOnderzoek. gemeenteVanInschrijving kan niet in onderzoek staan.
> 
> Ik begrijp deze opmerking niet. gemeenteVanInschrijving komt bij alle verblijfplaats inonderzoek types voor. Moet het gemeenteVanInschrijving veld bij alle inOnderzoek types weg?

ik heb denk ik niet goed gekeken. Dacht me ook te herinneren dat gemeenteVanInschrijving niet in onderzoek kan staan, maar heb nog even gecheckt: in v1.3 zit die ook in inOnderzoek.

je kan mijn opmerking negeren
