### ISSUE TITLE
Als PO wil ik dat de documentatie in lijn is met de vs. 2.0 beta

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#988]
...zodat developers op de API lab over de juiste documentatie beschikken

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by fsamwel** [comment]
@MelvLee 
- getting started
- kleine clientimplementatie polymorfisme in verschillende ontwikkelomgevingen: (Python, Javascript, Java)
- tonen in GitHub pages

**Comment by CathyDingemanse** [comment]
Melvin:
- Getting Started
- Polymorphisme (ook voor Python, Javascript, Java)

Robert: 
- Getting Started github pages v2.0 beta, wordt een specifieke getting started voor APIlab
- verwijzing naar 2.0 beta naar Github


-
