### ISSUE TITLE
Als PO wil ik weten welk probleem een developer-afnemer wil oplossen

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BRP-bevragen#989]
...zodat we de route daar naar toe kunnen verbeteren/verkorten

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by fsamwel** [comment]
Dus wat is de informatiebehoefte of functionele behoefte is van de gebruikers. Daaruit user stories: Als ... wil ik ... zodat ik kan ...
